import type { MaterialPreset, StylePreset } from '../../types'

export const MATERIALS: MaterialPreset[] = [
  {
    id: 'floor_light_wood',
    name: '浅木纹地板',
    category: 'floor',
    color: '#d4b896',
    roughness: 0.7,
    metalness: 0.0,
    thumbnail: '#d4b896',
  },
  {
    id: 'floor_dark_wood',
    name: '深木纹地板',
    category: 'floor',
    color: '#6b4423',
    roughness: 0.75,
    metalness: 0.0,
    thumbnail: '#6b4423',
  },
  {
    id: 'floor_marble_white',
    name: '白色大理石',
    category: 'floor',
    color: '#f0ebe3',
    roughness: 0.2,
    metalness: 0.1,
    thumbnail: '#f0ebe3',
  },
  {
    id: 'floor_marble_gray',
    name: '灰色大理石',
    category: 'floor',
    color: '#9ca3af',
    roughness: 0.25,
    metalness: 0.1,
    thumbnail: '#9ca3af',
  },
  {
    id: 'floor_concrete',
    name: '水泥地面',
    category: 'floor',
    color: '#6b7280',
    roughness: 0.9,
    metalness: 0.0,
    thumbnail: '#6b7280',
  },
  {
    id: 'floor_tile',
    name: '米色瓷砖',
    category: 'floor',
    color: '#e8dcc4',
    roughness: 0.4,
    metalness: 0.0,
    thumbnail: '#e8dcc4',
  },
  {
    id: 'wall_white',
    name: '白色墙面',
    category: 'wall',
    color: '#fafafa',
    roughness: 0.95,
    metalness: 0.0,
    thumbnail: '#fafafa',
  },
  {
    id: 'wall_beige',
    name: '米色墙纸',
    category: 'wall',
    color: '#f5deb3',
    roughness: 0.9,
    metalness: 0.0,
    thumbnail: '#f5deb3',
  },
  {
    id: 'wall_gray',
    name: '浅灰墙面',
    category: 'wall',
    color: '#d1d5db',
    roughness: 0.9,
    metalness: 0.0,
    thumbnail: '#d1d5db',
  },
  {
    id: 'wall_dark_gray',
    name: '深灰水泥墙',
    category: 'wall',
    color: '#4b5563',
    roughness: 0.95,
    metalness: 0.0,
    thumbnail: '#4b5563',
  },
  {
    id: 'wall_brick',
    name: '文化砖',
    category: 'wall',
    color: '#a0522d',
    roughness: 0.95,
    metalness: 0.0,
    thumbnail: '#a0522d',
  },
  {
    id: 'wall_green',
    name: '北欧绿墙',
    category: 'wall',
    color: '#7d9b84',
    roughness: 0.9,
    metalness: 0.0,
    thumbnail: '#7d9b84',
  },
  {
    id: 'wall_light_blue',
    name: '浅蓝色墙',
    category: 'wall',
    color: '#b0c4de',
    roughness: 0.9,
    metalness: 0.0,
    thumbnail: '#b0c4de',
  },
  {
    id: 'wall_wallpaper',
    name: '花纹墙纸',
    category: 'wall',
    color: '#e6d5c3',
    roughness: 0.85,
    metalness: 0.0,
    thumbnail: '#e6d5c3',
  },
  {
    id: 'sofa_beige',
    name: '米色沙发',
    category: 'furniture',
    color: '#d4c4a8',
    roughness: 0.85,
    metalness: 0.0,
    thumbnail: '#d4c4a8',
  },
  {
    id: 'sofa_gray',
    name: '灰色沙发',
    category: 'furniture',
    color: '#808080',
    roughness: 0.85,
    metalness: 0.0,
    thumbnail: '#808080',
  },
  {
    id: 'sofa_navy',
    name: '藏蓝沙发',
    category: 'furniture',
    color: '#2c3e50',
    roughness: 0.8,
    metalness: 0.0,
    thumbnail: '#2c3e50',
  },
  {
    id: 'sofa_green',
    name: '墨绿沙发',
    category: 'furniture',
    color: '#2f4f4f',
    roughness: 0.8,
    metalness: 0.0,
    thumbnail: '#2f4f4f',
  },
  {
    id: 'sofa_brown_leather',
    name: '棕皮沙发',
    category: 'furniture',
    color: '#5c3317',
    roughness: 0.5,
    metalness: 0.05,
    thumbnail: '#5c3317',
  },
  {
    id: 'table_wood_light',
    name: '浅木茶几',
    category: 'furniture',
    color: '#deb887',
    roughness: 0.65,
    metalness: 0.0,
    thumbnail: '#deb887',
  },
  {
    id: 'table_metal_black',
    name: '黑色金属茶几',
    category: 'furniture',
    color: '#1f1f1f',
    roughness: 0.3,
    metalness: 0.8,
    thumbnail: '#1f1f1f',
  },
  {
    id: 'table_marble_top',
    name: '大理石台面',
    category: 'furniture',
    color: '#e8e4e0',
    roughness: 0.2,
    metalness: 0.1,
    thumbnail: '#e8e4e0',
  },
  {
    id: 'table_glass',
    name: '玻璃茶几',
    category: 'furniture',
    color: '#c0c0c0',
    roughness: 0.05,
    metalness: 0.0,
    thumbnail: '#c0c0c0',
  },
]

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'modern',
    name: '现代风格',
    description: '简洁明快，线条流畅',
    lighting: {
      ambientIntensity: 0.6,
      directionalIntensity: 1.0,
      ambientColor: '#fff5e6',
      directionalColor: '#ffffff',
    },
    materials: {
      floor: 'floor_light_wood',
      walls: {
        north: 'wall_white',
        south: 'wall_white',
        east: 'wall_gray',
        west: 'wall_gray',
      },
      sofa: 'sofa_gray',
      table: 'table_marble_top',
    },
  },
  {
    id: 'nordic',
    name: '北欧风格',
    description: '自然清新，明亮舒适',
    lighting: {
      ambientIntensity: 0.8,
      directionalIntensity: 1.2,
      ambientColor: '#e6f2ff',
      directionalColor: '#f5faff',
    },
    materials: {
      floor: 'floor_light_wood',
      walls: {
        north: 'wall_white',
        south: 'wall_white',
        east: 'wall_beige',
        west: 'wall_green',
      },
      sofa: 'sofa_beige',
      table: 'table_wood_light',
    },
  },
  {
    id: 'industrial',
    name: '工业风格',
    description: '粗犷质感，硬朗个性',
    lighting: {
      ambientIntensity: 0.4,
      directionalIntensity: 0.8,
      ambientColor: '#3d2817',
      directionalColor: '#ffe4b5',
    },
    materials: {
      floor: 'floor_concrete',
      walls: {
        north: 'wall_dark_gray',
        south: 'wall_brick',
        east: 'wall_dark_gray',
        west: 'wall_dark_gray',
      },
      sofa: 'sofa_brown_leather',
      table: 'table_metal_black',
    },
  },
]

export function findMaterialById(id: string): MaterialPreset | undefined {
  return MATERIALS.find((m) => m.id === id)
}

export function findStyleById(id: StylePreset['id']): StylePreset | undefined {
  return STYLE_PRESETS.find((s) => s.id === id)
}

export function getMaterialsByCategory(
  category: MaterialPreset['category'],
): MaterialPreset[] {
  return MATERIALS.filter((m) => m.category === category)
}
