import { Constellation } from './types';

export const CONSTELLATIONS: Constellation[] = [
  { id: 'jiao', name: '角宿', pinyin: 'Jiao', element: '木', x: 0.5, y: 0.15, size: 8, color: '#7CB342', lines: ['kang'], description: '东方青龙之首，主造化万物' },
  { id: 'kang', name: '亢宿', pinyin: 'Kang', element: '金', x: 0.55, y: 0.2, size: 7, color: '#FFD700', lines: ['di'], description: '青龙之颈，主朝堂之事' },
  { id: 'di', name: '氐宿', pinyin: 'Di', element: '土', x: 0.6, y: 0.25, size: 9, color: '#8D6E63', lines: ['fang'], description: '青龙之胸，主宫室之象' },
  { id: 'fang', name: '房宿', pinyin: 'Fang', element: '火', x: 0.62, y: 0.32, size: 10, color: '#E53935', lines: ['xin'], description: '青龙之腹，主明堂布政' },
  { id: 'xin', name: '心宿', pinyin: 'Xin', element: '火', x: 0.58, y: 0.4, size: 11, color: '#C0392B', lines: ['wei'], description: '青龙之心，主天子之位' },
  { id: 'wei', name: '尾宿', pinyin: 'Wei', element: '火', x: 0.52, y: 0.48, size: 9, color: '#FF7043', lines: ['ji'], description: '青龙之尾，主后宫之事' },
  { id: 'ji', name: '箕宿', pinyin: 'Ji', element: '水', x: 0.45, y: 0.55, size: 7, color: '#4FC3F7', lines: ['dou'], description: '青龙之末，主口舌风波' },
  { id: 'dou', name: '斗宿', pinyin: 'Dou', element: '水', x: 0.38, y: 0.6, size: 8, color: '#29B6F6', lines: ['niu'], description: '北方玄武之首，主权衡之事' },
  { id: 'niu', name: '牛宿', pinyin: 'Niu', element: '金', x: 0.3, y: 0.65, size: 7, color: '#FFCA28', lines: ['nv'], description: '玄武之项，主五谷桑麻' },
  { id: 'nv', name: '女宿', pinyin: 'Nv', element: '土', x: 0.22, y: 0.68, size: 6, color: '#A1887F', lines: ['xu'], description: '玄武之胸，主女工嫁娶' },
  { id: 'xu', name: '虚宿', pinyin: 'Xu', element: '水', x: 0.15, y: 0.7, size: 8, color: '#81D4FA', lines: ['wei2'], description: '玄武之腹，主哭泣祭祀' },
  { id: 'wei2', name: '危宿', pinyin: 'Wei', element: '水', x: 0.08, y: 0.72, size: 7, color: '#4FC3F7', lines: ['shi'], description: '玄武之腰，主宗庙祠堂' },
  { id: 'shi', name: '室宿', pinyin: 'Shi', element: '火', x: 0.08, y: 0.78, size: 9, color: '#EF5350', lines: ['bi'], description: '玄武之膝，主营造宫室' },
  { id: 'bi', name: '壁宿', pinyin: 'Bi', element: '水', x: 0.15, y: 0.82, size: 8, color: '#29B6F6', lines: ['kui'], description: '玄武之足，主图书秘籍' },
  { id: 'kui', name: '奎宿', pinyin: 'Kui', element: '木', x: 0.25, y: 0.85, size: 9, color: '#66BB6A', lines: ['lou'], description: '西方白虎之首，主文章书画' },
  { id: 'lou', name: '娄宿', pinyin: 'Lou', element: '金', x: 0.35, y: 0.87, size: 8, color: '#FFD54F', lines: ['wei3'], description: '白虎之项，主苑牧牲畜' },
  { id: 'wei3', name: '胃宿', pinyin: 'Wei', element: '土', x: 0.45, y: 0.88, size: 7, color: '#BCAAA4', lines: ['mao'], description: '白虎之胸，主仓库五谷' },
  { id: 'mao', name: '昴宿', pinyin: 'Mao', element: '火', x: 0.55, y: 0.87, size: 10, color: '#F44336', lines: ['bi2'], description: '白虎之腹，主兵戈征讨' },
  { id: 'bi2', name: '毕宿', pinyin: 'Bi', element: '水', x: 0.65, y: 0.85, size: 9, color: '#4FC3F7', lines: ['zi'], description: '白虎之腰，主田猎游弋' },
  { id: 'zi', name: '觜宿', pinyin: 'Zi', element: '火', x: 0.72, y: 0.82, size: 6, color: '#FF5722', lines: ['shen'], description: '白虎之爪，主行军镇守' },
  { id: 'shen', name: '参宿', pinyin: 'Shen', element: '水', x: 0.78, y: 0.78, size: 11, color: '#81D4FA', lines: ['jing'], description: '白虎之足，主忠臣孝子' },
  { id: 'jing', name: '井宿', pinyin: 'Jing', element: '木', x: 0.82, y: 0.72, size: 8, color: '#81C784', lines: ['gui'], description: '南方朱雀之首，主水源泉脉' },
  { id: 'gui', name: '鬼宿', pinyin: 'Gui', element: '金', x: 0.85, y: 0.65, size: 6, color: '#FFB300', lines: ['liu'], description: '朱雀之项，主祠祀鬼神' },
  { id: 'liu', name: '柳宿', pinyin: 'Liu', element: '土', x: 0.87, y: 0.58, size: 7, color: '#D7CCC8', lines: ['xing'], description: '朱雀之喙，主御膳酒食' },
  { id: 'xing', name: '星宿', pinyin: 'Xing', element: '火', x: 0.85, y: 0.5, size: 8, color: '#FF5252', lines: ['zhang'], description: '朱雀之颈，主衣裳文绣' },
  { id: 'zhang', name: '张宿', pinyin: 'Zhang', element: '火', x: 0.82, y: 0.42, size: 9, color: '#FF7043', lines: ['yi'], description: '朱雀之喉，主珠宝珍玩' },
  { id: 'yi', name: '翼宿', pinyin: 'Yi', element: '水', x: 0.75, y: 0.35, size: 8, color: '#4FC3F7', lines: ['zhen'], description: '朱雀之翼，主礼乐歌舞' },
  { id: 'zhen', name: '轸宿', pinyin: 'Zhen', element: '水', x: 0.65, y: 0.28, size: 9, color: '#29B6F6', lines: ['jiao'], description: '朱雀之尾，主车骑征伐' },
];

export const INSCRIPTIONS = [
  { id: 'zhen1', text: '镇星安位', meaning: '安定星宿方位', element: '土' },
  { id: 'hui1', text: '辉光普照', meaning: '星光辉耀四方', element: '火' },
  { id: 'run1', text: '润物无声', meaning: '水德润泽万物', element: '水' },
  { id: 'mu1', text: '木秀于林', meaning: '木德生生不息', element: '木' },
  { id: 'gang1', text: '金刚不坏', meaning: '金德坚固不摧', element: '金' },
  { id: 'ji2', text: '吉星高照', meaning: '吉祥之星降临', element: '火' },
  { id: 'bi1', text: '避邪扶正', meaning: '驱除邪恶之气', element: '金' },
  { id: 'ning1', text: '凝神聚气', meaning: '凝聚星官神力', element: '土' },
  { id: 'qing1', text: '清风徐来', meaning: '化解暴戾之气', element: '木' },
  { id: 'jing3', text: '静水流深', meaning: '平息动荡之象', element: '水' },
  { id: 'ming1', text: '明镜高悬', meaning: '洞察一切真相', element: '金' },
  { id: 'yan3', text: '偃武修文', meaning: '止息兵戈战事', element: '木' },
];
