import type { Town, Cargo, Risk, Terrain } from '../src/types';

export const towns: Town[] = [
  {
    id: 'khara-khoto',
    name: '黑水城',
    x: 400,
    y: 300,
    type: 'fortress',
    description: '西夏王朝重要军事城镇，丝绸之路北道重镇，商贾云集之地',
    priceModifiers: {
      silk: 1.2,
      spice: 0.8,
      jade: 1.5,
      tea: 0.9,
      porcelain: 1.1,
      medicine: 1.0,
    },
  },
  {
    id: 'khotan',
    name: '于阗',
    x: 150,
    y: 450,
    type: 'oasis',
    description: '西域绿洲王国，以出产美玉闻名，丝绸之路南道重镇',
    priceModifiers: {
      silk: 1.4,
      spice: 1.0,
      jade: 0.6,
      tea: 1.1,
      porcelain: 1.3,
      medicine: 0.9,
    },
  },
  {
    id: 'kashgar',
    name: '喀什噶尔',
    x: 80,
    y: 250,
    type: 'oasis',
    description: '西域交通枢纽，东西方文化交汇之地，商贸繁盛',
    priceModifiers: {
      silk: 1.6,
      spice: 0.7,
      jade: 1.2,
      tea: 1.2,
      porcelain: 1.4,
      medicine: 0.8,
    },
  },
  {
    id: 'samarkand',
    name: '撒马尔罕',
    x: 50,
    y: 150,
    type: 'fortress',
    description: '中亚文明中心，商业发达，文化繁荣',
    priceModifiers: {
      silk: 1.8,
      spice: 0.5,
      jade: 1.3,
      tea: 1.3,
      porcelain: 1.5,
      medicine: 0.7,
    },
  },
  {
    id: 'bukhara',
    name: '布哈拉',
    x: 120,
    y: 100,
    type: 'oasis',
    description: '学术与商业并重的绿洲城市，以皮革和毛毯闻名',
    priceModifiers: {
      silk: 1.7,
      spice: 0.6,
      jade: 1.4,
      tea: 1.2,
      porcelain: 1.4,
      medicine: 0.8,
    },
  },
  {
    id: 'turfan',
    name: '高昌',
    x: 550,
    y: 200,
    type: 'oasis',
    description: '东疆门户，佛教文化中心，葡萄美酒产地',
    priceModifiers: {
      silk: 1.1,
      spice: 1.1,
      jade: 1.1,
      tea: 0.8,
      porcelain: 0.9,
      medicine: 1.1,
    },
  },
  {
    id: 'dunhuang',
    name: '敦煌',
    x: 600,
    y: 350,
    type: 'gobi',
    description: '河西走廊西端，东西交通咽喉，佛教艺术宝库',
    priceModifiers: {
      silk: 1.0,
      spice: 1.0,
      jade: 1.2,
      tea: 0.7,
      porcelain: 0.8,
      medicine: 1.0,
    },
  },
  {
    id: 'kocho',
    name: '瓜州',
    x: 680,
    y: 400,
    type: 'desert',
    description: '沙漠边缘的军事要塞，连接河西走廊重要驿站',
    priceModifiers: {
      silk: 0.9,
      spice: 1.1,
      jade: 1.1,
      tea: 0.6,
      porcelain: 0.7,
      medicine: 1.1,
    },
  },
  {
    id: 'loulan',
    name: '楼兰',
    x: 300,
    y: 480,
    type: 'desert',
    description: '神秘的沙漠古国，现已湮没于黄沙之下',
    priceModifiers: {
      silk: 1.3,
      spice: 1.2,
      jade: 1.3,
      tea: 1.0,
      porcelain: 1.1,
      medicine: 1.2,
    },
  },
  {
    id: 'niya',
    name: '尼雅',
    x: 220,
    y: 520,
    type: 'desert',
    description: '精绝国故地，沙漠中的绿洲文明',
    priceModifiers: {
      silk: 1.3,
      spice: 1.1,
      jade: 0.9,
      tea: 1.1,
      porcelain: 1.2,
      medicine: 1.0,
    },
  },
];

export const cargoTypes: Cargo[] = [
  {
    id: 'silk',
    name: '丝绸',
    icon: '🧵',
    basePrice: 100,
    weight: 5,
    quantity: 0,
    description: '来自中原的上等丝绸，西域诸国趋之若鹜',
  },
  {
    id: 'spice',
    name: '香料',
    icon: '🌶️',
    basePrice: 80,
    weight: 2,
    quantity: 0,
    description: '从西方传入的珍贵香料，用于烹饪和药用',
  },
  {
    id: 'jade',
    name: '玉石',
    icon: '💎',
    basePrice: 200,
    weight: 10,
    quantity: 0,
    description: '于阗美玉，温润如脂，君子之石',
  },
  {
    id: 'tea',
    name: '茶叶',
    icon: '🍵',
    basePrice: 60,
    weight: 8,
    quantity: 0,
    description: '中原名茶，消食解腻，游牧民族必需品',
  },
  {
    id: 'porcelain',
    name: '瓷器',
    icon: '🏺',
    basePrice: 150,
    weight: 15,
    quantity: 0,
    description: '精美瓷器，中华工艺之瑰宝，易碎需小心运输',
  },
  {
    id: 'medicine',
    name: '药材',
    icon: '🌿',
    basePrice: 120,
    weight: 6,
    quantity: 0,
    description: '珍贵中草药，治病救人，旅途必备',
  },
];

export const risks: Risk[] = [
  {
    id: 'sandstorm-1',
    type: 'sandstorm',
    x: 300,
    y: 300,
    radius: 60,
    probability: 0.4,
    impact: {
      cost: 50,
      delay: 3,
      cargoLoss: 0.15,
    },
  },
  {
    id: 'sandstorm-2',
    type: 'sandstorm',
    x: 500,
    y: 450,
    radius: 50,
    probability: 0.3,
    impact: {
      cost: 40,
      delay: 2,
      cargoLoss: 0.1,
    },
  },
  {
    id: 'bandits-1',
    type: 'bandits',
    x: 180,
    y: 180,
    radius: 45,
    probability: 0.25,
    impact: {
      cost: 200,
      delay: 1,
      cargoLoss: 0.3,
    },
  },
  {
    id: 'bandits-2',
    type: 'bandits',
    x: 450,
    y: 280,
    radius: 40,
    probability: 0.2,
    impact: {
      cost: 150,
      delay: 1,
      cargoLoss: 0.25,
    },
  },
  {
    id: 'plague-1',
    type: 'plague',
    x: 100,
    y: 350,
    radius: 35,
    probability: 0.15,
    impact: {
      cost: 300,
      delay: 5,
      cargoLoss: 0.05,
    },
  },
  {
    id: 'drought-1',
    type: 'drought',
    x: 350,
    y: 500,
    radius: 55,
    probability: 0.35,
    impact: {
      cost: 80,
      delay: 2,
      cargoLoss: 0.1,
    },
  },
];

export const terrainData: Record<string, Terrain> = {
  desert: {
    type: 'desert',
    costMultiplier: 2.0,
    speedMultiplier: 0.6,
    riskLevel: 3,
  },
  oasis: {
    type: 'oasis',
    costMultiplier: 0.5,
    speedMultiplier: 1.2,
    riskLevel: 1,
  },
  gobi: {
    type: 'gobi',
    costMultiplier: 1.5,
    speedMultiplier: 0.8,
    riskLevel: 2,
  },
  mountain: {
    type: 'mountain',
    costMultiplier: 1.8,
    speedMultiplier: 0.5,
    riskLevel: 3,
  },
  fortress: {
    type: 'fortress',
    costMultiplier: 0.8,
    speedMultiplier: 1.0,
    riskLevel: 1,
  },
};
