import { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: '1',
    name: '番茄炒蛋',
    timeMinutes: 15,
    difficulty: 1,
    tags: ['快手', '家常', '蔬菜'],
    ingredients: [
      { name: '番茄', quantity: 2, unit: '个', category: '蔬菜' },
      { name: '鸡蛋', quantity: 3, unit: '个', category: '蛋类' },
      { name: '葱花', quantity: 5, unit: '克', category: '蔬菜' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '白糖', quantity: 5, unit: '克', category: '调料' },
    ],
    steps: [
      '番茄洗净切块，鸡蛋打散备用',
      '热锅冷油，倒入蛋液炒至凝固盛出',
      '锅中再加少许油，放入番茄翻炒出汁',
      '加入盐和白糖调味',
      '倒入炒好的鸡蛋翻炒均匀',
      '撒上葱花出锅',
    ],
  },
  {
    id: '2',
    name: '青椒肉丝',
    timeMinutes: 20,
    difficulty: 2,
    tags: ['家常', '肉类', '快手'],
    ingredients: [
      { name: '青椒', quantity: 2, unit: '个', category: '蔬菜' },
      { name: '猪肉', quantity: 200, unit: '克', category: '肉类' },
      { name: '蒜末', quantity: 10, unit: '克', category: '调料' },
      { name: '生抽', quantity: 10, unit: '毫升', category: '调料' },
      { name: '淀粉', quantity: 5, unit: '克', category: '调料' },
      { name: '盐', quantity: 2, unit: '克', category: '调料' },
    ],
    steps: [
      '猪肉切丝，用生抽和淀粉腌制10分钟',
      '青椒去籽切丝备用',
      '热锅冷油，放入肉丝滑炒至变色盛出',
      '锅中留底油，爆香蒜末',
      '放入青椒丝翻炒至断生',
      '加入肉丝和盐翻炒均匀出锅',
    ],
  },
  {
    id: '3',
    name: '蒜蓉西兰花',
    timeMinutes: 10,
    difficulty: 1,
    tags: ['快手', '低卡', '健康', '素食', '蔬菜'],
    ingredients: [
      { name: '西兰花', quantity: 300, unit: '克', category: '蔬菜' },
      { name: '大蒜', quantity: 5, unit: '瓣', category: '调料' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '蚝油', quantity: 10, unit: '毫升', category: '调料' },
    ],
    steps: [
      '西兰花掰成小朵，用盐水浸泡后洗净',
      '大蒜切末备用',
      '锅中烧水，加少许盐和油，西兰花焯水2分钟捞出',
      '热锅冷油，爆香蒜末',
      '放入西兰花翻炒',
      '加盐和蚝油调味出锅',
    ],
  },
  {
    id: '4',
    name: '红烧肉',
    timeMinutes: 60,
    difficulty: 4,
    tags: ['家常', '肉类'],
    ingredients: [
      { name: '五花肉', quantity: 500, unit: '克', category: '肉类' },
      { name: '冰糖', quantity: 30, unit: '克', category: '调料' },
      { name: '生抽', quantity: 20, unit: '毫升', category: '调料' },
      { name: '老抽', quantity: 10, unit: '毫升', category: '调料' },
      { name: '料酒', quantity: 30, unit: '毫升', category: '调料' },
      { name: '姜片', quantity: 15, unit: '克', category: '调料' },
      { name: '八角', quantity: 2, unit: '个', category: '调料' },
    ],
    steps: [
      '五花肉切块，冷水下锅焯水去血沫',
      '锅中放少许油，加入冰糖小火炒出糖色',
      '放入五花肉翻炒上色',
      '加入姜片、八角、料酒、生抽、老抽',
      '加入没过肉的热水，大火烧开转小火炖40分钟',
      '大火收汁出锅',
    ],
  },
  {
    id: '5',
    name: '麻婆豆腐',
    timeMinutes: 20,
    difficulty: 3,
    tags: ['辣', '家常', '素食'],
    ingredients: [
      { name: '豆腐', quantity: 400, unit: '克', category: '豆制品' },
      { name: '猪肉末', quantity: 100, unit: '克', category: '肉类' },
      { name: '郫县豆瓣酱', quantity: 20, unit: '克', category: '调料' },
      { name: '花椒粉', quantity: 3, unit: '克', category: '调料' },
      { name: '生抽', quantity: 10, unit: '毫升', category: '调料' },
      { name: '蒜末', quantity: 10, unit: '克', category: '调料' },
      { name: '葱花', quantity: 10, unit: '克', category: '蔬菜' },
      { name: '淀粉', quantity: 5, unit: '克', category: '调料' },
    ],
    steps: [
      '豆腐切块，用盐水浸泡5分钟',
      '热锅冷油，放入肉末炒香',
      '加入豆瓣酱和蒜末炒出红油',
      '加入适量水烧开',
      '放入豆腐，加生抽小火煮5分钟',
      '用淀粉勾芡，撒上花椒粉和葱花出锅',
    ],
  },
  {
    id: '6',
    name: '清蒸鲈鱼',
    timeMinutes: 25,
    difficulty: 2,
    tags: ['海鲜', '健康', '低卡'],
    ingredients: [
      { name: '鲈鱼', quantity: 1, unit: '条', category: '海鲜' },
      { name: '姜丝', quantity: 20, unit: '克', category: '调料' },
      { name: '葱丝', quantity: 20, unit: '克', category: '蔬菜' },
      { name: '蒸鱼豉油', quantity: 30, unit: '毫升', category: '调料' },
      { name: '料酒', quantity: 15, unit: '毫升', category: '调料' },
    ],
    steps: [
      '鲈鱼处理干净，两面划几刀',
      '鱼身抹上料酒，放上姜丝',
      '水烧开后，将鱼放入蒸锅，大火蒸8分钟',
      '取出倒掉盘中汤汁，铺上葱丝',
      '淋上蒸鱼豉油',
      '热油浇在葱丝上即可',
    ],
  },
  {
    id: '7',
    name: '宫保鸡丁',
    timeMinutes: 25,
    difficulty: 3,
    tags: ['辣', '家常', '肉类', '快手'],
    ingredients: [
      { name: '鸡胸肉', quantity: 300, unit: '克', category: '肉类' },
      { name: '花生米', quantity: 50, unit: '克', category: '干货' },
      { name: '干辣椒', quantity: 10, unit: '个', category: '调料' },
      { name: '花椒', quantity: 3, unit: '克', category: '调料' },
      { name: '生抽', quantity: 15, unit: '毫升', category: '调料' },
      { name: '醋', quantity: 10, unit: '毫升', category: '调料' },
      { name: '白糖', quantity: 10, unit: '克', category: '调料' },
      { name: '淀粉', quantity: 10, unit: '克', category: '调料' },
    ],
    steps: [
      '鸡胸肉切丁，用生抽和淀粉腌制15分钟',
      '干辣椒剪段，调汁：生抽、醋、白糖、淀粉、水',
      '热锅冷油，炸香花生米盛出',
      '锅中留油，爆香花椒和干辣椒',
      '放入鸡丁滑炒至变色',
      '倒入调好的汁翻炒，最后加花生米出锅',
    ],
  },
  {
    id: '8',
    name: '凉拌黄瓜',
    timeMinutes: 10,
    difficulty: 1,
    tags: ['快手', '低卡', '健康', '素食', '蔬菜'],
    ingredients: [
      { name: '黄瓜', quantity: 2, unit: '根', category: '蔬菜' },
      { name: '蒜末', quantity: 15, unit: '克', category: '调料' },
      { name: '生抽', quantity: 15, unit: '毫升', category: '调料' },
      { name: '醋', quantity: 10, unit: '毫升', category: '调料' },
      { name: '香油', quantity: 5, unit: '毫升', category: '调料' },
      { name: '盐', quantity: 2, unit: '克', category: '调料' },
    ],
    steps: [
      '黄瓜拍碎切段，加少许盐腌制5分钟',
      '倒掉腌出的水分',
      '加入蒜末、生抽、醋',
      '滴入香油',
      '搅拌均匀即可',
    ],
  },
  {
    id: '9',
    name: '酸辣土豆丝',
    timeMinutes: 15,
    difficulty: 2,
    tags: ['快手', '辣', '家常', '素食', '蔬菜'],
    ingredients: [
      { name: '土豆', quantity: 2, unit: '个', category: '蔬菜' },
      { name: '干辣椒', quantity: 5, unit: '个', category: '调料' },
      { name: '青椒', quantity: 1, unit: '个', category: '蔬菜' },
      { name: '醋', quantity: 15, unit: '毫升', category: '调料' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '蒜末', quantity: 10, unit: '克', category: '调料' },
    ],
    steps: [
      '土豆和青椒切丝，土豆丝用清水浸泡去淀粉',
      '干辣椒剪段备用',
      '热锅冷油，爆香蒜末和干辣椒',
      '放入土豆丝大火快炒',
      '加入青椒丝、醋和盐',
      '翻炒均匀出锅',
    ],
  },
  {
    id: '10',
    name: '可乐鸡翅',
    timeMinutes: 30,
    difficulty: 2,
    tags: ['家常', '肉类'],
    ingredients: [
      { name: '鸡翅', quantity: 500, unit: '克', category: '肉类' },
      { name: '可乐', quantity: 250, unit: '毫升', category: '饮料' },
      { name: '生抽', quantity: 20, unit: '毫升', category: '调料' },
      { name: '老抽', quantity: 5, unit: '毫升', category: '调料' },
      { name: '料酒', quantity: 15, unit: '毫升', category: '调料' },
      { name: '姜片', quantity: 10, unit: '克', category: '调料' },
    ],
    steps: [
      '鸡翅两面划刀，冷水下锅焯水去血沫',
      '热锅冷油，放入鸡翅煎至两面金黄',
      '加入姜片、料酒、生抽、老抽',
      '倒入可乐没过鸡翅',
      '大火烧开转中小火炖15分钟',
      '大火收汁出锅',
    ],
  },
  {
    id: '11',
    name: '水煮肉片',
    timeMinutes: 30,
    difficulty: 4,
    tags: ['辣', '肉类'],
    ingredients: [
      { name: '猪肉', quantity: 300, unit: '克', category: '肉类' },
      { name: '豆芽', quantity: 200, unit: '克', category: '蔬菜' },
      { name: '郫县豆瓣酱', quantity: 30, unit: '克', category: '调料' },
      { name: '干辣椒', quantity: 15, unit: '个', category: '调料' },
      { name: '花椒', quantity: 5, unit: '克', category: '调料' },
      { name: '蒜末', quantity: 20, unit: '克', category: '调料' },
      { name: '淀粉', quantity: 15, unit: '克', category: '调料' },
    ],
    steps: [
      '猪肉切片，用淀粉和生抽腌制10分钟',
      '豆芽焯水铺在碗底',
      '热锅冷油，炒香豆瓣酱和蒜末',
      '加水烧开，放入肉片煮至变色',
      '连汤带肉倒入碗中',
      '表面撒上干辣椒和花椒，热油浇香',
    ],
  },
  {
    id: '12',
    name: '虾仁滑蛋',
    timeMinutes: 15,
    difficulty: 2,
    tags: ['海鲜', '快手', '低卡', '健康'],
    ingredients: [
      { name: '虾仁', quantity: 200, unit: '克', category: '海鲜' },
      { name: '鸡蛋', quantity: 4, unit: '个', category: '蛋类' },
      { name: '葱花', quantity: 10, unit: '克', category: '蔬菜' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '料酒', quantity: 10, unit: '毫升', category: '调料' },
    ],
    steps: [
      '虾仁去虾线，用料酒和少许盐腌制5分钟',
      '鸡蛋打散，加少许盐和葱花',
      '热锅冷油，放入虾仁炒至变色',
      '倒入蛋液',
      '小火慢推至蛋液凝固',
      '出锅装盘',
    ],
  },
  {
    id: '13',
    name: '鱼香茄子',
    timeMinutes: 25,
    difficulty: 3,
    tags: ['家常', '素食', '蔬菜'],
    ingredients: [
      { name: '茄子', quantity: 2, unit: '根', category: '蔬菜' },
      { name: '猪肉末', quantity: 50, unit: '克', category: '肉类' },
      { name: '蒜末', quantity: 15, unit: '克', category: '调料' },
      { name: '生抽', quantity: 15, unit: '毫升', category: '调料' },
      { name: '醋', quantity: 10, unit: '毫升', category: '调料' },
      { name: '白糖', quantity: 10, unit: '克', category: '调料' },
      { name: '豆瓣酱', quantity: 15, unit: '克', category: '调料' },
    ],
    steps: [
      '茄子切条，撒盐腌制10分钟挤干水分',
      '调鱼香汁：生抽、醋、白糖、淀粉、水',
      '茄子油炸至金黄盛出',
      '锅中留油，炒香肉末和豆瓣酱',
      '加入蒜末炒香，倒入茄子',
      '淋入鱼香汁翻炒均匀',
    ],
  },
  {
    id: '14',
    name: '紫菜蛋花汤',
    timeMinutes: 10,
    difficulty: 1,
    tags: ['快手', '低卡', '健康'],
    ingredients: [
      { name: '紫菜', quantity: 5, unit: '克', category: '干货' },
      { name: '鸡蛋', quantity: 2, unit: '个', category: '蛋类' },
      { name: '虾皮', quantity: 5, unit: '克', category: '海鲜' },
      { name: '葱花', quantity: 10, unit: '克', category: '蔬菜' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '香油', quantity: 3, unit: '毫升', category: '调料' },
    ],
    steps: [
      '鸡蛋打散备用',
      '锅中烧开水',
      '放入紫菜和虾皮煮1分钟',
      '缓缓倒入蛋液，形成蛋花',
      '加盐调味，撒上葱花',
      '滴入香油出锅',
    ],
  },
  {
    id: '15',
    name: '豆角焖面',
    timeMinutes: 35,
    difficulty: 3,
    tags: ['家常', '蔬菜', '肉类'],
    ingredients: [
      { name: '面条', quantity: 300, unit: '克', category: '主食' },
      { name: '豆角', quantity: 200, unit: '克', category: '蔬菜' },
      { name: '猪肉丝', quantity: 100, unit: '克', category: '肉类' },
      { name: '生抽', quantity: 20, unit: '毫升', category: '调料' },
      { name: '老抽', quantity: 5, unit: '毫升', category: '调料' },
      { name: '蒜末', quantity: 15, unit: '克', category: '调料' },
    ],
    steps: [
      '豆角洗净掰段，肉丝用生抽腌制',
      '热锅冷油，炒香肉丝盛出',
      '锅中加少许油，爆香蒜末',
      '放入豆角翻炒，加生抽、老抽和水',
      '煮开后铺上肉丝和面条',
      '小火焖15分钟，翻拌均匀出锅',
    ],
  },
  {
    id: '16',
    name: '冬瓜排骨汤',
    timeMinutes: 90,
    difficulty: 3,
    tags: ['健康', '肉类', '蔬菜'],
    ingredients: [
      { name: '排骨', quantity: 500, unit: '克', category: '肉类' },
      { name: '冬瓜', quantity: 300, unit: '克', category: '蔬菜' },
      { name: '姜片', quantity: 15, unit: '克', category: '调料' },
      { name: '葱段', quantity: 15, unit: '克', category: '蔬菜' },
      { name: '盐', quantity: 5, unit: '克', category: '调料' },
      { name: '料酒', quantity: 20, unit: '毫升', category: '调料' },
    ],
    steps: [
      '排骨冷水下锅焯水去血沫',
      '冬瓜去皮切块',
      '砂锅加水，放入排骨、姜片、葱段、料酒',
      '大火烧开转小火炖60分钟',
      '加入冬瓜继续炖20分钟',
      '加盐调味出锅',
    ],
  },
  {
    id: '17',
    name: '干煸四季豆',
    timeMinutes: 20,
    difficulty: 3,
    tags: ['辣', '家常', '素食', '蔬菜'],
    ingredients: [
      { name: '四季豆', quantity: 300, unit: '克', category: '蔬菜' },
      { name: '猪肉末', quantity: 50, unit: '克', category: '肉类' },
      { name: '干辣椒', quantity: 10, unit: '个', category: '调料' },
      { name: '花椒', quantity: 3, unit: '克', category: '调料' },
      { name: '蒜末', quantity: 15, unit: '克', category: '调料' },
      { name: '生抽', quantity: 10, unit: '毫升', category: '调料' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
    ],
    steps: [
      '四季豆去筋掰段',
      '四季豆油炸至表皮起皱盛出',
      '锅中留油，炒香肉末',
      '加入干辣椒、花椒、蒜末爆香',
      '放入四季豆翻炒',
      '加生抽和盐调味出锅',
    ],
  },
  {
    id: '18',
    name: '蛋炒饭',
    timeMinutes: 10,
    difficulty: 1,
    tags: ['快手', '家常'],
    ingredients: [
      { name: '米饭', quantity: 400, unit: '克', category: '主食' },
      { name: '鸡蛋', quantity: 2, unit: '个', category: '蛋类' },
      { name: '葱花', quantity: 15, unit: '克', category: '蔬菜' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
    ],
    steps: [
      '鸡蛋打散备用',
      '热锅冷油，倒入蛋液炒至凝固',
      '加入米饭大火翻炒均匀',
      '加盐调味',
      '撒上葱花翻炒',
      '出锅装盘',
    ],
  },
  {
    id: '19',
    name: '素炒三丝',
    timeMinutes: 15,
    difficulty: 1,
    tags: ['快手', '素食', '健康', '低卡', '蔬菜'],
    ingredients: [
      { name: '胡萝卜', quantity: 1, unit: '根', category: '蔬菜' },
      { name: '土豆', quantity: 1, unit: '个', category: '蔬菜' },
      { name: '青椒', quantity: 1, unit: '个', category: '蔬菜' },
      { name: '蒜末', quantity: 10, unit: '克', category: '调料' },
      { name: '盐', quantity: 3, unit: '克', category: '调料' },
      { name: '生抽', quantity: 5, unit: '毫升', category: '调料' },
    ],
    steps: [
      '胡萝卜、土豆、青椒切丝',
      '土豆丝用清水浸泡去淀粉',
      '热锅冷油，爆香蒜末',
      '先放胡萝卜丝翻炒1分钟',
      '加入土豆丝和青椒丝翻炒',
      '加盐和生抽调味出锅',
    ],
  },
  {
    id: '20',
    name: '白灼虾',
    timeMinutes: 15,
    difficulty: 1,
    tags: ['海鲜', '健康', '低卡', '快手'],
    ingredients: [
      { name: '虾', quantity: 300, unit: '克', category: '海鲜' },
      { name: '姜片', quantity: 10, unit: '克', category: '调料' },
      { name: '葱段', quantity: 10, unit: '克', category: '蔬菜' },
      { name: '料酒', quantity: 15, unit: '毫升', category: '调料' },
      { name: '蘸料生抽', quantity: 20, unit: '毫升', category: '调料' },
      { name: '芥末', quantity: 3, unit: '克', category: '调料' },
    ],
    steps: [
      '虾去虾线洗净',
      '锅中烧水，加入姜片、葱段、料酒',
      '水开后放入虾煮3-4分钟',
      '变红弯曲即可捞出',
      '生抽加芥末调蘸料',
      '摆盘上桌',
    ],
  },
  {
    id: '21',
    name: '洋葱炒牛肉',
    timeMinutes: 20,
    difficulty: 3,
    tags: ['家常', '肉类', '快手'],
    ingredients: [
      { name: '牛肉', quantity: 250, unit: '克', category: '肉类' },
      { name: '洋葱', quantity: 1, unit: '个', category: '蔬菜' },
      { name: '青椒', quantity: 1, unit: '个', category: '蔬菜' },
      { name: '生抽', quantity: 15, unit: '毫升', category: '调料' },
      { name: '淀粉', quantity: 10, unit: '克', category: '调料' },
      { name: '蚝油', quantity: 10, unit: '毫升', category: '调料' },
      { name: '黑胡椒', quantity: 3, unit: '克', category: '调料' },
    ],
    steps: [
      '牛肉切片，用生抽、淀粉、黑胡椒腌制15分钟',
      '洋葱和青椒切块',
      '热锅冷油，放入牛肉滑炒至变色盛出',
      '锅中留油，炒香洋葱',
      '加入青椒和蚝油翻炒',
      '倒入牛肉翻炒均匀出锅',
    ],
  },
  {
    id: '22',
    name: '醋溜白菜',
    timeMinutes: 10,
    difficulty: 1,
    tags: ['快手', '素食', '家常', '蔬菜', '低卡'],
    ingredients: [
      { name: '白菜', quantity: 400, unit: '克', category: '蔬菜' },
      { name: '干辣椒', quantity: 5, unit: '个', category: '调料' },
      { name: '醋', quantity: 20, unit: '毫升', category: '调料' },
      { name: '生抽', quantity: 10, unit: '毫升', category: '调料' },
      { name: '白糖', quantity: 5, unit: '克', category: '调料' },
      { name: '盐', quantity: 2, unit: '克', category: '调料' },
    ],
    steps: [
      '白菜叶切片，帮切片分开',
      '调汁：醋、生抽、白糖、淀粉、水',
      '热锅冷油，爆香干辣椒',
      '先放入白菜帮翻炒',
      '再放白菜叶炒至变软',
      '淋入调好的汁翻炒均匀',
    ],
  },
];
