import type { BlockConfig } from '../components/BlockEditor';

const animationKeyframes: Record<string, string> = {
  'fade-in': `
    @keyframes fadeIn {
      from { opacity: 0; }
      to { opacity: 1; }
    }`,
  'slide-left': `
    @keyframes slideLeft {
      from { opacity: 0; transform: translateX(-60px); }
      to { opacity: 1; transform: translateX(0); }
    }`,
  'fly-up': `
    @keyframes flyUp {
      from { opacity: 0; transform: translateY(60px); }
      to { opacity: 1; transform: translateY(0); }
    }`,
  'scale-in': `
    @keyframes scaleIn {
      from { opacity: 0; transform: scale(0.8); }
      to { opacity: 1; transform: scale(1); }
    }`,
};

const animationNameMap: Record<string, string> = {
  'fade-in': 'fadeIn',
  'slide-left': 'slideLeft',
  'fly-up': 'flyUp',
  'scale-in': 'scaleIn',
};

export function exportCSS(blocks: BlockConfig[]): string {
  const usedAnimations = new Set<string>();
  const blockRules: string[] = [];

  for (const block of blocks) {
    const safeId = block.id.replace(/[^a-zA-Z0-9]/g, '_');
    const animName = animationNameMap[block.animationType] || 'fadeIn';
    usedAnimations.add(block.animationType);

    const translateYStart = 0;
    const translateYMid = 50 * block.parallaxSpeed;
    const translateYEnd = 100 * block.parallaxSpeed;

    const opacityStart = block.initialOpacity;
    const opacityMid = block.initialOpacity * (1 - 0.15);
    const opacityEnd = block.initialOpacity * (1 - 0.3);

    blockRules.push(`
.block-${safeId} {
  animation-name: ${animName}, block-${safeId}-parallax;
  animation-duration: 0.8s, 1s;
  animation-timing-function: ease-out, linear;
  animation-fill-mode: both;
  background-color: ${block.bgColor || 'transparent'};
  ${block.bgImageUrl ? `background-image: url('${block.bgImageUrl}');` : ''}
  background-size: cover;
  background-position: center;
}

@keyframes block-${safeId}-parallax {
  0% {
    transform: translateY(${translateYStart}px);
    opacity: ${opacityStart};
  }
  50% {
    transform: translateY(${translateYMid}px);
    opacity: ${opacityMid};
  }
  100% {
    transform: translateY(${translateYEnd}px);
    opacity: ${opacityEnd};
  }
}`);
  }

  const keyframesStr = Array.from(usedAnimations)
    .map((a) => animationKeyframes[a] || '')
    .join('\n');

  return `/* Parallax Scroll Layout - Generated by Visual Builder */
@media (prefers-reduced-motion: no-preference) {
${keyframesStr}
${blockRules.join('\n')}
}
`;
}
