import React, { useState, useRef, useEffect, useMemo } from 'react';
import { useVoteStore } from './vote/store';
import { useCanvasStore } from './canvas/store';
import { ICONS, STICKER_SVG } from './canvas/icons';
import { CANVAS_WIDTH, CANVAS_HEIGHT } from './canvas/CanvasBoard';
import type { CanvasAction } from './canvas/types';

export const Report: React.FC<{ onBack?: () => void }> = ({ onBack }) => {
  const { currentVote, getResult } = useVoteStore();
  const { actions } = useCanvasStore();
  const reportRef = useRef<HTMLDivElement>(null);
  const [expandedOption, setExpandedOption] = useState<string | null>(null);
  const [zoom, setZoom] = useState(1);
  const [isExporting, setIsExporting] = useState(false);

  const result = useMemo(() => getResult(), [getResult, currentVote]);
  const maxVotes = Math.max(...result.items.map((i) => i.count), 1);

  const getActionsForOption = (optionId: string): CanvasAction[] => {
    return actions.filter((a) => a.associatedOptionId === optionId);
  };

  const downloadPNG = async () => {
    if (!reportRef.current || !currentVote) return;
    setIsExporting(true);

    try {
      const canvas = document.createElement('canvas');
      canvas.width = CANVAS_WIDTH;
      const height = CANVAS_HEIGHT + 600;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.fillStyle = '#1a1a1a';
      ctx.font = 'bold 48px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(currentVote.title, canvas.width / 2, 80);

      if (currentVote.description) {
        ctx.fillStyle = '#666';
        ctx.font = '22px Inter, sans-serif';
        ctx.fillText(currentVote.description, canvas.width / 2, 130);
      }

      ctx.fillStyle = '#999';
      ctx.font = '18px Inter, sans-serif';
      ctx.fillText(`邀请码: ${currentVote.inviteCode} | 总票数: ${result.totalVotes}`, canvas.width / 2, 180);

      const barChartTop = 230;
      const barWidth = 140;
      const barGap = 40;
      const totalBarWidth = currentVote.options.length * barWidth + (currentVote.options.length - 1) * barGap;
      const barStartX = (canvas.width - totalBarWidth) / 2;
      const barMaxHeight = 280;

      currentVote.options.forEach((opt, idx) => {
        const count = opt.votes;
        const barHeight = (count / maxVotes) * barMaxHeight;
        const x = barStartX + idx * (barWidth + barGap);
        const y = barChartTop + (barMaxHeight - barHeight);

        const gradient = ctx.createLinearGradient(x, y, x + barWidth, y + barHeight);
        gradient.addColorStop(0, opt.color + 'dd');
        gradient.addColorStop(1, opt.color + '99');
        ctx.fillStyle = gradient;
        roundRect(ctx, x, y, barWidth, barHeight, 16);
        ctx.fill();

        ctx.fillStyle = '#1a1a1a';
        ctx.font = 'bold 36px Inter, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(`${count}`, x + barWidth / 2, y - 24);

        ctx.fillStyle = '#333';
        ctx.font = 'bold 20px Inter, sans-serif';
        ctx.fillText(opt.text, x + barWidth / 2, barChartTop + barMaxHeight + 40);

        const pct = result.totalVotes === 0 ? 0 : Math.round((count / result.totalVotes) * 100);
        ctx.fillStyle = '#888';
        ctx.font = '16px Inter, sans-serif';
        ctx.fillText(`${pct}%`, x + barWidth / 2, barChartTop + barMaxHeight + 68);
      });

      const canvasTop = 560;
      ctx.fillStyle = '#fafafa';
      ctx.fillRect(60, canvasTop, canvas.width - 120, CANVAS_HEIGHT);
      ctx.strokeStyle = '#e9ecef';
      ctx.lineWidth = 2;
      ctx.strokeRect(60, canvasTop, canvas.width - 120, CANVAS_HEIGHT);

      ctx.save();
      ctx.translate(60, canvasTop);

      actions.forEach((action) => {
        if (action.type === 'brush') {
          ctx.strokeStyle = action.color;
          ctx.lineWidth = action.lineWidth;
          ctx.lineCap = 'round';
          ctx.lineJoin = 'round';
          ctx.globalAlpha = action.opacity;
          ctx.beginPath();
          if (action.points.length > 0) {
            ctx.moveTo(action.points[0].x, action.points[0].y);
            for (let i = 1; i < action.points.length; i++) {
              ctx.lineTo(action.points[i].x, action.points[i].y);
            }
            ctx.stroke();
          }
          ctx.globalAlpha = 1;
        }
      });

      ctx.restore();

      ctx.fillStyle = '#ccc';
      ctx.font = '14px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Generated by VoteCanvas', canvas.width / 2, canvas.height - 24);

      const link = document.createElement('a');
      link.download = `VoteCanvas_${currentVote.inviteCode}_${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (e) {
      console.error('Export failed:', e);
    } finally {
      setIsExporting(false);
    }
  };

  if (!currentVote) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%' }}>
        <div style={{ color: '#999' }}>暂无报告数据</div>
      </div>
    );
  }

  return (
    <div
      ref={reportRef}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'auto',
        background: '#fafafa',
        padding: '32px 24px 60px'
      }}
    >
      <div
        style={{
          maxWidth: '1100px',
          margin: '0 auto'
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '32px'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            {onBack && (
              <button
                onClick={onBack}
                style={{
                  padding: '10px 18px',
                  borderRadius: '12px',
                  background: '#fff',
                  border: '1px solid #e9ecef',
                  fontSize: '14px',
                  color: '#555',
                  boxShadow: '0 2px 8px rgba(0,0,0,0.05)'
                }}
              >
                ← 返回
              </button>
            )}
            <div>
              <h1 style={{ fontSize: '28px', fontWeight: 700, color: '#1a1a1a', marginBottom: '4px' }}>
                投票结果报告
              </h1>
              <p style={{ fontSize: '13px', color: '#888' }}>
                邀请码: {currentVote.inviteCode} · {result.totalVotes} 人参与
              </p>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '12px' }}>
            <button
              onClick={() => setZoom((z) => Math.max(0.5, z - 0.25))}
              style={reportBtnStyle}
            >
              🔍-
            </button>
            <div style={reportBtnStyle}>{Math.round(zoom * 100)}%</div>
            <button
              onClick={() => setZoom((z) => Math.min(2, z + 0.25))}
              style={reportBtnStyle}
            >
              🔍+
            </button>
            <button
              onClick={downloadPNG}
              disabled={isExporting}
              style={{
                ...reportBtnStyle,
                background: isExporting ? '#bfbfbf' : '#1890ff',
                color: '#fff',
                padding: '10px 20px',
                gap: '8px'
              }}
            >
              {isExporting ? '导出中...' : '📥 下载PNG'}
            </button>
          </div>
        </div>

        <div
          style={{
            background: '#fff',
            borderRadius: '16px',
            padding: '28px',
            boxShadow: '0 2px 12px rgba(0,0,0,0.05)',
            marginBottom: '24px'
          }}
        >
          <h2 style={{ fontSize: '20px', fontWeight: 600, marginBottom: '6px' }}>
            {currentVote.title}
          </h2>
          {currentVote.description && (
            <p style={{ fontSize: '14px', color: '#666', marginBottom: '28px' }}>
              {currentVote.description}
            </p>
          )}

          <svg
            viewBox={`0 0 ${800} ${320}`}
            style={{ width: '100%', height: '320px' }}
          >
            <defs>
              {currentVote.options.map((opt) => (
                <linearGradient
                  key={opt.id}
                  id={`barGrad-${opt.id}`}
                  x1="0%"
                  y1="0%"
                  x2="0%"
                  y2="100%"
                >
                  <stop offset="0%" stopColor={opt.color} stopOpacity="0.95" />
                  <stop offset="100%" stopColor={opt.color} stopOpacity="0.6" />
                </linearGradient>
              ))}
              <filter id="bar-shadow" x="-20%" y="-20%" width="140%" height="140%">
                <feDropShadow dx="0" dy="4" stdDeviation="6" floodOpacity="0.1" />
              </filter>
            </defs>

            {(() => {
              const barWidth = 100;
              const barGap = 40;
              const totalW = currentVote.options.length * barWidth + (currentVote.options.length - 1) * barGap;
              const startX = (800 - totalW) / 2;
              const chartTop = 50;
              const chartBottom = 240;
              const maxH = chartBottom - chartTop;

              return currentVote.options.map((opt, idx) => {
                const count = opt.votes;
                const barHeight = maxVotes > 0 ? (count / maxVotes) * maxH : 0;
                const x = startX + idx * (barWidth + barGap);
                const y = chartBottom - barHeight;
                const resultItem = result.items.find((i) => i.option.id === opt.id);
                const isExpanded = expandedOption === opt.id;

                return (
                  <g
                    key={opt.id}
                    onClick={() => setExpandedOption(isExpanded ? null : opt.id)}
                    style={{ cursor: 'pointer' }}
                  >
                    <rect
                      x={x}
                      y={y}
                      width={barWidth}
                      height={barHeight}
                      rx={isExpanded ? 20 : 14}
                      ry={isExpanded ? 20 : 14}
                      fill={`url(#barGrad-${opt.id})`}
                      filter="url(#bar-shadow)"
                      style={{
                        transition: 'all 300ms cubic-bezier(0.34, 1.56, 0.64, 1)',
                        transform: isExpanded ? `scale(1.08)` : undefined,
                        transformOrigin: `${x + barWidth / 2}px ${chartBottom}px`
                      }}
                    />

                    <g
                      transform={`translate(${x + barWidth / 2}, ${y - 36})`}
                      style={{
                        transition: 'all 300ms',
                        transform: isExpanded ? 'scale(1.3)' : undefined,
                        transformOrigin: 'center'
                      }}
                    >
                      <foreignObject x={-16} y={-20} width={32} height={32}>
                        <div
                          dangerouslySetInnerHTML={{
                            __html: ICONS[opt.icon as keyof typeof ICONS]?.(32, opt.color) || ''
                          }}
                          style={{ width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                        />
                      </foreignObject>
                    </g>

                    <text
                      x={x + barWidth / 2}
                      y={y - 8}
                      textAnchor="middle"
                      fill="#1a1a1a"
                      fontWeight={700}
                      fontSize={isExpanded ? 22 : 18}
                      style={{ transition: 'all 200ms' }}
                    >
                      {count}
                    </text>

                    <text
                      x={x + barWidth / 2}
                      y={chartBottom + 28}
                      textAnchor="middle"
                      fill="#333"
                      fontWeight={600}
                      fontSize={isExpanded ? 15 : 14}
                      style={{ transition: 'all 200ms' }}
                    >
                      {opt.text}
                    </text>

                    <text
                      x={x + barWidth / 2}
                      y={chartBottom + 50}
                      textAnchor="middle"
                      fill="#999"
                      fontSize={12}
                    >
                      {resultItem?.percentage || 0}%
                    </text>
                  </g>
                );
              });
            })()}
          </svg>
        </div>

        {expandedOption && (() => {
          const opt = currentVote.options.find((o) => o.id === expandedOption);
          const relatedActions = getActionsForOption(expandedOption);
          if (!opt) return null;

          return (
            <div
              className="animate-fade-in-up"
              style={{
                background: opt.color + '10',
                border: `2px solid ${opt.color}`,
                borderRadius: '16px',
                padding: '24px',
                marginBottom: '24px'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
                <div
                  dangerouslySetInnerHTML={{
                    __html: ICONS[opt.icon as keyof typeof ICONS]?.(28, opt.color) || ''
                  }}
                />
                <h3 style={{ fontSize: '18px', fontWeight: 600, color: '#1a1a1a' }}>
                  {opt.text} · 相关涂鸦 ({relatedActions.length})
                </h3>
                <button
                  onClick={() => setExpandedOption(null)}
                  style={{
                    marginLeft: 'auto',
                    padding: '6px 14px',
                    borderRadius: '10px',
                    background: '#fff',
                    fontSize: '13px',
                    color: '#666'
                  }}
                >
                  收起
                </button>
              </div>

              {relatedActions.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '40px', color: '#999', fontSize: '14px' }}>
                  该选项暂无关联的涂鸦内容
                </div>
              ) : (
                <div
                  style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
                    gap: '12px'
                  }}
                >
                  {relatedActions.map((action, idx) => (
                    <div
                      key={action.id}
                      className="animate-bounce-in"
                      style={{
                        background: '#fff',
                        borderRadius: '12px',
                        padding: '12px',
                        boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
                        animationDelay: `${idx * 0.05}s`
                      }}
                    >
                      <ActionThumbnail action={action} />
                      <div style={{ marginTop: '8px', fontSize: '12px', color: '#888' }}>
                        {action.userName}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })()}

        <div
          style={{
            background: '#fff',
            borderRadius: '16px',
            padding: '24px',
            boxShadow: '0 2px 12px rgba(0,0,0,0.05)',
            overflow: 'hidden'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
            <h3 style={{ fontSize: '18px', fontWeight: 600 }}>画板快照</h3>
            <span style={{ fontSize: '13px', color: '#888' }}>共 {actions.length} 条创作</span>
          </div>

          <div
            style={{
              width: '100%',
              overflow: 'auto',
              borderRadius: '12px',
              border: '1px solid #e9ecef',
              background: '#fafafa'
            }}
          >
            <div
              style={{
                width: CANVAS_WIDTH * zoom,
                height: CANVAS_HEIGHT * zoom,
                position: 'relative',
                minWidth: '100%'
              }}
            >
              <CanvasSnapshot actions={actions} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} scale={zoom} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const ActionThumbnail: React.FC<{ action: CanvasAction }> = ({ action }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = 160;
    canvas.height = 120;

    ctx.fillStyle = '#fafafa';
    ctx.fillRect(0, 0, 160, 120);

    if (action.type === 'brush') {
      if (action.points.length > 1) {
        const xs = action.points.map((p) => p.x);
        const ys = action.points.map((p) => p.y);
        const minX = Math.min(...xs);
        const maxX = Math.max(...xs);
        const minY = Math.min(...ys);
        const maxY = Math.max(...ys);
        const w = Math.max(maxX - minX, 10);
        const h = Math.max(maxY - minY, 10);
        const scale = Math.min(140 / w, 80 / h, 1);
        const offsetX = (160 - w * scale) / 2 - minX * scale;
        const offsetY = (120 - h * scale) / 2 - minY * scale;

        ctx.strokeStyle = action.color;
        ctx.lineWidth = action.lineWidth * scale;
        ctx.lineCap = 'round';
        ctx.lineJoin = 'round';
        ctx.globalAlpha = 0.9;
        ctx.beginPath();
        ctx.moveTo(action.points[0].x * scale + offsetX, action.points[0].y * scale + offsetY);
        for (let i = 1; i < action.points.length; i++) {
          ctx.lineTo(action.points[i].x * scale + offsetX, action.points[i].y * scale + offsetY);
        }
        ctx.stroke();
      }
    } else if (action.type === 'sticker') {
      ctx.font = '48px serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillStyle = action.color || '#FF6B6B';
      const size = 40;
      const svgStr = STICKER_SVG[action.stickerType]?.(size, action.color || '#FF6B6B') || '⭐';
      ctx.save();
      ctx.translate(80, 60);
      ctx.scale(action.scale, action.scale);
      const img = new Image();
      const svgBlob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);
      img.onload = () => {
        ctx.drawImage(img, -size / 2, -size / 2, size, size);
        URL.revokeObjectURL(url);
      };
      img.src = url;
      ctx.restore();
    } else if (action.type === 'text') {
      ctx.font = 'bold 16px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillStyle = action.bgColor;
      const textW = ctx.measureText(action.text).width + 20;
      const bx = 80 - textW / 2;
      const by = 48;
      ctx.beginPath();
      ctx.roundRect(bx, by, textW, 28, 8);
      ctx.fill();
      ctx.fillStyle = action.color;
      ctx.fillText(action.text.length > 10 ? action.text.slice(0, 10) + '...' : action.text, 80, 62);
    }
  }, [action]);

  return <canvas ref={canvasRef} style={{ width: '100%', borderRadius: '8px' }} />;
};

const CanvasSnapshot: React.FC<{ actions: CanvasAction[]; width: number; height: number; scale: number }> = ({
  actions,
  width,
  height,
  scale
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);

    const gridSize = 40;
    ctx.strokeStyle = 'rgba(0,0,0,0.03)';
    ctx.lineWidth = 1;
    for (let x = 0; x <= width; x += gridSize) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
      ctx.stroke();
    }
    for (let y = 0; y <= height; y += gridSize) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    actions.forEach((action) => {
      if (action.type === 'brush') {
        ctx.strokeStyle = action.color;
        ctx.lineWidth = action.lineWidth;
        ctx.lineCap = 'round';
        ctx.lineJoin = 'round';
        ctx.globalAlpha = action.opacity;
        ctx.beginPath();
        if (action.points.length > 0) {
          ctx.moveTo(action.points[0].x, action.points[0].y);
          for (let i = 1; i < action.points.length; i++) {
            ctx.lineTo(action.points[i].x, action.points[i].y);
          }
          ctx.stroke();
        }
        ctx.globalAlpha = 1;
      } else if (action.type === 'sticker') {
        const size = 48 * action.scale;
        const color = action.color || '#FF6B6B';
        const svgStr = STICKER_SVG[action.stickerType]?.(size, color) || '';
        const img = new Image();
        const svgBlob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(svgBlob);
        img.onload = () => {
          ctx.save();
          ctx.translate(action.x, action.y);
          ctx.rotate(action.rotation);
          ctx.drawImage(img, -size / 2, -size / 2, size, size);
          ctx.restore();
          URL.revokeObjectURL(url);
        };
        img.src = url;
      } else if (action.type === 'text') {
        ctx.font = `${action.fontSize}px Inter, sans-serif`;
        const padding = 12;
        const metrics = ctx.measureText(action.text);
        const textWidth = metrics.width;
        const bubbleWidth = textWidth + padding * 2;
        const bubbleHeight = action.fontSize + padding * 2;
        const bx = action.x - bubbleWidth / 2;
        const by = action.y - bubbleHeight / 2;

        ctx.fillStyle = action.bgColor;
        ctx.shadowColor = 'rgba(0,0,0,0.08)';
        ctx.shadowBlur = 6;
        ctx.shadowOffsetY = 2;
        ctx.beginPath();
        ctx.roundRect(bx, by, bubbleWidth, bubbleHeight, 16);
        ctx.fill();
        ctx.shadowColor = 'transparent';
        ctx.fillStyle = action.color;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.fillText(action.text, action.x, action.y);
      }
    });
  }, [actions, width, height]);

  return (
    <canvas
      ref={canvasRef}
      style={{
        width: width * scale,
        height: height * scale,
        display: 'block'
      }}
    />
  );
};

const reportBtnStyle: React.CSSProperties = {
  padding: '10px 14px',
  borderRadius: '12px',
  background: '#fff',
  border: '1px solid #e9ecef',
  fontSize: '14px',
  color: '#333',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  minWidth: '44px',
  boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
  transition: 'all 200ms'
};

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export default Report;
