export const SCENE_CONSTANTS = {
  HEMISPHERE_RADIUS: 50,
  SKY_ROTATION_SPEED: 0.001,
  STAR_COUNT: 5000,
  BRIGHT_STAR_COUNT: 30,
  OCEAN_SIZE: 100,
  MIN_CAMERA_DISTANCE: 5,
  MAX_CAMERA_DISTANCE: 30,
  MIN_POLAR_ANGLE: 0,
  MAX_POLAR_ANGLE: Math.PI / 3,
} as const;

export const NAVIGATION_CONSTANTS = {
  FLEET_SPEED: 0.5,
  WAVE_AMPLITUDE: 0.05,
  WAVE_PERIOD: 2,
  LIGHTHOUSE_HEIGHT: 0.5,
  LIGHTHOUSE_RADIUS: 0.15,
  LIGHT_BLINK_PERIOD: 0.8,
  MAX_WAYPOINTS: 10,
  MAX_LOG_ENTRIES: 20,
} as const;

export const UI_CONSTANTS = {
  SIDEBAR_WIDTH: '25%',
  SIDEBAR_MIN_WIDTH: 320,
  GALLERY_HEIGHT: 120,
  THUMBNAIL_WIDTH: 180,
  THUMBNAIL_HEIGHT: 120,
  THUMBNAIL_RADIUS: 6,
  MOBILE_BREAKPOINT: 768,
} as const;

export const COLORS = {
  PRIMARY: '#0b1628',
  SECONDARY: '#0a2a3a',
  ACCENT: '#ffd54f',
  ACCENT_LIGHT: '#ffe082',
  CARD_BG: 'rgba(26, 42, 74, 0.5)',
  CARD_HOVER: 'rgba(42, 58, 106, 0.5)',
  TEXT: '#f5f0e8',
  SUCCESS: '#66bb6a',
  DANGER: '#e53935',
  ROUTE: '#4fc3f7',
  DEEP_BLUE: '#1a3a5c',
} as const;
