import { shuffleArray } from '@/shared/utils'
import type { Difficulty } from '@/shared/utils'

export interface Word {
  id: string
  word: string
  meaning: string
  partOfSpeech: string
  difficulty: Difficulty
  example: string
}

const wordsData: Omit<Word, 'id'>[] = [
  { word: 'apple', meaning: '苹果', partOfSpeech: 'n.', difficulty: '初级', example: 'I eat an apple every day.' },
  { word: 'book', meaning: '书', partOfSpeech: 'n.', difficulty: '初级', example: 'This book is very interesting.' },
  { word: 'cat', meaning: '猫', partOfSpeech: 'n.', difficulty: '初级', example: 'The cat is sleeping on the sofa.' },
  { word: 'dog', meaning: '狗', partOfSpeech: 'n.', difficulty: '初级', example: 'My dog likes to run in the park.' },
  { word: 'egg', meaning: '鸡蛋', partOfSpeech: 'n.', difficulty: '初级', example: 'I had an egg for breakfast.' },
  { word: 'fish', meaning: '鱼', partOfSpeech: 'n.', difficulty: '初级', example: 'There are many fish in the river.' },
  { word: 'girl', meaning: '女孩', partOfSpeech: 'n.', difficulty: '初级', example: 'The girl is dancing happily.' },
  { word: 'hand', meaning: '手', partOfSpeech: 'n.', difficulty: '初级', example: 'Wash your hands before eating.' },
  { word: 'ice', meaning: '冰', partOfSpeech: 'n.', difficulty: '初级', example: 'The ice is melting in the sun.' },
  { word: 'jump', meaning: '跳', partOfSpeech: 'v.', difficulty: '初级', example: 'The rabbit can jump very high.' },
  { word: 'king', meaning: '国王', partOfSpeech: 'n.', difficulty: '初级', example: 'The king lives in a big castle.' },
  { word: 'love', meaning: '爱', partOfSpeech: 'v.', difficulty: '初级', example: 'I love my family very much.' },
  { word: 'milk', meaning: '牛奶', partOfSpeech: 'n.', difficulty: '初级', example: 'Children should drink milk every day.' },
  { word: 'name', meaning: '名字', partOfSpeech: 'n.', difficulty: '初级', example: 'What is your name?' },
  { word: 'open', meaning: '打开', partOfSpeech: 'v.', difficulty: '初级', example: 'Please open the window.' },
  { word: 'play', meaning: '玩', partOfSpeech: 'v.', difficulty: '初级', example: 'Children like to play games.' },
  { word: 'queen', meaning: '女王', partOfSpeech: 'n.', difficulty: '初级', example: 'The queen is wearing a golden crown.' },
  { word: 'rain', meaning: '雨', partOfSpeech: 'n.', difficulty: '初级', example: 'It is going to rain tomorrow.' },
  { word: 'sun', meaning: '太阳', partOfSpeech: 'n.', difficulty: '初级', example: 'The sun rises in the east.' },
  { word: 'tree', meaning: '树', partOfSpeech: 'n.', difficulty: '初级', example: 'There is a big tree in our yard.' },
  { word: 'umbrella', meaning: '雨伞', partOfSpeech: 'n.', difficulty: '初级', example: 'Take an umbrella with you.' },
  { word: 'voice', meaning: '声音', partOfSpeech: 'n.', difficulty: '初级', example: 'She has a beautiful voice.' },
  { word: 'water', meaning: '水', partOfSpeech: 'n.', difficulty: '初级', example: 'Drink more water every day.' },
  { word: 'box', meaning: '盒子', partOfSpeech: 'n.', difficulty: '初级', example: 'Put the toy in the box.' },
  { word: 'yellow', meaning: '黄色', partOfSpeech: 'adj.', difficulty: '初级', example: 'Bananas are yellow.' },
  { word: 'zoo', meaning: '动物园', partOfSpeech: 'n.', difficulty: '初级', example: 'We went to the zoo last Sunday.' },
  { word: 'bed', meaning: '床', partOfSpeech: 'n.', difficulty: '初级', example: 'I go to bed at ten o\'clock.' },
  { word: 'car', meaning: '汽车', partOfSpeech: 'n.', difficulty: '初级', example: 'My father has a new car.' },
  { word: 'door', meaning: '门', partOfSpeech: 'n.', difficulty: '初级', example: 'Please close the door.' },
  { word: 'eye', meaning: '眼睛', partOfSpeech: 'n.', difficulty: '初级', example: 'Close your eyes and sleep.' },
  { word: 'face', meaning: '脸', partOfSpeech: 'n.', difficulty: '初级', example: 'Wash your face in the morning.' },
  { word: 'game', meaning: '游戏', partOfSpeech: 'n.', difficulty: '初级', example: 'Let\'s play a game together.' },
  { word: 'happy', meaning: '快乐的', partOfSpeech: 'adj.', difficulty: '初级', example: 'I am very happy today.' },
  { word: 'idea', meaning: '主意', partOfSpeech: 'n.', difficulty: '初级', example: 'That\'s a good idea!' },
  { word: 'job', meaning: '工作', partOfSpeech: 'n.', difficulty: '初级', example: 'My mother has a busy job.' },
  { word: 'key', meaning: '钥匙', partOfSpeech: 'n.', difficulty: '初级', example: 'I lost my house key.' },
  { word: 'light', meaning: '光', partOfSpeech: 'n.', difficulty: '初级', example: 'Turn on the light please.' },
  { word: 'moon', meaning: '月亮', partOfSpeech: 'n.', difficulty: '初级', example: 'The moon is very bright tonight.' },
  { word: 'night', meaning: '夜晚', partOfSpeech: 'n.', difficulty: '初级', example: 'Good night, sweet dreams.' },
  { word: 'orange', meaning: '橙子', partOfSpeech: 'n.', difficulty: '初级', example: 'Oranges are rich in vitamin C.' },
  { word: 'paper', meaning: '纸', partOfSpeech: 'n.', difficulty: '初级', example: 'Write your name on the paper.' },
  { word: 'question', meaning: '问题', partOfSpeech: 'n.', difficulty: '初级', example: 'Do you have any questions?' },
  { word: 'room', meaning: '房间', partOfSpeech: 'n.', difficulty: '初级', example: 'Your room is very tidy.' },
  { word: 'school', meaning: '学校', partOfSpeech: 'n.', difficulty: '初级', example: 'I walk to school every day.' },
  { word: 'time', meaning: '时间', partOfSpeech: 'n.', difficulty: '初级', example: 'What time is it now?' },
  { word: 'university', meaning: '大学', partOfSpeech: 'n.', difficulty: '初级', example: 'She studies at a famous university.' },
  { word: 'village', meaning: '村庄', partOfSpeech: 'n.', difficulty: '初级', example: 'My grandma lives in a small village.' },
  { word: 'window', meaning: '窗户', partOfSpeech: 'n.', difficulty: '初级', example: 'Look out of the window.' },
  { word: 'year', meaning: '年', partOfSpeech: 'n.', difficulty: '初级', example: 'Happy New Year!' },
  { word: 'baby', meaning: '婴儿', partOfSpeech: 'n.', difficulty: '初级', example: 'The baby is crying.' },

  { word: 'achieve', meaning: '实现，达到', partOfSpeech: 'v.', difficulty: '中级', example: 'She worked hard to achieve her goal.' },
  { word: 'balance', meaning: '平衡', partOfSpeech: 'n.', difficulty: '中级', example: 'It\'s important to keep a balance between work and life.' },
  { word: 'calculate', meaning: '计算', partOfSpeech: 'v.', difficulty: '中级', example: 'Please calculate the total cost.' },
  { word: 'determine', meaning: '决定，确定', partOfSpeech: 'v.', difficulty: '中级', example: 'We need to determine the best solution.' },
  { word: 'environment', meaning: '环境', partOfSpeech: 'n.', difficulty: '中级', example: 'We should protect the environment.' },
  { word: 'fortunate', meaning: '幸运的', partOfSpeech: 'adj.', difficulty: '中级', example: 'I am fortunate to have such good friends.' },
  { word: 'generous', meaning: '慷慨的', partOfSpeech: 'adj.', difficulty: '中级', example: 'He is very generous with his time.' },
  { word: 'hesitate', meaning: '犹豫', partOfSpeech: 'v.', difficulty: '中级', example: 'Don\'t hesitate to ask for help.' },
  { word: 'imagine', meaning: '想象', partOfSpeech: 'v.', difficulty: '中级', example: 'Imagine a world without war.' },
  { word: 'journey', meaning: '旅程', partOfSpeech: 'n.', difficulty: '中级', example: 'Life is a long journey.' },
  { word: 'knowledge', meaning: '知识', partOfSpeech: 'n.', difficulty: '中级', example: 'Knowledge is power.' },
  { word: 'landscape', meaning: '风景', partOfSpeech: 'n.', difficulty: '中级', example: 'The landscape here is beautiful.' },
  { word: 'maintain', meaning: '维持，保持', partOfSpeech: 'v.', difficulty: '中级', example: 'It\'s hard to maintain a relationship.' },
  { word: 'negotiate', meaning: '谈判', partOfSpeech: 'v.', difficulty: '中级', example: 'They are negotiating a new contract.' },
  { word: 'obvious', meaning: '明显的', partOfSpeech: 'adj.', difficulty: '中级', example: 'It\'s obvious that he is lying.' },
  { word: 'participate', meaning: '参与', partOfSpeech: 'v.', difficulty: '中级', example: 'Everyone is welcome to participate.' },
  { word: 'quality', meaning: '质量', partOfSpeech: 'n.', difficulty: '中级', example: 'This product has high quality.' },
  { word: 'recognize', meaning: '认出，认可', partOfSpeech: 'v.', difficulty: '中级', example: 'I didn\'t recognize you with glasses.' },
  { word: 'schedule', meaning: '日程安排', partOfSpeech: 'n.', difficulty: '中级', example: 'What\'s your schedule for today?' },
  { word: 'traditional', meaning: '传统的', partOfSpeech: 'adj.', difficulty: '中级', example: 'It\'s a traditional Chinese festival.' },
  { word: 'unique', meaning: '独特的', partOfSpeech: 'adj.', difficulty: '中级', example: 'Every person is unique.' },
  { word: 'valuable', meaning: '有价值的', partOfSpeech: 'adj.', difficulty: '中级', example: 'Thank you for your valuable advice.' },
  { word: 'witness', meaning: '目击者，见证', partOfSpeech: 'n./v.', difficulty: '中级', example: 'She witnessed the accident.' },
  { word: 'abroad', meaning: '在国外', partOfSpeech: 'adv.', difficulty: '中级', example: 'He went abroad for further study.' },
  { word: 'benefit', meaning: '利益，好处', partOfSpeech: 'n.', difficulty: '中级', example: 'Exercise has many health benefits.' },
  { word: 'challenge', meaning: '挑战', partOfSpeech: 'n.', difficulty: '中级', example: 'This is a real challenge for me.' },
  { word: 'describe', meaning: '描述', partOfSpeech: 'v.', difficulty: '中级', example: 'Can you describe what happened?' },
  { word: 'emergency', meaning: '紧急情况', partOfSpeech: 'n.', difficulty: '中级', example: 'Call 911 in case of emergency.' },
  { word: 'familiar', meaning: '熟悉的', partOfSpeech: 'adj.', difficulty: '中级', example: 'This place looks familiar.' },
  { word: 'grateful', meaning: '感激的', partOfSpeech: 'adj.', difficulty: '中级', example: 'I am grateful for your help.' },
  { word: 'honest', meaning: '诚实的', partOfSpeech: 'adj.', difficulty: '中级', example: 'To be honest, I don\'t like it.' },
  { word: 'improve', meaning: '改进，提高', partOfSpeech: 'v.', difficulty: '中级', example: 'I want to improve my English.' },
  { word: 'jealous', meaning: '嫉妒的', partOfSpeech: 'adj.', difficulty: '中级', example: 'Don\'t be jealous of others.' },
  { word: 'kindness', meaning: '善良', partOfSpeech: 'n.', difficulty: '中级', example: 'Thank you for your kindness.' },
  { word: 'lonely', meaning: '孤独的', partOfSpeech: 'adj.', difficulty: '中级', example: 'He feels lonely in the big city.' },
  { word: 'mention', meaning: '提到', partOfSpeech: 'v.', difficulty: '中级', example: 'You didn\'t mention this before.' },
  { word: 'nervous', meaning: '紧张的', partOfSpeech: 'adj.', difficulty: '中级', example: 'I am nervous about the exam.' },
  { word: 'opportunity', meaning: '机会', partOfSpeech: 'n.', difficulty: '中级', example: 'This is a great opportunity.' },
  { word: 'patient', meaning: '耐心的', partOfSpeech: 'adj.', difficulty: '中级', example: 'Be patient with children.' },
  { word: 'relax', meaning: '放松', partOfSpeech: 'v.', difficulty: '中级', example: 'You need to relax after work.' },
  { word: 'serious', meaning: '严肃的，认真的', partOfSpeech: 'adj.', difficulty: '中级', example: 'Are you serious about this?' },
  { word: 'temperature', meaning: '温度', partOfSpeech: 'n.', difficulty: '中级', example: 'The temperature is rising.' },
  { word: 'understand', meaning: '理解', partOfSpeech: 'v.', difficulty: '中级', example: 'I don\'t understand what you mean.' },
  { word: 'vacation', meaning: '假期', partOfSpeech: 'n.', difficulty: '中级', example: 'We are going on vacation next week.' },
  { word: 'wonderful', meaning: '精彩的', partOfSpeech: 'adj.', difficulty: '中级', example: 'We had a wonderful time.' },
  { word: 'yesterday', meaning: '昨天', partOfSpeech: 'n.', difficulty: '中级', example: 'I saw him yesterday.' },
  { word: 'accept', meaning: '接受', partOfSpeech: 'v.', difficulty: '中级', example: 'I accept your apology.' },
  { word: 'believe', meaning: '相信', partOfSpeech: 'v.', difficulty: '中级', example: 'I believe in you.' },
  { word: 'confident', meaning: '自信的', partOfSpeech: 'adj.', difficulty: '中级', example: 'She is a confident speaker.' },
  { word: 'decision', meaning: '决定', partOfSpeech: 'n.', difficulty: '中级', example: 'It\'s time to make a decision.' },

  { word: 'accommodate', meaning: '容纳，适应', partOfSpeech: 'v.', difficulty: '高级', example: 'The hotel can accommodate 500 guests.' },
  { word: 'bureaucracy', meaning: '官僚主义', partOfSpeech: 'n.', difficulty: '高级', example: 'The bureaucracy slows down the process.' },
  { word: 'comprehensive', meaning: '全面的，综合的', partOfSpeech: 'adj.', difficulty: '高级', example: 'We need a comprehensive review.' },
  { word: 'deteriorate', meaning: '恶化', partOfSpeech: 'v.', difficulty: '高级', example: 'His health began to deteriorate.' },
  { word: 'entrepreneur', meaning: '企业家', partOfSpeech: 'n.', difficulty: '高级', example: 'He is a successful entrepreneur.' },
  { word: 'fluctuate', meaning: '波动', partOfSpeech: 'v.', difficulty: '高级', example: 'Stock prices fluctuate daily.' },
  { word: 'gregarious', meaning: '群居的，爱社交的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She is a gregarious person.' },
  { word: 'hypothesis', meaning: '假设', partOfSpeech: 'n.', difficulty: '高级', example: 'The hypothesis needs to be tested.' },
  { word: 'inevitable', meaning: '不可避免的', partOfSpeech: 'adj.', difficulty: '高级', example: 'Change is inevitable.' },
  { word: 'jurisdiction', meaning: '管辖权', partOfSpeech: 'n.', difficulty: '高级', example: 'This falls under federal jurisdiction.' },
  { word: 'kaleidoscope', meaning: '万花筒', partOfSpeech: 'n.', difficulty: '高级', example: 'Life is like a kaleidoscope.' },
  { word: 'legitimate', meaning: '合法的，正当的', partOfSpeech: 'adj.', difficulty: '高级', example: 'That is a legitimate concern.' },
  { word: 'meticulous', meaning: '一丝不苟的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He is meticulous about his work.' },
  { word: 'nuance', meaning: '细微差别', partOfSpeech: 'n.', difficulty: '高级', example: 'There are many nuances to consider.' },
  { word: 'ostentatious', meaning: '炫耀的', partOfSpeech: 'adj.', difficulty: '高级', example: 'They live in an ostentatious mansion.' },
  { word: 'paradigm', meaning: '范式，典范', partOfSpeech: 'n.', difficulty: '高级', example: 'This represents a paradigm shift.' },
  { word: 'quintessential', meaning: '典型的，精髓的', partOfSpeech: 'adj.', difficulty: '高级', example: 'It was the quintessential summer day.' },
  { word: 'repercussion', meaning: '反响，后果', partOfSpeech: 'n.', difficulty: '高级', example: 'The decision had serious repercussions.' },
  { word: 'scrutinize', meaning: '仔细检查', partOfSpeech: 'v.', difficulty: '高级', example: 'The contract was scrutinized carefully.' },
  { word: 'tangential', meaning: '切线的，离题的', partOfSpeech: 'adj.', difficulty: '高级', example: 'That is tangential to our main topic.' },
  { word: 'ubiquitous', meaning: '无处不在的', partOfSpeech: 'adj.', difficulty: '高级', example: 'Smartphones are ubiquitous today.' },
  { word: 'vicarious', meaning: '间接的，替代的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She lived vicariously through her children.' },
  { word: 'whimsical', meaning: '异想天开的', partOfSpeech: 'adj.', difficulty: '高级', example: 'The story has a whimsical charm.' },
  { word: 'xenophobia', meaning: '仇外心理', partOfSpeech: 'n.', difficulty: '高级', example: 'Xenophobia should be condemned.' },
  { word: 'zealous', meaning: '热心的，热情的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She is a zealous supporter of the cause.' },
  { word: 'ambiguous', meaning: '模糊的，模棱两可的', partOfSpeech: 'adj.', difficulty: '高级', example: 'The statement is ambiguous.' },
  { word: 'benevolent', meaning: '仁慈的', partOfSpeech: 'adj.', difficulty: '高级', example: 'The benevolent king was loved by all.' },
  { word: 'chronological', meaning: '按时间顺序的', partOfSpeech: 'adj.', difficulty: '高级', example: 'List the events in chronological order.' },
  { word: 'dichotomy', meaning: '二分法，对立', partOfSpeech: 'n.', difficulty: '高级', example: 'There is a dichotomy between theory and practice.' },
  { word: 'ephemeral', meaning: '短暂的', partOfSpeech: 'adj.', difficulty: '高级', example: 'Fame is often ephemeral.' },
  { word: 'fallacious', meaning: '谬误的', partOfSpeech: 'adj.', difficulty: '高级', example: 'That is a fallacious argument.' },
  { word: 'gerrymandering', meaning: '不公正划分选区', partOfSpeech: 'n.', difficulty: '高级', example: 'Gerrymandering affects election results.' },
  { word: 'hegemony', meaning: '霸权', partOfSpeech: 'n.', difficulty: '高级', example: 'They challenged the cultural hegemony.' },
  { word: 'idiosyncratic', meaning: '独特的，特异的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He has an idiosyncratic style.' },
  { word: 'juxtaposition', meaning: '并列，并置', partOfSpeech: 'n.', difficulty: '高级', example: 'The juxtaposition creates a striking effect.' },
  { word: 'lackadaisical', meaning: '无精打采的', partOfSpeech: 'adj.', difficulty: '高级', example: 'His lackadaisical attitude was frustrating.' },
  { word: 'magnanimous', meaning: '宽宏大量的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He was magnanimous in victory.' },
  { word: 'nonchalant', meaning: '漠不关心的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She appeared nonchalant about the news.' },
  { word: 'obfuscate', meaning: '使混淆，使模糊', partOfSpeech: 'v.', difficulty: '高级', example: 'They tried to obfuscate the truth.' },
  { word: 'perfunctory', meaning: '敷衍的，马虎的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He gave a perfunctory nod.' },
  { word: 'quixotic', meaning: '不切实际的', partOfSpeech: 'adj.', difficulty: '高级', example: 'It was a quixotic quest.' },
  { word: 'recalcitrant', meaning: '顽抗的，不服从的', partOfSpeech: 'adj.', difficulty: '高级', example: 'The recalcitrant student was expelled.' },
  { word: 'surreptitious', meaning: '秘密的，偷偷的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He made a surreptitious glance.' },
  { word: 'tenacious', meaning: '顽强的，坚韧的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She is tenacious in pursuing her goals.' },
  { word: 'unprecedented', meaning: '史无前例的', partOfSpeech: 'adj.', difficulty: '高级', example: 'This is an unprecedented situation.' },
  { word: 'vituperative', meaning: '辱骂的，斥责的', partOfSpeech: 'adj.', difficulty: '高级', example: 'He launched into a vituperative tirade.' },
  { word: 'wistful', meaning: '渴望的，怀旧的', partOfSpeech: 'adj.', difficulty: '高级', example: 'She gave a wistful smile.' },
  { word: 'yielding', meaning: '顺从的，易弯曲的', partOfSpeech: 'adj.', difficulty: '高级', example: 'The yielding surface absorbed the impact.' },
  { word: 'zenith', meaning: '顶点，顶峰', partOfSpeech: 'n.', difficulty: '高级', example: 'He was at the zenith of his career.' },
  { word: 'aberration', meaning: '偏差，异常', partOfSpeech: 'n.', difficulty: '高级', example: 'This behavior is an aberration.' },
]

const allWords: Word[] = wordsData.map((w, index) => ({
  ...w,
  id: `word-${index + 1}`,
}))

export function getAllWords(): Word[] {
  return allWords
}

async function fetchWords(difficulty: Difficulty, count: number = 10): Promise<Word[]> {
  return new Promise((resolve) => {
    setTimeout(() => {
      const filtered = allWords.filter((w) => w.difficulty === difficulty)
      const shuffled = shuffleArray(filtered)
      resolve(shuffled.slice(0, Math.min(count, shuffled.length)))
    }, 300)
  })
}

export default {
  fetchWords,
}
