import { saveAs } from 'file-saver';
import type { LayoutParams } from './LayoutEngine';

const SYSTEM_FONTS = new Set([
  'Arial', 'Arial Black', 'Verdana', 'Tahoma', 'Trebuchet MS',
  'Georgia', 'Times New Roman', 'Courier New', 'Lucida Console',
  'Impact', 'Comic Sans MS', 'Palatino', 'Garamond', 'Bookman',
  'Cambria', 'Didot', 'Calibri', 'Candara', 'Futura', 'Franklin Gothic',
  'Century Gothic', 'Copperplate', 'Brush Script MT', 'Lucida Calligraphy',
  'Blackadder ITC', 'Edwardian Script', 'Freestyle Script', 'Harrington',
  'Mistral', 'Old English Text MT', 'Parchment', 'Ravie', 'Snap ITC',
  'Stencil', 'Wide Latin', 'Viner Hand ITC', 'Vivaldi', 'Script MT Bold',
  'Curlz MT', 'Bradley Hand', 'Baskerville', 'Helvetica Neue', 'Segoe UI',
  'Microsoft YaHei', '微软雅黑', 'SimSun', '宋体', 'KaiTi', '楷体',
  'PingFang SC', '苹方', 'Heiti SC', '黑体'
]);

export class CodeExporter {
  private isSystemFont(fontFamily: string): boolean {
    return SYSTEM_FONTS.has(fontFamily);
  }

  private generateGoogleFontsLink(fontFamily: string): string {
    if (this.isSystemFont(fontFamily)) {
      return '';
    }
    const encodedFamily = encodeURIComponent(fontFamily).replace(/%20/g, '+');
    return `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=${encodedFamily}:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">`;
  }

  private generateFontFaceDeclaration(fontFamily: string): string {
    const safeFamily = fontFamily.includes(' ') ? `"${fontFamily}"` : fontFamily;
    if (this.isSystemFont(fontFamily)) {
      return `@font-face {
  font-family: ${safeFamily};
  src: local('${fontFamily}');
  font-display: swap;
}`;
    }
    return `@font-face {
  font-family: ${safeFamily};
  font-display: swap;
}`;
  }

  generateFullHTML(params: LayoutParams, css: string): string {
    const fontFamily = params.fontFamily.includes(' ') 
      ? `"${params.fontFamily}"` 
      : params.fontFamily;

    const escapedText = this.escapeHtml(params.text);
    const googleFontsLink = this.generateGoogleFontsLink(params.fontFamily);
    const fontFaceDecl = this.generateFontFaceDeclaration(params.fontFamily);

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Typography preview generated by Font Inspiration Sandbox">
  <title>Typography Preview - ${this.escapeHtml(params.fontFamily)}</title>
  ${googleFontsLink}
  <style>
    *,
    *::before,
    *::after {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      height: 100%;
      min-height: 100vh;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: linear-gradient(135deg, #f7f9fc 0%, #e8edf3 100%);
      padding: 40px 20px;
      color: #1e3a5f;
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-rendering: optimizeLegibility;
    }

    .page-wrapper {
      max-width: 1100px;
      margin: 0 auto;
      min-height: calc(100vh - 80px);
      display: flex;
      flex-direction: column;
      gap: 32px;
    }

    .page-header {
      text-align: center;
      padding: 24px;
    }

    .page-header h1 {
      font-size: 14px;
      font-weight: 500;
      color: #6b7c93;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      margin-bottom: 8px;
    }

    .page-header p {
      font-size: 12px;
      color: #a0aec0;
    }

    .preview-card {
      flex: 1;
      background: #ffffff;
      border-radius: 16px;
      box-shadow:
        0 1px 3px rgba(0, 0, 0, 0.05),
        0 8px 24px rgba(30, 58, 95, 0.08),
        0 24px 48px rgba(30, 58, 95, 0.06);
      padding: 64px 48px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      position: relative;
    }

    .preview-card::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 3px;
      background: linear-gradient(90deg, #4a6fa5, #ff6b6b, #4a6fa5);
    }

    ${fontFaceDecl}

    .typography-preview {
      font-family: ${fontFamily}, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: ${params.fontSize}px;
      line-height: ${params.lineHeight};
      letter-spacing: ${params.letterSpacing}em;
      color: ${params.color};
      word-wrap: break-word;
      overflow-wrap: break-word;
      -webkit-hyphens: auto;
      hyphens: auto;
      max-width: 100%;
    }

    .info-section {
      background: #ffffff;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
      overflow: hidden;
    }

    .info-header {
      padding: 16px 24px;
      background: linear-gradient(135deg, #f0f4f8 0%, #e8edf3 100%);
      border-bottom: 1px solid #d1d9e6;
    }

    .info-header h2 {
      font-size: 13px;
      font-weight: 600;
      color: #1e3a5f;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .info-content {
      padding: 24px;
    }

    .info-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 16px;
    }

    .info-item {
      padding: 16px;
      background: #fafbfc;
      border-radius: 8px;
      border: 1px solid #f0f4f8;
      transition: all 0.2s ease;
    }

    .info-item:hover {
      border-color: #4a6fa5;
      background: #ffffff;
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(74, 111, 165, 0.1);
    }

    .info-label {
      display: block;
      font-size: 11px;
      font-weight: 600;
      color: #6b7c93;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 6px;
    }

    .info-value {
      font-size: 15px;
      font-weight: 600;
      color: #4a6fa5;
      word-break: break-word;
    }

    .color-preview {
      display: inline-flex;
      align-items: center;
      gap: 8px;
    }

    .color-swatch {
      width: 20px;
      height: 20px;
      border-radius: 4px;
      border: 2px solid #ffffff;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
      vertical-align: middle;
    }

    .css-section {
      margin-top: 24px;
      background: #1e3a5f;
      border-radius: 8px;
      overflow: hidden;
    }

    .css-header {
      padding: 12px 20px;
      background: rgba(0, 0, 0, 0.2);
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .css-header span {
      color: #e8edf3;
      font-size: 12px;
      font-weight: 500;
      letter-spacing: 0.05em;
    }

    .css-dots {
      display: flex;
      gap: 6px;
    }

    .css-dots span {
      width: 12px;
      height: 12px;
      border-radius: 50%;
    }

    .css-dots span:nth-child(1) { background: #ff6b6b; }
    .css-dots span:nth-child(2) { background: #ffd93d; }
    .css-dots span:nth-child(3) { background: #6bcb77; }

    .css-code {
      padding: 20px;
      overflow-x: auto;
      font-family: 'JetBrains Mono', 'Fira Code', 'SF Mono', 'Consolas', monospace;
      font-size: 13px;
      line-height: 1.6;
      color: #e8edf3;
    }

    .css-code code {
      display: block;
      white-space: pre-wrap;
      word-break: break-word;
    }

    .page-footer {
      text-align: center;
      padding: 20px;
      font-size: 11px;
      color: #a0aec0;
    }

    @media (max-width: 768px) {
      body {
        padding: 20px 16px;
      }

      .preview-card {
        padding: 32px 24px;
        border-radius: 12px;
      }

      .info-grid {
        grid-template-columns: repeat(2, 1fr);
        gap: 12px;
      }

      .info-content {
        padding: 16px;
      }
    }

    @media (max-width: 480px) {
      .info-grid {
        grid-template-columns: 1fr;
      }
    }
  </style>
</head>
<body>
  <div class="page-wrapper">
    <header class="page-header">
      <h1>✨ Typography Preview</h1>
      <p>Generated by Font Inspiration Sandbox</p>
    </header>

    <main class="preview-card">
      <p class="typography-preview">${escapedText}</p>
    </main>

    <section class="info-section">
      <div class="info-header">
        <h2>📐 Typography Properties</h2>
      </div>
      <div class="info-content">
        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Font Family</span>
            <span class="info-value">${this.escapeHtml(params.fontFamily)}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Font Size</span>
            <span class="info-value">${params.fontSize}px</span>
          </div>
          <div class="info-item">
            <span class="info-label">Line Height</span>
            <span class="info-value">${params.lineHeight}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Letter Spacing</span>
            <span class="info-value">${params.letterSpacing}em</span>
          </div>
          <div class="info-item">
            <span class="info-label">Text Color</span>
            <span class="info-value color-preview">
              <span class="color-swatch" style="background-color: ${params.color}"></span>
              ${params.color}
            </span>
          </div>
          <div class="info-item">
            <span class="info-label">Characters</span>
            <span class="info-value">${params.text.length}</span>
          </div>
        </div>

        <div class="css-section">
          <div class="css-header">
            <div class="css-dots">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <span>CSS</span>
          </div>
          <pre class="css-code"><code>${this.escapeHtml(css)}</code></pre>
        </div>
      </div>
    </section>

    <footer class="page-footer">
      Generated with ❤️ by Font Inspiration Sandbox
    </footer>
  </div>
</body>
</html>`;
  }

  generateCSSOnly(css: string): string {
    return `/* ============================================
   Typography CSS
   Generated by Font Inspiration Sandbox
   ============================================ */

${css}

/* 
Usage Example:

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Font+Name:wght@400;700&display=swap" rel="stylesheet">

<p class="typography-preview">Your beautiful text here</p>
*/
`;
  }

  generateHTMLSnippet(params: LayoutParams): string {
    const escapedText = this.escapeHtml(params.text);
    return `<!-- Typography Snippet -->
<p class="typography-preview">${escapedText}</p>`;
  }

  async downloadHTML(params: LayoutParams, css: string): Promise<void> {
    const html = this.generateFullHTML(params, css);
    const blob = new Blob([html], { 
      type: 'text/html;charset=utf-8',
      endings: 'native'
    });
    const timestamp = this.generateTimestamp();
    const safeFontName = params.fontFamily.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
    saveAs(blob, `typography_${safeFontName}_${timestamp}.html`);
  }

  async copyToClipboard(content: string): Promise<boolean> {
    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(content);
        return true;
      }
      return this.fallbackCopy(content);
    } catch {
      return this.fallbackCopy(content);
    }
  }

  private fallbackCopy(content: string): boolean {
    try {
      const textArea = document.createElement('textarea');
      textArea.value = content;
      textArea.style.position = 'fixed';
      textArea.style.left = '-99999px';
      textArea.style.top = '-99999px';
      textArea.style.width = '1px';
      textArea.style.height = '1px';
      textArea.style.opacity = '0';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      textArea.setSelectionRange(0, 9999999);
      const successful = document.execCommand('copy');
      document.body.removeChild(textArea);
      return successful;
    } catch {
      return false;
    }
  }

  private generateTimestamp(): string {
    const now = new Date();
    const pad = (n: number) => String(n).padStart(2, '0');
    return (
      now.getFullYear().toString() +
      pad(now.getMonth() + 1) +
      pad(now.getDate()) +
      pad(now.getHours()) +
      pad(now.getMinutes()) +
      pad(now.getSeconds())
    );
  }

  private escapeHtml(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}
