import type { Scene, SceneType } from './types';

export const sceneTypeLabels: Record<SceneType, string> = {
  initial: '初次接触',
  objection: '异议处理',
  negotiation: '价格谈判',
  closing: '促成成交',
  followup: '售后跟进',
  custom: '自定义场景',
};

export const sceneTypeColors: Record<SceneType, string> = {
  initial: 'bg-blue-100 text-blue-800',
  objection: 'bg-orange-100 text-orange-800',
  negotiation: 'bg-purple-100 text-purple-800',
  closing: 'bg-green-100 text-green-800',
  followup: 'bg-cyan-100 text-cyan-800',
  custom: 'bg-gray-100 text-gray-800',
};

const presetScenes: Scene[] = [
  {
    id: 'scene-initial-1',
    name: '电话初次拜访',
    description: '通过电话首次联系潜在客户，建立初步信任并预约下次沟通',
    type: 'initial',
    difficulty: 2,
    startNodeId: 'node-1',
    nodes: {
      'node-1': {
        id: 'node-1',
        type: 'system',
        text: '您好，我是XX公司的销售代表李明，请问您是张经理吗？',
        options: [
          {
            id: 'opt-1-1',
            text: '您好李经理，我是张经理，请问有什么可以帮您的？',
            keywords: ['您好', '李经理', '张经理', '帮您'],
            score: 95,
            feedback: '非常专业的回应，礼貌且明确，展现了良好的职业素养。',
            nextNodeId: 'node-2',
            isOptimal: true,
          },
          {
            id: 'opt-1-2',
            text: '嗯，我是，什么事？',
            keywords: ['我是', '什么事'],
            score: 70,
            feedback: '回应略显生硬，建议增加问候语，建立更友好的沟通氛围。',
            nextNodeId: 'node-2',
          },
          {
            id: 'opt-1-3',
            text: '你打错了，我不是张经理。',
            keywords: ['打错了', '不是'],
            score: 0,
            feedback: '这不是正确的回应方式，客户不会主动说自己不是目标联系人。',
            nextNodeId: 'node-1',
          },
        ],
        position: { x: 100, y: 100 },
      },
      'node-2': {
        id: 'node-2',
        type: 'system',
        text: '张经理您好，非常感谢您百忙之中接听我的电话。我们公司专注于企业数字化转型解决方案，最近帮助很多同行业客户提升了30%的运营效率。想请教一下，贵公司目前在数字化转型方面有什么规划吗？',
        options: [
          {
            id: 'opt-2-1',
            text: '我们确实有这方面的考虑，你能具体介绍一下你们的方案吗？',
            keywords: ['确实', '考虑', '具体介绍', '方案'],
            score: 95,
            feedback: '太棒了！客户表现出明确兴趣，这是推进销售的好机会。',
            nextNodeId: 'node-3',
            isOptimal: true,
          },
          {
            id: 'opt-2-2',
            text: '我们暂时不需要，谢谢。',
            keywords: ['暂时', '不需要', '谢谢'],
            score: 50,
            feedback: '客户表示暂时不需要，这是常见的初次拒绝，需要巧妙回应而不是放弃。',
            nextNodeId: 'node-4',
          },
          {
            id: 'opt-2-3',
            text: '这个事情我不太清楚，你找我们技术部吧。',
            keywords: ['不清楚', '技术部'],
            score: 60,
            feedback: '客户推脱责任，需要确认关键决策人信息。',
            nextNodeId: 'node-5',
          },
        ],
        position: { x: 100, y: 250 },
      },
      'node-3': {
        id: 'node-3',
        type: 'system',
        text: '好的张经理，我们的方案主要包含三个核心模块：智能数据分析系统、流程自动化平台和移动端协同办公。根据贵公司的具体需求，我们可以提供定制化的方案。您看什么时候方便，我安排技术顾问给您做一个详细的演示？',
        options: [
          {
            id: 'opt-3-1',
            text: '那就安排在后天下午两点吧，我也叫上技术负责人一起参加。',
            keywords: ['后天', '下午两点', '技术负责人', '参加'],
            score: 100,
            feedback: '完美！成功预约了高质量的演示会议，并且客户主动邀请技术负责人，成交概率很高。',
            nextNodeId: 'node-6',
            isOptimal: true,
          },
          {
            id: 'opt-3-2',
            text: '你先发一些资料过来我先看看吧。',
            keywords: ['发资料', '先看看'],
            score: 75,
            feedback: '客户希望先了解资料，这是正常的决策过程。需要及时发送资料并跟进。',
            nextNodeId: 'node-6',
          },
          {
            id: 'opt-3-3',
            text: '我先考虑一下，有需要再联系你。',
            keywords: ['考虑一下', '再联系'],
            score: 60,
            feedback: '客户还在犹豫阶段，需要主动设置下次跟进时间，避免失去联系。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 100, y: 400 },
      },
      'node-4': {
        id: 'node-4',
        type: 'system',
        text: '理解张经理，您平时工作肯定很忙。我不会占用您太多时间，只是想了解一下，如果未来有这方面需求的话，什么样的解决方案会对您有帮助呢？',
        options: [
          {
            id: 'opt-4-1',
            text: '如果能降低我们的人工成本，可能会考虑。',
            keywords: ['降低', '人工成本', '考虑'],
            score: 85,
            feedback: '很好！客户透露了核心痛点，可以针对这个需求提供具体案例。',
            nextNodeId: 'node-6',
            isOptimal: true,
          },
          {
            id: 'opt-4-2',
            text: '以后再说吧，现在真的很忙。',
            keywords: ['以后再说', '很忙'],
            score: 55,
            feedback: '客户再次拒绝，需要礼貌结束并约定后续联系的时间窗口。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 400, y: 400 },
      },
      'node-5': {
        id: 'node-5',
        type: 'system',
        text: '好的张经理，麻烦您告诉我技术部负责人的姓名和联系方式，我直接和他沟通，这样也不会耽误您的时间。',
        options: [
          {
            id: 'opt-5-1',
            text: '技术负责人是王工，电话是138XXXX1234，你可以直接联系他。',
            keywords: ['王工', '138', '直接联系'],
            score: 90,
            feedback: '成功获取关键决策人信息，这是非常重要的进展。',
            nextNodeId: 'node-6',
            isOptimal: true,
          },
          {
            id: 'opt-5-2',
            text: '你直接打公司总机转技术部就行。',
            keywords: ['总机', '技术部'],
            score: 70,
            feedback: '只获得了总机信息，需要后续想办法获取具体联系人。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 700, y: 400 },
      },
      'node-6': {
        id: 'node-6',
        type: 'system',
        text: '非常感谢张经理的时间和信息，我会按照我们的约定安排后续工作。请问还有什么我可以帮到您的吗？',
        options: [
          {
            id: 'opt-6-1',
            text: '没有了，保持联系。',
            keywords: ['保持联系'],
            score: 90,
            feedback: '对话圆满结束，记得在约定时间前发送提醒邮件。',
            isOptimal: true,
          },
          {
            id: 'opt-6-2',
            text: '好的，再见。',
            keywords: ['再见'],
            score: 80,
            feedback: '对话正常结束，可以主动添加客户微信便于后续沟通。',
          },
        ],
        position: { x: 100, y: 550 },
      },
    },
    edges: [
      { id: 'edge-1', from: 'node-1', to: 'node-2' },
      { id: 'edge-2', from: 'node-2', to: 'node-3' },
      { id: 'edge-3', from: 'node-2', to: 'node-4' },
      { id: 'edge-4', from: 'node-2', to: 'node-5' },
      { id: 'edge-5', from: 'node-3', to: 'node-6' },
      { id: 'edge-6', from: 'node-4', to: 'node-6' },
      { id: 'edge-7', from: 'node-5', to: 'node-6' },
    ],
  },
  {
    id: 'scene-objection-1',
    name: '客户价格异议处理',
    description: '客户认为产品价格过高，需要通过价值展示化解价格异议',
    type: 'objection',
    difficulty: 3,
    startNodeId: 'node-1',
    nodes: {
      'node-1': {
        id: 'node-1',
        type: 'system',
        text: '李经理，你们的方案我大概了解了，但说实话，这个价格比我预期的高了不少。',
        options: [
          {
            id: 'opt-1-1',
            text: '王总，我理解您的感受，价格确实是重要的考虑因素。能不能先请教一下，您是和什么产品做比较觉得我们的价格高呢？',
            keywords: ['理解', '感受', '请教', '比较'],
            score: 90,
            feedback: '非常好！首先共情客户，然后通过提问了解客户的价格参照标准，为后续价值展示做铺垫。',
            nextNodeId: 'node-2',
            isOptimal: true,
          },
          {
            id: 'opt-1-2',
            text: '王总，我们的价格其实不算高，一分钱一分货嘛。',
            keywords: ['不算高', '一分钱一分货'],
            score: 50,
            feedback: '直接反驳客户容易引起对立，建议先认同再引导。',
            nextNodeId: 'node-3',
          },
          {
            id: 'opt-1-3',
            text: '那您觉得什么样的价格比较合适呢？',
            keywords: ['什么样的价格', '合适'],
            score: 60,
            feedback: '过早询问价格底线，容易陷入单纯的价格谈判，应该先展示价值。',
            nextNodeId: 'node-4',
          },
        ],
        position: { x: 100, y: 100 },
      },
      'node-2': {
        id: 'node-2',
        type: 'system',
        text: '主要是和XX公司比较，他们的报价比你们低了20%。',
        options: [
          {
            id: 'opt-2-1',
            text: '感谢王总的坦诚。XX公司确实是不错的竞争对手。不过王总，除了价格，您在选择供应商时还看重哪些因素呢？比如产品稳定性、售后服务、技术支持这些？',
            keywords: ['感谢', '坦诚', '除了价格', '看重', '稳定性', '售后服务', '技术支持'],
            score: 95,
            feedback: '太棒了！认可竞争对手避免了对比攻击，同时引导客户关注价格以外的价值因素。',
            nextNodeId: 'node-5',
            isOptimal: true,
          },
          {
            id: 'opt-2-2',
            text: 'XX公司的产品质量不如我们，您不能只看价格。',
            keywords: ['不如我们', '不能只看价格'],
            score: 55,
            feedback: '贬低竞争对手是销售大忌，会让客户怀疑你的专业性。',
            nextNodeId: 'node-3',
          },
          {
            id: 'opt-2-3',
            text: '那您之前了解过我们和XX公司在功能上的区别吗？',
            keywords: ['了解过', '功能', '区别'],
            score: 75,
            feedback: '引导关注功能差异是对的，但可以先通过提问了解客户更看重什么。',
            nextNodeId: 'node-5',
          },
        ],
        position: { x: 100, y: 250 },
      },
      'node-3': {
        id: 'node-3',
        type: 'system',
        text: '你这样说就没意思了，每个公司都说自己的产品好。我就问你，这个价格能不能再降一点？',
        options: [
          {
            id: 'opt-3-1',
            text: '王总您别生气，我非常理解您的立场。这样好不好，我们不着急谈价格，先看看我们的方案能帮您解决哪些实际问题、创造多少价值，您觉得这些价值值不值这个价，怎么样？',
            keywords: ['别生气', '理解', '不着急', '解决', '实际问题', '创造', '价值'],
            score: 85,
            feedback: '及时缓和气氛，把话题从单纯的价格谈判拉回到价值讨论上。',
            nextNodeId: 'node-5',
            isOptimal: true,
          },
          {
            id: 'opt-3-2',
            text: '价格真的已经很低了，我们的成本就在那里。',
            keywords: ['很低', '成本'],
            score: 45,
            feedback: '站在卖方角度强调成本，客户不会关心你的成本，只关心自己获得的价值。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 400, y: 250 },
      },
      'node-4': {
        id: 'node-4',
        type: 'system',
        text: '我觉得至少要降15%才合理。',
        options: [
          {
            id: 'opt-4-1',
            text: '王总，我理解您希望获得最优价格的心情。15%的折扣确实超出了我的权限，但我可以向公司申请。不过在这之前，能不能先确认一下，如果我们能给到这个价格，您这边是不是就能马上签约了？',
            keywords: ['理解', '最优价格', '超出权限', '申请', '确认', '马上签约'],
            score: 90,
            feedback: '非常专业的谈判技巧！不直接拒绝，但设置了前提条件，避免无意义的价格让步。',
            nextNodeId: 'node-6',
            isOptimal: true,
          },
          {
            id: 'opt-4-2',
            text: '15%太多了，最多给您降5%。',
            keywords: ['太多', '最多', '5%'],
            score: 60,
            feedback: '过早给出让步空间，而且没有设置任何交换条件。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 700, y: 250 },
      },
      'node-5': {
        id: 'node-5',
        type: 'system',
        text: '嗯，你说的也有道理。售后服务确实很重要，之前那家供应商的响应速度就很慢。',
        options: [
          {
            id: 'opt-5-1',
            text: '非常认同王总！选择供应商确实不能只看采购成本，还要考虑使用成本。我们的7x24小时响应机制，能确保您的问题在2小时内得到处理。上个月我们有个客户，就是因为系统故障及时得到处理，避免了上百万的损失。这些价值其实远远超过了初期的价格差异。',
            keywords: ['认同', '采购成本', '使用成本', '7x24', '2小时', '客户案例', '价值', '超过', '价格差异'],
            score: 100,
            feedback: '完美！通过客户痛点引入具体的服务承诺，再用真实案例量化价值，让客户感受到价格背后的价值。',
            nextNodeId: 'node-6',
            isOptimal: true,
          },
          {
            id: 'opt-5-2',
            text: '对的，我们的售后服务确实做得很好。',
            keywords: ['售后服务', '很好'],
            score: 65,
            feedback: '回答太笼统，没有具体化，也没有量化价值。',
            nextNodeId: 'node-6',
          },
        ],
        position: { x: 100, y: 400 },
      },
      'node-6': {
        id: 'node-6',
        type: 'system',
        text: '你说的这些我都明白了，让我再考虑考虑，下周给你答复。',
        options: [
          {
            id: 'opt-6-1',
            text: '好的王总，感谢您的时间。为了帮助您更好地做决策，我明天把我们服务过的同行业客户案例整理一份发给您，您看周三上午还是下午方便，我再给您打个电话沟通一下？',
            keywords: ['感谢', '帮助', '决策', '客户案例', '周三', '沟通'],
            score: 95,
            feedback: '非常好！不是被动等待，而是主动提供帮助并锁定下次跟进时间。',
            isOptimal: true,
          },
          {
            id: 'opt-6-2',
            text: '好的王总，那我等您消息。',
            keywords: ['等您消息'],
            score: 60,
            feedback: '被动等待很容易失去跟进机会，应该主动设置下次沟通的时间。',
          },
        ],
        position: { x: 100, y: 550 },
      },
    },
    edges: [
      { id: 'edge-1', from: 'node-1', to: 'node-2' },
      { id: 'edge-2', from: 'node-1', to: 'node-3' },
      { id: 'edge-3', from: 'node-1', to: 'node-4' },
      { id: 'edge-4', from: 'node-2', to: 'node-5' },
      { id: 'edge-5', from: 'node-2', to: 'node-3' },
      { id: 'edge-6', from: 'node-3', to: 'node-5' },
      { id: 'edge-7', from: 'node-4', to: 'node-6' },
      { id: 'edge-8', from: 'node-5', to: 'node-6' },
    ],
  },
  {
    id: 'scene-negotiation-1',
    name: '商务价格谈判',
    description: '进入最终商务谈判阶段，需要在保证利润的前提下达成合作',
    type: 'negotiation',
    difficulty: 4,
    startNodeId: 'node-1',
    nodes: {
      'node-1': {
        id: 'node-1',
        type: 'system',
        text: '李经理，方案和功能我们都很满意，现在就看价格了。如果价格合适，我们这个季度就可以启动项目。',
        options: [
          {
            id: 'opt-1-1',
            text: '非常感谢王总的认可！您觉得什么样的价格对贵公司来说是合适的呢？另外，我也想确认一下，如果价格达成一致，合同最快什么时候能签？',
            keywords: ['感谢', '认可', '什么样的价格', '合适', '确认', '合同', '什么时候签'],
            score: 95,
            feedback: '太棒了！首先确认成交信号，然后了解客户的价格预期，同时设置签约前提。',
            nextNodeId: 'node-2',
            isOptimal: true,
          },
          {
            id: 'opt-1-2',
            text: '王总，我们的报价已经是最优惠的了，您也看到我们方案的价值了。',
            keywords: ['最优惠', '价值'],
            score: 55,
            feedback: '过早锁死价格，没有了解客户预期就强调优惠，容易陷入被动。',
            nextNodeId: