import type { Recipe } from './types';

export const RECIPES: Recipe[] = [
  {
    id: 'r01',
    name: '番茄炒蛋',
    difficulty: 'easy',
    calories: 180,
    cookTime: 15,
    tags: ['家常', '快手菜'],
    ingredients: [
      { name: '番茄', amount: 2, unit: '个', isRequired: true },
      { name: '鸡蛋', amount: 3, unit: '个', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '糖', amount: 5, unit: 'g', isRequired: false },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '番茄洗净切块，鸡蛋打散加少许盐搅匀' },
      { stepNumber: 2, description: '锅中倒油烧至七成热，倒入蛋液翻炒至凝固盛出', timerSeconds: 60, timerLabel: '炒鸡蛋' },
      { stepNumber: 3, description: '锅中再倒少许油，放入番茄块翻炒出汁', timerSeconds: 120, timerLabel: '炒番茄' },
      { stepNumber: 4, description: '加入白糖和盐调味，倒回鸡蛋翻炒均匀即可' },
    ],
    nutritionRatio: { carbs: 0.35, protein: 0.4, fat: 0.25 },
  },
  {
    id: 'r02',
    name: '红烧肉',
    difficulty: 'medium',
    calories: 450,
    cookTime: 90,
    tags: ['经典', '硬菜'],
    ingredients: [
      { name: '五花肉', amount: 500, unit: 'g', isRequired: true },
      { name: '生姜', amount: 15, unit: 'g', isRequired: true },
      { name: '大葱', amount: 20, unit: 'g', isRequired: true },
      { name: '八角', amount: 2, unit: '个', isRequired: false },
      { name: '酱油', amount: 30, unit: 'ml', isRequired: true },
      { name: '冰糖', amount: 20, unit: 'g', isRequired: true },
      { name: '料酒', amount: 30, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '五花肉切3厘米方块，冷水下锅焯水去腥' },
      { stepNumber: 2, description: '锅中放少许油，小火炒冰糖至焦糖色', timerSeconds: 180, timerLabel: '炒糖色' },
      { stepNumber: 3, description: '放入肉块翻炒上色，加入姜葱八角' },
      { stepNumber: 4, description: '倒入料酒和酱油，加开水没过肉面' },
      { stepNumber: 5, description: '大火烧开转小火炖60分钟', timerSeconds: 3600, timerLabel: '炖煮' },
      { stepNumber: 6, description: '大火收汁至浓稠即可' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.3, fat: 0.5 },
  },
  {
    id: 'r03',
    name: '清蒸鲈鱼',
    difficulty: 'medium',
    calories: 200,
    cookTime: 25,
    tags: ['健康', '海鲜'],
    ingredients: [
      { name: '鲈鱼', amount: 1, unit: '条', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '大葱', amount: 15, unit: 'g', isRequired: true },
      { name: '蒸鱼豉油', amount: 30, unit: 'ml', isRequired: true },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '鲈鱼处理干净，鱼身划几刀，抹少许盐' },
      { stepNumber: 2, description: '鱼身铺姜丝，放入蒸锅大火蒸8-10分钟', timerSeconds: 600, timerLabel: '蒸鱼' },
      { stepNumber: 3, description: '倒掉蒸出的汤汁，铺上葱丝' },
      { stepNumber: 4, description: '淋上蒸鱼豉油，浇上热油激香' },
    ],
    nutritionRatio: { carbs: 0.15, protein: 0.6, fat: 0.25 },
  },
  {
    id: 'r04',
    name: '麻婆豆腐',
    difficulty: 'easy',
    calories: 220,
    cookTime: 20,
    tags: ['川菜', '下饭'],
    ingredients: [
      { name: '豆腐', amount: 400, unit: 'g', isRequired: true },
      { name: '猪肉末', amount: 100, unit: 'g', isRequired: true },
      { name: '豆瓣酱', amount: 20, unit: 'g', isRequired: true },
      { name: '花椒粉', amount: 3, unit: 'g', isRequired: false },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '小葱', amount: 5, unit: 'g', isRequired: false },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '豆腐切2厘米方块，焯水备用' },
      { stepNumber: 2, description: '热油炒肉末至变色，加豆瓣酱炒出红油', timerSeconds: 90, timerLabel: '炒肉末' },
      { stepNumber: 3, description: '加入适量清水烧开，放入豆腐小火炖5分钟', timerSeconds: 300, timerLabel: '炖豆腐' },
      { stepNumber: 4, description: '水淀粉勾芡，撒花椒粉和葱花出锅' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r05',
    name: '宫保鸡丁',
    difficulty: 'medium',
    calories: 280,
    cookTime: 25,
    tags: ['川菜', '经典'],
    ingredients: [
      { name: '鸡胸肉', amount: 250, unit: 'g', isRequired: true },
      { name: '花生米', amount: 50, unit: 'g', isRequired: true },
      { name: '干辣椒', amount: 8, unit: '个', isRequired: true },
      { name: '花椒', amount: 5, unit: 'g', isRequired: false },
      { name: '大葱', amount: 15, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '醋', amount: 10, unit: 'ml', isRequired: true },
      { name: '糖', amount: 10, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '鸡胸肉切丁，加料酒和淀粉腌制10分钟' },
      { stepNumber: 2, description: '花生米小火炒至金黄备用', timerSeconds: 180, timerLabel: '炒花生' },
      { stepNumber: 3, description: '热油爆香干辣椒和花椒，下鸡丁翻炒', timerSeconds: 120, timerLabel: '炒鸡丁' },
      { stepNumber: 4, description: '加入酱油、醋、糖调成的酱汁，翻炒均匀' },
      { stepNumber: 5, description: '最后撒入花生米翻匀出锅' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.45, fat: 0.25 },
  },
  {
    id: 'r06',
    name: '蒜蓉西兰花',
    difficulty: 'easy',
    calories: 100,
    cookTime: 10,
    tags: ['健康', '素食'],
    ingredients: [
      { name: '西兰花', amount: 300, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 15, unit: 'g', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '西兰花掰小朵，清水浸泡10分钟后洗净' },
      { stepNumber: 2, description: '烧开水焯烫西兰花1分钟捞出', timerSeconds: 60, timerLabel: '焯水' },
      { stepNumber: 3, description: '热油爆香蒜末，倒入西兰花翻炒', timerSeconds: 120, timerLabel: '翻炒' },
      { stepNumber: 4, description: '加盐调味，翻炒均匀出锅' },
    ],
    nutritionRatio: { carbs: 0.45, protein: 0.3, fat: 0.25 },
  },
  {
    id: 'r07',
    name: '糖醋排骨',
    difficulty: 'medium',
    calories: 380,
    cookTime: 45,
    tags: ['经典', '硬菜'],
    ingredients: [
      { name: '排骨', amount: 500, unit: 'g', isRequired: true },
      { name: '醋', amount: 30, unit: 'ml', isRequired: true },
      { name: '糖', amount: 40, unit: 'g', isRequired: true },
      { name: '酱油', amount: 20, unit: 'ml', isRequired: true },
      { name: '料酒', amount: 20, unit: 'ml', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '大葱', amount: 10, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '排骨斩小段焯水去血沫' },
      { stepNumber: 2, description: '锅中放少许油，炒排骨至表面微黄', timerSeconds: 180, timerLabel: '煎排骨' },
      { stepNumber: 3, description: '加入料酒、酱油、醋、糖和适量水' },
      { stepNumber: 4, description: '大火烧开转小火炖30分钟', timerSeconds: 1800, timerLabel: '炖煮' },
      { stepNumber: 5, description: '大火收汁至浓稠，撒上白芝麻' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.35, fat: 0.35 },
  },
  {
    id: 'r08',
    name: '蛋炒饭',
    difficulty: 'easy',
    calories: 320,
    cookTime: 10,
    tags: ['快手菜', '主食'],
    ingredients: [
      { name: '米饭', amount: 300, unit: 'g', isRequired: true },
      { name: '鸡蛋', amount: 2, unit: '个', isRequired: true },
      { name: '小葱', amount: 10, unit: 'g', isRequired: false },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '鸡蛋打散，小葱切葱花' },
      { stepNumber: 2, description: '热油倒入蛋液快速翻炒至半凝固' },
      { stepNumber: 3, description: '倒入米饭大火翻炒，使每粒米裹上蛋液', timerSeconds: 180, timerLabel: '翻炒' },
      { stepNumber: 4, description: '加盐调味，撒葱花出锅' },
    ],
    nutritionRatio: { carbs: 0.55, protein: 0.2, fat: 0.25 },
  },
  {
    id: 'r09',
    name: '酸辣土豆丝',
    difficulty: 'easy',
    calories: 150,
    cookTime: 15,
    tags: ['家常', '下饭'],
    ingredients: [
      { name: '土豆', amount: 300, unit: 'g', isRequired: true },
      { name: '干辣椒', amount: 5, unit: '个', isRequired: true },
      { name: '醋', amount: 15, unit: 'ml', isRequired: true },
      { name: '大蒜', amount: 8, unit: 'g', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '土豆去皮切细丝，泡水去淀粉' },
      { stepNumber: 2, description: '热油爆香干辣椒和蒜末' },
      { stepNumber: 3, description: '倒入土豆丝大火快炒2分钟', timerSeconds: 120, timerLabel: '翻炒' },
      { stepNumber: 4, description: '沿锅边淋入醋，加盐调味翻匀出锅' },
    ],
    nutritionRatio: { carbs: 0.55, protein: 0.15, fat: 0.3 },
  },
  {
    id: 'r10',
    name: '鱼香肉丝',
    difficulty: 'medium',
    calories: 260,
    cookTime: 25,
    tags: ['川菜', '经典'],
    ingredients: [
      { name: '猪里脊', amount: 200, unit: 'g', isRequired: true },
      { name: '胡萝卜', amount: 50, unit: 'g', isRequired: true },
      { name: '木耳', amount: 30, unit: 'g', isRequired: true },
      { name: '青椒', amount: 50, unit: 'g', isRequired: false },
      { name: '豆瓣酱', amount: 15, unit: 'g', isRequired: true },
      { name: '醋', amount: 10, unit: 'ml', isRequired: true },
      { name: '糖', amount: 15, unit: 'g', isRequired: true },
      { name: '酱油', amount: 10, unit: 'ml', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '生姜', amount: 5, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '猪里脊切丝，加料酒淀粉腌制' },
      { stepNumber: 2, description: '胡萝卜、木耳、青椒切丝备用' },
      { stepNumber: 3, description: '热油滑炒肉丝至变色盛出', timerSeconds: 60, timerLabel: '炒肉丝' },
      { stepNumber: 4, description: '爆香蒜末姜末和豆瓣酱，加入配菜翻炒' },
      { stepNumber: 5, description: '倒回肉丝，加鱼香汁（醋、糖、酱油）翻炒均匀' },
    ],
    nutritionRatio: { carbs: 0.35, protein: 0.4, fat: 0.25 },
  },
  {
    id: 'r11',
    name: '白灼虾',
    difficulty: 'easy',
    calories: 120,
    cookTime: 10,
    tags: ['海鲜', '健康'],
    ingredients: [
      { name: '基围虾', amount: 500, unit: 'g', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '大葱', amount: 10, unit: 'g', isRequired: true },
      { name: '料酒', amount: 15, unit: 'ml', isRequired: false },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '虾去虾线洗净，姜切片葱切段' },
      { stepNumber: 2, description: '锅中加水放入姜片葱段和料酒烧开' },
      { stepNumber: 3, description: '放入虾煮至变红（约2-3分钟）', timerSeconds: 150, timerLabel: '煮虾' },
      { stepNumber: 4, description: '捞出摆盘，配酱油蘸食' },
    ],
    nutritionRatio: { carbs: 0.1, protein: 0.7, fat: 0.2 },
  },
  {
    id: 'r12',
    name: '可乐鸡翅',
    difficulty: 'easy',
    calories: 300,
    cookTime: 30,
    tags: ['创意', '下饭'],
    ingredients: [
      { name: '鸡翅', amount: 10, unit: '个', isRequired: true },
      { name: '可乐', amount: 330, unit: 'ml', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '料酒', amount: 15, unit: 'ml', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '鸡翅两面划刀，焯水去腥' },
      { stepNumber: 2, description: '锅中少许油，煎鸡翅至两面金黄', timerSeconds: 180, timerLabel: '煎鸡翅' },
      { stepNumber: 3, description: '倒入可乐和酱油，加姜片' },
      { stepNumber: 4, description: '大火烧开转中火炖20分钟', timerSeconds: 1200, timerLabel: '炖煮' },
      { stepNumber: 5, description: '大火收汁至浓稠即可' },
    ],
    nutritionRatio: { carbs: 0.4, protein: 0.35, fat: 0.25 },
  },
  {
    id: 'r13',
    name: '西红柿牛腩',
    difficulty: 'hard',
    calories: 350,
    cookTime: 120,
    tags: ['经典', '硬菜'],
    ingredients: [
      { name: '牛腩', amount: 500, unit: 'g', isRequired: true },
      { name: '番茄', amount: 3, unit: '个', isRequired: true },
      { name: '土豆', amount: 200, unit: 'g', isRequired: false },
      { name: '洋葱', amount: 100, unit: 'g', isRequired: true },
      { name: '番茄酱', amount: 30, unit: 'g', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '八角', amount: 2, unit: '个', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '牛腩切块焯水去血沫，番茄切块' },
      { stepNumber: 2, description: '热油炒香洋葱和姜片，加入番茄炒出汁' },
      { stepNumber: 3, description: '放入牛腩翻炒，加番茄酱和适量水' },
      { stepNumber: 4, description: '大火烧开转小火炖90分钟', timerSeconds: 5400, timerLabel: '炖牛腩' },
      { stepNumber: 5, description: '加入土豆块继续炖15分钟', timerSeconds: 900, timerLabel: '炖土豆' },
      { stepNumber: 6, description: '加盐调味出锅' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r14',
    name: '蒜蓉蒸扇贝',
    difficulty: 'medium',
    calories: 150,
    cookTime: 15,
    tags: ['海鲜', '宴客'],
    ingredients: [
      { name: '扇贝', amount: 6, unit: '个', isRequired: true },
      { name: '大蒜', amount: 20, unit: 'g', isRequired: true },
      { name: '小葱', amount: 5, unit: 'g', isRequired: false },
      { name: '酱油', amount: 10, unit: 'ml', isRequired: true },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '扇贝洗净，蒜切末' },
      { stepNumber: 2, description: '每个扇贝上铺满蒜末', timerSeconds: 120, timerLabel: '铺蒜蓉' },
      { stepNumber: 3, description: '水开后上锅蒸6-8分钟', timerSeconds: 480, timerLabel: '蒸扇贝' },
      { stepNumber: 4, description: '出锅淋酱油和热油，撒葱花' },
    ],
    nutritionRatio: { carbs: 0.15, protein: 0.55, fat: 0.3 },
  },
  {
    id: 'r15',
    name: '地三鲜',
    difficulty: 'easy',
    calories: 200,
    cookTime: 20,
    tags: ['东北菜', '素食'],
    ingredients: [
      { name: '土豆', amount: 200, unit: 'g', isRequired: true },
      { name: '茄子', amount: 200, unit: 'g', isRequired: true },
      { name: '青椒', amount: 100, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '糖', amount: 5, unit: 'g', isRequired: false },
      { name: '食用油', amount: 30, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '土豆茄子切滚刀块，青椒切块' },
      { stepNumber: 2, description: '油锅炸至土豆和茄子表面金黄捞出', timerSeconds: 300, timerLabel: '油炸' },
      { stepNumber: 3, description: '留底油爆香蒜末，加酱油糖调味' },
      { stepNumber: 4, description: '倒入全部食材翻炒均匀，勾薄芡出锅' },
    ],
    nutritionRatio: { carbs: 0.45, protein: 0.15, fat: 0.4 },
  },
  {
    id: 'r16',
    name: '葱爆羊肉',
    difficulty: 'medium',
    calories: 320,
    cookTime: 15,
    tags: ['北方菜', '下饭'],
    ingredients: [
      { name: '羊肉片', amount: 300, unit: 'g', isRequired: true },
      { name: '大葱', amount: 100, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '料酒', amount: 15, unit: 'ml', isRequired: true },
      { name: '孜然粉', amount: 5, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '大葱切斜段，羊肉片加料酒腌制' },
      { stepNumber: 2, description: '热锅大火爆炒羊肉至变色盛出', timerSeconds: 60, timerLabel: '爆炒羊肉' },
      { stepNumber: 3, description: '余油炒葱段至微软' },
      { stepNumber: 4, description: '倒回羊肉，加酱油孜然粉大火翻匀出锅' },
    ],
    nutritionRatio: { carbs: 0.15, protein: 0.45, fat: 0.4 },
  },
  {
    id: 'r17',
    name: '黄瓜炒鸡蛋',
    difficulty: 'easy',
    calories: 130,
    cookTime: 10,
    tags: ['家常', '快手菜'],
    ingredients: [
      { name: '黄瓜', amount: 1, unit: '个', isRequired: true },
      { name: '鸡蛋', amount: 3, unit: '个', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '黄瓜切片，鸡蛋打散' },
      { stepNumber: 2, description: '热油炒鸡蛋至凝固盛出' },
      { stepNumber: 3, description: '同锅炒黄瓜片1分钟', timerSeconds: 60, timerLabel: '炒黄瓜' },
      { stepNumber: 4, description: '倒回鸡蛋翻匀，加盐调味' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r18',
    name: '红烧茄子',
    difficulty: 'easy',
    calories: 180,
    cookTime: 20,
    tags: ['家常', '素食'],
    ingredients: [
      { name: '茄子', amount: 400, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 15, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '糖', amount: 10, unit: 'g', isRequired: false },
      { name: '醋', amount: 5, unit: 'ml', isRequired: false },
      { name: '食用油', amount: 20, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '茄子切滚刀块，撒盐腌制10分钟挤水' },
      { stepNumber: 2, description: '热油煎茄子至两面金黄', timerSeconds: 180, timerLabel: '煎茄子' },
      { stepNumber: 3, description: '爆香蒜末，加酱油糖醋调味' },
      { stepNumber: 4, description: '放入茄子翻炒均匀，小火焖2分钟', timerSeconds: 120, timerLabel: '焖煮' },
    ],
    nutritionRatio: { carbs: 0.4, protein: 0.15, fat: 0.45 },
  },
  {
    id: 'r19',
    name: '清炒时蔬',
    difficulty: 'easy',
    calories: 80,
    cookTime: 8,
    tags: ['健康', '素食'],
    ingredients: [
      { name: '时令蔬菜', amount: 300, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '蔬菜洗净切好，蒜切片' },
      { stepNumber: 2, description: '热油爆香蒜片' },
      { stepNumber: 3, description: '大火快炒蔬菜2分钟', timerSeconds: 120, timerLabel: '快炒' },
      { stepNumber: 4, description: '加盐调味出锅' },
    ],
    nutritionRatio: { carbs: 0.5, protein: 0.25, fat: 0.25 },
  },
  {
    id: 'r20',
    name: '水煮牛肉',
    difficulty: 'hard',
    calories: 380,
    cookTime: 40,
    tags: ['川菜', '辣'],
    ingredients: [
      { name: '牛肉', amount: 300, unit: 'g', isRequired: true },
      { name: '豆芽', amount: 150, unit: 'g', isRequired: true },
      { name: '生菜', amount: 100, unit: 'g', isRequired: false },
      { name: '豆瓣酱', amount: 20, unit: 'g', isRequired: true },
      { name: '干辣椒', amount: 10, unit: '个', isRequired: true },
      { name: '花椒', amount: 10, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 15, unit: 'g', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '牛肉切薄片，加料酒和淀粉腌制' },
      { stepNumber: 2, description: '豆芽和生菜焯水铺碗底' },
      { stepNumber: 3, description: '热油炒香豆瓣酱姜蒜末，加水烧开' },
      { stepNumber: 4, description: '下入牛肉片滑散至变色捞出铺菜上', timerSeconds: 90, timerLabel: '煮牛肉' },
      { stepNumber: 5, description: '撒上干辣椒碎和花椒，浇上热油激香' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.5, fat: 0.3 },
  },
  {
    id: 'r21',
    name: '香菇滑鸡',
    difficulty: 'easy',
    calories: 230,
    cookTime: 30,
    tags: ['家常', '下饭'],
    ingredients: [
      { name: '鸡腿肉', amount: 300, unit: 'g', isRequired: true },
      { name: '香菇', amount: 150, unit: 'g', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '料酒', amount: 10, unit: 'ml', isRequired: false },
      { name: '淀粉', amount: 10, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '鸡腿肉切块，加酱油料酒淀粉腌制15分钟' },
      { stepNumber: 2, description: '香菇切块，姜切片' },
      { stepNumber: 3, description: '热油炒香姜片，放入鸡块翻炒', timerSeconds: 120, timerLabel: '炒鸡块' },
      { stepNumber: 4, description: '加入香菇和适量水，小火炖10分钟', timerSeconds: 600, timerLabel: '炖煮' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.5, fat: 0.3 },
  },
  {
    id: 'r22',
    name: '凉拌黄瓜',
    difficulty: 'easy',
    calories: 60,
    cookTime: 5,
    tags: ['凉菜', '快手菜'],
    ingredients: [
      { name: '黄瓜', amount: 2, unit: '个', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '醋', amount: 15, unit: 'ml', isRequired: true },
      { name: '辣椒油', amount: 10, unit: 'ml', isRequired: false },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '糖', amount: 5, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '黄瓜拍碎切小段，蒜切末' },
      { stepNumber: 2, description: '加蒜末、醋、盐、糖拌匀' },
      { stepNumber: 3, description: '淋上辣椒油，冷藏10分钟后食用更佳', timerSeconds: 600, timerLabel: '冷藏' },
    ],
    nutritionRatio: { carbs: 0.5, protein: 0.15, fat: 0.35 },
  },
  {
    id: 'r23',
    name: '紫菜蛋花汤',
    difficulty: 'easy',
    calories: 80,
    cookTime: 10,
    tags: ['汤品', '快手菜'],
    ingredients: [
      { name: '紫菜', amount: 10, unit: 'g', isRequired: true },
      { name: '鸡蛋', amount: 2, unit: '个', isRequired: true },
      { name: '小葱', amount: 5, unit: 'g', isRequired: false },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '香油', amount: 5, unit: 'ml', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '紫菜撕碎，鸡蛋打散' },
      { stepNumber: 2, description: '锅中加水烧开，放入紫菜' },
      { stepNumber: 3, description: '沿锅边缓缓倒入蛋液，形成蛋花', timerSeconds: 30, timerLabel: '倒蛋液' },
      { stepNumber: 4, description: '加盐和香油调味，撒葱花出锅' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r24',
    name: '干煸四季豆',
    difficulty: 'medium',
    calories: 170,
    cookTime: 20,
    tags: ['川菜', '下饭'],
    ingredients: [
      { name: '四季豆', amount: 400, unit: 'g', isRequired: true },
      { name: '猪肉末', amount: 80, unit: 'g', isRequired: true },
      { name: '干辣椒', amount: 5, unit: '个', isRequired: true },
      { name: '大蒜', amount: 10, unit: 'g', isRequired: true },
      { name: '酱油', amount: 10, unit: 'ml', isRequired: true },
      { name: '食用油', amount: 20, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '四季豆去筋掰段' },
      { stepNumber: 2, description: '油温七成下四季豆炸至表面起皱', timerSeconds: 240, timerLabel: '炸四季豆' },
      { stepNumber: 3, description: '留底油炒肉末至酥香，加蒜末干辣椒' },
      { stepNumber: 4, description: '倒入四季豆加酱油翻炒均匀' },
    ],
    nutritionRatio: { carbs: 0.35, protein: 0.3, fat: 0.35 },
  },
  {
    id: 'r25',
    name: '韭菜炒鸡蛋',
    difficulty: 'easy',
    calories: 150,
    cookTime: 10,
    tags: ['家常', '快手菜'],
    ingredients: [
      { name: '韭菜', amount: 200, unit: 'g', isRequired: true },
      { name: '鸡蛋', amount: 3, unit: '个', isRequired: true },
      { name: '盐', amount: 3, unit: 'g', isRequired: false },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '韭菜切段，鸡蛋打散' },
      { stepNumber: 2, description: '热油炒鸡蛋至半凝固盛出' },
      { stepNumber: 3, description: '同锅炒韭菜30秒', timerSeconds: 30, timerLabel: '炒韭菜' },
      { stepNumber: 4, description: '倒回鸡蛋翻匀，加盐调味' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r26',
    name: '回锅肉',
    difficulty: 'medium',
    calories: 350,
    cookTime: 30,
    tags: ['川菜', '经典'],
    ingredients: [
      { name: '五花肉', amount: 300, unit: 'g', isRequired: true },
      { name: '青蒜', amount: 100, unit: 'g', isRequired: true },
      { name: '豆瓣酱', amount: 20, unit: 'g', isRequired: true },
      { name: '甜面酱', amount: 10, unit: 'g', isRequired: false },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '五花肉整块冷水下锅煮至八成熟', timerSeconds: 1200, timerLabel: '煮肉' },
      { stepNumber: 2, description: '捞出晾凉切薄片，青蒜切段' },
      { stepNumber: 3, description: '热锅少油煎肉片至出油卷起', timerSeconds: 120, timerLabel: '煎肉片' },
      { stepNumber: 4, description: '推至锅边，下豆瓣酱姜蒜末炒出红油' },
      { stepNumber: 5, description: '加入甜面酱和青蒜翻炒均匀出锅' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.3, fat: 0.5 },
  },
  {
    id: 'r27',
    name: '皮蛋豆腐',
    difficulty: 'easy',
    calories: 120,
    cookTime: 5,
    tags: ['凉菜', '快手菜'],
    ingredients: [
      { name: '皮蛋', amount: 2, unit: '个', isRequired: true },
      { name: '豆腐', amount: 300, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '香油', amount: 5, unit: 'ml', isRequired: false },
      { name: '小葱', amount: 5, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '豆腐切小块摆盘' },
      { stepNumber: 2, description: '皮蛋切瓣铺在豆腐上' },
      { stepNumber: 3, description: '淋上酱油和香油，撒葱花' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.45, fat: 0.35 },
  },
  {
    id: 'r28',
    name: '玉米排骨汤',
    difficulty: 'easy',
    calories: 200,
    cookTime: 60,
    tags: ['汤品', '滋补'],
    ingredients: [
      { name: '排骨', amount: 400, unit: 'g', isRequired: true },
      { name: '玉米', amount: 1, unit: '个', isRequired: true },
      { name: '胡萝卜', amount: 100, unit: 'g', isRequired: false },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '盐', amount: 5, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '排骨焯水去血沫，玉米胡萝卜切块' },
      { stepNumber: 2, description: '砂锅加排骨姜片和水大火烧开' },
      { stepNumber: 3, description: '转小火炖40分钟', timerSeconds: 2400, timerLabel: '炖排骨' },
      { stepNumber: 4, description: '加入玉米胡萝卜继续炖15分钟', timerSeconds: 900, timerLabel: '炖玉米' },
      { stepNumber: 5, description: '加盐调味即可' },
    ],
    nutritionRatio: { carbs: 0.35, protein: 0.35, fat: 0.3 },
  },
  {
    id: 'r29',
    name: '蚝油生菜',
    difficulty: 'easy',
    calories: 70,
    cookTime: 5,
    tags: ['快手菜', '素食'],
    ingredients: [
      { name: '生菜', amount: 300, unit: 'g', isRequired: true },
      { name: '蚝油', amount: 15, unit: 'ml', isRequired: true },
      { name: '大蒜', amount: 8, unit: 'g', isRequired: true },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '生菜洗净掰开' },
      { stepNumber: 2, description: '开水焯烫生菜30秒捞出摆盘', timerSeconds: 30, timerLabel: '焯水' },
      { stepNumber: 3, description: '热油爆香蒜末，加蚝油和少许水煮开' },
      { stepNumber: 4, description: '将蚝油汁浇在生菜上' },
    ],
    nutritionRatio: { carbs: 0.4, protein: 0.2, fat: 0.4 },
  },
  {
    id: 'r30',
    name: '木须肉',
    difficulty: 'easy',
    calories: 240,
    cookTime: 15,
    tags: ['家常', '下饭'],
    ingredients: [
      { name: '猪里脊', amount: 150, unit: 'g', isRequired: true },
      { name: '鸡蛋', amount: 3, unit: '个', isRequired: true },
      { name: '木耳', amount: 30, unit: 'g', isRequired: true },
      { name: '黄瓜', amount: 50, unit: 'g', isRequired: false },
      { name: '酱油', amount: 10, unit: 'ml', isRequired: true },
      { name: '料酒', amount: 10, unit: 'ml', isRequired: false },
      { name: '大葱', amount: 10, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '猪里脊切片，加料酒腌制，鸡蛋打散' },
      { stepNumber: 2, description: '热油炒鸡蛋至凝固盛出' },
      { stepNumber: 3, description: '再热油炒肉片至变色，加葱和木耳翻炒', timerSeconds: 90, timerLabel: '炒肉片' },
      { stepNumber: 4, description: '倒入鸡蛋，加酱油调味翻匀' },
    ],
    nutritionRatio: { carbs: 0.25, protein: 0.45, fat: 0.3 },
  },
  {
    id: 'r31',
    name: '椒盐虾',
    difficulty: 'medium',
    calories: 220,
    cookTime: 20,
    tags: ['海鲜', '下酒'],
    ingredients: [
      { name: '基围虾', amount: 400, unit: 'g', isRequired: true },
      { name: '椒盐', amount: 5, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 15, unit: 'g', isRequired: true },
      { name: '干辣椒', amount: 3, unit: '个', isRequired: false },
      { name: '食用油', amount: 30, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '虾去虾线剪去虾须，沥干水分' },
      { stepNumber: 2, description: '油温七成炸虾至酥脆金黄', timerSeconds: 180, timerLabel: '炸虾' },
      { stepNumber: 3, description: '留底油爆香蒜末和干辣椒' },
      { stepNumber: 4, description: '倒入炸好的虾，撒椒盐翻匀' },
    ],
    nutritionRatio: { carbs: 0.15, protein: 0.5, fat: 0.35 },
  },
  {
    id: 'r32',
    name: '蒜苔炒肉',
    difficulty: 'easy',
    calories: 200,
    cookTime: 15,
    tags: ['家常', '下饭'],
    ingredients: [
      { name: '蒜苔', amount: 250, unit: 'g', isRequired: true },
      { name: '猪肉', amount: 150, unit: 'g', isRequired: true },
      { name: '酱油', amount: 10, unit: 'ml', isRequired: true },
      { name: '料酒', amount: 10, unit: 'ml', isRequired: false },
      { name: '生姜', amount: 5, unit: 'g', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '蒜苔切段，猪肉切丝加料酒腌制' },
      { stepNumber: 2, description: '热油炒肉丝至变色盛出' },
      { stepNumber: 3, description: '同锅炒蒜苔至断生', timerSeconds: 120, timerLabel: '炒蒜苔' },
      { stepNumber: 4, description: '倒回肉丝，加酱油翻匀出锅' },
    ],
    nutritionRatio: { carbs: 0.35, protein: 0.35, fat: 0.3 },
  },
  {
    id: 'r33',
    name: '醋溜白菜',
    difficulty: 'easy',
    calories: 90,
    cookTime: 10,
    tags: ['家常', '素食'],
    ingredients: [
      { name: '白菜', amount: 400, unit: 'g', isRequired: true },
      { name: '醋', amount: 20, unit: 'ml', isRequired: true },
      { name: '干辣椒', amount: 3, unit: '个', isRequired: false },
      { name: '大蒜', amount: 8, unit: 'g', isRequired: true },
      { name: '食用油', amount: 10, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '白菜手撕成片，蒜切片' },
      { stepNumber: 2, description: '热油爆香蒜片和干辣椒' },
      { stepNumber: 3, description: '大火炒白菜至软', timerSeconds: 90, timerLabel: '翻炒' },
      { stepNumber: 4, description: '沿锅边淋入醋，快速翻匀出锅' },
    ],
    nutritionRatio: { carbs: 0.5, protein: 0.15, fat: 0.35 },
  },
  {
    id: 'r34',
    name: '红烧豆腐',
    difficulty: 'easy',
    calories: 160,
    cookTime: 15,
    tags: ['素食', '家常'],
    ingredients: [
      { name: '豆腐', amount: 400, unit: 'g', isRequired: true },
      { name: '酱油', amount: 15, unit: 'ml', isRequired: true },
      { name: '糖', amount: 5, unit: 'g', isRequired: false },
      { name: '大葱', amount: 10, unit: 'g', isRequired: true },
      { name: '大蒜', amount: 8, unit: 'g', isRequired: true },
      { name: '食用油', amount: 15, unit: 'ml', isRequired: true },
    ],
    steps: [
      { stepNumber: 1, description: '豆腐切块，葱蒜切末' },
      { stepNumber: 2, description: '热油煎豆腐至两面金黄', timerSeconds: 180, timerLabel: '煎豆腐' },
      { stepNumber: 3, description: '爆香葱蒜末，加酱油糖和水' },
      { stepNumber: 4, description: '放入豆腐小火焖3分钟', timerSeconds: 180, timerLabel: '焖煮' },
    ],
    nutritionRatio: { carbs: 0.3, protein: 0.4, fat: 0.3 },
  },
  {
    id: 'r35',
    name: '蘑菇鸡汤',
    difficulty: 'easy',
    calories: 180,
    cookTime: 50,
    tags: ['汤品', '滋补'],
    ingredients: [
      { name: '鸡肉', amount: 400, unit: 'g', isRequired: true },
      { name: '蘑菇', amount: 200, unit: 'g', isRequired: true },
      { name: '生姜', amount: 10, unit: 'g', isRequired: true },
      { name: '红枣', amount: 5, unit: '个', isRequired: false },
      { name: '盐', amount: 5, unit: 'g', isRequired: false },
    ],
    steps: [
      { stepNumber: 1, description: '鸡肉焯水，蘑菇洗净撕开' },
      { stepNumber: 2, description: '砂锅放入鸡肉姜片红枣加水烧开' },
      { stepNumber: 3, description: '小火炖30分钟', timerSeconds: 1800, timerLabel: '炖鸡' },
      { stepNumber: 4, description: '加入蘑菇继续炖15分钟', timerSeconds: 900, timerLabel: '炖蘑菇' },
      { stepNumber: 5, description: '加盐调味即可' },
    ],
    nutritionRatio: { carbs: 0.2, protein: 0.5, fat: 0.3 },
  },
];
