import type { Ingredient } from '../types';

export const FOOD_DATABASE: Ingredient[] = [
  {
    id: 'chicken-breast',
    name: '鸡胸肉',
    emoji: '🍗',
    category: 'protein',
    nutrition: { calories: 165, protein: 31, carbs: 0, fat: 3.6 },
    flavors: ['umami'],
    pixelIcon: '🐔',
  },
  {
    id: 'beef',
    name: '牛肉',
    emoji: '🥩',
    category: 'protein',
    nutrition: { calories: 250, protein: 26, carbs: 0, fat: 15 },
    flavors: ['umami'],
    pixelIcon: '🐄',
  },
  {
    id: 'shrimp',
    name: '虾仁',
    emoji: '🦐',
    category: 'protein',
    nutrition: { calories: 99, protein: 24, carbs: 0, fat: 0.3 },
    flavors: ['umami', 'sweet'],
    pixelIcon: '🦐',
  },
  {
    id: 'tofu',
    name: '豆腐',
    emoji: '🧈',
    category: 'protein',
    nutrition: { calories: 76, protein: 8, carbs: 1.9, fat: 4.8 },
    flavors: ['umami'],
    pixelIcon: '🧈',
  },
  {
    id: 'egg',
    name: '鸡蛋',
    emoji: '🥚',
    category: 'protein',
    nutrition: { calories: 155, protein: 13, carbs: 1.1, fat: 11 },
    flavors: ['umami'],
    pixelIcon: '🥚',
  },
  {
    id: 'broccoli',
    name: '西兰花',
    emoji: '🥦',
    category: 'vegetable',
    nutrition: { calories: 34, protein: 2.8, carbs: 7, fat: 0.4 },
    flavors: ['bitter'],
    pixelIcon: '🥦',
  },
  {
    id: 'carrot',
    name: '胡萝卜',
    emoji: '🥕',
    category: 'vegetable',
    nutrition: { calories: 41, protein: 0.9, carbs: 10, fat: 0.2 },
    flavors: ['sweet'],
    pixelIcon: '🥕',
  },
  {
    id: 'tomato',
    name: '番茄',
    emoji: '🍅',
    category: 'vegetable',
    nutrition: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
    flavors: ['sour', 'sweet'],
    pixelIcon: '🍅',
  },
  {
    id: 'bell-pepper',
    name: '青椒',
    emoji: '🫑',
    category: 'vegetable',
    nutrition: { calories: 20, protein: 0.9, carbs: 4.6, fat: 0.2 },
    flavors: ['bitter', 'sweet'],
    pixelIcon: '🫑',
  },
  {
    id: 'mushroom',
    name: '蘑菇',
    emoji: '🍄',
    category: 'vegetable',
    nutrition: { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
    flavors: ['umami'],
    pixelIcon: '🍄',
  },
  {
    id: 'spinach',
    name: '菠菜',
    emoji: '🥬',
    category: 'vegetable',
    nutrition: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
    flavors: ['bitter'],
    pixelIcon: '🥬',
  },
  {
    id: 'soy-sauce',
    name: '酱油',
    emoji: '🫗',
    category: 'seasoning',
    nutrition: { calories: 53, protein: 8, carbs: 4, fat: 0.3 },
    flavors: ['salty', 'umami'],
    pixelIcon: '🫗',
  },
  {
    id: 'salt',
    name: '盐',
    emoji: '🧂',
    category: 'seasoning',
    nutrition: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    flavors: ['salty'],
    pixelIcon: '🧂',
  },
  {
    id: 'sugar',
    name: '糖',
    emoji: '🍬',
    category: 'seasoning',
    nutrition: { calories: 387, protein: 0, carbs: 100, fat: 0 },
    flavors: ['sweet'],
    pixelIcon: '🍬',
  },
  {
    id: 'vinegar',
    name: '醋',
    emoji: '🍶',
    category: 'seasoning',
    nutrition: { calories: 21, protein: 0.3, carbs: 5.7, fat: 0 },
    flavors: ['sour'],
    pixelIcon: '🍶',
  },
  {
    id: 'ginger',
    name: '姜',
    emoji: '🫚',
    category: 'seasoning',
    nutrition: { calories: 80, protein: 1.8, carbs: 18, fat: 0.8 },
    flavors: ['spicy', 'umami'],
    pixelIcon: '🫚',
  },
  {
    id: 'garlic',
    name: '蒜',
    emoji: '🧄',
    category: 'seasoning',
    nutrition: { calories: 149, protein: 6.4, carbs: 33, fat: 0.5 },
    flavors: ['umami', 'spicy'],
    pixelIcon: '🧄',
  },
  {
    id: 'chili',
    name: '辣椒',
    emoji: '🌶️',
    category: 'seasoning',
    nutrition: { calories: 40, protein: 1.9, carbs: 8.8, fat: 0.4 },
    flavors: ['spicy'],
    pixelIcon: '🌶️',
  },
  {
    id: 'honey',
    name: '蜂蜜',
    emoji: '🍯',
    category: 'seasoning',
    nutrition: { calories: 304, protein: 0.3, carbs: 82, fat: 0 },
    flavors: ['sweet'],
    pixelIcon: '🍯',
  },
  {
    id: 'rice',
    name: '米饭',
    emoji: '🍚',
    category: 'grain',
    nutrition: { calories: 130, protein: 2.7, carbs: 28, fat: 0.3 },
    flavors: [],
    pixelIcon: '🍚',
  },
  {
    id: 'noodle',
    name: '面条',
    emoji: '🍜',
    category: 'grain',
    nutrition: { calories: 138, protein: 4.5, carbs: 25, fat: 2.1 },
    flavors: [],
    pixelIcon: '🍜',
  },
];

export const getIngredientById = (id: string): Ingredient | undefined => {
  return FOOD_DATABASE.find((item) => item.id === id);
};
