import type { AuctionItem, BidRecord, FavoriteItem } from '@/types';
import { v4 as uuidv4 } from 'uuid';
import dayjs from 'dayjs';

const imagePrompts = [
  'antique chinese porcelain vase with intricate patterns on velvet display, museum lighting, luxury auction photography',
  'renaissance style oil painting portrait of noble person, golden frame, dim gallery lighting',
  'vintage gold pocket watch with engravings, open face, macro shot, velvet background',
  'rare first edition book collection with leather bound covers, marble table, warm lighting',
  'ancient roman bronze sculpture bust, museum pedestal, dramatic side lighting',
  'modern abstract contemporary art painting with vibrant colors on canvas, gallery wall',
  'handcrafted jade jewelry set with diamonds, black velvet, studio lighting',
  'limited edition vintage camera leica collection, wooden display case, soft lighting',
  'ancient persian silk carpet with intricate patterns, rolled display, warm oriental lighting',
  'rare silver coin collection numismatics, black velvet, macro photography',
  'modern minimalist sculpture marble stone, white gallery space, natural lighting',
  'art deco diamond necklace with emerald, black velvet display, luxury jewelry photography',
  'vintage vinyl record collection rare editions, wooden shelf, retro room',
  'antique french Louis XV style furniture chair, silk upholstery, ornate woodwork',
  'rare mechanical watch Rolex vintage, polished stainless steel, macro shot',
  'asian ink wash painting traditional chinese landscape, scroll mounted, silk border',
  'collectible first generation iPhone mint condition, original packaging, white background',
  'antique silver teapot set victorian era, polished, ornate engravings, marble surface',
  'contemporary glass art sculpture hand blown, colorful patterns, dark gallery background',
  'vintage rolex submariner watch, macro detail shot, professional product photography',
  'stamp collection rare vintage stamps, album display, warm soft lighting',
  'rare guitar vintage 1950s Fender Stratocaster, sunburst finish, stand display',
  'art nouveau stained glass window panel, vibrant colors, light passing through',
  'antique japanese katana sword, hand forged, display stand, subtle lighting',
];

function imageUrl(prompt: string, size: 'portrait_4_3' | 'landscape_4_3' = 'portrait_4_3'): string {
  return `https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=${encodeURIComponent(prompt)}&image_size=${size}`;
}

const auctionItems: Omit<AuctionItem, 'id' | 'thumbnail' | 'image'>[] = [
  {
    name: '清乾隆青花缠枝莲纹尊',
    description: '本品为清乾隆时期官窑精品，通体绘缠枝莲纹，青花发色纯正，器型端庄大气，为不可多得的宫廷御瓷。底部有"大清乾隆年制"六字篆书款。来源清晰，传承有序。',
    category: 'antique',
    currentPrice: 2850000,
    startPrice: 1800000,
    bidCount: 47,
    endTime: dayjs().add(3, 'day').add(5, 'hour').add(23, 'minute').toISOString(),
    highestBidder: '藏家王先生',
  },
  {
    name: '文艺复兴贵族肖像油画',
    description: '16世纪意大利文艺复兴时期作品，画布为珍贵的亚麻布，描绘一位贵族女性的半身像。画技精湛，色彩保存完好，经多位艺术史专家鉴定为真迹。',
    category: 'art',
    currentPrice: 5600000,
    startPrice: 3500000,
    bidCount: 89,
    endTime: dayjs().add(1, 'day').add(12, 'hour').toISOString(),
    highestBidder: '海外收藏家',
  },
  {
    name: '18K金雕花海神怀表',
    description: '百达翡丽1890年制怀表，18K黄金表壳，通体手工雕刻希腊海神波塞冬图案，机芯运转精准。附带原始表盒和证书，是怀表收藏家的梦想藏品。',
    category: 'antique',
    currentPrice: 685000,
    startPrice: 420000,
    bidCount: 32,
    endTime: dayjs().add(5, 'hour').add(42, 'minute').toISOString(),
    highestBidder: 'Time先生',
  },
  {
    name: '初版善本古籍合集',
    description: '包含明版《本草纲目》、清武英殿版《康熙字典》等12部珍稀古籍，多为皇家御赐版本，藏书印章清晰可考。整体保存状态极佳，具有极高的文献价值。',
    category: 'antique',
    currentPrice: 1280000,
    startPrice: 800000,
    bidCount: 28,
    endTime: dayjs().add(7, 'day').toISOString(),
    highestBidder: '古籍研究所',
  },
  {
    name: '罗马时期青铜帝王头像',
    description: '公元2世纪罗马帝国时期作品，表现皇帝马可·奥勒留的形象。青铜铸造工艺精湛，人物表情威严庄重。来源为欧洲老牌拍卖行旧藏，附完整来源证明。',
    category: 'art',
    currentPrice: 8900000,
    startPrice: 5500000,
    bidCount: 112,
    endTime: dayjs().add(2, 'day').add(8, 'hour').toISOString(),
    highestBidder: '博物馆代表',
  },
  {
    name: '当代抽象大师《色彩之舞》',
    description: '知名当代艺术家赵无极后期作品，画布油彩，色彩层次丰富，融合东方水墨意境与西方抽象语言。作品发表于多种权威出版物，来源直接得自艺术家工作室。',
    category: 'art',
    currentPrice: 4200000,
    startPrice: 2800000,
    bidCount: 64,
    endTime: dayjs().add(4, 'day').add(3, 'hour').toISOString(),
    highestBidder: '艺术基金会',
  },
  {
    name: '翡翠满绿镶钻项链套装',
    description: '缅甸老坑冰种满绿翡翠，正阳绿色泽均匀，质地通透莹润。主石重达38克拉，配钻2.5克拉，18K金镶嵌。附国家级权威鉴定证书，收藏投资皆宜。',
    category: 'art',
    currentPrice: 3500000,
    startPrice: 2200000,
    bidCount: 56,
    endTime: dayjs().add(2, 'day').add(14, 'hour').toISOString(),
    highestBidder: 'L女士',
  },
  {
    name: '徕卡M3黑漆初代机套装',
    description: '1954年徕卡M3首款黑漆机型，机身编号极早期，状态保存完美，功能一切正常。附带原厂50mm Summicron镜头、皮套、说明书等原装配件，极其罕见。',
    category: 'electronics',
    currentPrice: 425000,
    startPrice: 260000,
    bidCount: 78,
    endTime: dayjs().add(36, 'hour').toISOString(),
    highestBidder: '相机博物馆',
  },
  {
    name: '波斯皇家手工丝毯',
    description: '19世纪中期波斯伊斯法罕皇家工坊出品，纯蚕丝编织，密度每平方厘米800结。图案为经典的中央玫瑰花园设计，配色优雅，保存状态极佳。',
    category: 'antique',
    currentPrice: 980000,
    startPrice: 600000,
    bidCount: 23,
    endTime: dayjs().add(6, 'day').add(9, 'hour').toISOString(),
    highestBidder: '皇家艺术中心',
  },
  {
    name: '摩根银元全套珍品集',
    description: '包含1878-1904年间全部年份及造币厂版别的摩根银元，共95枚。大部分品相为MS-64以上，其中包含多枚罕见版别。附有PCGS/NGC认证及专业集藏册。',
    category: 'antique',
    currentPrice: 568000,
    startPrice: 350000,
    bidCount: 45,
    endTime: dayjs().add(2, 'day').add(5, 'hour').toISOString(),
    highestBidder: '钱币学会',
  },
  {
    name: '现代简约大理石雕塑',
    description: '当代著名雕塑家代表作品，采用意大利卡拉拉白色大理石，手工雕刻打磨。造型简约流畅，光影效果优美。附带艺术家签名及真品证书。',
    category: 'art',
    currentPrice: 1850000,
    startPrice: 1200000,
    bidCount: 37,
    endTime: dayjs().add(5, 'day').add(2, 'hour').toISOString(),
    highestBidder: '画廊主理人',
  },
  {
    name: 'Art Déco祖母绿钻石项链',
    description: '1925年卡地亚出品装饰艺术风格项链，主石为5.2克拉哥伦比亚祖母绿，配钻共计6.8克拉，铂金镶嵌。设计几何感强烈，是装饰艺术时期的典型佳作。',
    category: 'art',
    currentPrice: 7800000,
    startPrice: 4800000,
    bidCount: 93,
    endTime: dayjs().add(1, 'day').add(6, 'hour').toISOString(),
    highestBidder: '私人藏家',
  },
  {
    name: '披头士白专辑签名初版',
    description: '1968年英国Parlophone首版《The White Album》，编号0002345，由四位成员亲笔签名于内封。封面保存完好，唱片近新。附带来源证明及笔迹鉴定证书。',
    category: 'electronics',
    currentPrice: 1280000,
    startPrice: 680000,
    bidCount: 156,
    endTime: dayjs().add(3, 'day').add(8, 'hour').toISOString(),
    highestBidder: '摇滚纪念馆',
  },
  {
    name: '路易十五鎏金锦缎扶手椅',
    description: '十八世纪中期法国家具大师Jean-Baptiste Tilliard作品，胡桃木雕花鎏金框架，原品皇室锦缎面料重新裱覆。来源为法国贵族旧藏，附巴黎家具协会鉴定证书。',
    category: 'antique',
    currentPrice: 1560000,
    startPrice: 980000,
    bidCount: 31,
    endTime: dayjs().add(4, 'day').add(10, 'hour').toISOString(),
    highestBidder: '欧洲古董商',
  },
  {
    name: '劳力士初代潜航者型腕表',
    description: '1954年Rolex Submariner Ref.6204，精钢表壳，配黑色旋转表圈。机芯状态极佳，走时精准。为潜水表历史上的传奇之作，存世量稀少，极具投资价值。',
    category: 'antique',
    currentPrice: 2980000,
    startPrice: 1800000,
    bidCount: 134,
    endTime: dayjs().add(18, 'hour').toISOString(),
    highestBidder: '腕表收藏家',
  },
  {
    name: '水墨山水长卷',
    description: '近现代国画大师齐白石晚年精品《溪山无尽图》，水墨纸本手卷。纵28厘米，横485厘米，构图宏阔，笔墨苍润。后附多位名家题跋，著录清晰。',
    category: 'art',
    currentPrice: 16500000,
    startPrice: 9800000,
    bidCount: 201,
    endTime: dayjs().add(2, 'day').add(4, 'hour').toISOString(),
    highestBidder: '亚洲艺术收藏馆',
  },
  {
    name: '第一代iPhone 2G全新原封',
    description: '2007年苹果第一代iPhone 8GB版本，未拆封原封包装，状态完美，包装盒条形码与序列码清晰。是定义现代智能手机的划时代产品，全球存世原封不足百台。',
    category: 'electronics',
    currentPrice: 385000,
    startPrice: 198000,
    bidCount: 189,
    endTime: dayjs().add(28, 'hour').toISOString(),
    highestBidder: '科技博物馆',
  },
  {
    name: '维多利亚时期银制茶具套组',
    description: '1880年伦敦制银师Paul Storr作品，纯银整套茶具含茶壶、糖罐、奶罐、托盘四件。通体浮雕葡萄藤缠枝纹，做工精致，含英国银标与工匠戳记。',
    category: 'antique',
    currentPrice: 328000,
    startPrice: 195000,
    bidCount: 27,
    endTime: dayjs().add(3, 'day').add(5, 'hour').toISOString(),
    highestBidder: '银器收藏家',
  },
  {
    name: '当代手工吹制玻璃艺术',
    description: '美国玻璃艺术大师Dale Chihuly工作室作品，彩色玻璃雕塑系列。由多层不同色料吹制而成，光线穿透时呈现梦幻效果。附艺术家签名及真品证书。',
    category: 'art',
    currentPrice: 785000,
    startPrice: 450000,
    bidCount: 41,
    endTime: dayjs().add(5, 'day').add(6, 'hour').toISOString(),
    highestBidder: '当代艺术中心',
  },
  {
    name: '日本古董武士刀正真作',
    description: '江户时代末期幕末著名刀匠"源清麿"作打刀，刀身铭文清晰可见，地肌丁子刃文优美。配黑漆描金刀鞘、赤铜镡，附日本美术刀剑保存协会特别保存刀鉴定书。',
    category: 'antique',
    currentPrice: 688000,
    startPrice: 420000,
    bidCount: 58,
    endTime: dayjs().add(4, 'day').add(9, 'hour').toISOString(),
    highestBidder: '刀剑研究会',
  },
  {
    name: '华邮红印花小字当壹圆',
    description: '清代珍邮1897年红印花加盖小字当壹圆新票，原胶轻贴，色泽鲜艳，齿孔完整。为"华邮四宝"之首，存世不足20枚，是中国邮票收藏的金字塔尖藏品。',
    category: 'antique',
    currentPrice: 5600000,
    startPrice: 3200000,
    bidCount: 147,
    endTime: dayjs().add(2, 'day').add(11, 'hour').toISOString(),
    highestBidder: '邮品大王',
  },
  {
    name: '1954年Fender Strat电吉他',
    description: '元年款Fender Stratocaster，日落色漆面，枫木指板，原装单线圈拾音器。琴身使用痕迹自然，一切功能完好。附带原装琴箱，是电吉他收藏家梦寐以求的圣物。',
    category: 'electronics',
    currentPrice: 2450000,
    startPrice: 1500000,
    bidCount: 118,
    endTime: dayjs().add(3, 'day').add(14, 'hour').toISOString(),
    highestBidder: '摇滚名人堂',
  },
  {
    name: '新艺术风格彩色玻璃窗',
    description: '1900年法国南锡学派Emile Galle工作室出品，彩色玻璃镶嵌作品。图案为鸢尾花与藤蔓，色彩瑰丽，光影效果惊艳。为新艺术运动时期装饰艺术的巅峰之作。',
    category: 'art',
    currentPrice: 2180000,
    startPrice: 1350000,
    bidCount: 66,
    endTime: dayjs().add(5, 'day').add(8, 'hour').toISOString(),
    highestBidder: '装饰艺术博物馆',
  },
  {
    name: '劳力士复古迪通拿 6263',
    description: '1971年Rolex Daytona Ref.6263，精钢表壳，银色熊猫面盘，手动上链机芯Valjoux 72。原装表圈完整，走时精准。为古董运动表之王，近年涨幅惊人。',
    category: 'antique',
    currentPrice: 3980000,
    startPrice: 2500000,
    bidCount: 172,
    endTime: dayjs().add(1, 'day').add(9, 'hour').toISOString(),
    highestBidder: '名表收藏基金',
  },
];

export function generateAuctionItems(): AuctionItem[] {
  return auctionItems.map((item, idx) => {
    const prompt = imagePrompts[idx % imagePrompts.length];
    return {
      ...item,
      id: uuidv4(),
      thumbnail: imageUrl(prompt, 'portrait_4_3'),
      image: imageUrl(prompt, 'landscape_4_3'),
    };
  });
}

export function generateInitialBidHistory(): BidRecord[] {
  const now = dayjs();
  return [
    {
      id: uuidv4(),
      itemId: 'demo-1',
      itemName: '清乾隆青花缠枝莲纹尊',
      amount: 2800000,
      time: now.subtract(2, 'hour').toISOString(),
      status: 'outbid',
    },
    {
      id: uuidv4(),
      itemId: 'demo-2',
      itemName: '18K金雕花海神怀表',
      amount: 678000,
      time: now.subtract(8, 'hour').toISOString(),
      status: 'leading',
    },
    {
      id: uuidv4(),
      itemId: 'demo-3',
      itemName: '徕卡M3黑漆初代机套装',
      amount: 410000,
      time: now.subtract(1, 'day').subtract(3, 'hour').toISOString(),
      status: 'leading',
    },
    {
      id: uuidv4(),
      itemId: 'demo-4',
      itemName: '第一代iPhone 2G全新原封',
      amount: 375000,
      time: now.subtract(2, 'day').toISOString(),
      status: 'leading',
    },
    {
      id: uuidv4(),
      itemId: 'demo-5',
      itemName: '当代抽象大师《色彩之舞》',
      amount: 4000000,
      time: now.subtract(3, 'day').subtract(5, 'hour').toISOString(),
      status: 'outbid',
    },
    {
      id: uuidv4(),
      itemId: 'demo-6',
      itemName: '劳力士复古迪通拿 6263',
      amount: 3800000,
      time: now.subtract(4, 'day').toISOString(),
      status: 'outbid',
    },
  ];
}

export function generateInitialFavorites(items: AuctionItem[]): FavoriteItem[] {
  const pick = [0, 2, 5, 7, 9, 13];
  return pick.map((idx, order) => ({
    id: uuidv4(),
    itemId: items[idx]?.id ?? '',
    order,
    addedAt: dayjs().subtract(order, 'day').toISOString(),
  }));
}
