import { Card, Rarity, SkillType, SkillEffect } from './CardTypes';

export const cardPool: Card[] = [
  {
    id: 'card_001',
    name: '火焰剑士',
    cost: 2,
    attack: 3,
    defense: 2,
    description: '一名挥舞火焰之剑的战士',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_FRONT_ENEMY,
    skillValue: 1,
    skillDescription: '召唤时：对正前方敌方卡牌造成1点伤害',
  },
  {
    id: 'card_002',
    name: '水晶守卫',
    cost: 3,
    attack: 2,
    defense: 5,
    description: '坚固的水晶构造体',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.TAUNT,
    skillValue: 0,
    skillDescription: '嘲讽：敌方必须优先攻击此卡牌',
  },
  {
    id: 'card_003',
    name: '圣光祭司',
    cost: 2,
    attack: 1,
    defense: 3,
    description: '神圣之光的侍奉者',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.HEAL_ALL_ALLIES,
    skillValue: 1,
    skillDescription: '召唤时：为所有友方卡牌恢复1点防御',
  },
  {
    id: 'card_004',
    name: '暗影刺客',
    cost: 2,
    attack: 4,
    defense: 1,
    description: '来自暗影的杀手',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.CHARGE,
    skillValue: 0,
    skillDescription: '冲锋：召唤当回合即可攻击',
  },
  {
    id: 'card_005',
    name: '森林德鲁伊',
    cost: 1,
    attack: 1,
    defense: 2,
    description: '自然之力的守护者',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 1,
    skillDescription: '召唤时：抽一张牌',
  },
  {
    id: 'card_006',
    name: '石像鬼',
    cost: 4,
    attack: 3,
    defense: 4,
    description: '苏醒的石像守卫',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.SHIELD,
    skillValue: 2,
    skillDescription: '护盾：首次受到的伤害减少2点',
  },
  {
    id: 'card_007',
    name: '狂战士',
    cost: 3,
    attack: 5,
    defense: 2,
    description: '无所畏惧的战士',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: null,
    skillValue: 0,
    skillDescription: '没有特殊技能',
  },
  {
    id: 'card_008',
    name: '寒冰法师',
    cost: 3,
    attack: 2,
    defense: 3,
    description: '掌握寒冰魔法的法师',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.FREEZE,
    skillValue: 1,
    skillDescription: '攻击时：冻结目标一回合',
  },
  {
    id: 'card_009',
    name: '吸血鬼',
    cost: 4,
    attack: 3,
    defense: 3,
    description: '永生的暗夜贵族',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.LIFESTEAL,
    skillValue: 0,
    skillDescription: '吸血：造成伤害时恢复等量生命值',
  },
  {
    id: 'card_010',
    name: '火焰元素',
    cost: 5,
    attack: 5,
    defense: 4,
    description: '燃烧的元素生物',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 1,
    skillDescription: '召唤时：对所有敌方卡牌造成1点伤害',
  },
  {
    id: 'card_011',
    name: '精灵弓手',
    cost: 2,
    attack: 2,
    defense: 2,
    description: '百步穿杨的精灵射手',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.PIERCE,
    skillValue: 0,
    skillDescription: '穿透：伤害可以无视护盾',
  },
  {
    id: 'card_012',
    name: '战争号角',
    cost: 3,
    attack: 2,
    defense: 2,
    description: '鼓舞士气的号角',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: SkillEffect.BUFF_ATTACK_ALLIES,
    skillValue: 1,
    skillDescription: '光环：所有友方卡牌攻击力+1',
  },
  {
    id: 'card_013',
    name: '圣光护盾',
    cost: 2,
    attack: 1,
    defense: 4,
    description: '神圣能量的护盾',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: SkillEffect.BUFF_DEFENSE_ALLIES,
    skillValue: 1,
    skillDescription: '光环：所有友方卡牌防御力+1',
  },
  {
    id: 'card_014',
    name: '炎龙幼崽',
    cost: 4,
    attack: 4,
    defense: 3,
    description: '年幼但危险的火龙',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.BURN,
    skillValue: 2,
    skillDescription: '攻击时：对目标造成2点灼烧伤害',
  },
  {
    id: 'card_015',
    name: '冰霜巨人',
    cost: 6,
    attack: 5,
    defense: 6,
    description: '来自北境的巨人',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.FREEZE,
    skillValue: 2,
    skillDescription: '召唤时：冻结两个随机敌方卡牌',
  },
  {
    id: 'card_016',
    name: '暗影牧师',
    cost: 3,
    attack: 2,
    defense: 4,
    description: '堕落的圣光牧师',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 2,
    skillDescription: '召唤时：对所有敌方卡牌造成2点伤害',
  },
  {
    id: 'card_017',
    name: '雷霆武士',
    cost: 4,
    attack: 4,
    defense: 3,
    description: '雷电之力的战士',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.DAMAGE_FRONT_ENEMY,
    skillValue: 2,
    skillDescription: '攻击时：对目标周围造成2点溅射伤害',
  },
  {
    id: 'card_018',
    name: '毒蛇刺客',
    cost: 3,
    attack: 3,
    defense: 2,
    description: '剧毒的暗杀者',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.PIERCE,
    skillValue: 1,
    skillDescription: '剧毒：攻击时额外造成1点穿透伤害',
  },
  {
    id: 'card_019',
    name: '圣骑士',
    cost: 5,
    attack: 4,
    defense: 5,
    description: '正义的守护者',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.HEAL_ALL_ALLIES,
    skillValue: 2,
    skillDescription: '召唤时：为所有友方卡牌恢复2点防御',
  },
  {
    id: 'card_020',
    name: '风暴术士',
    cost: 4,
    attack: 3,
    defense: 3,
    description: '操控风暴的法师',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 2,
    skillDescription: '召唤时：抽两张牌',
  },
  {
    id: 'card_021',
    name: '烈焰凤凰',
    cost: 7,
    attack: 6,
    defense: 5,
    description: '浴火重生的神鸟',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 3,
    skillDescription: '召唤时：对所有敌方卡牌造成3点伤害',
  },
  {
    id: 'card_022',
    name: '远古巨龙',
    cost: 8,
    attack: 8,
    defense: 8,
    description: '沉睡千年的巨龙',
    rarity: Rarity.EPIC,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.CHARGE,
    skillValue: 0,
    skillDescription: '冲锋：召唤当回合即可攻击',
  },
  {
    id: 'card_023',
    name: '大德鲁伊',
    cost: 6,
    attack: 4,
    defense: 6,
    description: '自然之力的化身',
    rarity: Rarity.EPIC,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: SkillEffect.BUFF_ATTACK_ALLIES,
    skillValue: 2,
    skillDescription: '光环：所有友方卡牌攻击力+2',
  },
  {
    id: 'card_024',
    name: '光明大主教',
    cost: 7,
    attack: 3,
    defense: 7,
    description: '圣光教会的最高领袖',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.HEAL_ALL_ALLIES,
    skillValue: 4,
    skillDescription: '召唤时：为所有友方卡牌恢复4点防御',
  },
  {
    id: 'card_025',
    name: '暗影领主',
    cost: 6,
    attack: 6,
    defense: 4,
    description: '暗影王国的统治者',
    rarity: Rarity.EPIC,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.LIFESTEAL,
    skillValue: 2,
    skillDescription: '吸血：造成伤害时恢复等量生命值+2额外回复',
  },
  {
    id: 'card_026',
    name: '冰霜女王',
    cost: 7,
    attack: 5,
    defense: 6,
    description: '永恒冻土的女王',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.FREEZE,
    skillValue: 4,
    skillDescription: '召唤时：冻结所有敌方卡牌',
  },
  {
    id: 'card_027',
    name: '地狱火',
    cost: 5,
    attack: 5,
    defense: 5,
    description: '来自深渊的火焰恶魔',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.BURN,
    skillValue: 3,
    skillDescription: '攻击时：对目标造成3点灼烧伤害',
  },
  {
    id: 'card_028',
    name: '泰坦守卫',
    cost: 8,
    attack: 4,
    defense: 10,
    description: '远古泰坦的守卫者',
    rarity: Rarity.EPIC,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.TAUNT,
    skillValue: 0,
    skillDescription: '嘲讽：敌方必须优先攻击此卡牌',
  },
  {
    id: 'card_029',
    name: '星辰法师',
    cost: 6,
    attack: 4,
    defense: 4,
    description: '操控星辰之力的法师',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 3,
    skillDescription: '召唤时：抽三张牌',
  },
  {
    id: 'card_030',
    name: '剑圣',
    cost: 5,
    attack: 7,
    defense: 3,
    description: '剑术登峰造极的大师',
    rarity: Rarity.EPIC,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.PIERCE,
    skillValue: 2,
    skillDescription: '穿透：攻击无视2点防御',
  },
  {
    id: 'card_031',
    name: '炎龙之王',
    cost: 10,
    attack: 10,
    defense: 10,
    description: '万龙之王，火焰的化身',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 5,
    skillDescription: '召唤时：对所有敌方卡牌造成5点伤害',
  },
  {
    id: 'card_032',
    name: '光明之神',
    cost: 9,
    attack: 6,
    defense: 8,
    description: '神圣光芒的具现化',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.HEAL_ALL_ALLIES,
    skillValue: 6,
    skillDescription: '召唤时：为所有友方卡牌恢复6点防御',
  },
  {
    id: 'card_033',
    name: '暗影之主',
    cost: 9,
    attack: 8,
    defense: 6,
    description: '黑暗深渊的主宰',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: SkillEffect.BUFF_ATTACK_ALLIES,
    skillValue: 3,
    skillDescription: '光环：所有友方卡牌攻击力+3',
  },
  {
    id: 'card_034',
    name: '时间守护者',
    cost: 8,
    attack: 5,
    defense: 7,
    description: '操控时间之流的存在',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 4,
    skillDescription: '召唤时：抽四张牌',
  },
  {
    id: 'card_035',
    name: '冰霜巨龙',
    cost: 10,
    attack: 8,
    defense: 9,
    description: '永冻之地的远古巨龙',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.FREEZE,
    skillValue: 1,
    skillDescription: '攻击时：永久冻结目标',
  },
  {
    id: 'card_036',
    name: '生命之树',
    cost: 7,
    attack: 2,
    defense: 12,
    description: '世界树的化身',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: SkillEffect.BUFF_DEFENSE_ALLIES,
    skillValue: 3,
    skillDescription: '光环：所有友方卡牌防御力+3',
  },
  {
    id: 'card_037',
    name: '死神',
    cost: 9,
    attack: 9,
    defense: 5,
    description: '死亡的化身',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.LIFESTEAL,
    skillValue: 5,
    skillDescription: '吸血：造成伤害时恢复等量生命值+5额外回复',
  },
  {
    id: 'card_038',
    name: '雷神',
    cost: 10,
    attack: 7,
    defense: 7,
    description: '雷霆之神',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 2,
    skillDescription: '攻击时：对所有敌方卡牌造成2点伤害',
  },
  {
    id: 'card_039',
    name: '创世神',
    cost: 12,
    attack: 12,
    defense: 12,
    description: '创造万物的至高存在',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.CHARGE,
    skillValue: 0,
    skillDescription: '冲锋+护盾：召唤当回合可攻击，首次免疫伤害',
  },
  {
    id: 'card_040',
    name: '毁灭者',
    cost: 11,
    attack: 11,
    defense: 8,
    description: '终结一切的毁灭化身',
    rarity: Rarity.LEGENDARY,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 4,
    skillDescription: '召唤时：对所有敌方卡牌造成4点伤害，并穿透护盾',
  },
  {
    id: 'card_041',
    name: '新兵',
    cost: 1,
    attack: 1,
    defense: 1,
    description: '刚刚入伍的士兵',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_GLOBAL,
    skillEffect: null,
    skillValue: 0,
    skillDescription: '没有特殊技能',
  },
  {
    id: 'card_042',
    name: '盾牌兵',
    cost: 2,
    attack: 1,
    defense: 4,
    description: '手持盾牌的防御者',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.TAUNT,
    skillValue: 0,
    skillDescription: '嘲讽：敌方必须优先攻击此卡牌',
  },
  {
    id: 'card_043',
    name: '火焰小鬼',
    cost: 1,
    attack: 2,
    defense: 1,
    description: '调皮的火焰生物',
    rarity: Rarity.COMMON,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_FRONT_ENEMY,
    skillValue: 1,
    skillDescription: '召唤时：对正前方敌方卡牌造成1点伤害',
  },
  {
    id: 'card_044',
    name: '治疗师',
    cost: 3,
    attack: 1,
    defense: 4,
    description: '专业的战地医师',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.HEAL_ALL_ALLIES,
    skillValue: 2,
    skillDescription: '召唤时：为所有友方卡牌恢复2点防御',
  },
  {
    id: 'card_045',
    name: '狼骑兵',
    cost: 4,
    attack: 4,
    defense: 3,
    description: '骑乘巨狼的战士',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.CHARGE,
    skillValue: 0,
    skillDescription: '冲锋：召唤当回合即可攻击',
  },
  {
    id: 'card_046',
    name: '火枪手',
    cost: 3,
    attack: 3,
    defense: 2,
    description: '熟练的火器使用者',
    rarity: Rarity.COMMON,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.PIERCE,
    skillValue: 1,
    skillDescription: '穿透：攻击无视1点防御',
  },
  {
    id: 'card_047',
    name: '亡灵法师',
    cost: 5,
    attack: 3,
    defense: 4,
    description: '操控亡灵的黑暗法师',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 2,
    skillDescription: '召唤时：抽两张牌',
  },
  {
    id: 'card_048',
    name: '山岭巨人',
    cost: 7,
    attack: 6,
    defense: 7,
    description: '来自山脉的巨人',
    rarity: Rarity.RARE,
    skillType: SkillType.PASSIVE_BUFF,
    skillEffect: SkillEffect.SHIELD,
    skillValue: 3,
    skillDescription: '护盾：首次受到的伤害减少3点',
  },
  {
    id: 'card_049',
    name: '精灵龙',
    cost: 5,
    attack: 4,
    defense: 4,
    description: '优雅的精灵龙族',
    rarity: Rarity.RARE,
    skillType: SkillType.ACTIVE_ATTACK,
    skillEffect: SkillEffect.DRAW_CARD,
    skillValue: 1,
    skillDescription: '攻击时：抽一张牌',
  },
  {
    id: 'card_050',
    name: '末日审判者',
    cost: 10,
    attack: 7,
    defense: 7,
    description: '审判一切的天使',
    rarity: Rarity.EPIC,
    skillType: SkillType.ACTIVE_SUMMON,
    skillEffect: SkillEffect.DAMAGE_ALL_ENEMIES,
    skillValue: 3,
    skillDescription: '召唤时：对所有敌方卡牌造成3点伤害',
  },
];

export function getCardById(id: string): Card | undefined {
  return cardPool.find((card) => card.id === id);
}

export function getCardsByRarity(rarity: Rarity): Card[] {
  return cardPool.filter((card) => card.rarity === rarity);
}
