const COUNTRY_CONTINENT_MAP: Record<string, string> = {
  CN: 'Asia', JP: 'Asia', KR: 'Asia', IN: 'Asia', TH: 'Asia',
  VN: 'Asia', SG: 'Asia', MY: 'Asia', ID: 'Asia', PH: 'Asia',
  HK: 'Asia', TW: 'Asia', MO: 'Asia', KP: 'Asia', MN: 'Asia',
  KH: 'Asia', LA: 'Asia', MM: 'Asia', BD: 'Asia', NP: 'Asia',
  BT: 'Asia', LK: 'Asia', MV: 'Asia', AF: 'Asia', PK: 'Asia',
  IR: 'Asia', IQ: 'Asia', KW: 'Asia', SA: 'Asia', AE: 'Asia',
  OM: 'Asia', YE: 'Asia', SY: 'Asia', LB: 'Asia', IL: 'Asia',
  PS: 'Asia', JO: 'Asia', TR: 'Asia', CY: 'Asia', GE: 'Asia',
  AM: 'Asia', AZ: 'Asia', KZ: 'Asia', KG: 'Asia', TJ: 'Asia',
  TM: 'Asia', UZ: 'Asia', BN: 'Asia', TL: 'Asia',

  DE: 'Europe', FR: 'Europe', GB: 'Europe', IT: 'Europe', ES: 'Europe',
  PT: 'Europe', NL: 'Europe', BE: 'Europe', CH: 'Europe', AT: 'Europe',
  SE: 'Europe', NO: 'Europe', DK: 'Europe', FI: 'Europe', IS: 'Europe',
  PL: 'Europe', CZ: 'Europe', SK: 'Europe', HU: 'Europe', RO: 'Europe',
  BG: 'Europe', GR: 'Europe', RU: 'Europe', UA: 'Europe', BY: 'Europe',
  LT: 'Europe', LV: 'Europe', EE: 'Europe', IE: 'Europe', LU: 'Europe',
  MC: 'Europe', SM: 'Europe', VA: 'Europe', LI: 'Europe', AD: 'Europe',
  MT: 'Europe', SI: 'Europe', HR: 'Europe', BA: 'Europe', RS: 'Europe',
  MK: 'Europe', AL: 'Europe', ME: 'Europe', XK: 'Europe', MD: 'Europe',

  US: 'North America', CA: 'North America', MX: 'North America',
  CU: 'North America', JM: 'North America', HT: 'North America',
  DO: 'North America', CR: 'North America', PA: 'North America',
  GT: 'North America', HN: 'North America', SV: 'North America',
  NI: 'North America', BZ: 'North America', BS: 'North America',
  TT: 'North America', BB: 'North America',

  BR: 'South America', AR: 'South America', CL: 'South America',
  PE: 'South America', CO: 'South America', VE: 'South America',
  EC: 'South America', BO: 'South America', PY: 'South America',
  UY: 'South America', GY: 'South America', SR: 'South America',

  ZA: 'Africa', EG: 'Africa', NG: 'Africa', KE: 'Africa', MA: 'Africa',
  TN: 'Africa', DZ: 'Africa', LY: 'Africa', ET: 'Africa', GH: 'Africa',
  CI: 'Africa', CM: 'Africa', UG: 'Africa', TZ: 'Africa', ZM: 'Africa',
  ZW: 'Africa', NA: 'Africa', BW: 'Africa', MZ: 'Africa', AO: 'Africa',
  CD: 'Africa', CG: 'Africa', GA: 'Africa', SN: 'Africa', MR: 'Africa',
  ML: 'Africa', NE: 'Africa', TD: 'Africa', SD: 'Africa', SO: 'Africa',
  KE: 'Africa', MG: 'Africa',

  AU: 'Oceania', NZ: 'Oceania', FJ: 'Oceania', PG: 'Oceania',
  WS: 'Oceania', TO: 'Oceania', TV: 'Oceania', KI: 'Oceania',
  MH: 'Oceania', FM: 'Oceania', PW: 'Oceania', NR: 'Oceania',
  VU: 'Oceania', SB: 'Oceania', NC: 'Oceania', PF: 'Oceania',
}

export function getContinentByCountryCode(countryCode: string): string {
  return COUNTRY_CONTINENT_MAP[countryCode] || 'Unknown'
}

export function getContinentByLatLng(lat: number, lng: number): string {
  if (lat > 35 && lng > -10 && lng < 60) return 'Europe'
  if (lat > 0 && lng > 60 && lng < 150) return 'Asia'
  if (lat < 35 && lat > -35 && lng > -20 && lng < 55) return 'Africa'
  if (lat > 15 && lng < -50 && lng > -170) return 'North America'
  if (lat < 15 && lat > -55 && lng < -30 && lng > -85) return 'South America'
  if (lat < 0 && lng > 110 && lng < 180) return 'Oceania'
  if (lat < -60) return 'Antarctica'
  return 'Unknown'
}

export const COUNTRY_NAMES_ZH_TO_EN: Record<string, string> = {
  '中国': 'China', '美国': 'United States of America', '日本': 'Japan',
  '德国': 'Germany', '法国': 'France', '英国': 'United Kingdom',
  '意大利': 'Italy', '西班牙': 'Spain', '加拿大': 'Canada',
  '澳大利亚': 'Australia', '韩国': 'South Korea', '俄罗斯': 'Russia',
  '巴西': 'Brazil', '印度': 'India', '墨西哥': 'Mexico',
  '印度尼西亚': 'Indonesia', '泰国': 'Thailand', '越南': 'Vietnam',
  '菲律宾': 'Philippines', '马来西亚': 'Malaysia', '新加坡': 'Singapore',
  '新西兰': 'New Zealand', '荷兰': 'Netherlands', '比利时': 'Belgium',
  '瑞士': 'Switzerland', '奥地利': 'Austria', '瑞典': 'Sweden',
  '挪威': 'Norway', '丹麦': 'Denmark', '芬兰': 'Finland',
  '波兰': 'Poland', '捷克': 'Czech Republic', '匈牙利': 'Hungary',
  '希腊': 'Greece', '葡萄牙': 'Portugal', '土耳其': 'Turkey',
  '埃及': 'Egypt', '南非': 'South Africa', '肯尼亚': 'Kenya',
  '摩洛哥': 'Morocco', '阿根廷': 'Argentina', '智利': 'Chile',
  '秘鲁': 'Peru', '哥伦比亚': 'Colombia', '委内瑞拉': 'Venezuela',
  '中国香港': 'Hong Kong', '中国台湾': 'Taiwan', '中国澳门': 'Macao',
  '古巴': 'Cuba', '牙买加': 'Jamaica', '哥斯达黎加': 'Costa Rica',
  '巴拿马': 'Panama', '危地马拉': 'Guatemala', '洪都拉斯': 'Honduras',
  '萨尔瓦多': 'El Salvador', '尼加拉瓜': 'Nicaragua', '伯利兹': 'Belize',
  '爱尔兰': 'Ireland', '冰岛': 'Iceland', '乌克兰': 'Ukraine',
  '克罗地亚': 'Croatia', '塞尔维亚': 'Serbia', '罗马尼亚': 'Romania',
  '保加利亚': 'Bulgaria', '斯洛伐克': 'Slovakia', '斯洛文尼亚': 'Slovenia',
  '立陶宛': 'Lithuania', '拉脱维亚': 'Latvia', '爱沙尼亚': 'Estonia',
  '以色列': 'Israel', '沙特阿拉伯': 'Saudi Arabia', '阿拉伯联合酋长国': 'United Arab Emirates',
  '伊朗': 'Iran', '伊拉克': 'Iraq', '巴基斯坦': 'Pakistan',
  '孟加拉国': 'Bangladesh', '斯里兰卡': 'Sri Lanka', '尼泊尔': 'Nepal',
  '缅甸': 'Myanmar', '柬埔寨': 'Cambodia', '老挝': 'Laos',
  '蒙古': 'Mongolia', '朝鲜': 'North Korea', '文莱': 'Brunei',
  '东帝汶': 'East Timor', '马尔代夫': 'Maldives', '不丹': 'Bhutan',
  '阿富汗': 'Afghanistan', '约旦': 'Jordan', '黎巴嫩': 'Lebanon',
  '叙利亚': 'Syria', '也门': 'Yemen', '阿曼': 'Oman',
  '科威特': 'Kuwait', '卡塔尔': 'Qatar', '巴林': 'Bahrain',
  '格鲁吉亚': 'Georgia', '亚美尼亚': 'Armenia', '阿塞拜疆': 'Azerbaijan',
  '哈萨克斯坦': 'Kazakhstan', '乌兹别克斯坦': 'Uzbekistan',
  '土库曼斯坦': 'Turkmenistan', '吉尔吉斯斯坦': 'Kyrgyzstan',
  '塔吉克斯坦': 'Tajikistan', '斐济': 'Fiji', '巴布亚新几内亚': 'Papua New Guinea',
  '玻利维亚': 'Bolivia', '巴拉圭': 'Paraguay', '乌拉圭': 'Uruguay',
  '圭亚那': 'Guyana', '苏里南': 'Suriname', '厄瓜多尔': 'Ecuador',
  '阿尔及利亚': 'Algeria', '利比亚': 'Libya', '突尼斯': 'Tunisia',
  '苏丹': 'Sudan', '南苏丹': 'South Sudan', '乍得': 'Chad',
  '尼日尔': 'Niger', '马里': 'Mali', '毛里塔尼亚': 'Mauritania',
  '塞内加尔': 'Senegal', '冈比亚': 'Gambia', '几内亚': 'Guinea',
  '几内亚比绍': 'Guinea-Bissau', '塞拉利昂': 'Sierra Leone',
  '利比里亚': 'Liberia', '科特迪瓦': 'Ivory Coast',
  '布基纳法索': 'Burkina Faso', '加纳': 'Ghana', '多哥': 'Togo',
  '贝宁': 'Benin', '尼日利亚': 'Nigeria', '喀麦隆': 'Cameroon',
  '赤道几内亚': 'Equatorial Guinea', '加蓬': 'Gabon',
  '刚果共和国': 'Republic of the Congo', '刚果民主共和国': 'Democratic Republic of the Congo',
  '中非共和国': 'Central African Republic', '安哥拉': 'Angola',
  '赞比亚': 'Zambia', '津巴布韦': 'Zimbabwe', '莫桑比克': 'Mozambique',
  '马拉维': 'Malawi', '博茨瓦纳': 'Botswana', '纳米比亚': 'Namibia',
  '马达加斯加': 'Madagascar', '坦桑尼亚': 'Tanzania', '乌干达': 'Uganda',
  '卢旺达': 'Rwanda', '布隆迪': 'Burundi', '吉布提': 'Djibouti',
  '厄立特里亚': 'Eritrea', '埃塞俄比亚': 'Ethiopia', '索马里': 'Somalia',
  '佛得角': 'Cape Verde', '科摩罗': 'Comoros', '毛里求斯': 'Mauritius',
  '塞舌尔': 'Seychelles', '圣多美和普林西比': 'São Tomé and Príncipe',
  '西撒哈拉': 'W. Sahara',
}

export const ISO_ALPHA2_TO_NUMERIC: Record<string, string> = {
  CN: '156', US: '840', JP: '392', DE: '276', FR: '250',
  GB: '826', IT: '380', ES: '724', CA: '124', AU: '036',
  KR: '410', RU: '643', BR: '076', IN: '356', MX: '484',
  ID: '360', TH: '764', VN: '704', PH: '608', MY: '458',
  SG: '702', NZ: '554', NL: '528', BE: '056', CH: '756',
  AT: '040', SE: '752', NO: '578', DK: '208', FI: '246',
  PL: '616', CZ: '203', HU: '348', GR: '300', PT: '620',
  TR: '792', EG: '818', ZA: '710', KE: '404', MA: '504',
  AR: '032', CL: '152', PE: '604', CO: '170', VE: '862',
  HK: '344', TW: '158', MO: '446', CU: '192', JM: '388',
  CR: '188', PA: '591', GT: '320', HN: '340', SV: '222',
  NI: '558', BZ: '084', IE: '372', IS: '352', UA: '804',
  HR: '191', RS: '688', RO: '642', BG: '100', SK: '703',
  SI: '705', LT: '440', LV: '428', EE: '233', IL: '376',
  SA: '682', AE: '784', IR: '364', IQ: '368', PK: '586',
  BD: '050', LK: '144', NP: '524', MM: '104', KH: '116',
  LA: '418', MN: '496', KP: '408', BN: '096', TL: '626',
  AF: '004', JO: '400', LB: '422', SY: '760', YE: '887',
  OM: '512', KW: '414', QA: '634', BH: '048', GE: '268',
  AM: '051', AZ: '031', KZ: '398', UZ: '860', TM: '795',
  KG: '417', TJ: '762', FJ: '242', PG: '598', BO: '068',
  PY: '600', UY: '858', GY: '328', SR: '740', EC: '218',
  DZ: '012', LY: '434', TN: '788', SD: '736', TD: '148',
  NE: '562', ML: '466', MR: '478', SN: '686', GM: '270',
  GN: '324', GW: '624', SL: '694', LR: '430', CI: '384',
  BF: '854', GH: '288', TG: '768', BJ: '204', NG: '566',
  CM: '120', GA: '266', CG: '178', CD: '180', CF: '140',
  AO: '024', ZM: '894', ZW: '716', MZ: '508', MW: '454',
  BW: '072', NA: '516', MG: '450', TZ: '834', UG: '800',
  RW: '646', BI: '108', DJ: '262', ER: '232', ET: '231',
  SO: '706', BJ: '204', MU: '480', SC: '690',
}
