FOODS = [
    {"id": 1, "name": "白米饭", "name_en": "White Rice", "pinyin": "bai mi fan", "calories": 116, "protein": 2.6, "fat": 0.3, "carbs": 25.6, "fiber": 0.3, "sodium": 2, "category": "grain"},
    {"id": 2, "name": "糙米饭", "name_en": "Brown Rice", "pinyin": "cao mi fan", "calories": 123, "protein": 2.6, "fat": 0.9, "carbs": 25.9, "fiber": 1.8, "sodium": 3, "category": "grain"},
    {"id": 3, "name": "馒头", "name_en": "Steamed Bun", "pinyin": "man tou", "calories": 221, "protein": 7.0, "fat": 1.1, "carbs": 47.0, "fiber": 1.3, "sodium": 165, "category": "grain"},
    {"id": 4, "name": "全麦面包", "name_en": "Whole Wheat Bread", "pinyin": "quan mai mian bao", "calories": 250, "protein": 10.0, "fat": 3.5, "carbs": 49.0, "fiber": 6.0, "sodium": 400, "category": "grain"},
    {"id": 5, "name": "面条", "name_en": "Noodles", "pinyin": "mian tiao", "calories": 284, "protein": 8.3, "fat": 1.6, "carbs": 56.8, "fiber": 1.5, "sodium": 150, "category": "grain"},
    {"id": 6, "name": "燕麦片", "name_en": "Oatmeal", "pinyin": "yan mai pian", "calories": 367, "protein": 15.0, "fat": 6.7, "carbs": 61.6, "fiber": 5.3, "sodium": 12, "category": "grain"},
    {"id": 7, "name": "玉米", "name_en": "Corn", "pinyin": "yu mi", "calories": 106, "protein": 4.0, "fat": 1.2, "carbs": 22.8, "fiber": 2.9, "sodium": 2, "category": "grain"},
    {"id": 8, "name": "红薯", "name_en": "Sweet Potato", "pinyin": "hong shu", "calories": 86, "protein": 1.6, "fat": 0.1, "carbs": 20.1, "fiber": 3.0, "sodium": 55, "category": "grain"},
    {"id": 9, "name": "土豆", "name_en": "Potato", "pinyin": "tu dou", "calories": 77, "protein": 2.0, "fat": 0.1, "carbs": 17.2, "fiber": 0.7, "sodium": 27, "category": "grain"},
    {"id": 10, "name": "小米粥", "name_en": "Millet Porridge", "pinyin": "xiao mi zhou", "calories": 46, "protein": 1.4, "fat": 0.7, "carbs": 8.4, "fiber": 0.4, "sodium": 3, "category": "grain"},
    {"id": 11, "name": "面包", "name_en": "Bread", "pinyin": "mian bao", "calories": 312, "protein": 8.3, "fat": 5.1, "carbs": 58.6, "fiber": 1.5, "sodium": 250, "category": "grain"},
    {"id": 12, "name": "饺子", "name_en": "Dumpling", "pinyin": "jiao zi", "calories": 253, "protein": 8.3, "fat": 10.5, "carbs": 33.3, "fiber": 1.8, "sodium": 280, "category": "grain"},
    {"id": 13, "name": "包子", "name_en": "Steamed Stuffed Bun", "pinyin": "bao zi", "calories": 227, "protein": 7.9, "fat": 3.4, "carbs": 41.8, "fiber": 1.6, "sodium": 200, "category": "grain"},
    {"id": 14, "name": "油条", "name_en": "Deep-fried Dough Stick", "pinyin": "you tiao", "calories": 388, "protein": 6.9, "fat": 17.6, "carbs": 51.6, "fiber": 0.7, "sodium": 250, "category": "grain"},
    {"id": 15, "name": "煎饼", "name_en": "Pancake", "pinyin": "jian bing", "calories": 354, "protein": 7.6, "fat": 11.3, "carbs": 53.7, "fiber": 1.2, "sodium": 150, "category": "grain"},
    {"id": 16, "name": "炒饭", "name_en": "Fried Rice", "pinyin": "chao fan", "calories": 173, "protein": 5.8, "fat": 3.2, "carbs": 29.3, "fiber": 0.8, "sodium": 200, "category": "grain"},
    {"id": 17, "name": "牛肉面", "name_en": "Beef Noodles", "pinyin": "niu rou mian", "calories": 180, "protein": 8.5, "fat": 4.2, "carbs": 25.3, "fiber": 0.8, "sodium": 350, "category": "grain"},
    {"id": 18, "name": "披萨", "name_en": "Pizza", "pinyin": "pi sa", "calories": 266, "protein": 11.2, "fat": 10.5, "carbs": 33.3, "fiber": 1.5, "sodium": 450, "category": "grain"},
    {"id": 19, "name": "汉堡", "name_en": "Hamburger", "pinyin": "han bao", "calories": 295, "protein": 14.5, "fat": 11.8, "carbs": 32.6, "fiber": 1.2, "sodium": 380, "category": "grain"},
    {"id": 20, "name": "牛奶麦片", "name_en": "Milk Cereal", "pinyin": "niu nai mai pian", "calories": 210, "protein": 7.2, "fat": 4.8, "carbs": 35.6, "fiber": 3.2, "sodium": 85, "category": "grain"},
    {"id": 21, "name": "三明治", "name_en": "Sandwich", "pinyin": "san ming zhi", "calories": 280, "protein": 12.5, "fat": 9.5, "carbs": 36.8, "fiber": 2.1, "sodium": 420, "category": "grain"},
    {"id": 22, "name": "寿司", "name_en": "Sushi", "pinyin": "shou si", "calories": 150, "protein": 5.8, "fat": 2.5, "carbs": 25.3, "fiber": 0.8, "sodium": 280, "category": "grain"},
    {"id": 23, "name": "紫薯", "name_en": "Purple Sweet Potato", "pinyin": "zi shu", "calories": 82, "protein": 1.4, "fat": 0.1, "carbs": 18.5, "fiber": 2.8, "sodium": 28, "category": "grain"},
    {"id": 24, "name": "皮蛋瘦肉粥", "name_en": "Century Egg Pork Congee", "pinyin": "pi dan shou rou zhou", "calories": 65, "protein": 2.8, "fat": 1.2, "carbs": 10.5, "fiber": 0.3, "sodium": 320, "category": "grain"},
    {"id": 25, "name": "糯米", "name_en": "Glutinous Rice", "pinyin": "nuo mi", "calories": 348, "protein": 7.3, "fat": 1.0, "carbs": 77.5, "fiber": 0.8, "sodium": 2, "category": "grain"},
    {"id": 26, "name": "黑米", "name_en": "Black Rice", "pinyin": "hei mi", "calories": 333, "protein": 9.4, "fat": 2.5, "carbs": 72.2, "fiber": 3.9, "sodium": 3, "category": "grain"},
    {"id": 27, "name": "紫米", "name_en": "Purple Rice", "pinyin": "zi mi", "calories": 343, "protein": 8.8, "fat": 2.2, "carbs": 75.1, "fiber": 3.5, "sodium": 2, "category": "grain"},
    {"id": 28, "name": "小米", "name_en": "Millet", "pinyin": "xiao mi", "calories": 358, "protein": 9.0, "fat": 3.1, "carbs": 73.5, "fiber": 1.6, "sodium": 4, "category": "grain"},
    {"id": 29, "name": "大黄米", "name_en": "Broomcorn Millet", "pinyin": "da huang mi", "calories": 350, "protein": 11.3, "fat": 3.0, "carbs": 71.0, "fiber": 2.5, "sodium": 3, "category": "grain"},
    {"id": 30, "name": "高粱米", "name_en": "Sorghum Rice", "pinyin": "gao liang mi", "calories": 360, "protein": 10.4, "fat": 3.1, "carbs": 74.7, "fiber": 4.3, "sodium": 2, "category": "grain"},
    {"id": 31, "name": "薏米", "name_en": "Coix Seed", "pinyin": "yi mi", "calories": 357, "protein": 12.8, "fat": 3.3, "carbs": 69.1, "fiber": 2.0, "sodium": 4, "category": "grain"},
    {"id": 32, "name": "糙米", "name_en": "Brown Rice", "pinyin": "cao mi", "calories": 348, "protein": 7.7, "fat": 2.7, "carbs": 75.6, "fiber": 3.4, "sodium": 2, "category": "grain"},
    {"id": 33, "name": "燕麦米", "name_en": "Oat Groats", "pinyin": "yan mai mi", "calories": 367, "protein": 15.0, "fat": 6.7, "carbs": 61.6, "fiber": 5.3, "sodium": 3, "category": "grain"},
    {"id": 34, "name": "荞麦", "name_en": "Buckwheat", "pinyin": "qiao mai", "calories": 324, "protein": 9.7, "fat": 2.7, "carbs": 67.0, "fiber": 5.8, "sodium": 3, "category": "grain"},
    {"id": 35, "name": "挂面", "name_en": "Dried Noodles", "pinyin": "gua mian", "calories": 347, "protein": 10.7, "fat": 0.9, "carbs": 75.6, "fiber": 1.6, "sodium": 150, "category": "grain"},
    {"id": 36, "name": "意大利面", "name_en": "Pasta", "pinyin": "yi da li mian", "calories": 351, "protein": 12.5, "fat": 1.9, "carbs": 73.0, "fiber": 3.2, "sodium": 6, "category": "grain"},
    {"id": 37, "name": "通心粉", "name_en": "Macaroni", "pinyin": "tong xin fen", "calories": 350, "protein": 11.5, "fat": 1.5, "carbs": 74.5, "fiber": 2.5, "sodium": 5, "category": "grain"},
    {"id": 38, "name": "粉丝", "name_en": "Glass Noodles", "pinyin": "fen si", "calories": 335, "protein": 0.8, "fat": 0.2, "carbs": 84.2, "fiber": 0.6, "sodium": 15, "category": "grain"},
    {"id": 39, "name": "粉条", "name_en": "Sweet Potato Noodles", "pinyin": "fen tiao", "calories": 337, "protein": 0.5, "fat": 0.1, "carbs": 83.6, "fiber": 0.5, "sodium": 12, "category": "grain"},
    {"id": 40, "name": "凉皮", "name_en": "Cold Rice Noodles", "pinyin": "liang pi", "calories": 118, "protein": 3.1, "fat": 1.7, "carbs": 21.8, "fiber": 0.8, "sodium": 180, "category": "grain"},
    {"id": 41, "name": "米粉", "name_en": "Rice Noodles", "pinyin": "mi fen", "calories": 346, "protein": 6.3, "fat": 0.8, "carbs": 78.2, "fiber": 1.2, "sodium": 10, "category": "grain"},
    {"id": 42, "name": "河粉", "name_en": "Rice Sticks", "pinyin": "he fen", "calories": 330, "protein": 5.5, "fat": 0.5, "carbs": 76.5, "fiber": 0.9, "sodium": 8, "category": "grain"},
    {"id": 43, "name": "烧饼", "name_en": "Sesame Cake", "pinyin": "shao bing", "calories": 298, "protein": 7.8, "fat": 8.5, "carbs": 48.9, "fiber": 1.6, "sodium": 320, "category": "grain"},
    {"id": 44, "name": "花卷", "name_en": "Steamed Twisted Roll", "pinyin": "hua juan", "calories": 214, "protein": 6.4, "fat": 1.0, "carbs": 45.6, "fiber": 1.5, "sodium": 200, "category": "grain"},
    {"id": 45, "name": "葱油饼", "name_en": "Scallion Pancake", "pinyin": "cong you bing", "calories": 283, "protein": 7.0, "fat": 10.6, "carbs": 40.8, "fiber": 1.3, "sodium": 250, "category": "grain"},
    {"id": 46, "name": "手抓饼", "name_en": "Hand-grabbed Pancake", "pinyin": "shou zhua bing", "calories": 306, "protein": 6.9, "fat": 12.5, "carbs": 41.5, "fiber": 1.1, "sodium": 280, "category": "grain"},
    {"id": 47, "name": "鸡蛋灌饼", "name_en": "Egg Pancake", "pinyin": "ji dan guan bing", "calories": 268, "protein": 8.5, "fat": 9.8, "carbs": 36.4, "fiber": 1.2, "sodium": 220, "category": "grain"},
    {"id": 48, "name": "肉夹馍", "name_en": "Chinese Hamburger", "pinyin": "rou jia mo", "calories": 285, "protein": 12.3, "fat": 10.2, "carbs": 35.6, "fiber": 1.5, "sodium": 350, "category": "grain"},
    {"id": 49, "name": "驴肉火烧", "name_en": "Donkey Burger", "pinyin": "lv rou huo shao", "calories": 275, "protein": 15.6, "fat": 9.8, "carbs": 28.5, "fiber": 1.2, "sodium": 320, "category": "grain"},
    {"id": 50, "name": "小笼包", "name_en": "Xiaolongbao", "pinyin": "xiao long bao", "calories": 230, "protein": 9.5, "fat": 10.8, "carbs": 22.5, "fiber": 0.9, "sodium": 380, "category": "grain"},
    {"id": 51, "name": "生煎包", "name_en": "Shengjian Bao", "pinyin": "sheng jian bao", "calories": 265, "protein": 8.9, "fat": 12.5, "carbs": 28.3, "fiber": 1.1, "sodium": 350, "category": "grain"},
    {"id": 52, "name": "锅贴", "name_en": "Pot Stickers", "pinyin": "guo tie", "calories": 228, "protein": 7.5, "fat": 10.2, "carbs": 26.4, "fiber": 1.0, "sodium": 320, "category": "grain"},
    {"id": 53, "name": "烧麦", "name_en": "Shaomai", "pinyin": "shao mai", "calories": 220, "protein": 8.2, "fat": 9.5, "carbs": 24.8, "fiber": 0.8, "sodium": 300, "category": "grain"},
    {"id": 54, "name": "春卷", "name_en": "Spring Roll", "pinyin": "chun juan", "calories": 235, "protein": 5.8, "fat": 12.3, "carbs": 26.5, "fiber": 1.5, "sodium": 280, "category": "grain"},
    {"id": 55, "name": "叉烧包", "name_en": "BBQ Pork Bun", "pinyin": "cha shao bao", "calories": 250, "protein": 7.8, "fat": 5.6, "carbs": 40.2, "fiber": 1.3, "sodium": 280, "category": "grain"},
    {"id": 56, "name": "流沙包", "name_en": "Salted Egg Yolk Bun", "pinyin": "liu sha bao", "calories": 320, "protein": 6.5, "fat": 12.8, "carbs": 45.6, "fiber": 0.9, "sodium": 200, "category": "grain"},
    {"id": 57, "name": "奶黄包", "name_en": "Custard Bun", "pinyin": "nai huang bao", "calories": 285, "protein": 6.2, "fat": 8.5, "carbs": 46.8, "fiber": 0.8, "sodium": 180, "category": "grain"},
    {"id": 58, "name": "豆沙包", "name_en": "Red Bean Bun", "pinyin": "dou sha bao", "calories": 226, "protein": 6.8, "fat": 2.5, "carbs": 43.2, "fiber": 2.1, "sodium": 150, "category": "grain"},
    {"id": 59, "name": "粽子", "name_en": "Zongzi", "pinyin": "zong zi", "calories": 195, "protein": 4.5, "fat": 2.8, "carbs": 38.2, "fiber": 1.5, "sodium": 50, "category": "grain"},
    {"id": 60, "name": "月饼", "name_en": "Mooncake", "pinyin": "yue bing", "calories": 424, "protein": 6.0, "fat": 16.8, "carbs": 65.6, "fiber": 1.5, "sodium": 120, "category": "grain"},
    {"id": 61, "name": "汤圆", "name_en": "Tangyuan", "pinyin": "tang yuan", "calories": 262, "protein": 4.3, "fat": 1.8, "carbs": 58.9, "fiber": 1.0, "sodium": 15, "category": "grain"},
    {"id": 62, "name": "年糕", "name_en": "Rice Cake", "pinyin": "nian gao", "calories": 156, "protein": 3.5, "fat": 0.6, "carbs": 34.7, "fiber": 0.8, "sodium": 30, "category": "grain"},
    {"id": 63, "name": "发糕", "name_en": "Steamed Sponge Cake", "pinyin": "fa gao", "calories": 215, "protein": 5.2, "fat": 1.5, "carbs": 46.8, "fiber": 1.2, "sodium": 80, "category": "grain"},
    {"id": 64, "name": "马拉糕", "name_en": "Cantonese Sponge Cake", "pinyin": "ma la gao", "calories": 265, "protein": 4.8, "fat": 6.5, "carbs": 49.5, "fiber": 0.6, "sodium": 120, "category": "grain"},
    {"id": 65, "name": "萝卜糕", "name_en": "Turnip Cake", "pinyin": "luo bo gao", "calories": 185, "protein": 4.2, "fat": 7.8, "carbs": 24.6, "fiber": 1.2, "sodium": 280, "category": "grain"},
    {"id": 66, "name": "芋头糕", "name_en": "Taro Cake", "pinyin": "yu tou gao", "calories": 178, "protein": 3.8, "fat": 6.5, "carbs": 26.8, "fiber": 1.8, "sodium": 250, "category": "grain"},
    {"id": 67, "name": "西米", "name_en": "Sago", "pinyin": "xi mi", "calories": 310, "protein": 0.2, "fat": 0.1, "carbs": 78.5, "fiber": 0.5, "sodium": 3, "category": "grain"},
    {"id": 68, "name": "藕粉", "name_en": "Lotus Root Powder", "pinyin": "ou fen", "calories": 372, "protein": 0.2, "fat": 0.1, "carbs": 93.0, "fiber": 0.1, "sodium": 8, "category": "grain"},
    {"id": 69, "name": "葛根粉", "name_en": "Kudzu Powder", "pinyin": "ge gen fen", "calories": 345, "protein": 0.3, "fat": 0.1, "carbs": 86.2, "fiber": 0.2, "sodium": 5, "category": "grain"},
    {"id": 70, "name": "白粥", "name_en": "Rice Congee", "pinyin": "bai zhou", "calories": 46, "protein": 1.1, "fat": 0.3, "carbs": 9.9, "fiber": 0.1, "sodium": 2, "category": "grain"},
    {"id": 71, "name": "八宝粥", "name_en": "Eight Treasures Congee", "pinyin": "ba bao zhou", "calories": 85, "protein": 2.5, "fat": 0.8, "carbs": 17.6, "fiber": 1.2, "sodium": 35, "category": "grain"},
    {"id": 72, "name": "南瓜粥", "name_en": "Pumpkin Congee", "pinyin": "nan gua zhou", "calories": 55, "protein": 1.2, "fat": 0.3, "carbs": 11.8, "fiber": 0.8, "sodium": 5, "category": "grain"},
    {"id": 73, "name": "山药", "name_en": "Chinese Yam", "pinyin": "shan yao", "calories": 57, "protein": 1.9, "fat": 0.2, "carbs": 12.4, "fiber": 0.8, "sodium": 18, "category": "grain"},
    {"id": 74, "name": "芋头", "name_en": "Taro", "pinyin": "yu tou", "calories": 79, "protein": 2.2, "fat": 0.2, "carbs": 18.1, "fiber": 1.8, "sodium": 33, "category": "grain"},
    {"id": 75, "name": "木薯", "name_en": "Cassava", "pinyin": "mu shu", "calories": 116, "protein": 1.4, "fat": 0.3, "carbs": 27.8, "fiber": 1.8, "sodium": 2, "category": "grain"},
    {"id": 76, "name": "魔芋", "name_en": "Konjac", "pinyin": "mo yu", "calories": 18, "protein": 0.3, "fat": 0.1, "carbs": 4.1, "fiber": 3.3, "sodium": 2, "category": "grain"},
    {"id": 77, "name": "凉粉", "name_en": "Bean Jelly", "pinyin": "liang fen", "calories": 50, "protein": 0.2, "fat": 0.1, "carbs": 12.3, "fiber": 0.8, "sodium": 15, "category": "grain"},
    {"id": 78, "name": "碗托", "name_en": "Buckwheat Jelly", "pinyin": "wan tuo", "calories": 65, "protein": 2.3, "fat": 0.3, "carbs": 14.2, "fiber": 1.1, "sodium": 20, "category": "grain"},
    {"id": 79, "name": "米豆腐", "name_en": "Rice Tofu", "pinyin": "mi dou fu", "calories": 58, "protein": 1.5, "fat": 0.2, "carbs": 12.8, "fiber": 0.5, "sodium": 25, "category": "grain"},
    {"id": 80, "name": "藜麦", "name_en": "Quinoa", "pinyin": "li mai", "calories": 368, "protein": 14.1, "fat": 6.1, "carbs": 64.2, "fiber": 7.0, "sodium": 5, "category": "grain"},
    {"id": 81, "name": "鸡胸肉", "name_en": "Chicken Breast", "pinyin": "ji xiong rou", "calories": 133, "protein": 19.4, "fat": 5.0, "carbs": 2.5, "fiber": 0, "sodium": 69, "category": "meat"},
    {"id": 82, "name": "鸡腿肉", "name_en": "Chicken Thigh", "pinyin": "ji tui rou", "calories": 181, "protein": 16.0, "fat": 13.0, "carbs": 0, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 83, "name": "猪瘦肉", "name_en": "Lean Pork", "pinyin": "zhu shou rou", "calories": 143, "protein": 20.3, "fat": 6.2, "carbs": 1.5, "fiber": 0, "sodium": 57, "category": "meat"},
    {"id": 84, "name": "牛肉", "name_en": "Beef", "pinyin": "niu rou", "calories": 125, "protein": 19.9, "fat": 4.2, "carbs": 2.0, "fiber": 0, "sodium": 84, "category": "meat"},
    {"id": 85, "name": "羊肉", "name_en": "Lamb", "pinyin": "yang rou", "calories": 203, "protein": 19.0, "fat": 14.1, "carbs": 0, "fiber": 0, "sodium": 78, "category": "meat"},
    {"id": 86, "name": "炸鸡", "name_en": "Fried Chicken", "pinyin": "zha ji", "calories": 260, "protein": 17.0, "fat": 15.5, "carbs": 10.0, "fiber": 0.3, "sodium": 280, "category": "meat"},
    {"id": 87, "name": "红烧肉", "name_en": "Braised Pork", "pinyin": "hong shao rou", "calories": 350, "protein": 10.2, "fat": 28.5, "carbs": 8.5, "fiber": 0.2, "sodium": 250, "category": "meat"},
    {"id": 88, "name": "宫保鸡丁", "name_en": "Kung Pao Chicken", "pinyin": "gong bao ji ding", "calories": 245, "protein": 16.3, "fat": 14.8, "carbs": 12.6, "fiber": 1.2, "sodium": 380, "category": "meat"},
    {"id": 89, "name": "鱼香肉丝", "name_en": "Fish-flavored Pork", "pinyin": "yu xiang rou si", "calories": 185, "protein": 12.5, "fat": 10.2, "carbs": 13.8, "fiber": 0.8, "sodium": 420, "category": "meat"},
    {"id": 90, "name": "叉烧", "name_en": "BBQ Pork", "pinyin": "cha shao", "calories": 285, "protein": 23.8, "fat": 18.5, "carbs": 5.2, "fiber": 0, "sodium": 480, "category": "meat"},
    {"id": 91, "name": "腊肠", "name_en": "Chinese Sausage", "pinyin": "la chang", "calories": 584, "protein": 18.0, "fat": 48.3, "carbs": 17.6, "fiber": 0, "sodium": 1200, "category": "meat"},
    {"id": 92, "name": "猪五花肉", "name_en": "Pork Belly", "pinyin": "zhu wu hua rou", "calories": 395, "protein": 13.6, "fat": 37.0, "carbs": 2.4, "fiber": 0, "sodium": 59, "category": "meat"},
    {"id": 93, "name": "猪里脊肉", "name_en": "Pork Tenderloin", "pinyin": "zhu li ji rou", "calories": 155, "protein": 20.2, "fat": 7.9, "carbs": 0.7, "fiber": 0, "sodium": 43, "category": "meat"},
    {"id": 94, "name": "猪排骨", "name_en": "Pork Ribs", "pinyin": "zhu pai gu", "calories": 264, "protein": 18.3, "fat": 20.4, "carbs": 1.7, "fiber": 0, "sodium": 62, "category": "meat"},
    {"id": 95, "name": "猪蹄", "name_en": "Pork Trotter", "pinyin": "zhu ti", "calories": 260, "protein": 22.6, "fat": 18.8, "carbs": 0, "fiber": 0, "sodium": 55, "category": "meat"},
    {"id": 96, "name": "猪肝", "name_en": "Pork Liver", "pinyin": "zhu gan", "calories": 129, "protein": 19.3, "fat": 3.5, "carbs": 5.0, "fiber": 0, "sodium": 68, "category": "meat"},
    {"id": 97, "name": "猪腰子", "name_en": "Pork Kidney", "pinyin": "zhu yao zi", "calories": 96, "protein": 15.4, "fat": 3.2, "carbs": 1.4, "fiber": 0, "sodium": 140, "category": "meat"},
    {"id": 98, "name": "猪肚", "name_en": "Pork Tripe", "pinyin": "zhu du", "calories": 110, "protein": 15.2, "fat": 5.1, "carbs": 0.7, "fiber": 0, "sodium": 75, "category": "meat"},
    {"id": 99, "name": "猪大肠", "name_en": "Pork Intestine", "pinyin": "zhu da chang", "calories": 196, "protein": 6.9, "fat": 18.7, "carbs": 0, "fiber": 0, "sodium": 60, "category": "meat"},
    {"id": 100, "name": "猪心", "name_en": "Pork Heart", "pinyin": "zhu xin", "calories": 119, "protein": 16.6, "fat": 5.3, "carbs": 1.1, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 101, "name": "猪脑", "name_en": "Pork Brain", "pinyin": "zhu nao", "calories": 131, "protein": 10.8, "fat": 9.8, "carbs": 0, "fiber": 0, "sodium": 130, "category": "meat"},
    {"id": 102, "name": "牛肉里脊", "name_en": "Beef Tenderloin", "pinyin": "niu rou li ji", "calories": 105, "protein": 22.1, "fat": 1.9, "carbs": 0, "fiber": 0, "sodium": 58, "category": "meat"},
    {"id": 103, "name": "牛腩", "name_en": "Beef Brisket", "pinyin": "niu nan", "calories": 185, "protein": 19.5, "fat": 11.8, "carbs": 0, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 104, "name": "牛腱子", "name_en": "Beef Shank", "pinyin": "niu jian zi", "calories": 140, "protein": 21.8, "fat": 5.5, "carbs": 0, "fiber": 0, "sodium": 65, "category": "meat"},
    {"id": 105, "name": "牛排", "name_en": "Beef Steak", "pinyin": "niu pai", "calories": 250, "protein": 18.5, "fat": 19.0, "carbs": 0, "fiber": 0, "sodium": 70, "category": "meat"},
    {"id": 106, "name": "牛肉卷", "name_en": "Beef Roll", "pinyin": "niu rou juan", "calories": 165, "protein": 18.6, "fat": 9.8, "carbs": 0, "fiber": 0, "sodium": 65, "category": "meat"},
    {"id": 107, "name": "牛肚", "name_en": "Beef Tripe", "pinyin": "niu du", "calories": 72, "protein": 14.8, "fat": 1.8, "carbs": 0, "fiber": 0, "sodium": 68, "category": "meat"},
    {"id": 108, "name": "牛舌", "name_en": "Beef Tongue", "pinyin": "niu she", "calories": 196, "protein": 17.5, "fat": 13.8, "carbs": 0, "fiber": 0, "sodium": 70, "category": "meat"},
    {"id": 109, "name": "羊肉卷", "name_en": "Lamb Roll", "pinyin": "yang rou juan", "calories": 215, "protein": 18.2, "fat": 15.6, "carbs": 0, "fiber": 0, "sodium": 68, "category": "meat"},
    {"id": 110, "name": "羊排", "name_en": "Lamb Chop", "pinyin": "yang pai", "calories": 265, "protein": 17.5, "fat": 21.2, "carbs": 0, "fiber": 0, "sodium": 75, "category": "meat"},
    {"id": 111, "name": "羊腿肉", "name_en": "Lamb Leg", "pinyin": "yang tui rou", "calories": 185, "protein": 20.5, "fat": 10.8, "carbs": 0, "fiber": 0, "sodium": 70, "category": "meat"},
    {"id": 112, "name": "鸡肉", "name_en": "Chicken", "pinyin": "ji rou", "calories": 167, "protein": 19.3, "fat": 9.4, "carbs": 1.3, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 113, "name": "鸡翅中", "name_en": "Chicken Wing", "pinyin": "ji chi zhong", "calories": 194, "protein": 17.4, "fat": 13.8, "carbs": 0, "fiber": 0, "sodium": 68, "category": "meat"},
    {"id": 114, "name": "鸡爪", "name_en": "Chicken Feet", "pinyin": "ji zhua", "calories": 254, "protein": 23.9, "fat": 16.4, "carbs": 2.4, "fiber": 0, "sodium": 75, "category": "meat"},
    {"id": 115, "name": "鸡胗", "name_en": "Chicken Gizzard", "pinyin": "ji zhen", "calories": 118, "protein": 19.2, "fat": 2.8, "carbs": 4.1, "fiber": 0, "sodium": 78, "category": "meat"},
    {"id": 116, "name": "鸭肉", "name_en": "Duck", "pinyin": "ya rou", "calories": 240, "protein": 15.5, "fat": 19.7, "carbs": 0.2, "fiber": 0, "sodium": 69, "category": "meat"},
    {"id": 117, "name": "鸭脖", "name_en": "Duck Neck", "pinyin": "ya bo", "calories": 235, "protein": 15.8, "fat": 18.5, "carbs": 1.5, "fiber": 0, "sodium": 85, "category": "meat"},
    {"id": 118, "name": "鸭翅", "name_en": "Duck Wing", "pinyin": "ya chi", "calories": 220, "protein": 16.5, "fat": 16.8, "carbs": 0.5, "fiber": 0, "sodium": 70, "category": "meat"},
    {"id": 119, "name": "鸭掌", "name_en": "Duck Feet", "pinyin": "ya zhang", "calories": 245, "protein": 24.5, "fat": 15.2, "carbs": 1.2, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 120, "name": "鹅肉", "name_en": "Goose", "pinyin": "e rou", "calories": 251, "protein": 17.9, "fat": 19.9, "carbs": 0, "fiber": 0, "sodium": 58, "category": "meat"},
    {"id": 121, "name": "兔肉", "name_en": "Rabbit", "pinyin": "tu rou", "calories": 102, "protein": 19.7, "fat": 2.2, "carbs": 0.4, "fiber": 0, "sodium": 45, "category": "meat"},
    {"id": 122, "name": "驴肉", "name_en": "Donkey", "pinyin": "lv rou", "calories": 116, "protein": 21.5, "fat": 3.2, "carbs": 0.4, "fiber": 0, "sodium": 52, "category": "meat"},
    {"id": 123, "name": "培根", "name_en": "Bacon", "pinyin": "pei gen", "calories": 181, "protein": 22.3, "fat": 9.7, "carbs": 2.0, "fiber": 0, "sodium": 800, "category": "meat"},
    {"id": 124, "name": "火腿", "name_en": "Ham", "pinyin": "huo tui", "calories": 145, "protein": 16.5, "fat": 8.2, "carbs": 2.5, "fiber": 0, "sodium": 650, "category": "meat"},
    {"id": 125, "name": "腊肉", "name_en": "Cured Meat", "pinyin": "la rou", "calories": 498, "protein": 11.8, "fat": 48.8, "carbs": 2.1, "fiber": 0, "sodium": 760, "category": "meat"},
    {"id": 126, "name": "午餐肉", "name_en": "Luncheon Meat", "pinyin": "wu can rou", "calories": 229, "protein": 9.4, "fat": 17.4, "carbs": 7.5, "fiber": 0, "sodium": 980, "category": "meat"},
    {"id": 127, "name": "肉丸子", "name_en": "Meatball", "pinyin": "rou wan zi", "calories": 205, "protein": 12.8, "fat": 15.2, "carbs": 4.5, "fiber": 0.3, "sodium": 350, "category": "meat"},
    {"id": 128, "name": "狮子头", "name_en": "Lion's Head Meatball", "pinyin": "shi zi tou", "calories": 280, "protein": 15.2, "fat": 22.5, "carbs": 3.8, "fiber": 0.5, "sodium": 380, "category": "meat"},
    {"id": 129, "name": "糖醋里脊", "name_en": "Sweet and Sour Pork", "pinyin": "tang cu li ji", "calories": 310, "protein": 14.5, "fat": 16.8, "carbs": 25.5, "fiber": 0.3, "sodium": 320, "category": "meat"},
    {"id": 130, "name": "京酱肉丝", "name_en": "Pork in Beijing Sauce", "pinyin": "jing jiang rou si", "calories": 225, "protein": 13.8, "fat": 12.5, "carbs": 12.2, "fiber": 0.4, "sodium": 450, "category": "meat"},
    {"id": 131, "name": "回锅肉", "name_en": "Twice-cooked Pork", "pinyin": "hui guo rou", "calories": 345, "protein": 12.5, "fat": 28.8, "carbs": 8.5, "fiber": 0.5, "sodium": 420, "category": "meat"},
    {"id": 132, "name": "水煮牛肉", "name_en": "Sichuan Boiled Beef", "pinyin": "shui zhu niu rou", "calories": 265, "protein": 18.5, "fat": 18.5, "carbs": 6.8, "fiber": 0.8, "sodium": 520, "category": "meat"},
    {"id": 133, "name": "黑椒牛柳", "name_en": "Black Pepper Beef", "pinyin": "hei jiao niu liu", "calories": 215, "protein": 19.2, "fat": 12.5, "carbs": 5.8, "fiber": 0.3, "sodium": 380, "category": "meat"},
    {"id": 134, "name": "咖喱鸡", "name_en": "Curry Chicken", "pinyin": "ka li ji", "calories": 268, "protein": 15.8, "fat": 16.5, "carbs": 12.8, "fiber": 1.2, "sodium": 420, "category": "meat"},
    {"id": 135, "name": "可乐鸡翅", "name_en": "Coca-Cola Chicken Wings", "pinyin": "ke le ji chi", "calories": 245, "protein": 15.2, "fat": 12.8, "carbs": 15.5, "fiber": 0.2, "sodium": 280, "category": "meat"},
    {"id": 136, "name": "啤酒鸭", "name_en": "Beer Duck", "pinyin": "pi jiu ya", "calories": 285, "protein": 14.5, "fat": 20.5, "carbs": 6.8, "fiber": 0.5, "sodium": 350, "category": "meat"},
    {"id": 137, "name": "鸡蛋", "name_en": "Egg", "pinyin": "ji dan", "calories": 144, "protein": 13.3, "fat": 8.8, "carbs": 2.8, "fiber": 0, "sodium": 132, "category": "egg"},
    {"id": 138, "name": "鸭蛋", "name_en": "Duck Egg", "pinyin": "ya dan", "calories": 180, "protein": 12.6, "fat": 13.0, "carbs": 3.1, "fiber": 0, "sodium": 106, "category": "egg"},
    {"id": 139, "name": "咸鸭蛋", "name_en": "Salted Duck Egg", "pinyin": "xian ya dan", "calories": 190, "protein": 12.7, "fat": 12.7, "carbs": 6.3, "fiber": 0, "sodium": 2706, "category": "egg"},
    {"id": 140, "name": "鹌鹑蛋", "name_en": "Quail Egg", "pinyin": "an chun dan", "calories": 160, "protein": 12.8, "fat": 11.1, "carbs": 2.1, "fiber": 0, "sodium": 106, "category": "egg"},
    {"id": 141, "name": "鹅蛋", "name_en": "Goose Egg", "pinyin": "e dan", "calories": 196, "protein": 11.1, "fat": 15.6, "carbs": 2.8, "fiber": 0, "sodium": 90, "category": "egg"},
    {"id": 142, "name": "皮蛋", "name_en": "Century Egg", "pinyin": "pi dan", "calories": 171, "protein": 14.2, "fat": 10.7, "carbs": 4.5, "fiber": 0, "sodium": 542, "category": "egg"},
    {"id": 143, "name": "茶叶蛋", "name_en": "Tea Egg", "pinyin": "cha ye dan", "calories": 148, "protein": 13.5, "fat": 8.9, "carbs": 3.2, "fiber": 0, "sodium": 185, "category": "egg"},
    {"id": 144, "name": "卤蛋", "name_en": "Marinated Egg", "pinyin": "lu dan", "calories": 150, "protein": 13.6, "fat": 9.2, "carbs": 2.8, "fiber": 0, "sodium": 220, "category": "egg"},
    {"id": 145, "name": "鸡蛋羹", "name_en": "Egg Custard", "pinyin": "ji dan geng", "calories": 85, "protein": 6.8, "fat": 4.5, "carbs": 2.5, "fiber": 0, "sodium": 120, "category": "egg"},
    {"id": 146, "name": "荷包蛋", "name_en": "Fried Egg", "pinyin": "he bao dan", "calories": 196, "protein": 13.5, "fat": 15.2, "carbs": 1.5, "fiber": 0, "sodium": 150, "category": "egg"},
    {"id": 147, "name": "牛奶", "name_en": "Milk", "pinyin": "niu nai", "calories": 54, "protein": 3.0, "fat": 3.2, "carbs": 3.4, "fiber": 0, "sodium": 37, "category": "dairy"},
    {"id": 148, "name": "酸奶", "name_en": "Yogurt", "pinyin": "suan nai", "calories": 72, "protein": 2.5, "fat": 2.7, "carbs": 9.3, "fiber": 0, "sodium": 39, "category": "dairy"},
    {"id": 149, "name": "奶酪", "name_en": "Cheese", "pinyin": "nai lao", "calories": 328, "protein": 25.7, "fat": 23.5, "carbs": 3.5, "fiber": 0, "sodium": 584, "category": "dairy"},
    {"id": 150, "name": "酸奶水果捞", "name_en": "Yogurt Fruit Bowl", "pinyin": "suan nai shui guo lao", "calories": 110, "protein": 3.5, "fat": 2.2, "carbs": 21.5, "fiber": 1.8, "sodium": 45, "category": "dairy"},
    {"id": 151, "name": "全脂牛奶", "name_en": "Whole Milk", "pinyin": "quan zhi niu nai", "calories": 65, "protein": 3.2, "fat": 3.8, "carbs": 4.8, "fiber": 0, "sodium": 45, "category": "dairy"},
    {"id": 152, "name": "脱脂牛奶", "name_en": "Skim Milk", "pinyin": "tuo zhi niu nai", "calories": 34, "protein": 3.4, "fat": 0.2, "carbs": 4.8, "fiber": 0, "sodium": 45, "category": "dairy"},
    {"id": 153, "name": "低脂牛奶", "name_en": "Low-fat Milk", "pinyin": "di zhi niu nai", "calories": 48, "protein": 3.3, "fat": 1.5, "carbs": 4.8, "fiber": 0, "sodium": 43, "category": "dairy"},
    {"id": 154, "name": "羊奶", "name_en": "Goat Milk", "pinyin": "yang nai", "calories": 59, "protein": 3.0, "fat": 3.5, "carbs": 5.4, "fiber": 0, "sodium": 40, "category": "dairy"},
    {"id": 155, "name": "黄油", "name_en": "Butter", "pinyin": "huang you", "calories": 888, "protein": 1.4, "fat": 98.0, "carbs": 0, "fiber": 0, "sodium": 12, "category": "dairy"},
    {"id": 156, "name": "淡奶油", "name_en": "Heavy Cream", "pinyin": "dan nai you", "calories": 345, "protein": 2.1, "fat": 37.0, "carbs": 3.0, "fiber": 0, "sodium": 35, "category": "dairy"},
    {"id": 157, "name": "炼乳", "name_en": "Condensed Milk", "pinyin": "lian ru", "calories": 332, "protein": 8.0, "fat": 8.7, "carbs": 55.5, "fiber": 0, "sodium": 128, "category": "dairy"},
    {"id": 158, "name": "奶油奶酪", "name_en": "Cream Cheese", "pinyin": "nai you nai lao", "calories": 342, "protein": 7.5, "fat": 34.0, "carbs": 3.0, "fiber": 0, "sodium": 320, "category": "dairy"},
    {"id": 159, "name": "马苏里拉奶酪", "name_en": "Mozzarella", "pinyin": "ma su li la nai lao", "calories": 280, "protein": 25.0, "fat": 18.0, "carbs": 3.0, "fiber": 0, "sodium": 620, "category": "dairy"},
    {"id": 160, "name": "老酸奶", "name_en": "Greek Yogurt", "pinyin": "lao suan nai", "calories": 95, "protein": 5.5, "fat": 4.5, "carbs": 7.5, "fiber": 0, "sodium": 55, "category": "dairy"},
    {"id": 161, "name": "豆浆", "name_en": "Soy Milk", "pinyin": "dou jiang", "calories": 31, "protein": 1.8, "fat": 0.7, "carbs": 4.0, "fiber": 0.3, "sodium": 10, "category": "bean"},
    {"id": 162, "name": "豆腐", "name_en": "Tofu", "pinyin": "dou fu", "calories": 81, "protein": 8.1, "fat": 3.7, "carbs": 4.2, "fiber": 0.4, "sodium": 7.2, "category": "bean"},
    {"id": 163, "name": "黄豆", "name_en": "Soybean", "pinyin": "huang dou", "calories": 359, "protein": 35.1, "fat": 16.0, "carbs": 34.2, "fiber": 15.5, "sodium": 2, "category": "bean"},
    {"id": 164, "name": "红豆", "name_en": "Red Bean", "pinyin": "hong dou", "calories": 324, "protein": 20.2, "fat": 0.6, "carbs": 63.4, "fiber": 7.7, "sodium": 2, "category": "bean"},
    {"id": 165, "name": "绿豆", "name_en": "Mung Bean", "pinyin": "lv dou", "calories": 319, "protein": 21.6, "fat": 0.8, "carbs": 62.0, "fiber": 6.4, "sodium": 3, "category": "bean"},
    {"id": 166, "name": "麻婆豆腐", "name_en": "Mapo Tofu", "pinyin": "ma po dou fu", "calories": 105, "protein": 6.8, "fat": 5.2, "carbs": 7.2, "fiber": 0.6, "sodium": 320, "category": "bean"},
    {"id": 167, "name": "黑豆", "name_en": "Black Bean", "pinyin": "hei dou", "calories": 381, "protein": 36.0, "fat": 15.9, "carbs": 33.6, "fiber": 10.2, "sodium": 3, "category": "bean"},
    {"id": 168, "name": "芸豆", "name_en": "Kidney Bean", "pinyin": "yun dou", "calories": 314, "protein": 21.4, "fat": 1.3, "carbs": 62.5, "fiber": 8.3, "sodium": 2, "category": "bean"},
    {"id": 169, "name": "豌豆", "name_en": "Pea", "pinyin": "wan dou", "calories": 334, "protein": 20.3, "fat": 1.1, "carbs": 65.8, "fiber": 10.4, "sodium": 2, "category": "bean"},
    {"id": 170, "name": "蚕豆", "name_en": "Broad Bean", "pinyin": "can dou", "calories": 338, "protein": 25.8, "fat": 1.5, "carbs": 58.4, "fiber": 12.0, "sodium": 2, "category": "bean"},
    {"id": 171, "name": "鹰嘴豆", "name_en": "Chickpea", "pinyin": "ying zui dou", "calories": 364, "protein": 19.0, "fat": 6.0, "carbs": 61.0, "fiber": 17.4, "sodium": 6, "category": "bean"},
    {"id": 172, "name": "扁豆", "name_en": "Lentil", "pinyin": "bian dou", "calories": 326, "protein": 25.8, "fat": 0.9, "carbs": 60.1, "fiber": 30.5, "sodium": 6, "category": "bean"},
    {"id": 173, "name": "四季豆", "name_en": "Green Bean", "pinyin": "si ji dou", "calories": 28, "protein": 2.0, "fat": 0.4, "carbs": 5.7, "fiber": 2.1, "sodium": 12, "category": "bean"},
    {"id": 174, "name": "豆角", "name_en": "Cowpea", "pinyin": "dou jiao", "calories": 30, "protein": 2.5, "fat": 0.3, "carbs": 6.7, "fiber": 2.3, "sodium": 3, "category": "bean"},
    {"id": 175, "name": "荷兰豆", "name_en": "Snow Pea", "pinyin": "he lan dou", "calories": 27, "protein": 2.5, "fat": 0.3, "carbs": 4.9, "fiber": 1.4, "sodium": 5, "category": "bean"},
    {"id": 176, "name": "毛豆", "name_en": "Edamame", "pinyin": "mao dou", "calories": 123, "protein": 13.1, "fat": 5.0, "carbs": 10.5, "fiber": 4.0, "sodium": 5, "category": "bean"},
    {"id": 177, "name": "豆腐干", "name_en": "Dried Tofu", "pinyin": "dou fu gan", "calories": 140, "protein": 16.2, "fat": 3.6, "carbs": 10.7, "fiber": 0.8, "sodium": 25, "category": "bean"},
    {"id": 178, "name": "豆腐皮", "name_en": "Tofu Skin", "pinyin": "dou fu pi", "calories": 409, "protein": 44.6, "fat": 17.4, "carbs": 18.8, "fiber": 0.3, "sodium": 25, "category": "bean"},
    {"id": 179, "name": "腐竹", "name_en": "Yuba", "pinyin": "fu zhu", "calories": 459, "protein": 44.6, "fat": 21.7, "carbs": 22.3, "fiber": 1.0, "sodium": 26, "category": "bean"},
    {"id": 180, "name": "素鸡", "name_en": "Vegetarian Chicken", "pinyin": "su ji", "calories": 192, "protein": 16.5, "fat": 12.5, "carbs": 3.3, "fiber": 0.3, "sodium": 35, "category": "bean"},
    {"id": 181, "name": "油豆腐", "name_en": "Fried Tofu", "pinyin": "you dou fu", "calories": 244, "protein": 17.0, "fat": 17.6, "carbs": 4.9, "fiber": 0.4, "sodium": 17, "category": "bean"},
    {"id": 182, "name": "内酯豆腐", "name_en": "Silken Tofu", "pinyin": "nei zhi dou fu", "calories": 49, "protein": 5.0, "fat": 2.4, "carbs": 2.0, "fiber": 0.2, "sodium": 8, "category": "bean"},
    {"id": 183, "name": "北豆腐", "name_en": "Firm Tofu", "pinyin": "bei dou fu", "calories": 98, "protein": 12.2, "fat": 4.8, "carbs": 1.5, "fiber": 0.4, "sodium": 10, "category": "bean"},
    {"id": 184, "name": "南豆腐", "name_en": "Soft Tofu", "pinyin": "nan dou fu", "calories": 57, "protein": 6.2, "fat": 2.5, "carbs": 1.5, "fiber": 0.2, "sodium": 6, "category": "bean"},
    {"id": 185, "name": "豆芽", "name_en": "Bean Sprouts", "pinyin": "dou ya", "calories": 18, "protein": 1.5, "fat": 0.1, "carbs": 3.2, "fiber": 0.5, "sodium": 4, "category": "bean"},
    {"id": 186, "name": "绿豆芽", "name_en": "Mung Bean Sprouts", "pinyin": "lv dou ya", "calories": 16, "protein": 1.4, "fat": 0.1, "carbs": 2.9, "fiber": 0.4, "sodium": 3, "category": "bean"},
    {"id": 187, "name": "黄豆芽", "name_en": "Soybean Sprouts", "pinyin": "huang dou ya", "calories": 44, "protein": 4.5, "fat": 1.6, "carbs": 3.0, "fiber": 1.5, "sodium": 5, "category": "bean"},
    {"id": 188, "name": "红豆沙", "name_en": "Red Bean Paste", "pinyin": "hong dou sha", "calories": 240, "protein": 5.5, "fat": 1.8, "carbs": 52.5, "fiber": 3.5, "sodium": 15, "category": "bean"},
    {"id": 189, "name": "豆沙馅", "name_en": "Bean Paste Filling", "pinyin": "dou sha xian", "calories": 268, "protein": 5.8, "fat": 2.0, "carbs": 58.5, "fiber": 3.8, "sodium": 18, "category": "bean"},
    {"id": 190, "name": "豆腐乳", "name_en": "Fermented Tofu", "pinyin": "dou fu ru", "calories": 133, "protein": 10.9, "fat": 8.2, "carbs": 3.9, "fiber": 0.5, "sodium": 2460, "category": "seasoning"},
    {"id": 191, "name": "白菜", "name_en": "Chinese Cabbage", "pinyin": "bai cai", "calories": 17, "protein": 1.5, "fat": 0.1, "carbs": 3.2, "fiber": 0.8, "sodium": 89, "category": "vegetable"},
    {"id": 192, "name": "菠菜", "name_en": "Spinach", "pinyin": "bo cai", "calories": 28, "protein": 2.6, "fat": 0.3, "carbs": 4.5, "fiber": 1.7, "sodium": 209, "category": "vegetable"},
    {"id": 193, "name": "西兰花", "name_en": "Broccoli", "pinyin": "xi lan hua", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 6.6, "fiber": 1.7, "sodium": 33, "category": "vegetable"},
    {"id": 194, "name": "胡萝卜", "name_en": "Carrot", "pinyin": "hu luo bo", "calories": 39, "protein": 1.0, "fat": 0.2, "carbs": 8.8, "fiber": 1.6, "sodium": 25, "category": "vegetable"},
    {"id": 195, "name": "西红柿", "name_en": "Tomato", "pinyin": "xi hong shi", "calories": 20, "protein": 0.9, "fat": 0.2, "carbs": 4.0, "fiber": 0.5, "sodium": 5, "category": "vegetable"},
    {"id": 196, "name": "黄瓜", "name_en": "Cucumber", "pinyin": "huang gua", "calories": 16, "protein": 0.8, "fat": 0.2, "carbs": 2.9, "fiber": 0.5, "sodium": 2, "category": "vegetable"},
    {"id": 197, "name": "茄子", "name_en": "Eggplant", "pinyin": "qie zi", "calories": 23, "protein": 1.1, "fat": 0.2, "carbs": 4.9, "fiber": 1.3, "sodium": 5, "category": "vegetable"},
    {"id": 198, "name": "青椒", "name_en": "Green Pepper", "pinyin": "qing jiao", "calories": 22, "protein": 1.0, "fat": 0.2, "carbs": 4.6, "fiber": 0.8, "sodium": 2, "category": "vegetable"},
    {"id": 199, "name": "洋葱", "name_en": "Onion", "pinyin": "yang cong", "calories": 40, "protein": 1.1, "fat": 0.2, "carbs": 9.0, "fiber": 0.9, "sodium": 4, "category": "vegetable"},
    {"id": 200, "name": "生菜", "name_en": "Lettuce", "pinyin": "sheng cai", "calories": 15, "protein": 1.4, "fat": 0.2, "carbs": 2.1, "fiber": 0.6, "sodium": 28, "category": "vegetable"},
    {"id": 201, "name": "芹菜", "name_en": "Celery", "pinyin": "qin cai", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 3.9, "fiber": 1.3, "sodium": 75, "category": "vegetable"},
    {"id": 202, "name": "韭菜", "name_en": "Leek", "pinyin": "jiu cai", "calories": 29, "protein": 2.4, "fat": 0.4, "carbs": 4.6, "fiber": 1.4, "sodium": 27, "category": "vegetable"},
    {"id": 203, "name": "蘑菇", "name_en": "Mushroom", "pinyin": "mo gu", "calories": 27, "protein": 2.7, "fat": 0.1, "carbs": 4.1, "fiber": 2.1, "sodium": 11, "category": "vegetable"},
    {"id": 204, "name": "海带", "name_en": "Kelp", "pinyin": "hai dai", "calories": 13, "protein": 1.1, "fat": 0.1, "carbs": 2.1, "fiber": 0.5, "sodium": 251, "category": "vegetable"},
    {"id": 205, "name": "南瓜", "name_en": "Pumpkin", "pinyin": "nan gua", "calories": 26, "protein": 0.7, "fat": 0.1, "carbs": 6.5, "fiber": 0.8, "sodium": 8, "category": "vegetable"},
    {"id": 206, "name": "芦笋", "name_en": "Asparagus", "pinyin": "lu sun", "calories": 22, "protein": 2.6, "fat": 0.1, "carbs": 4.9, "fiber": 1.9, "sodium": 3, "category": "vegetable"},
    {"id": 207, "name": "秋葵", "name_en": "Okra", "pinyin": "qiu kui", "calories": 37, "protein": 2.0, "fat": 0.1, "carbs": 7.1, "fiber": 3.3, "sodium": 4, "category": "vegetable"},
    {"id": 208, "name": "莲藕", "name_en": "Lotus Root", "pinyin": "lian ou", "calories": 73, "protein": 1.9, "fat": 0.2, "carbs": 16.4, "fiber": 1.2, "sodium": 44, "category": "vegetable"},
    {"id": 209, "name": "凉拌黄瓜", "name_en": "Cucumber Salad", "pinyin": "liang ban huang gua", "calories": 35, "protein": 1.2, "fat": 2.1, "carbs": 3.5, "fiber": 0.6, "sodium": 180, "category": "vegetable"},
    {"id": 210, "name": "炒青菜", "name_en": "Stir-fried Greens", "pinyin": "chao qing cai", "calories": 65, "protein": 2.1, "fat": 4.5, "carbs": 4.2, "fiber": 1.2, "sodium": 220, "category": "vegetable"},
    {"id": 211, "name": "地三鲜", "name_en": "Di San Xian", "pinyin": "di san xian", "calories": 148, "protein": 3.5, "fat": 8.6, "carbs": 15.8, "fiber": 2.1, "sodium": 280, "category": "vegetable"},
    {"id": 212, "name": "沙拉", "name_en": "Salad", "pinyin": "sha la", "calories": 85, "protein": 2.8, "fat": 5.2, "carbs": 7.8, "fiber": 2.5, "sodium": 180, "category": "vegetable"},
    {"id": 213, "name": "大白菜", "name_en": "Napa Cabbage", "pinyin": "da bai cai", "calories": 15, "protein": 1.4, "fat": 0.1, "carbs": 2.8, "fiber": 0.9, "sodium": 57, "category": "vegetable"},
    {"id": 214, "name": "小白菜", "name_en": "Bok Choy", "pinyin": "xiao bai cai", "calories": 15, "protein": 1.5, "fat": 0.3, "carbs": 2.7, "fiber": 1.1, "sodium": 73, "category": "vegetable"},
    {"id": 215, "name": "娃娃菜", "name_en": "Baby Cabbage", "pinyin": "wa wa cai", "calories": 13, "protein": 1.7, "fat": 0.1, "carbs": 2.4, "fiber": 0.9, "sodium": 60, "category": "vegetable"},
    {"id":  216, "name": "油菜", "name_en": "Rapeseed Greens", "pinyin": "you cai", "calories": 23, "protein": 1.8, "fat": 0.5, "carbs": 3.8, "fiber": 1.2, "sodium": 55, "category": "vegetable"},
    {"id": 217, "name": "油麦菜", "name_en": "Lettuce", "pinyin": "you mai cai", "calories": 15, "protein": 1.4, "fat": 0.4, "carbs": 2.1, "fiber": 0.6, "sodium": 35, "category": "vegetable"},
    {"id": 218, "name": "空心菜", "name_en": "Water Spinach", "pinyin": "kong xin cai", "calories": 20, "protein": 2.2, "fat": 0.3, "carbs": 3.6, "fiber": 1.4, "sodium": 94, "category": "vegetable"},
    {"id": 219, "name": "苋菜", "name_en": "Amaranth", "pinyin": "xian cai", "calories": 25, "protein": 2.8, "fat": 0.4, "carbs": 4.9, "fiber": 1.8, "sodium": 45, "category": "vegetable"},
    {"id": 220, "name": "茼蒿", "name_en": "Crown Daisy", "pinyin": "tong hao", "calories": 24, "protein": 1.9, "fat": 0.3, "carbs": 4.5, "fiber": 1.2, "sodium": 161, "category": "vegetable"},
    {"id": 221, "name": "香菜", "name_en": "Coriander", "pinyin": "xiang cai", "calories": 24, "protein": 1.8, "fat": 0.4, "carbs": 5.0, "fiber": 1.2, "sodium": 48, "category": "vegetable"},
    {"id": 222, "name": "蒜苗", "name_en": "Garlic Sprout", "pinyin": "suan miao", "calories": 37, "protein": 2.1, "fat": 0.4, "carbs": 8.0, "fiber": 1.8, "sodium": 5, "category": "vegetable"},
    {"id": 223, "name": "蒜苔", "name_en": "Garlic Bolt", "pinyin": "suan tai", "calories": 61, "protein": 2.0, "fat": 0.1, "carbs": 15.4, "fiber": 2.5, "sodium": 4, "category": "vegetable"},
    {"id": 224, "name": "大葱", "name_en": "Scallion", "pinyin": "da cong", "calories": 28, "protein": 1.7, "fat": 0.3, "carbs": 6.5, "fiber": 1.3, "sodium": 4.8, "category": "vegetable"},
    {"id": 225, "name": "小葱", "name_en": "Green Onion", "pinyin": "xiao cong", "calories": 24, "protein": 1.6, "fat": 0.4, "carbs": 4.9, "fiber": 1.4, "sodium": 5, "category": "vegetable"},
    {"id": 226, "name": "大蒜", "name_en": "Garlic", "pinyin": "da suan", "calories": 126, "protein": 4.5, "fat": 0.2, "carbs": 27.6, "fiber": 1.1, "sodium": 19, "category": "seasoning"},
    {"id": 227, "name": "生姜", "name_en": "Ginger", "pinyin": "sheng jiang", "calories": 41, "protein": 1.3, "fat": 0.6, "carbs": 10.3, "fiber": 2.7, "sodium": 2, "category": "seasoning"},
    {"id": 228, "name": "辣椒", "name_en": "Chili", "pinyin": "la jiao", "calories": 32, "protein": 1.3, "fat": 0.4, "carbs": 8.9, "fiber": 3.2, "sodium": 3, "category": "vegetable"},
    {"id": 229, "name": "红椒", "name_en": "Red Pepper", "pinyin": "hong jiao", "calories": 26, "protein": 1.3, "fat": 0.3, "carbs": 6.0, "fiber": 2.5, "sodium": 3, "category": "vegetable"},
    {"id": 230, "name": "甜椒", "name_en": "Bell Pepper", "pinyin": "tian jiao", "calories": 20, "protein": 1.0, "fat": 0.2, "carbs": 6.4, "fiber": 1.4, "sodium": 2, "category": "vegetable"},
    {"id": 231, "name": "白萝卜", "name_en": "White Radish", "pinyin": "bai luo bo", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 4.0, "fiber": 1.6, "sodium": 62, "category": "vegetable"},
    {"id": 232, "name": "胡萝卜", "name_en": "Carrot", "pinyin": "hu luo bo", "calories": 39, "protein": 1.0, "fat": 0.2, "carbs": 8.8, "fiber": 1.6, "sodium": 25, "category": "vegetable"},
    {"id": 233, "name": "青萝卜", "name_en": "Green Radish", "pinyin": "qing luo bo", "calories": 29, "protein": 1.3, "fat": 0.2, "carbs": 6.8, "fiber": 2.1, "sodium": 35, "category": "vegetable"},
    {"id": 234, "name": "心里美萝卜", "name_en": "Heart Radish", "pinyin": "xin li mei luo bo", "calories": 21, "protein": 0.9, "fat": 0.1, "carbs": 5.1, "fiber": 1.4, "sodium": 42, "category": "vegetable"},
    {"id": 235, "name": "土豆丝", "name_en": "Shredded Potato", "pinyin": "tu dou si", "calories": 88, "protein": 2.3, "fat": 2.5, "carbs": 16.5, "fiber": 0.8, "sodium": 180, "category": "vegetable"},
    {"id": 236, "name": "酸辣土豆丝", "name_en": "Hot and Sour Potato", "pinyin": "suan la tu dou si", "calories": 102, "protein": 2.5, "fat": 4.2, "carbs": 16.8, "fiber": 0.9, "sodium": 280, "category": "vegetable"},
    {"id": 237, "name": "红烧茄子", "name_en": "Braised Eggplant", "pinyin": "hong shao qie zi", "calories": 85, "protein": 1.8, "fat": 5.2, "carbs": 10.5, "fiber": 1.8, "sodium": 320, "category": "vegetable"},
    {"id": 238, "name": "鱼香茄子", "name_en": "Fish-flavored Eggplant", "pinyin": "yu xiang qie zi", "calories": 108, "protein": 2.2, "fat": 6.8, "carbs": 12.5, "fiber": 1.6, "sodium": 380, "category": "vegetable"},
    {"id": 239, "name": "蒜蓉西兰花", "name_en": "Garlic Broccoli", "pinyin": "suan rong xi lan hua", "calories": 55, "protein": 3.2, "fat": 2.5, "carbs": 7.8, "fiber": 2.1, "sodium": 180, "category": "vegetable"},
    {"id": 240, "name": "清炒菠菜", "name_en": "Stir-fried Spinach", "pinyin": "qing chao bo cai", "calories": 55, "protein": 3.2, "fat": 3.5, "carbs": 5.8, "fiber": 2.1, "sodium": 220, "category": "vegetable"},
    {"id": 241, "name": "西红柿炒蛋", "name_en": "Tomato and Egg Stir-fry", "pinyin": "xi hong shi chao dan", "calories": 105, "protein": 6.5, "fat": 6.8, "carbs": 6.5, "fiber": 0.6, "sodium": 280, "category": "vegetable"},
    {"id": 242, "name": "黄瓜炒蛋", "name_en": "Cucumber and Egg", "pinyin": "huang gua chao dan", "calories": 85, "protein": 5.8, "fat": 5.5, "carbs": 4.2, "fiber": 0.5, "sodium": 220, "category": "vegetable"},
    {"id": 243, "name": "丝瓜", "name_en": "Loofah", "pinyin": "si gua", "calories": 20, "protein": 1.0, "fat": 0.2, "carbs": 4.2, "fiber": 0.6, "sodium": 3, "category": "vegetable"},
    {"id": 244, "name": "冬瓜", "name_en": "Winter Melon", "pinyin": "dong gua", "calories": 12, "protein": 0.4, "fat": 0.2, "carbs": 2.6, "fiber": 0.7, "sodium": 2, "category": "vegetable"},
    {"id": 245, "name": "苦瓜", "name_en": "Bitter Melon", "pinyin": "ku gua", "calories": 19, "protein": 1.0, "fat": 0.1, "carbs": 4.9, "fiber": 1.4, "sodium": 2, "category": "vegetable"},
    {"id": 246, "name": "黄瓜", "name_en": "Cucumber", "pinyin": "huang gua", "calories": 16, "protein": 0.8, "fat": 0.2, "carbs": 2.9, "fiber": 0.5, "sodium": 2, "category": "vegetable"},
    {"id": 247, "name": "西葫芦", "name_en": "Zucchini", "pinyin": "xi hu lu", "calories": 18, "protein": 0.8, "fat": 0.2, "carbs": 3.8, "fiber": 0.6, "sodium": 3, "category": "vegetable"},
    {"id": 248, "name": "佛手瓜", "name_en": "Chayote", "pinyin": "fo shou gua", "calories": 18, "protein": 0.8, "fat": 0.1, "carbs": 4.3, "fiber": 1.1, "sodium": 3, "category": "vegetable"},
    {"id": 249, "name": "香菇", "name_en": "Shiitake Mushroom", "pinyin": "xiang gu", "calories": 26, "protein": 2.2, "fat": 0.3, "carbs": 5.2, "fiber": 3.3, "sodium": 11, "category": "vegetable"},
    {"id": 250, "name": "平菇", "name_en": "Oyster Mushroom", "pinyin": "ping gu", "calories": 24, "protein": 1.9, "fat": 0.3, "carbs": 4.6, "fiber": 2.3, "sodium": 8, "category": "vegetable"},
    {"id": 251, "name": "金针菇", "name_en": "Enoki Mushroom", "pinyin": "jin zhen gu", "calories": 26, "protein": 2.4, "fat": 0.4, "carbs": 6.0, "fiber": 2.7, "sodium": 4, "category": "vegetable"},
    {"id": 252, "name": "杏鲍菇", "name_en": "King Oyster Mushroom", "pinyin": "xing bao gu", "calories": 35, "protein": 1.3, "fat": 0.1, "carbs": 8.3, "fiber": 2.1, "sodium": 6, "category": "vegetable"},
    {"id": 253, "name": "木耳", "name_en": "Black Fungus", "pinyin": "mu er", "calories": 25, "protein": 1.5, "fat": 0.2, "carbs": 6.7, "fiber": 2.6, "sodium": 8, "category": "vegetable"},
    {"id": 254, "name": "银耳", "name_en": "White Fungus", "pinyin": "yin er", "calories": 200, "protein": 10.0, "fat": 1.4, "carbs": 67.3, "fiber": 30.4, "sodium": 8, "category": "vegetable"},
    {"id": 255, "name": "紫菜", "name_en": "Nori", "pinyin": "zi cai", "calories": 207, "protein": 26.7, "fat": 1.1, "carbs": 44.1, "fiber": 21.6, "sodium": 710, "category": "vegetable"},
    {"id": 256, "name": "裙带菜", "name_en": "Wakame", "pinyin": "qun dai cai", "calories": 45, "protein": 5.8, "fat": 1.4, "carbs": 9.1, "fiber": 6.1, "sodium": 272, "category": "vegetable"},
    {"id": 257, "name": "苹果", "name_en": "Apple", "pinyin": "ping guo", "calories": 54, "protein": 0.2, "fat": 0.2, "carbs": 13.5, "fiber": 1.2, "sodium": 3, "category": "fruit"},
    {"id": 258, "name": "香蕉", "name_en": "Banana", "pinyin": "xiang jiao", "calories": 93, "protein": 1.4, "fat": 0.2, "carbs": 22.0, "fiber": 1.2, "sodium": 1, "category": "fruit"},
    {"id": 259, "name": "橙子", "name_en": "Orange", "pinyin": "cheng zi", "calories": 48, "protein": 0.8, "fat": 0.2, "carbs": 11.1, "fiber": 0.6, "sodium": 4, "category": "fruit"},
    {"id": 260, "name": "葡萄", "name_en": "Grape", "pinyin": "pu tao", "calories": 44, "protein": 0.5, "fat": 0.2, "carbs": 10.3, "fiber": 0.4, "sodium": 2, "category": "fruit"},
    {"id": 261, "name": "西瓜", "name_en": "Watermelon", "pinyin": "xi gua", "calories": 26, "protein": 0.6, "fat": 0.1, "carbs": 5.8, "fiber": 0.3, "sodium": 3, "category": "fruit"},
    {"id": 262, "name": "草莓", "name_en": "Strawberry", "pinyin": "cao mei", "calories": 32, "protein": 1.0, "fat": 0.2, "carbs": 7.1, "fiber": 1.1, "sodium": 2, "category": "fruit"},
    {"id": 263, "name": "蓝莓", "name_en": "Blueberry", "pinyin": "lan mei", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "fiber": 2.4, "sodium": 4, "category": "fruit"},
    {"id": 264, "name": "猕猴桃", "name_en": "Kiwi", "pinyin": "mi hou tao", "calories": 61, "protein": 0.8, "fat": 0.6, "carbs": 14.5, "fiber": 2.6, "sodium": 5, "category": "fruit"},
    {"id": 265, "name": "芒果", "name_en": "Mango", "pinyin": "mang guo", "calories": 32, "protein": 0.6, "fat": 0.2, "carbs": 7.0, "fiber": 1.3, "sodium": 3, "category": "fruit"},
    {"id": 266, "name": "菠萝", "name_en": "Pineapple", "pinyin": "bo luo", "calories": 44, "protein": 0.5, "fat": 0.1, "carbs": 10.8, "fiber": 1.3, "sodium": 2, "category": "fruit"},
    {"id": 267, "name": "梨", "name_en": "Pear", "pinyin": "li", "calories": 45, "protein": 0.4, "fat": 0.2, "carbs": 11.2, "fiber": 2.6, "sodium": 3, "category": "fruit"},
    {"id": 268, "name": "桃子", "name_en": "Peach", "pinyin": "tao zi", "calories": 48, "protein": 0.9, "fat": 0.1, "carbs": 12.2, "fiber": 1.3, "sodium": 1, "category": "fruit"},
    {"id": 269, "name": "柠檬", "name_en": "Lemon", "pinyin": "ning meng", "calories": 35, "protein": 1.1, "fat": 1.2, "carbs": 6.2, "fiber": 1.3, "sodium": 1, "category": "fruit"},
    {"id": 270, "name": "樱桃", "name_en": "Cherry", "pinyin": "ying tao", "calories": 46, "protein": 1.1, "fat": 0.2, "carbs": 10.2, "fiber": 0.3, "sodium": 8, "category": "fruit"},
    {"id": 271, "name": "柚子", "name_en": "Pomelo", "pinyin": "you zi", "calories": 41, "protein": 0.8, "fat": 0.2, "carbs": 9.5, "fiber": 0.4, "sodium": 3, "category": "fruit"},
    {"id": 272, "name": "橘子", "name_en": "Tangerine", "pinyin": "ju zi", "calories": 51, "protein": 0.7, "fat": 0.2, "carbs": 11.9, "fiber": 0.4, "sodium": 1, "category": "fruit"},
    {"id": 273, "name": "芦柑", "name_en": "Mandarin", "pinyin": "lu gan", "calories": 43, "protein": 0.6, "fat": 0.2, "carbs": 10.3, "fiber": 0.6, "sodium": 1, "category": "fruit"},
    {"id": 274, "name": "金桔", "name_en": "Kumquat", "pinyin": "jin ju", "calories": 55, "protein": 1.0, "fat": 0.2, "carbs": 13.7, "fiber": 1.4, "sodium": 3, "category": "fruit"},
    {"id": 275, "name": "哈密瓜", "name_en": "Hami Melon", "pinyin": "ha mi gua", "calories": 34, "protein": 0.5, "fat": 0.1, "carbs": 7.9, "fiber": 0.2, "sodium": 26, "category": "fruit"},
    {"id": 276, "name": "甜瓜", "name_en": "Cantaloupe", "pinyin": "tian gua", "calories": 26, "protein": 0.4, "fat": 0.1, "carbs": 6.2, "fiber": 0.4, "sodium": 8, "category": "fruit"},
    {"id": 277, "name": "木瓜", "name_en": "Papaya", "pinyin": "mu gua", "calories": 27, "protein": 0.4, "fat": 0.1, "carbs": 7.0, "fiber": 0.8, "sodium": 5, "category": "fruit"},
    {"id": 278, "name": "火龙果", "name_en": "Dragon Fruit", "pinyin": "huo long guo", "calories": 51, "protein": 1.1, "fat": 0.2, "carbs": 13.3, "fiber": 2.0, "sodium": 3, "category": "fruit"},
    {"id": 279, "name": "榴莲", "name_en": "Durian", "pinyin": "liu lian", "calories": 147, "protein": 2.6, "fat": 3.3, "carbs": 28.3, "fiber": 3.8, "sodium": 2, "category": "fruit"},
    {"id": 280, "name": "山竹", "name_en": "Mangosteen", "pinyin": "shan zhu", "calories": 69, "protein": 0.4, "fat": 0.6, "carbs": 18.0, "fiber": 1.8, "sodium": 3, "category": "fruit"},
    {"id": 281, "name": "荔枝", "name_en": "Lychee", "pinyin": "li zhi", "calories": 70, "protein": 0.9, "fat": 0.2, "carbs": 16.6, "fiber": 0.5, "sodium": 2, "category": "fruit"},
    {"id": 282, "name": "龙眼", "name_en": "Longan", "pinyin": "long yan", "calories": 71, "protein": 1.2, "fat": 0.1, "carbs": 16.6, "fiber": 0.4, "sodium": 1, "category": "fruit"},
    {"id": 283, "name": "杨梅", "name_en": "Waxberry", "pinyin": "yang mei", "calories": 28, "protein": 0.8, "fat": 0.2, "carbs": 6.7, "fiber": 1.0, "sodium": 1, "category": "fruit"},
    {"id": 284, "name": "枇杷", "name_en": "Loquat", "pinyin": "pi pa", "calories": 39, "protein": 0.8, "fat": 0.2, "carbs": 9.3, "fiber": 0.8, "sodium": 1, "category": "fruit"},
    {"id": 285, "name": "杏子", "name_en": "Apricot", "pinyin": "xing zi", "calories": 36, "protein": 0.9, "fat": 0.1, "carbs": 9.1, "fiber": 1.3, "sodium": 2, "category": "fruit"},
    {"id": 286, "name": "李子", "name_en": "Plum", "pinyin": "li zi", "calories": 36, "protein": 0.7, "fat": 0.2, "carbs": 8.7, "fiber": 0.9, "sodium": 3, "category": "fruit"},
    {"id": 287, "name": "柿子", "name_en": "Persimmon", "pinyin": "shi zi", "calories": 74, "protein": 0.4, "fat": 0.1, "carbs": 18.5, "fiber": 1.4, "sodium": 1, "category": "fruit"},
    {"id": 288, "name": "山楂", "name_en": "Hawthorn", "pinyin": "shan zha", "calories": 95, "protein": 0.5, "fat": 0.6, "carbs": 25.1, "fiber": 3.1, "sodium": 1, "category": "fruit"},
    {"id": 289, "name": "红枣", "name_en": "Red Date", "pinyin": "hong zao", "calories": 264, "protein": 3.2, "fat": 0.5, "carbs": 67.8, "fiber": 6.2, "sodium": 6, "category": "fruit"},
    {"id": 290, "name": "冬枣", "name_en": "Winter Jujube", "pinyin": "dong zao", "calories": 105, "protein": 1.8, "fat": 0.2, "carbs": 27.8, "fiber": 3.8, "sodium": 3, "category": "fruit"},
    {"id": 291, "name": "椰子", "name_en": "Coconut", "pinyin": "ye zi", "calories": 231, "protein": 4.0, "fat": 12.1, "carbs": 31.3, "fiber": 4.7, "sodium": 55, "category": "fruit"},
    {"id": 292, "name": "石榴", "name_en": "Pomegranate", "pinyin": "shi liu", "calories": 63, "protein": 1.3, "fat": 0.2, "carbs": 18.7, "fiber": 4.8, "sodium": 3, "category": "fruit"},
    {"id": 293, "name": "无花果", "name_en": "Fig", "pinyin": "wu hua guo", "calories": 59, "protein": 1.5, "fat": 0.1, "carbs": 16.0, "fiber": 3.0, "sodium": 1, "category": "fruit"},
    {"id": 294, "name": "桑葚", "name_en": "Mulberry", "pinyin": "sang shen", "calories": 49, "protein": 1.6, "fat": 0.4, "carbs": 13.8, "fiber": 4.1, "sodium": 2, "category": "fruit"},
    {"id": 295, "name": "蓝莓干", "name_en": "Dried Blueberry", "pinyin": "lan mei gan", "calories": 338, "protein": 2.4, "fat": 0.8, "carbs": 82.5, "fiber": 7.5, "sodium": 8, "category": "fruit"},
    {"id": 296, "name": "葡萄干", "name_en": "Raisin", "pinyin": "pu tao gan", "calories": 299, "protein": 2.5, "fat": 0.4, "carbs": 83.4, "fiber": 1.6, "sodium": 19, "category": "fruit"},
    {"id": 297, "name": "杏干", "name_en": "Dried Apricot", "pinyin": "xing gan", "calories": 330, "protein": 2.8, "fat": 0.5, "carbs": 83.2, "fiber": 4.8, "sodium": 40, "category": "fruit"},
    {"id": 298, "name": "蔓越莓干", "name_en": "Dried Cranberry", "pinyin": "man yue mei gan", "calories": 325, "protein": 0.5, "fat": 0.2, "carbs": 84.0, "fiber": 5.3, "sodium": 15, "category": "fruit"},
    {"id": 299, "name": "杏仁", "name_en": "Almond", "pinyin": "xing ren", "calories": 579, "protein": 22.5, "fat": 50.6, "carbs": 19.9, "fiber": 12.5, "sodium": 1, "category": "nut"},
    {"id": 300, "name": "核桃", "name_en": "Walnut", "pinyin": "he tao", "calories": 646, "protein": 14.9, "fat": 58.8, "carbs": 19.1, "fiber": 9.7, "sodium": 1, "category": "nut"},
    {"id": 301, "name": "花生", "name_en": "Peanut", "pinyin": "hua sheng", "calories": 567, "protein": 24.8, "fat": 44.3, "carbs": 21.7, "fiber": 8.5, "sodium": 4, "category": "nut"},
    {"id": 302, "name": "腰果", "name_en": "Cashew", "pinyin": "yao guo", "calories": 552, "protein": 17.3, "fat": 36.7, "carbs": 41.6, "fiber": 3.6, "sodium": 25, "category": "nut"},
    {"id": 303, "name": "坚果混合", "name_en": "Mixed Nuts", "pinyin": "jian guo hun he", "calories": 607, "protein": 20.3, "fat": 52.8, "carbs": 21.5, "fiber": 8.2, "sodium": 5, "category": "nut"},
    {"id": 304, "name": "芝麻", "name_en": "Sesame", "pinyin": "zhi ma", "calories": 531, "protein": 19.1, "fat": 46.1, "carbs": 24.0, "fiber": 14.0, "sodium": 8, "category": "nut"},
    {"id": 305, "name": "开心果", "name_en": "Pistachio", "pinyin": "kai xin guo", "calories": 557, "protein": 21.0, "fat": 45.4, "carbs": 27.6, "fiber": 8.2, "sodium": 380, "category": "nut"},
    {"id": 306, "name": "夏威夷果", "name_en": "Macadamia", "pinyin": "xia wei yi guo", "calories": 718, "protein": 7.9, "fat": 75.8, "carbs": 9.6, "fiber": 8.6, "sodium": 3, "category": "nut"},
    {"id": 307, "name": "碧根果", "name_en": "Pecan", "pinyin": "bi gen guo", "calories": 670, "protein": 9.2, "fat": 71.2, "carbs": 14.5, "fiber": 9.6, "sodium": 1, "category": "nut"},
    {"id": 308, "name": "松子", "name_en": "Pine Nut", "pinyin": "song zi", "calories": 644, "protein": 13.4, "fat": 62.6, "carbs": 15.2, "fiber": 12.4, "sodium": 3, "category": "nut"},
    {"id": 309, "name": "榛子", "name_en": "Hazelnut", "pinyin": "zhen zi", "calories": 617, "protein": 20.0, "fat": 54.0, "carbs": 22.4, "fiber": 9.7, "sodium": 3, "category": "nut"},
    {"id": 310, "name": "葵花籽", "name_en": "Sunflower Seed", "pinyin": "kui hua zi", "calories": 605, "protein": 23.9, "fat": 49.9, "carbs": 16.7, "fiber": 6.1, "sodium": 2, "category": "nut"},
    {"id": 311, "name": "南瓜子", "name_en": "Pumpkin Seed", "pinyin": "nan gua zi", "calories": 566, "protein": 36.0, "fat": 46.1, "carbs": 7.9, "fiber": 4.1, "sodium": 16, "category": "nut"},
    {"id": 312, "name": "西瓜子", "name_en": "Watermelon Seed", "pinyin": "xi gua zi", "calories": 532, "protein": 32.7, "fat": 44.8, "carbs": 14.2, "fiber": 4.5, "sodium": 187, "category": "nut"},
    {"id": 313, "name": "板栗", "name_en": "Chestnut", "pinyin": "ban li", "calories": 185, "protein": 4.2, "fat": 0.7, "carbs": 42.2, "fiber": 2.7, "sodium": 8, "category": "nut"},
    {"id": 314, "name": "莲子", "name_en": "Lotus Seed", "pinyin": "lian zi", "calories": 350, "protein": 17.2, "fat": 2.0, "carbs": 67.2, "fiber": 3.0, "sodium": 5, "category": "nut"},
    {"id": 315, "name": "白果", "name_en": "Ginkgo", "pinyin": "bai guo", "calories": 355, "protein": 13.2, "fat": 1.3, "carbs": 72.6, "fiber": 0.2, "sodium": 17, "category": "nut"},
    {"id": 316, "name": "可乐", "name_en": "Coca-Cola", "pinyin": "ke le", "calories": 43, "protein": 0, "fat": 0, "carbs": 10.6, "fiber": 0, "sodium": 8, "category": "beverage"},
    {"id": 317, "name": "橙汁", "name_en": "Orange Juice", "pinyin": "cheng zhi", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4, "fiber": 0.2, "sodium": 2, "category": "beverage"},
    {"id": 318, "name": "咖啡", "name_en": "Coffee", "pinyin": "ka fei", "calories": 2, "protein": 0.1, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 319, "name": "绿茶", "name_en": "Green Tea", "pinyin": "lv cha", "calories": 1, "protein": 0, "fat": 0, "carbs": 0.2, "fiber": 0, "sodium": 1, "category": "beverage"},
    {"id": 320, "name": "奶茶", "name_en": "Milk Tea", "pinyin": "nai cha", "calories": 95, "protein": 1.5, "fat": 3.5, "carbs": 14.5, "fiber": 0, "sodium": 45, "category": "beverage"},
    {"id": 321, "name": "啤酒", "name_en": "Beer", "pinyin": "pi jiu", "calories": 43, "protein": 0.4, "fat": 0, "carbs": 3.6, "fiber": 0, "sodium": 4, "category": "beverage"},
    {"id": 322, "name": "椰子水", "name_en": "Coconut Water", "pinyin": "ye zi shui", "calories": 19, "protein": 0.5, "fat": 0.1, "carbs": 3.8, "fiber": 0.1, "sodium": 18, "category": "beverage"},
    {"id": 323, "name": "气泡水", "name_en": "Sparkling Water", "pinyin": "qi pao shui", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 5, "category": "beverage"},
    {"id": 324, "name": "苏打水", "name_en": "Soda Water", "pinyin": "su da shui", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 12, "category": "beverage"},
    {"id": 325, "name": "矿泉水", "name_en": "Mineral Water", "pinyin": "kuang quan shui", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 8, "category": "beverage"},
    {"id": 326, "name": "纯净水", "name_en": "Purified Water", "pinyin": "chun jing shui", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 327, "name": "红茶", "name_en": "Black Tea", "pinyin": "hong cha", "calories": 2, "protein": 0.1, "fat": 0, "carbs": 0.4, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 328, "name": "乌龙茶", "name_en": "Oolong Tea", "pinyin": "wu long cha", "calories": 2, "protein": 0.1, "fat": 0, "carbs": 0.3, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 329, "name": "普洱茶", "name_en": "Pu-erh Tea", "pinyin": "pu er cha", "calories": 3, "protein": 0.1, "fat": 0, "carbs": 0.5, "fiber": 0, "sodium": 3, "category": "beverage"},
    {"id": 330, "name": "茉莉花茶", "name_en": "Jasmine Tea", "pinyin": "mo li hua cha", "calories": 2, "protein": 0.1, "fat": 0, "carbs": 0.3, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 331, "name": "柠檬水", "name_en": "Lemon Water", "pinyin": "ning meng shui", "calories": 6, "protein": 0.1, "fat": 0, "carbs": 1.5, "fiber": 0.1, "sodium": 2, "category": "beverage"},
    {"id": 332, "name": "蜂蜜水", "name_en": "Honey Water", "pinyin": "feng mi shui", "calories": 55, "protein": 0.1, "fat": 0, "carbs": 14.0, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 333, "name": "果汁", "name_en": "Fruit Juice", "pinyin": "guo zhi", "calories": 50, "protein": 0.5, "fat": 0.1, "carbs": 12.0, "fiber": 0.2, "sodium": 5, "category": "beverage"},
    {"id": 334, "name": "苹果汁", "name_en": "Apple Juice", "pinyin": "ping guo zhi", "calories": 46, "protein": 0.1, "fat": 0.1, "carbs": 11.7, "fiber": 0.1, "sodium": 4, "category": "beverage"},
    {"id": 335, "name": "葡萄汁", "name_en": "Grape Juice", "pinyin": "pu tao zhi", "calories": 55, "protein": 0.3, "fat": 0.1, "carbs": 14.0, "fiber": 0.2, "sodium": 3, "category": "beverage"},
    {"id": 336, "name": "桃汁", "name_en": "Peach Juice", "pinyin": "tao zhi", "calories": 52, "protein": 0.3, "fat": 0.1, "carbs": 13.0, "fiber": 0.1, "sodium": 3, "category": "beverage"},
    {"id": 337, "name": "运动饮料", "name_en": "Sports Drink", "pinyin": "yun dong yin liao", "calories": 26, "protein": 0, "fat": 0, "carbs": 6.5, "fiber": 0, "sodium": 55, "category": "beverage"},
    {"id": 338, "name": "功能饮料", "name_en": "Energy Drink", "pinyin": "gong neng yin liao", "calories": 45, "protein": 0, "fat": 0, "carbs": 11.5, "fiber": 0, "sodium": 45, "category": "beverage"},
    {"id": 339, "name": "白酒", "name_en": "Chinese Liquor", "pinyin": "bai jiu", "calories": 298, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 1, "category": "beverage"},
    {"id": 340, "name": "红酒", "name_en": "Red Wine", "pinyin": "hong jiu", "calories": 85, "protein": 0.1, "fat": 0, "carbs": 2.6, "fiber": 0, "sodium": 4, "category": "beverage"},
    {"id": 341, "name": "黄酒", "name_en": "Rice Wine", "pinyin": "huang jiu", "calories": 126, "protein": 1.5, "fat": 0.1, "carbs": 4.7, "fiber": 0, "sodium": 8, "category": "beverage"},
    {"id": 342, "name": "米酒", "name_en": "Sweet Rice Wine", "pinyin": "mi jiu", "calories": 70, "protein": 1.5, "fat": 0.1, "carbs": 15.5, "fiber": 0, "sodium": 3, "category": "beverage"},
    "protein": 55,
    "fat": 65,
    "carbs": 275,
    "fiber": 28,
    "sodium": 2000,
}