FOODS = [
    {"id": 1, "name": "白米饭", "name_en": "White Rice", "pinyin": "bai mi fan", "calories": 116, "protein": 2.6, "fat": 0.3, "carbs": 25.6, "fiber": 0.3, "sodium": 2, "category": "grain"},
    {"id": 2, "name": "糙米饭", "name_en": "Brown Rice", "pinyin": "cao mi fan", "calories": 123, "protein": 2.6, "fat": 0.9, "carbs": 25.9, "fiber": 1.8, "sodium": 3, "category": "grain"},
    {"id": 3, "name": "馒头", "name_en": "Steamed Bun", "pinyin": "man tou", "calories": 221, "protein": 7.0, "fat": 1.1, "carbs": 47.0, "fiber": 1.3, "sodium": 165, "category": "grain"},
    {"id": 4, "name": "全麦面包", "name_en": "Whole Wheat Bread", "pinyin": "quan mai mian bao", "calories": 250, "protein": 10.0, "fat": 3.5, "carbs": 49.0, "fiber": 6.0, "sodium": 400, "category": "grain"},
    {"id": 5, "name": "面条", "name_en": "Noodles", "pinyin": "mian tiao", "calories": 284, "protein": 8.3, "fat": 1.6, "carbs": 56.8, "fiber": 1.5, "sodium": 150, "category": "grain"},
    {"id": 6, "name": "燕麦片", "name_en": "Oatmeal", "pinyin": "yan mai pian", "calories": 367, "protein": 15.0, "fat": 6.7, "carbs": 61.6, "fiber": 5.3, "sodium": 12, "category": "grain"},
    {"id": 7, "name": "玉米", "name_en": "Corn", "pinyin": "yu mi", "calories": 106, "protein": 4.0, "fat": 1.2, "carbs": 22.8, "fiber": 2.9, "sodium": 2, "category": "grain"},
    {"id": 8, "name": "红薯", "name_en": "Sweet Potato", "pinyin": "hong shu", "calories": 86, "protein": 1.6, "fat": 0.1, "carbs": 20.1, "fiber": 3.0, "sodium": 55, "category": "grain"},
    {"id": 9, "name": "土豆", "name_en": "Potato", "pinyin": "tu dou", "calories": 77, "protein": 2.0, "fat": 0.1, "carbs": 17.2, "fiber": 0.7, "sodium": 27, "category": "grain"},
    {"id": 10, "name": "小米粥", "name_en": "Millet Porridge", "pinyin": "xiao mi zhou", "calories": 46, "protein": 1.4, "fat": 0.7, "carbs": 8.4, "fiber": 0.4, "sodium": 3, "category": "grain"},
    {"id": 11, "name": "鸡胸肉", "name_en": "Chicken Breast", "pinyin": "ji xiong rou", "calories": 133, "protein": 19.4, "fat": 5.0, "carbs": 2.5, "fiber": 0, "sodium": 69, "category": "meat"},
    {"id": 12, "name": "鸡腿肉", "name_en": "Chicken Thigh", "pinyin": "ji tui rou", "calories": 181, "protein": 16.0, "fat": 13.0, "carbs": 0, "fiber": 0, "sodium": 72, "category": "meat"},
    {"id": 13, "name": "猪瘦肉", "name_en": "Lean Pork", "pinyin": "zhu shou rou", "calories": 143, "protein": 20.3, "fat": 6.2, "carbs": 1.5, "fiber": 0, "sodium": 57, "category": "meat"},
    {"id": 14, "name": "牛肉", "name_en": "Beef", "pinyin": "niu rou", "calories": 125, "protein": 19.9, "fat": 4.2, "carbs": 2.0, "fiber": 0, "sodium": 84, "category": "meat"},
    {"id": 15, "name": "羊肉", "name_en": "Lamb", "pinyin": "yang rou", "calories": 203, "protein": 19.0, "fat": 14.1, "carbs": 0, "fiber": 0, "sodium": 78, "category": "meat"},
    {"id": 16, "name": "三文鱼", "name_en": "Salmon", "pinyin": "san wen yu", "calories": 139, "protein": 17.2, "fat": 7.8, "carbs": 0, "fiber": 0, "sodium": 59, "category": "meat"},
    {"id": 17, "name": "虾", "name_en": "Shrimp", "pinyin": "xia", "calories": 93, "protein": 18.6, "fat": 0.8, "carbs": 2.8, "fiber": 0, "sodium": 165, "category": "meat"},
    {"id": 18, "name": "鸡蛋", "name_en": "Egg", "pinyin": "ji dan", "calories": 144, "protein": 13.3, "fat": 8.8, "carbs": 2.8, "fiber": 0, "sodium": 132, "category": "egg"},
    {"id": 19, "name": "鸭蛋", "name_en": "Duck Egg", "pinyin": "ya dan", "calories": 180, "protein": 12.6, "fat": 13.0, "carbs": 3.1, "fiber": 0, "sodium": 106, "category": "egg"},
    {"id": 20, "name": "咸鸭蛋", "name_en": "Salted Duck Egg", "pinyin": "xian ya dan", "calories": 190, "protein": 12.7, "fat": 12.7, "carbs": 6.3, "fiber": 0, "sodium": 2706, "category": "egg"},
    {"id": 21, "name": "牛奶", "name_en": "Milk", "pinyin": "niu nai", "calories": 54, "protein": 3.0, "fat": 3.2, "carbs": 3.4, "fiber": 0, "sodium": 37, "category": "dairy"},
    {"id": 22, "name": "酸奶", "name_en": "Yogurt", "pinyin": "suan nai", "calories": 72, "protein": 2.5, "fat": 2.7, "carbs": 9.3, "fiber": 0, "sodium": 39, "category": "dairy"},
    {"id": 23, "name": "奶酪", "name_en": "Cheese", "pinyin": "nai lao", "calories": 328, "protein": 25.7, "fat": 23.5, "carbs": 3.5, "fiber": 0, "sodium": 584, "category": "dairy"},
    {"id": 24, "name": "豆浆", "name_en": "Soy Milk", "pinyin": "dou jiang", "calories": 31, "protein": 1.8, "fat": 0.7, "carbs": 4.0, "fiber": 0.3, "sodium": 10, "category": "bean"},
    {"id": 25, "name": "豆腐", "name_en": "Tofu", "pinyin": "dou fu", "calories": 81, "protein": 8.1, "fat": 3.7, "carbs": 4.2, "fiber": 0.4, "sodium": 7.2, "category": "bean"},
    {"id": 26, "name": "黄豆", "name_en": "Soybean", "pinyin": "huang dou", "calories": 359, "protein": 35.1, "fat": 16.0, "carbs": 34.2, "fiber": 15.5, "sodium": 2, "category": "bean"},
    {"id": 27, "name": "红豆", "name_en": "Red Bean", "pinyin": "hong dou", "calories": 324, "protein": 20.2, "fat": 0.6, "carbs": 63.4, "fiber": 7.7, "sodium": 2, "category": "bean"},
    {"id": 28, "name": "绿豆", "name_en": "Mung Bean", "pinyin": "lv dou", "calories": 319, "protein": 21.6, "fat": 0.8, "carbs": 62.0, "fiber": 6.4, "sodium": 3, "category": "bean"},
    {"id": 29, "name": "白菜", "name_en": "Chinese Cabbage", "pinyin": "bai cai", "calories": 17, "protein": 1.5, "fat": 0.1, "carbs": 3.2, "fiber": 0.8, "sodium": 89, "category": "vegetable"},
    {"id": 30, "name": "菠菜", "name_en": "Spinach", "pinyin": "bo cai", "calories": 28, "protein": 2.6, "fat": 0.3, "carbs": 4.5, "fiber": 1.7, "sodium": 209, "category": "vegetable"},
    {"id": 31, "name": "西兰花", "name_en": "Broccoli", "pinyin": "xi lan hua", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 6.6, "fiber": 1.7, "sodium": 33, "category": "vegetable"},
    {"id": 32, "name": "胡萝卜", "name_en": "Carrot", "pinyin": "hu luo bo", "calories": 39, "protein": 1.0, "fat": 0.2, "carbs": 8.8, "fiber": 1.6, "sodium": 25, "category": "vegetable"},
    {"id": 33, "name": "西红柿", "name_en": "Tomato", "pinyin": "xi hong shi", "calories": 20, "protein": 0.9, "fat": 0.2, "carbs": 4.0, "fiber": 0.5, "sodium": 5, "category": "vegetable"},
    {"id": 34, "name": "黄瓜", "name_en": "Cucumber", "pinyin": "huang gua", "calories": 16, "protein": 0.8, "fat": 0.2, "carbs": 2.9, "fiber": 0.5, "sodium": 2, "category": "vegetable"},
    {"id": 35, "name": "茄子", "name_en": "Eggplant", "pinyin": "qie zi", "calories": 23, "protein": 1.1, "fat": 0.2, "carbs": 4.9, "fiber": 1.3, "sodium": 5, "category": "vegetable"},
    {"id": 36, "name": "青椒", "name_en": "Green Pepper", "pinyin": "qing jiao", "calories": 22, "protein": 1.0, "fat": 0.2, "carbs": 4.6, "fiber": 0.8, "sodium": 2, "category": "vegetable"},
    {"id": 37, "name": "洋葱", "name_en": "Onion", "pinyin": "yang cong", "calories": 40, "protein": 1.1, "fat": 0.2, "carbs": 9.0, "fiber": 0.9, "sodium": 4, "category": "vegetable"},
    {"id": 38, "name": "生菜", "name_en": "Lettuce", "pinyin": "sheng cai", "calories": 15, "protein": 1.4, "fat": 0.2, "carbs": 2.1, "fiber": 0.6, "sodium": 28, "category": "vegetable"},
    {"id": 39, "name": "芹菜", "name_en": "Celery", "pinyin": "qin cai", "calories": 16, "protein": 0.7, "fat": 0.1, "carbs": 3.9, "fiber": 1.3, "sodium": 75, "category": "vegetable"},
    {"id": 40, "name": "韭菜", "name_en": "Leek", "pinyin": "jiu cai", "calories": 29, "protein": 2.4, "fat": 0.4, "carbs": 4.6, "fiber": 1.4, "sodium": 27, "category": "vegetable"},
    {"id": 41, "name": "蘑菇", "name_en": "Mushroom", "pinyin": "mo gu", "calories": 27, "protein": 2.7, "fat": 0.1, "carbs": 4.1, "fiber": 2.1, "sodium": 11, "category": "vegetable"},
    {"id": 42, "name": "海带", "name_en": "Kelp", "pinyin": "hai dai", "calories": 13, "protein": 1.1, "fat": 0.1, "carbs": 2.1, "fiber": 0.5, "sodium": 251, "category": "vegetable"},
    {"id": 43, "name": "苹果", "name_en": "Apple", "pinyin": "ping guo", "calories": 54, "protein": 0.2, "fat": 0.2, "carbs": 13.5, "fiber": 1.2, "sodium": 3, "category": "fruit"},
    {"id": 44, "name": "香蕉", "name_en": "Banana", "pinyin": "xiang jiao", "calories": 93, "protein": 1.4, "fat": 0.2, "carbs": 22.0, "fiber": 1.2, "sodium": 1, "category": "fruit"},
    {"id": 45, "name": "橙子", "name_en": "Orange", "pinyin": "cheng zi", "calories": 48, "protein": 0.8, "fat": 0.2, "carbs": 11.1, "fiber": 0.6, "sodium": 4, "category": "fruit"},
    {"id": 46, "name": "葡萄", "name_en": "Grape", "pinyin": "pu tao", "calories": 44, "protein": 0.5, "fat": 0.2, "carbs": 10.3, "fiber": 0.4, "sodium": 2, "category": "fruit"},
    {"id": 47, "name": "西瓜", "name_en": "Watermelon", "pinyin": "xi gua", "calories": 26, "protein": 0.6, "fat": 0.1, "carbs": 5.8, "fiber": 0.3, "sodium": 3, "category": "fruit"},
    {"id": 48, "name": "草莓", "name_en": "Strawberry", "pinyin": "cao mei", "calories": 32, "protein": 1.0, "fat": 0.2, "carbs": 7.1, "fiber": 1.1, "sodium": 2, "category": "fruit"},
    {"id": 49, "name": "蓝莓", "name_en": "Blueberry", "pinyin": "lan mei", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.5, "fiber": 2.4, "sodium": 4, "category": "fruit"},
    {"id": 50, "name": "猕猴桃", "name_en": "Kiwi", "pinyin": "mi hou tao", "calories": 61, "protein": 0.8, "fat": 0.6, "carbs": 14.5, "fiber": 2.6, "sodium": 5, "category": "fruit"},
    {"id": 51, "name": "芒果", "name_en": "Mango", "pinyin": "mang guo", "calories": 32, "protein": 0.6, "fat": 0.2, "carbs": 7.0, "fiber": 1.3, "sodium": 3, "category": "fruit"},
    {"id": 52, "name": "菠萝", "name_en": "Pineapple", "pinyin": "bo luo", "calories": 44, "protein": 0.5, "fat": 0.1, "carbs": 10.8, "fiber": 1.3, "sodium": 2, "category": "fruit"},
    {"id": 53, "name": "梨", "name_en": "Pear", "pinyin": "li", "calories": 45, "protein": 0.4, "fat": 0.2, "carbs": 11.2, "fiber": 2.6, "sodium": 3, "category": "fruit"},
    {"id": 54, "name": "桃子", "name_en": "Peach", "pinyin": "tao zi", "calories": 48, "protein": 0.9, "fat": 0.1, "carbs": 12.2, "fiber": 1.3, "sodium": 1, "category": "fruit"},
    {"id": 55, "name": "杏仁", "name_en": "Almond", "pinyin": "xing ren", "calories": 579, "protein": 22.5, "fat": 50.6, "carbs": 19.9, "fiber": 12.5, "sodium": 1, "category": "nut"},
    {"id": 56, "name": "核桃", "name_en": "Walnut", "pinyin": "he tao", "calories": 646, "protein": 14.9, "fat": 58.8, "carbs": 19.1, "fiber": 9.7, "sodium": 1, "category": "nut"},
    {"id": 57, "name": "花生", "name_en": "Peanut", "pinyin": "hua sheng", "calories": 567, "protein": 24.8, "fat": 44.3, "carbs": 21.7, "fiber": 8.5, "sodium": 4, "category": "nut"},
    {"id": 58, "name": "腰果", "name_en": "Cashew", "pinyin": "yao guo", "calories": 552, "protein": 17.3, "fat": 36.7, "carbs": 41.6, "fiber": 3.6, "sodium": 25, "category": "nut"},
    {"id": 59, "name": "可乐", "name_en": "Coca-Cola", "pinyin": "ke le", "calories": 43, "protein": 0, "fat": 0, "carbs": 10.6, "fiber": 0, "sodium": 8, "category": "beverage"},
    {"id": 60, "name": "橙汁", "name_en": "Orange Juice", "pinyin": "cheng zhi", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.4, "fiber": 0.2, "sodium": 2, "category": "beverage"},
    {"id": 61, "name": "咖啡", "name_en": "Coffee", "pinyin": "ka fei", "calories": 2, "protein": 0.1, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 2, "category": "beverage"},
    {"id": 62, "name": "绿茶", "name_en": "Green Tea", "pinyin": "lv cha", "calories": 1, "protein": 0, "fat": 0, "carbs": 0.2, "fiber": 0, "sodium": 1, "category": "beverage"},
    {"id": 63, "name": "奶茶", "name_en": "Milk Tea", "pinyin": "nai cha", "calories": 95, "protein": 1.5, "fat": 3.5, "carbs": 14.5, "fiber": 0, "sodium": 45, "category": "beverage"},
    {"id": 64, "name": "啤酒", "name_en": "Beer", "pinyin": "pi jiu", "calories": 43, "protein": 0.4, "fat": 0, "carbs": 3.6, "fiber": 0, "sodium": 4, "category": "beverage"},
    {"id": 65, "name": "薯片", "name_en": "Potato Chips", "pinyin": "shu pian", "calories": 547, "protein": 6.3, "fat": 34.7, "carbs": 52.9, "fiber": 4.2, "sodium": 450, "category": "snack"},
    {"id": 66, "name": "巧克力", "name_en": "Chocolate", "pinyin": "qiao ke li", "calories": 546, "protein": 4.3, "fat": 30.7, "carbs": 63.1, "fiber": 4.3, "sodium": 22, "category": "snack"},
    {"id": 67, "name": "饼干", "name_en": "Biscuit", "pinyin": "bing gan", "calories": 435, "protein": 9.0, "fat": 12.7, "carbs": 71.7, "fiber": 1.1, "sodium": 200, "category": "snack"},
    {"id": 68, "name": "蛋糕", "name_en": "Cake", "pinyin": "dan gao", "calories": 347, "protein": 7.2, "fat": 5.1, "carbs": 67.8, "fiber": 0.6, "sodium": 65, "category": "snack"},
    {"id": 69, "name": "冰淇淋", "name_en": "Ice Cream", "pinyin": "bing qi lin", "calories": 207, "protein": 3.5, "fat": 8.6, "carbs": 17.3, "fiber": 0, "sodium": 65, "category": "snack"},
    {"id": 70, "name": "火腿肠", "name_en": "Ham Sausage", "pinyin": "huo tui chang", "calories": 212, "protein": 11.7, "fat": 15.6, "carbs": 6.3, "fiber": 0, "sodium": 598, "category": "snack"},
    {"id": 71, "name": "方便面", "name_en": "Instant Noodles", "pinyin": "fang bian mian", "calories": 473, "protein": 9.5, "fat": 21.1, "carbs": 61.6, "fiber": 1.5, "sodium": 1144, "category": "snack"},
    {"id": 72, "name": "面包", "name_en": "Bread", "pinyin": "mian bao", "calories": 312, "protein": 8.3, "fat": 5.1, "carbs": 58.6, "fiber": 1.5, "sodium": 250, "category": "grain"},
    {"id": 73, "name": "饺子", "name_en": "Dumpling", "pinyin": "jiao zi", "calories": 253, "protein": 8.3, "fat": 10.5, "carbs": 33.3, "fiber": 1.8, "sodium": 280, "category": "grain"},
    {"id": 74, "name": "包子", "name_en": "Steamed Stuffed Bun", "pinyin": "bao zi", "calories": 227, "protein": 7.9, "fat": 3.4, "carbs": 41.8, "fiber": 1.6, "sodium": 200, "category": "grain"},
    {"id": 75, "name": "油条", "name_en": "Deep-fried Dough Stick", "pinyin": "you tiao", "calories": 388, "protein": 6.9, "fat": 17.6, "carbs": 51.6, "fiber": 0.7, "sodium": 250, "category": "grain"},
    {"id": 76, "name": "煎饼", "name_en": "Pancake", "pinyin": "jian bing", "calories": 354, "protein": 7.6, "fat": 11.3, "carbs": 53.7, "fiber": 1.2, "sodium": 150, "category": "grain"},
    {"id": 77, "name": "炒饭", "name_en": "Fried Rice", "pinyin": "chao fan", "calories": 173, "protein": 5.8, "fat": 3.2, "carbs": 29.3, "fiber": 0.8, "sodium": 200, "category": "grain"},
    {"id": 78, "name": "牛肉面", "name_en": "Beef Noodles", "pinyin": "niu rou mian", "calories": 180, "protein": 8.5, "fat": 4.2, "carbs": 25.3, "fiber": 0.8, "sodium": 350, "category": "grain"},
    {"id": 79, "name": "披萨", "name_en": "Pizza", "pinyin": "pi sa", "calories": 266, "protein": 11.2, "fat": 10.5, "carbs": 33.3, "fiber": 1.5, "sodium": 450, "category": "grain"},
    {"id": 80, "name": "汉堡", "name_en": "Hamburger", "pinyin": "han bao", "calories": 295, "protein": 14.5, "fat": 11.8, "carbs": 32.6, "fiber": 1.2, "sodium": 380, "category": "grain"},
    {"id": 81, "name": "炸鸡", "name_en": "Fried Chicken", "pinyin": "zha ji", "calories": 260, "protein": 17.0, "fat": 15.5, "carbs": 10.0, "fiber": 0.3, "sodium": 280, "category": "meat"},
    {"id": 82, "name": "红烧肉", "name_en": "Braised Pork", "pinyin": "hong shao rou", "calories": 350, "protein": 10.2, "fat": 28.5, "carbs": 8.5, "fiber": 0.2, "sodium": 250, "category": "meat"},
    {"id": 83, "name": "宫保鸡丁", "name_en": "Kung Pao Chicken", "pinyin": "gong bao ji ding", "calories": 245, "protein": 16.3, "fat": 14.8, "carbs": 12.6, "fiber": 1.2, "sodium": 380, "category": "meat"},
    {"id": 84, "name": "鱼香肉丝", "name_en": "Fish-flavored Pork", "pinyin": "yu xiang rou si", "calories": 185, "protein": 12.5, "fat": 10.2, "carbs": 13.8, "fiber": 0.8, "sodium": 420, "category": "meat"},
    {"id": 85, "name": "麻婆豆腐", "name_en": "Mapo Tofu", "pinyin": "ma po dou fu", "calories": 105, "protein": 6.8, "fat": 5.2, "carbs": 7.2, "fiber": 0.6, "sodium": 320, "category": "bean"},
    {"id": 86, "name": "凉拌黄瓜", "name_en": "Cucumber Salad", "pinyin": "liang ban huang gua", "calories": 35, "protein": 1.2, "fat": 2.1, "carbs": 3.5, "fiber": 0.6, "sodium": 180, "category": "vegetable"},
    {"id": 87, "name": "炒青菜", "name_en": "Stir-fried Greens", "pinyin": "chao qing cai", "calories": 65, "protein": 2.1, "fat": 4.5, "carbs": 4.2, "fiber": 1.2, "sodium": 220, "category": "vegetable"},
    {"id": 88, "name": "地三鲜", "name_en": "Di San Xian", "pinyin": "di san xian", "calories": 148, "protein": 3.5, "fat": 8.6, "carbs": 15.8, "fiber": 2.1, "sodium": 280, "category": "vegetable"},
    {"id": 89, "name": "牛奶麦片", "name_en": "Milk Cereal", "pinyin": "niu nai mai pian", "calories": 210, "protein": 7.2, "fat": 4.8, "carbs": 35.6, "fiber": 3.2, "sodium": 85, "category": "grain"},
    {"id": 90, "name": "三明治", "name_en": "Sandwich", "pinyin": "san ming zhi", "calories": 280, "protein": 12.5, "fat": 9.5, "carbs": 36.8, "fiber": 2.1, "sodium": 420, "category": "grain"},
    {"id": 91, "name": "寿司", "name_en": "Sushi", "pinyin": "shou si", "calories": 150, "protein": 5.8, "fat": 2.5, "carbs": 25.3, "fiber": 0.8, "sodium": 280, "category": "grain"},
    {"id": 92, "name": "沙拉", "name_en": "Salad", "pinyin": "sha la", "calories": 85, "protein": 2.8, "fat": 5.2, "carbs": 7.8, "fiber": 2.5, "sodium": 180, "category": "vegetable"},
    {"id": 93, "name": "酸奶水果捞", "name_en": "Yogurt Fruit Bowl", "pinyin": "suan nai shui guo lao", "calories": 110, "protein": 3.5, "fat": 2.2, "carbs": 21.5, "fiber": 1.8, "sodium": 45, "category": "dairy"},
    {"id": 94, "name": "紫薯", "name_en": "Purple Sweet Potato", "pinyin": "zi shu", "calories": 82, "protein": 1.4, "fat": 0.1, "carbs": 18.5, "fiber": 2.8, "sodium": 28, "category": "grain"},
    {"id": 95, "name": "南瓜", "name_en": "Pumpkin", "pinyin": "nan gua", "calories": 26, "protein": 0.7, "fat": 0.1, "carbs": 6.5, "fiber": 0.8, "sodium": 8, "category": "vegetable"},
    {"id": 96, "name": "芦笋", "name_en": "Asparagus", "pinyin": "lu sun", "calories": 22, "protein": 2.6, "fat": 0.1, "carbs": 4.9, "fiber": 1.9, "sodium": 3, "category": "vegetable"},
    {"id": 97, "name": "秋葵", "name_en": "Okra", "pinyin": "qiu kui", "calories": 37, "protein": 2.0, "fat": 0.1, "carbs": 7.1, "fiber": 3.3, "sodium": 4, "category": "vegetable"},
    {"id": 98, "name": "莲藕", "name_en": "Lotus Root", "pinyin": "lian ou", "calories": 73, "protein": 1.9, "fat": 0.2, "carbs": 16.4, "fiber": 1.2, "sodium": 44, "category": "vegetable"},
    {"id": 99, "name": "椰子水", "name_en": "Coconut Water", "pinyin": "ye zi shui", "calories": 19, "protein": 0.5, "fat": 0.1, "carbs": 3.8, "fiber": 0.1, "sodium": 18, "category": "beverage"},
    {"id": 100, "name": "气泡水", "name_en": "Sparkling Water", "pinyin": "qi pao shui", "calories": 0, "protein": 0, "fat": 0, "carbs": 0, "fiber": 0, "sodium": 5, "category": "beverage"},
    {"id": 101, "name": "坚果混合", "name_en": "Mixed Nuts", "pinyin": "jian guo hun he", "calories": 607, "protein": 20.3, "fat": 52.8, "carbs": 21.5, "fiber": 8.2, "sodium": 5, "category": "nut"},
    {"id": 102, "name": "芝麻", "name_en": "Sesame", "pinyin": "zhi ma", "calories": 531, "protein": 19.1, "fat": 46.1, "carbs": 24.0, "fiber": 14.0, "sodium": 8, "category": "nut"},
    {"id": 103, "name": "叉烧", "name_en": "BBQ Pork", "pinyin": "cha shao", "calories": 285, "protein": 23.8, "fat": 18.5, "carbs": 5.2, "fiber": 0, "sodium": 480, "category": "meat"},
    {"id": 104, "name": "腊肠", "name_en": "Chinese Sausage", "pinyin": "la chang", "calories": 584, "protein": 18.0, "fat": 48.3, "carbs": 17.6, "fiber": 0, "sodium": 1200, "category": "meat"},
    {"id": 105, "name": "皮蛋瘦肉粥", "name_en": "Century Egg Pork Congee", "pinyin": "pi dan shou rou zhou", "calories": 65, "protein": 2.8, "fat": 1.2, "carbs": 10.5, "fiber": 0.3, "sodium": 320, "category": "grain"},
]

CATEGORY_NAMES = {
    "grain": "主食",
    "meat": "肉类",
    "egg": "蛋类",
    "dairy": "乳制品",
    "bean": "豆制品",
    "vegetable": "蔬菜",
    "fruit": "水果",
    "nut": "坚果",
    "beverage": "饮料",
    "snack": "零食",
}

RECOMMENDED_INTAKE = {
    "calories": 2000,
    "protein": 55,
    "fat": 65,
    "carbs": 275,
    "fiber": 28,
    "sodium": 2000,
}
