import { Herb } from '../types';

export const herbs: Herb[] = [
  {
    id: 'mahuang',
    name: '麻黄',
    alias: '龙沙、卑相',
    smell: '气微香，味涩、微苦',
    shape: '呈细长圆柱形，少分枝，表面淡绿色至黄绿色',
    effect: '发汗散寒，宣肺平喘，利水消肿',
    emoji: '🌿',
    category: '解表药',
  },
  {
    id: 'guizhi',
    name: '桂枝',
    alias: '玉桂、柳桂',
    smell: '有特异香气，味甜、微辛，皮部味较浓',
    shape: '呈长圆柱形，多分枝，表面红棕色至棕色',
    effect: '发汗解肌，温通经脉，助阳化气',
    emoji: '🍃',
    category: '解表药',
  },
  {
    id: 'bohe',
    name: '薄荷',
    alias: '野薄荷、夜息香',
    smell: '揉搓后有特殊清凉香气，味辛凉',
    shape: '茎呈方柱形，有对生分枝，表面紫棕色或淡绿色',
    effect: '疏散风热，清利头目，利咽透疹，疏肝行气',
    emoji: '🌱',
    category: '解表药',
  },
  {
    id: 'juhua',
    name: '菊花',
    alias: '寿客、金英',
    smell: '气清香，味甘、微苦',
    shape: '呈扁球形或不规则球形，舌状花类白色或黄色',
    effect: '疏散风热，平抑肝阳，清肝明目，清热解毒',
    emoji: '🌸',
    category: '解表药',
  },
  {
    id: 'jinyinhua',
    name: '金银花',
    alias: '忍冬花、双花',
    smell: '气清香，味淡、微苦',
    shape: '呈棒状，上粗下细，略弯曲，表面黄白色或绿白色',
    effect: '清热解毒，疏散风热',
    emoji: '🌼',
    category: '清热药',
  },
  {
    id: 'lianciao',
    name: '连翘',
    alias: '黄花条、连壳',
    smell: '气微香，味苦',
    shape: '呈长卵形至卵形，稍扁，表面有不规则的纵皱纹',
    effect: '清热解毒，消肿散结，疏散风热',
    emoji: '🌿',
    category: '清热药',
  },
  {
    id: 'banlangen',
    name: '板蓝根',
    alias: '靛青根、蓝靛根',
    smell: '气微，味微甜后苦涩',
    shape: '呈圆柱形，稍扭曲，表面淡灰黄色或淡棕黄色',
    effect: '清热解毒，凉血，利咽',
    emoji: '🍃',
    category: '清热药',
  },
  {
    id: 'huanglian',
    name: '黄连',
    alias: '味连、川连',
    smell: '气微，味极苦',
    shape: '呈不规则结节状，表面黄褐色或灰黄色',
    effect: '清热燥湿，泻火解毒',
    emoji: '🌱',
    category: '清热药',
  },
  {
    id: 'renshen',
    name: '人参',
    alias: '黄参、地精',
    smell: '香气特异，味微苦、甘',
    shape: '主根呈纺锤形或圆柱形，表面灰黄色，上部有横纹',
    effect: '大补元气，复脉固脱，补脾益肺，生津养血',
    emoji: '🌿',
    category: '补益药',
  },
  {
    id: 'huangqi',
    name: '黄芪',
    alias: '绵芪、黄耆',
    smell: '气微，味微甜，嚼之微有豆腥味',
    shape: '呈圆柱形，有的有分枝，表面淡棕黄色或淡棕褐色',
    effect: '补气升阳，固表止汗，利水消肿，生津养血',
    emoji: '🍃',
    category: '补益药',
  },
  {
    id: 'danggui',
    name: '当归',
    alias: '干归、秦归',
    smell: '有浓郁的香气，味甘、辛、微苦',
    shape: '呈圆柱形，有支根，表面黄棕色至棕褐色',
    effect: '补血活血，调经止痛，润肠通便',
    emoji: '🌱',
    category: '补益药',
  },
  {
    id: 'gouqi',
    name: '枸杞',
    alias: '枸杞子、红耳坠',
    smell: '气微，味甜',
    shape: '呈类纺锤形或椭圆形，表面红色或暗红色',
    effect: '滋补肝肾，益精明目',
    emoji: '🍒',
    category: '补益药',
  },
  {
    id: 'xingren',
    name: '杏仁',
    alias: '苦杏仁、杏核仁',
    smell: '气微，味苦',
    shape: '呈扁心形，表面黄棕色至深棕色',
    effect: '降气止咳平喘，润肠通便',
    emoji: '🌿',
    category: '止咳药',
  },
  {
    id: 'jiegeng',
    name: '桔梗',
    alias: '包袱花、铃铛花',
    smell: '气微，味微甜后苦',
    shape: '呈圆柱形或略呈纺锤形，表面白色或淡黄白色',
    effect: '宣肺，利咽，祛痰，排脓',
    emoji: '🍃',
    category: '止咳药',
  },
  {
    id: 'chuanbei',
    name: '川贝',
    alias: '川贝母、贝母',
    smell: '气微，味微苦',
    shape: '呈类圆锥形或近球形，表面类白色',
    effect: '清热润肺，化痰止咳，散结消痈',
    emoji: '🌱',
    category: '止咳药',
  },
  {
    id: 'pipaye',
    name: '枇杷叶',
    alias: '巴叶、芦桔叶',
    smell: '气微，味微苦',
    shape: '呈长圆形或倒卵形，边缘有疏锯齿',
    effect: '清肺止咳，降逆止呕',
    emoji: '🍃',
    category: '止咳药',
  },
  {
    id: 'chenpi',
    name: '陈皮',
    alias: '橘皮、贵老',
    smell: '气香，味辛、苦',
    shape: '常剥成数瓣，基部相连，呈不规则的片状',
    effect: '理气健脾，燥湿化痰',
    emoji: '🍊',
    category: '理气药',
  },
  {
    id: 'muxiang',
    name: '木香',
    alias: '广木香、云木香',
    smell: '气香特异，味微苦',
    shape: '呈圆柱形或半圆柱形，表面黄棕色至灰褐色',
    effect: '行气止痛，健脾消食',
    emoji: '🌿',
    category: '理气药',
  },
  {
    id: 'xiangfu',
    name: '香附',
    alias: '莎草根、香附子',
    smell: '气香，味微苦',
    shape: '多呈纺锤形，有的略弯曲，表面棕褐色或黑褐色',
    effect: '疏肝解郁，理气宽中，调经止痛',
    emoji: '🍃',
    category: '理气药',
  },
  {
    id: 'wuyao',
    name: '乌药',
    alias: '台乌、矮樟',
    smell: '气香，味微苦、辛，有清凉感',
    shape: '呈纺锤形，有的中部收缩成连珠状，表面黄棕色或黄褐色',
    effect: '行气止痛，温肾散寒',
    emoji: '🌱',
    category: '理气药',
  },
];

export const getHerbById = (id: string): Herb | undefined => {
  return herbs.find(herb => herb.id === id);
};

export const getHerbsByCategory = (category: string): Herb[] => {
  return herbs.filter(herb => herb.category === category);
};

export const categories = ['解表药', '清热药', '补益药', '止咳药', '理气药'];
