import type { Scene, DialogueNode, DialogueOption, SceneType } from './types';

export { Scene, DialogueNode, DialogueOption, SceneType };

export const SCENE_TYPE_LABELS: Record<SceneType, string> = {
  initial: '初次接触',
  objection: '异议处理',
  negotiation: '价格谈判',
  closing: '促成成交',
  followup: '售后跟进',
  custom: '自定义场景',
};

const initialContactOptions1: DialogueOption[] = [
  {
    id: 'initial-opt-1-1',
    text: '您好，我是XX公司的销售顾问李明，请问是张经理吗？想跟您聊聊我们的企业管理系统，可能对贵公司有帮助。',
    keywords: ['您好', '自我介绍', '公司', '职位', '姓名', '确认身份', '产品价值'],
    score: 95,
    feedback: '非常专业！完整的自我介绍+身份确认+价值陈述，给客户留下了良好的第一印象。',
    nextNodeId: 'initial-node-2a',
    isOptimal: true,
  },
  {
    id: 'initial-opt-1-2',
    text: '喂，你好，张经理在吗？我是做软件的。',
    keywords: ['你好', '身份确认'],
    score: 45,
    feedback: '不够完整，缺少自我介绍、公司信息和产品价值，客户可能直接挂断。',
    nextNodeId: 'initial-node-2b',
  },
  {
    id: 'initial-opt-1-3',
    text: '请问是张总吗？我是XX科技的，我们产品特别好，你肯定需要。',
    keywords: ['身份确认', '公司名', '产品'],
    score: 55,
    feedback: '过于夸张，缺少可信度，应该先了解客户需求再介绍产品。',
    nextNodeId: 'initial-node-2b',
  },
];

const objectionOptions1: DialogueOption[] = [
  {
    id: 'objection-opt-1-1',
    text: '王总，我完全理解您的顾虑，价格确实是一个重要考量。我们可以先算一下，这套系统每月能帮您节省约30小时的人工成本，折算下来其实不到两个月就能回本。',
    keywords: ['理解', '共情', '价格', '成本', '节省', '时间', '回本', 'ROI'],
    score: 95,
    feedback: '优秀！先表示理解，再用数据呈现价值，让客户感受到这是投资而非支出。',
    nextNodeId: 'objection-node-2a',
    isOptimal: true,
  },
  {
    id: 'objection-opt-1-2',
    text: '这个价格真的不贵，相比同行已经很便宜了。',
    keywords: ['价格', '同行', '便宜'],
    score: 40,
    feedback: '单纯强调便宜无法打动客户，需要量化价值。',
    nextNodeId: 'objection-node-2b',
  },
  {
    id: 'objection-opt-1-3',
    text: '那您觉得多少钱合适？我们可以商量。',
    keywords: ['价格', '商量'],
    score: 35,
    feedback: '过早进入议价阶段，容易被动，应先建立价值感知。',
    nextNodeId: 'objection-node-2b',
  },
];

const negotiationOptions1: DialogueOption[] = [
  {
    id: 'negotiation-opt-1-1',
    text: '陈总，您的需求我完全理解。如果签约三年，我们可以提供8折优惠，还免费赠送价值2万的定制化培训服务。这个方案既能满足预算要求，又能获得更多增值服务。',
    keywords: ['理解', '多年签约', '折扣', '免费', '增值服务', '培训', '定制化', '双赢'],
    score: 95,
    feedback: '非常好！用长期签约换折扣+增值服务，既让客户觉得划算，又保证了公司的长期收益。',
    nextNodeId: 'negotiation-node-2a',
    isOptimal: true,
  },
  {
    id: 'negotiation-opt-1-2',
    text: '我去跟领导申请一下，看看能不能给您降点。',
    keywords: ['申请', '领导', '降价'],
    score: 45,
    feedback: '显得没有决策权，而且单纯降价会损失利润，应考虑其他增值方案。',
    nextNodeId: 'negotiation-node-2b',
  },
  {
    id: 'negotiation-opt-1-3',
    text: '实在不行就给您打个9折，但不能再低了。',
    keywords: ['折扣', '9折'],
    score: 50,
    feedback: '直接降价没有附加条件，会让客户觉得还有降价空间。',
    nextNodeId: 'negotiation-node-2b',
  },
];

const closingOptions1: DialogueOption[] = [
  {
    id: 'closing-opt-1-1',
    text: '刘总，看来您对方案整体还是很认可的。我们这边合同已经准备好了，您看是今天签还是明天方便？您也可以先付个定金，我们马上安排实施团队对接。',
    keywords: ['认可', '合同', '二选一', '今天', '明天', '定金', '实施', '紧迫感'],
    score: 95,
    feedback: '完美！假设成交+二选一法+紧迫感，巧妙地推动客户做出决策。',
    nextNodeId: 'closing-node-2a',
    isOptimal: true,
  },
  {
    id: 'closing-opt-1-2',
    text: '那您考虑得怎么样了？要不要买？',
    keywords: ['考虑', '买'],
    score: 35,
    feedback: '太直接了，客户容易说再等等，应该用更委婉的方式引导成交。',
    nextNodeId: 'closing-node-2b',
  },
  {
    id: 'closing-opt-1-3',
    text: '没问题的话我们就签合同吧。',
    keywords: ['合同', '签'],
    score: 55,
    feedback: '可以但不够巧妙，缺少备选方案和推动力。',
    nextNodeId: 'closing-node-2b',
  },
];

const followupOptions1: DialogueOption[] = [
  {
    id: 'followup-opt-1-1',
    text: '赵总您好，打扰您了。上次的系统上线一周了，想跟您确认下使用情况如何？团队有没有遇到什么问题？另外想了解一下，您对我们的服务有什么改进建议？',
    keywords: ['您好', '确认', '使用情况', '问题', '建议', '服务', '满意度'],
    score: 95,
    feedback: '非常专业的售后跟进！关心使用情况+主动解决问题+收集反馈，有利于客户留存和转介绍。',
    nextNodeId: 'followup-node-2a',
    isOptimal: true,
  },
  {
    id: 'followup-opt-1-2',
    text: '赵总，系统用着还行吧？',
    keywords: ['用着', '还行'],
    score: 40,
    feedback: '太随意了，缺乏专业性和关怀感。',
    nextNodeId: 'followup-node-2b',
  },
  {
    id: 'followup-opt-1-3',
    text: '赵总，合同到期了吗？要不要续约？',
    keywords: ['合同', '续约'],
    score: 30,
    feedback: '直奔主题，客户可能反感，应先建立关系再谈续约。',
    nextNodeId: 'followup-node-2b',
  },
];

export const PRESET_SCENES: Scene[] = [
  {
    id: 'scene-initial',
    name: '初次电话拜访',
    description: '模拟第一次给潜在客户打电话，练习破冰和建立第一印象的技巧',
    type: 'initial',
    difficulty: 2,
    startNodeId: 'initial-node-1',
    nodes: {
      'initial-node-1': {
        id: 'initial-node-1',
        type: 'system',
        text: '（电话接通）嘟...嘟...你好，请问哪位？',
        options: initialContactOptions1,
      },
      'initial-node-2a': {
        id: 'initial-node-2a',
        type: 'system',
        text: '哦，你好李经理，我是张总。你们是做什么系统来着？说来听听。',
        options: [
          {
            id: 'initial-opt-2a-1',
            text: '张总您好，我们是做一站式企业管理系统的，涵盖CRM客户管理、进销存和财务模块。了解到贵公司目前有50人规模，正处在快速发展期，这套系统能帮您提升30%以上的运营效率。',
            keywords: ['您好', '产品介绍', '模块', '客户规模', '效率提升', '数据', '价值'],
            score: 95,
            feedback: '很棒！产品介绍+客户洞察+量化价值，客户会继续听下去。',
            nextNodeId: 'initial-node-3a',
            isOptimal: true,
          },
          {
            id: 'initial-opt-2a-2',
            text: '我们做企业管理软件的，功能挺多的，什么都有。',
            keywords: ['企业管理', '软件'],
            score: 40,
            feedback: '太笼统，客户无法感知价值，应具体说明功能和带来的好处。',
            nextNodeId: 'initial-node-3b',
          },
        ],
      },
      'initial-node-2b': {
        id: 'initial-node-2b',
        type: 'system',
        text: '哦...我现在有点忙，你稍后再打吧。',
        options: [
          {
            id: 'initial-opt-2b-1',
            text: '理解张总，打扰您了。请问您明天上午10点方便吗？我到时再打给您，只需要2分钟就能说清楚。',
            keywords: ['理解', '道歉', '预约', '具体时间', '短时承诺'],
            score: 85,
            feedback: '不错！尊重客户时间并预约具体时间，增加了下次沟通的机会。',
            nextNodeId: 'initial-node-3c',
            isOptimal: true,
          },
          {
            id: 'initial-opt-2b-2',
            text: '好的，那我改天再打。',
            keywords: ['改天'],
            score: 45,
            feedback: '没有预约具体时间，下次很可能被遗忘。',
            nextNodeId: 'initial-node-3c',
          },
        ],
      },
      'initial-node-3a': {
        id: 'initial-node-3a',
        type: 'system',
        text: '听起来还不错，那具体怎么收费呢？',
        options: [
          {
            id: 'initial-opt-3a-1',
            text: '张总问得好。我们是按用户数收费，50人规模一年约1.8万，平均每天不到100块。下周三下午我方便上门给您做个详细演示，顺便带几个同行业客户的案例。您看合适吗？',
            keywords: ['收费', '价格', '用户数', '日均', '演示', '案例', '上门', '预约'],
            score: 95,
            feedback: '完美！价格拆分降低感知+引导线下演示，是B2B销售的标准打法。',
            isOptimal: true,
          },
          {
            id: 'initial-opt-3a-2',
            text: '一年2万左右，具体看需求。',
            keywords: ['价格', '2万'],
            score: 50,
            feedback: '价格报得太直接，没有价值铺垫，客户容易觉得贵。',
          },
        ],
      },
      'initial-node-3b': {
        id: 'initial-node-3b',
        type: 'system',
        text: '我知道了，有需要再联系你吧。',
        options: [
          {
            id: 'initial-opt-3b-1',
            text: '好的张总，您先忙。我加您个微信，发一些行业案例给您参考，您有空可以看看。请问您微信号就是这个手机号吗？',
            keywords: ['理解', '微信', '案例', '参考', '手机号'],
            score: 80,
            feedback: '不错！添加私域+发送内容，保持长期联系的机会。',
            isOptimal: true,
          },
          {
            id: 'initial-opt-3b-2',
            text: '好的，那先这样，再见。',
            keywords: ['再见'],
            score: 40,
            feedback: '没有留下任何后续联系方式，这次沟通就白费了。',
          },
        ],
      },
      'initial-node-3c': {
        id: 'initial-node-3c',
        type: 'system',
        text: '好的，那就先这样。',
        options: [
          {
            id: 'initial-opt-3c-1',
            text: '好的张总，感谢您的时间，我记下了，到时准时联系您。祝您工作愉快！',
            keywords: ['感谢', '确认', '祝福'],
            score: 85,
            feedback: '礼貌收尾，给客户留下好印象。',
            isOptimal: true,
          },
          {
            id: 'initial-opt-3c-2',
            text: '嗯，好。',
            keywords: [],
            score: 50,
            feedback: '略显敷衍，应该更礼貌一些。',
          },
        ],
      },
    },
    edges: [
      { id: 'e1', from: 'initial-node-1', to: 'initial-node-2a' },
      { id: 'e2', from: 'initial-node-1', to: 'initial-node-2b' },
      { id: 'e3', from: 'initial-node-2a', to: 'initial-node-3a' },
      { id: 'e4', from: 'initial-node-2a', to: 'initial-node-3b' },
      { id: 'e5', from: 'initial-node-2b', to: 'initial-node-3c' },
    ],
  },
  {
    id: 'scene-objection',
    name: '价格异议处理',
    description: '客户觉得产品太贵，练习如何通过价值呈现化解价格异议',
    type: 'objection',
    difficulty: 3,
    startNodeId: 'objection-node-1',
    nodes: {
      'objection-node-1': {
        id: 'objection-node-1',
        type: 'system',
        text: '小李啊，方案我看了，功能还行，但这个价格也太贵了，比我预想的高出不少。',
        options: objectionOptions1,
      },
      'objection-node-2a': {
        id: 'objection-node-2a',
        type: 'system',
        text: '嗯...你这么算下来好像确实有道理，但我还是觉得一次性投入有点大。',
        options: [
          {
            id: 'objection-opt-2a-1',
            text: '王总，我特别理解。您看这样行不行，我们支持分期付款，首付30%就能上线使用，剩下的分12个月支付，每月压力就很小了。或者先从核心模块开始，后续再逐步扩展。',
            keywords: ['理解', '分期付款', '首付', '按月', '核心模块', '逐步扩展', '灵活方案'],
            score: 95,
            feedback: '优秀！提供多种灵活方案让客户选择，大大降低了决策门槛。',
            nextNodeId: 'objection-node-3a',
            isOptimal: true,
          },
          {
            id: 'objection-opt-2a-2',
            text: '那我给您申请一个优惠价，您看9折怎么样？',
            keywords: ['优惠', '9折'],
            score: 50,
            feedback: '又回到简单降价了，应该优先考虑分期等不直接降价的方案。',
            nextNodeId: 'objection-node-3b',
          },
        ],
      },
      'objection-node-2b': {
        id: 'objection-node-2b',
        type: 'system',
        text: '反正我觉得贵了，你看看能不能再便宜点？',
        options: [
          {
            id: 'objection-opt-2b-1',
            text: '王总，价格方面我确实需要跟公司申请，但在这之前，我想确认一下，如果价格合适，您这边能在本周内确定合作吗？这样我也好去争取最优的政策。',
            keywords: ['申请', '价格', '确认', '本周', '合作', '最优政策'],
            score: 85,
            feedback: '不错！先锁定成交条件再去申请，避免价格降了但客户还不签。',
            nextNodeId: 'objection-node-3a',
            isOptimal: true,
          },
          {
            id: 'objection-opt-2b-2',
            text: '行，我去跟领导说说。',
            keywords: ['领导', '说说'],
            score: 40,
            feedback: '没有确认成交意向就去申请，很可能白忙活。',
            nextNodeId: 'objection-node-3b',
          },
        ],
      },
      'objection-node-3a': {
        id: 'objection-node-3a',
        type: 'system',
        text: '分期这个方案听起来不错，具体怎么操作？',
        options: [
          {
            id: 'objection-opt-3a-1',
            text: '王总，操作很简单。我们签约后您付首款，系统3个工作日内上线，我全程跟进对接。我把合同和分期方案发给您，您看还有什么细节需要确认的？',
            keywords: ['操作简单', '签约', '首款', '上线', '跟进', '合同', '方案', '确认'],
            score: 95,
            feedback: '很好！简化流程说明+推动下一步，离成交更近一步。',
            isOptimal: true,
          },
          {
            id: 'objection-opt-3a-2',
            text: '具体流程比较复杂，回头我整理一下发给您。',
            keywords: ['复杂', '回头', '整理'],
            score: 50,
            feedback: '说复杂会增加客户顾虑，应该强调简单方便。',
          },
        ],
      },
      'objection-node-3b': {
        id: 'objection-node-3b',
        type: 'system',
        text: '那我再考虑考虑吧。',
        options: [
          {
            id: 'objection-opt-3b-1',
            text: '完全理解，王总。这样，我把几个同行业客户的真实ROI数据和案例发给您，您可以参考一下。另外下周二我正好在附近，方便的话可以坐下来当面聊聊您的顾虑。',
            keywords: ['理解', '案例', '数据', 'ROI', '约见', '当面', '顾虑'],
            score: 85,
            feedback: '不错！用客户案例增强信任，同时争取面访机会。',
            isOptimal: true,
          },
          {
            id: 'objection-opt-3b-2',
            text: '好的，考虑好了联系我。',
            keywords: ['考虑', '联系'],
            score: 40,
            feedback: '太被动了，客户大概率不会主动联系。',
          },
        ],
      },
    },
    edges: [
      { id: 'e1', from: 'objection-node-1', to: 'objection-node-2a' },
      { id: 'e2', from: 'objection-node-1', to: 'objection-node-2b' },
      { id: 'e3', from: 'objection-node-2a', to: 'objection-node-3a' },
      { id: 'e4', from: 'objection-node-2a', to: 'objection-node-3b' },
      { id: 'e5', from: 'objection-node-2b', to: 'objection-node-3a' },
      { id: 'e6', from: 'objection-node-2b', to: 'objection-node-3b' },
    ],
  },
  {
    id: 'scene-negotiation',
    name: '合同价格谈判',
    description: '进入实质性商务谈判阶段，练习在保证利润的前提下促成签约',
    type: 'negotiation',
    difficulty: 4,
    startNodeId: 'negotiation-node-1',
    nodes: {
      'negotiation-node-1': {
        id: 'negotiation-node-1',
        type: 'system',
        text: '方案我们都挺满意的，但价格上希望你们能再给个诚意价，毕竟我们也是大公司，后续还有很多合作机会。',
        options: negotiationOptions1,
      },
      'negotiation-node-2a': {
        id: 'negotiation-node-2a',
        type: 'system',
        text: '三年签约确实可以考虑，但8折还是有点高，能不能给到7.5折？培训服务要包含全员培训。',
        options: [
          {
            id: 'negotiation-opt-2a-1',
            text: '陈总，您的提议我记下来了。7.5折确实有点挑战，但考虑到我们的长期合作，我可以去申请这个折扣。不过培训方面，全员培训需要额外增加成本，您看我们能不能做个交换——您这边先推荐2个其他部门的负责人给我认识，我这边帮您争取全员培训的名额。',
            keywords: ['记下来', '挑战', '长期合作', '申请', '交换条件', '推荐', '名额', '双赢'],
            score: 95,
            feedback: '太精彩了！用交换条件代替让步，既满足了客户需求，又为自己争取了新的商机。',
            nextNodeId: 'negotiation-node-3a',
            isOptimal: true,
          },
          {
            id: 'negotiation-opt-2a-2',
            text: '行，我去申请一下，应该问题不大。',
            keywords: ['申请'],
            score: 45,
            feedback: '轻易答应客户所有条件，没有为公司争取任何利益。',
            nextNodeId: 'negotiation-node-3b',
          },
        ],
      },
      'negotiation-node-2b': {
        id: 'negotiation-node-2b',
        type: 'system',
        text: '我们预算有限，只能出到X万，行就签，不行就算了。',
        options: [
          {
            id: 'negotiation-opt-2b-1',
            text: '陈总，预算的问题我非常理解。您看这样，X万的预算我们可以做精简版方案，保留核心的CRM和报表模块，去掉高级分析和定制开发。先满足基本需求，后续业务发展了再升级，您觉得怎么样？',
            keywords: ['理解', '预算', '精简版', '核心模块', '保留', '去掉', '先满足', '后续升级'],
            score: 90,
            feedback: '非常好！不直接拒绝，而是提供降级方案，保住了合作机会。',
            nextNodeId: 'negotiation-node-3a',
            isOptimal: true,
          },
          {
            id: 'negotiation-opt-2b-2',
            text: '这个价格实在做不了，成本都不够。',
            keywords: ['做不了', '成本'],
            score: 35,
            feedback: '直接拒绝，容易让谈判陷入僵局。',
            nextNodeId: 'negotiation-node-3b',
          },
        ],
      },
      'negotiation-node-3a': {
        id: 'negotiation-node-3a',
        type: 'system',
        text: '你的方案我觉得可以，那就按我们说的来。',
        options: [
          {
            id: 'negotiation-opt-3a-1',
            text: '太好了陈总！感谢您的信任和支持。我马上整理最终合同发给您，您确认无误后我们安排签约。对了，您方便的话我下午就可以把合同送过来。',
            keywords: ['感谢', '信任', '支持', '合同', '确认', '签约', '下午', '送过来'],
            score: 95,
            feedback: '完美！趁热打铁，立刻推动签约，防止夜长梦多。',
            isOptimal: true,
          },
          {
            id: 'negotiation-opt-3a-2',
            text: '好的，那我们合同上见。',
            keywords: ['合同'],
            score: 55,
            feedback: '缺少紧迫感，应该尽快推动签约。',
          },
        ],
      },
      'negotiation-node-3b': {
        id: 'negotiation-node-3b',
        type: 'system',
        text: '这个我需要再跟老板汇报一下。',
        options: [
          {
            id: 'negotiation-opt-3b-1',
            text: '理解，向领导汇报是应该的。我帮您准备一份汇报用的PPT，包含方案对比、ROI分析和同行业案例，您直接给老板看就行，省得您费心整理。预计什么时候有消息呢？',
            keywords: ['理解', '汇报', 'PPT', '方案对比', 'ROI', '案例', '省时间', '预计时间'],
            score: 90,
            feedback: '优秀！主动帮客户准备汇报材料，既减少客户工作又能控制汇报内容。',
            isOptimal: true,
          },
          {
            id: 'negotiation-opt-3b-2',
            text: '好的，等您消息。',
            keywords: ['消息'],
            score: 40,
            feedback: '太被动，没有为客户提供任何帮助。',
          },
        ],
      },
    },
    edges: [
      { id: 'e1', from: 'negotiation-node-1', to: 'negotiation-node-2a' },
      { id: 'e2', from: 'negotiation-node-1', to: 'negotiation-node-2b' },
      { id: 'e3', from: 'negotiation-node-2a', to: 'negotiation-node-3a' },
      { id: 'e4', from: 'negotiation-node-2a', to: 'negotiation-node-3b' },
      { id: 'e5', from: 'negotiation-node-2b', to: 'negotiation-node-3a' },
      { id: 'e6', from: 'negotiation-node-2b', to: 'negotiation-node-3b' },
    ],
  },
  {
    id: 'scene-closing',
    name: '成交临门一脚',
    description: '客户已经基本认可产品，练习如何有效促成最终签约',
    type: 'closing',
    difficulty: 4,
    startNodeId: 'closing-node-1',
    nodes: {
      'closing-node-1': {
        id: 'closing-node-1',
        type: 'system',
        text: '整体来看方案还是不错的，功能和服务都能满足我们的需求。',
        options: closingOptions1,
      },
      'closing-node-2a': {
        id: 'closing-node-2a',
        type: 'system',
        text: '嗯...我今天还有点别的事，明天再说吧。',
        options: [
          {
            id: 'closing-opt-2a-1',
            text: '明白刘总，您肯定很忙。那我们先把意向确认一下，您先付10%的定金，我帮您锁定这个优惠价格和实施档期，剩下的明天签约时再付。定金也是随时可退的，您完全没有风险。',
            keywords: ['理解', '忙', '意向确认', '定金', '锁定', '优惠', '档期', '可退', '无风险'],
            score: 95,
            feedback: '非常棒！小额定金锁单+强调无风险，有效防止客户反悔。',
            nextNodeId: 'closing-node-3a',
            isOptimal: true,
          },
          {
            id: 'closing-opt-2a-2',
            text: '好的，那明天我再联系您。',
            keywords: ['明天', '联系'],
            score: 45,
            feedback: '没有任何锁定动作，客户很可能今晚就变卦。',
            nextNodeId: 'closing-node-3b',
          },
        ],
      },
      'closing-node-2b': {
        id: 'closing-node-2b',
        type: 'system',
        text: '我再想想，和同事商量一下。',
        options: [
          {
            id: 'closing-opt-2b-1',
            text: '刘总这个太应该了，采购确实需要团队意见一致。您看要不要安排个15分钟的电话会，我跟您同事做个简短介绍，当场解答他们的疑问，这样商量起来也更高效。',
            keywords: ['理解', '团队', '电话会', '简短介绍', '解答', '疑问', '高效'],
            score: 90,
            feedback: '很好！主动参与客户内部沟通，帮助客户说服其他人。',
            nextNodeId: 'closing-node-3a',
            isOptimal: true,
          },
          {
            id: 'closing-opt-2b-2',
            text: '好的，商量好了告诉我。',
            keywords: ['商量', '告诉'],
            score: 40,
            feedback: '完全把主动权交给客户，容易失控。',
            nextNodeId: 'closing-node-3b',
          },
        ],
      },
      'closing-node-3a': {
        id: 'closing-node-3a',
        type: 'system',
        text: '好，那就先付定金吧，怎么付？',
        options: [
          {
            id: 'closing-opt-3a-1',
            text: '刘总爽快！我马上发付款链接给您，您手机上就能付，5分钟搞定。付完我立刻给您发确认函，并且通知实施经理明天准备对接。合作愉快！',
            keywords: ['爽快', '付款链接', '手机', '快速', '确认函', '实施经理', '对接', '合作愉快'],
            score: 95,
            feedback: '完美！简化付款流程+立刻确认后续动作+积极情绪感染。',
            isOptimal: true,
          },
          {
            id: 'closing-opt-3a-2',
            text: '我让财务发账号给您，您对公转账就行。',
            keywords: ['财务', '账号', '转账'],
            score: 55,
            feedback: '流程太繁琐，应该提供更便捷的付款方式。',
          },
        ],
      },
      'closing-node-3b': {
        id: 'closing-node-3b',
        type: 'system',
        text: '嗯，好的，我再考虑考虑。',
        options: [
          {
            id: 'closing-opt-3b-1',
            text: '刘总，耽误您1分钟，我想了解一下，您现在主要顾虑的是什么呢？是价格、功能还是其他方面？我看能不能当场帮您解决。',
            keywords: ['耽误', '1分钟', '顾虑', '价格', '功能', '当场', '解决'],
            score: 85,
            feedback: '不错！用封闭式问题找出真实顾虑，再针对性解决。',
            isOptimal: true,
          },
          {
            id: 'closing-opt-3b-2',
            text: '好的，想好了随时联系我。',
            keywords: ['联系'],
            score: 35