import type { Material, Project } from './types'
import { toHexColor } from './types'

export const mockMaterials: Material[] = [
  {
    id: 'm1',
    name: '松木板',
    quantity: 3,
    dimensions: '120×60×2cm',
    materialType: '木材',
    color: toHexColor('#D4A574'),
    condition: 4,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wooden%20plank%20pine%20board%20natural%20texture%20close%20up&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '张师傅',
    contact: '138****1234',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'm2',
    name: '白色乳胶漆',
    quantity: 2,
    dimensions: '5L/桶',
    materialType: '涂料',
    color: toHexColor('#F5F5F5'),
    condition: 5,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=white%20paint%20bucket%20latex%20paint%20interior&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '李女士',
    contact: '139****5678',
    createdAt: Date.now() - 172800000,
  },
  {
    id: 'm3',
    name: '铜质门把手',
    quantity: 6,
    dimensions: '标准尺寸',
    materialType: '金属',
    color: toHexColor('#B87333'),
    condition: 5,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=brass%20door%20handle%20copper%20hardware%20elegant&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '王先生',
    contact: '137****9012',
    createdAt: Date.now() - 259200000,
  },
  {
    id: 'm4',
    name: '亚麻窗帘布',
    quantity: 1,
    dimensions: '3×2.8m',
    materialType: '织物',
    color: toHexColor('#C4B99A'),
    condition: 3,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=linen%20curtain%20fabric%20beige%20natural%20fold&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '赵阿姨',
    contact: '136****3456',
    createdAt: Date.now() - 345600000,
  },
  {
    id: 'm5',
    name: 'PVC水管',
    quantity: 4,
    dimensions: '直径5cm×1m',
    materialType: '塑料',
    color: toHexColor('#E8E8E8'),
    condition: 4,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=PVC%20water%20pipe%20white%20plumbing%20tube&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '刘工',
    contact: '135****7890',
    createdAt: Date.now() - 432000000,
  },
  {
    id: 'm6',
    name: '复古铁艺挂钩',
    quantity: 8,
    dimensions: '10cm',
    materialType: '五金',
    color: toHexColor('#2C2C2C'),
    condition: 5,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vintage%20iron%20wall%20hook%20black%20metal%20decorative&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '陈小姐',
    contact: '134****2345',
    createdAt: Date.now() - 518400000,
  },
  {
    id: 'm7',
    name: '花纹壁纸卷',
    quantity: 2,
    dimensions: '0.53×10m',
    materialType: '织物',
    color: toHexColor('#8B7355'),
    condition: 5,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=floral%20wallpaper%20roll%20vintage%20pattern%20brown&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '周女士',
    contact: '133****6789',
    createdAt: Date.now() - 604800000,
  },
  {
    id: 'm8',
    name: '磨砂玻璃板',
    quantity: 1,
    dimensions: '80×60×0.5cm',
    materialType: '玻璃',
    color: toHexColor('#D0E8F0'),
    condition: 3,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=frosted%20glass%20panel%20translucent%20modern&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '孙先生',
    contact: '132****0123',
    createdAt: Date.now() - 691200000,
  },
  {
    id: 'm9',
    name: '实木地板余料',
    quantity: 5,
    dimensions: '90×12×1.5cm',
    materialType: '木材',
    color: toHexColor('#8B6914'),
    condition: 4,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solid%20hardwood%20flooring%20oak%20plank%20warm&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '吴师傅',
    contact: '131****4567',
    createdAt: Date.now() - 777600000,
  },
  {
    id: 'm10',
    name: '墨绿墙面漆',
    quantity: 1,
    dimensions: '2.5L/桶',
    materialType: '涂料',
    color: toHexColor('#2C5F3B'),
    condition: 5,
    photos: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=dark%20green%20wall%20paint%20bucket%20forest%20color&image_size=landscape_4_3',
    ],
    status: 'available',
    publisherName: '郑女士',
    contact: '130****8901',
    createdAt: Date.now() - 864000000,
  },
]

export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: '田园风花架',
    requiredMaterialTypes: ['木材', '涂料'],
    difficulty: '新手',
    estimatedHours: 4,
    matchScore: 90,
    publisherName: '小明',
    contact: '138****1111',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'p2',
    name: '工业风书架',
    requiredMaterialTypes: ['木材', '金属', '五金'],
    difficulty: '进阶',
    estimatedHours: 8,
    matchScore: 85,
    publisherName: '大伟',
    contact: '139****2222',
    createdAt: Date.now() - 172800000,
  },
  {
    id: 'p3',
    name: '阳台绿植墙',
    requiredMaterialTypes: ['木材', '塑料', '织物'],
    difficulty: '新手',
    estimatedHours: 3,
    matchScore: 75,
    publisherName: '小红',
    contact: '137****3333',
    createdAt: Date.now() - 259200000,
  },
  {
    id: 'p4',
    name: '玻璃隔断屏风',
    requiredMaterialTypes: ['玻璃', '金属', '五金'],
    difficulty: '专家',
    estimatedHours: 12,
    matchScore: 60,
    publisherName: '老陈',
    contact: '136****4444',
    createdAt: Date.now() - 345600000,
  },
  {
    id: 'p5',
    name: '布艺收纳盒',
    requiredMaterialTypes: ['织物', '塑料'],
    difficulty: '新手',
    estimatedHours: 2,
    matchScore: 80,
    publisherName: '小美',
    contact: '135****5555',
    createdAt: Date.now() - 432000000,
  },
  {
    id: 'p6',
    name: '复古相框墙',
    requiredMaterialTypes: ['木材', '玻璃', '涂料', '五金'],
    difficulty: '进阶',
    estimatedHours: 6,
    matchScore: 95,
    publisherName: '阿杰',
    contact: '134****6666',
    createdAt: Date.now() - 518400000,
  },
]
