export const CANVAS_CONFIG = {
  BACKGROUND_COLOR: '#0B0E27',
  ASPECT_RATIO: 16 / 9,
  TARGET_FPS: 30,
}

export const PARTICLE_CONFIG = {
  MIN_COUNT: 100,
  MAX_COUNT: 600,
  DEFAULT_COUNT: 300,
  MIN_RADIUS: 2,
  MAX_RADIUS: 6,
  BROWNIAN_RANGE: 3,
  VELOCITY_SCALE: 0.5,
}

export const STAR_CONFIG = {
  COUNT: 100,
  MIN_SIZE: 1,
  MAX_SIZE: 3,
  MIN_PERIOD: 2,
  MAX_PERIOD: 4,
}

export const COLORS = {
  LOW_FREQ_START: '#FF6B6B',
  LOW_FREQ_END: '#FFD93D',
  MID_FREQ_START: '#4ECDC4',
  MID_FREQ_END: '#4D96FF',
  HIGH_FREQ_START: '#9C89B8',
  HIGH_FREQ_END: '#FF6B6B',
  PANEL_BG: '#1A1A2E',
  CONTROL_BG: '#16162A',
  BORDER: '#2A2A44',
  SLIDER_TRACK: '#2A2A44',
  SLIDER_THUMB: '#4ECDC4',
  PROGRESS_START: '#4ECDC4',
  PROGRESS_END: '#FF6B6B',
  TEXT: '#E0E0E0',
}

export const UI_CONFIG = {
  UPLOAD_PANEL_WIDTH: 320,
  CONTROL_PANEL_WIDTH: 200,
  PANEL_BORDER_RADIUS: 16,
  CONTROL_BORDER_RADIUS: 12,
  BORDER_WIDTH: 1,
  PROGRESS_HEIGHT: 6,
  SLIDER_THUMB_SIZE: 14,
  SLIDER_THUMB_HOVER_SIZE: 16,
  HUE_MIN: -180,
  HUE_MAX: 180,
  HUE_DEFAULT: 0,
  HUE_STEP: 1,
  DENSITY_STEP: 10,
  MAX_AUDIO_DURATION: 30,
}

export const BREAKPOINTS = {
  LARGE: 1200,
  MEDIUM: 768,
}
