import express from 'express';
import cors from 'cors';
import multer from 'multer';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3001;

app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, '..', 'uploads')));

const dbDir = path.join(__dirname, '..', 'data');
if (!fs.existsSync(dbDir)) {
  fs.mkdirSync(dbDir, { recursive: true });
}

const uploadDir = path.join(__dirname, '..', 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

const dbFile = path.join(dbDir, 'garden.json');

function loadDB() {
  if (!fs.existsSync(dbFile)) {
    return { plants: [], tasks: [], photos: [] };
  }
  try {
    return JSON.parse(fs.readFileSync(dbFile, 'utf-8'));
  } catch {
    return { plants: [], tasks: [], photos: [] };
  }
}

function saveDB(db) {
  fs.writeFileSync(dbFile, JSON.stringify(db, null, 2), 'utf-8');
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname);
    cb(null, `${uuidv4()}${ext}`);
  },
});

const upload = multer({ storage });

app.get('/api/plants', (req, res) => {
  const db = loadDB();
  const plants = [...db.plants].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  res.json(plants);
});

app.post('/api/plants', (req, res) => {
  const db = loadDB();
  const { name, variety, plantDate, expectedBloomDate, expectedHarvestDate, status } = req.body;
  const id = uuidv4();
  const now = new Date().toISOString();
  const plant = {
    id,
    name,
    variety: variety || null,
    plantDate,
    expectedBloomDate: expectedBloomDate || null,
    expectedHarvestDate: expectedHarvestDate || null,
    status: status || 'seedling',
    createdAt: now,
    updatedAt: now,
  };
  db.plants.push(plant);
  saveDB(db);
  res.json(plant);
});

app.put('/api/plants/:id', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const { name, variety, plantDate, expectedBloomDate, expectedHarvestDate, status } = req.body;
  const now = new Date().toISOString();
  const idx = db.plants.findIndex(p => p.id === id);
  if (idx === -1) return res.status(404).json({ error: 'Plant not found' });
  db.plants[idx] = {
    ...db.plants[idx],
    name,
    variety: variety || null,
    plantDate,
    expectedBloomDate: expectedBloomDate || null,
    expectedHarvestDate: expectedHarvestDate || null,
    status,
    updatedAt: now,
  };
  saveDB(db);
  res.json(db.plants[idx]);
});

app.delete('/api/plants/:id', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  db.plants = db.plants.filter(p => p.id !== id);
  db.tasks = db.tasks.filter(t => t.plantId !== id);
  const photosToDelete = db.photos.filter(p => p.plantId === id);
  photosToDelete.forEach(photo => {
    const filePath = path.join(__dirname, '..', photo.url);
    if (fs.existsSync(filePath)) {
      try { fs.unlinkSync(filePath); } catch {}
    }
  });
  db.photos = db.photos.filter(p => p.plantId !== id);
  saveDB(db);
  res.json({ success: true });
});

app.get('/api/tasks', (req, res) => {
  const db = loadDB();
  const tasks = [...db.tasks].sort((a, b) => a.date.localeCompare(b.date));
  res.json(tasks);
});

app.post('/api/tasks', (req, res) => {
  const db = loadDB();
  const { plantId, type, date, isAutoGenerated } = req.body;
  const id = uuidv4();
  const now = new Date().toISOString();
  const task = {
    id,
    plantId: plantId || null,
    type,
    date,
    completed: false,
    completedAt: null,
    postponedCount: 0,
    isAutoGenerated: !!isAutoGenerated,
    createdAt: now,
  };
  db.tasks.push(task);
  saveDB(db);
  res.json(task);
});

app.put('/api/tasks/:id', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const { plantId, type, date } = req.body;
  const idx = db.tasks.findIndex(t => t.id === id);
  if (idx === -1) return res.status(404).json({ error: 'Task not found' });
  db.tasks[idx] = {
    ...db.tasks[idx],
    plantId: plantId || null,
    type,
    date,
  };
  saveDB(db);
  res.json(db.tasks[idx]);
});

app.delete('/api/tasks/:id', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  db.tasks = db.tasks.filter(t => t.id !== id);
  saveDB(db);
  res.json({ success: true });
});

app.post('/api/tasks/:id/complete', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const now = new Date().toISOString();
  const idx = db.tasks.findIndex(t => t.id === id);
  if (idx === -1) return res.status(404).json({ error: 'Task not found' });
  db.tasks[idx] = { ...db.tasks[idx], completed: true, completedAt: now };
  saveDB(db);
  res.json(db.tasks[idx]);
});

app.post('/api/tasks/:id/postpone', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const idx = db.tasks.findIndex(t => t.id === id);
  if (idx === -1) return res.status(404).json({ error: 'Task not found' });
  const nextDate = new Date(db.tasks[idx].date);
  nextDate.setDate(nextDate.getDate() + 1);
  db.tasks[idx] = {
    ...db.tasks[idx],
    date: nextDate.toISOString().split('T')[0],
    postponedCount: db.tasks[idx].postponedCount + 1,
  };
  saveDB(db);
  res.json(db.tasks[idx]);
});

app.get('/api/plants/:id/photos', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const photos = db.photos
    .filter(p => p.plantId === id)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  res.json(photos);
});

app.post('/api/plants/:id/photos', upload.single('photo'), (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const { note } = req.body;
  if (!req.file) return res.status(400).json({ error: 'No file uploaded' });
  const photoId = uuidv4();
  const now = new Date().toISOString();
  const url = `/uploads/${req.file.filename}`;
  const photo = {
    id: photoId,
    plantId: id,
    url,
    note: note || null,
    createdAt: now,
  };
  db.photos.push(photo);
  saveDB(db);
  res.json(photo);
});

app.delete('/api/photos/:id', (req, res) => {
  const db = loadDB();
  const { id } = req.params;
  const photo = db.photos.find(p => p.id === id);
  if (photo) {
    const filePath = path.join(__dirname, '..', photo.url);
    if (fs.existsSync(filePath)) {
      try { fs.unlinkSync(filePath); } catch {}
    }
  }
  db.photos = db.photos.filter(p => p.id !== id);
  saveDB(db);
  res.json({ success: true });
});

app.listen(PORT, () => {
  console.log(`Garden Manager API server running on port ${PORT}`);
});
