import type { ConstellationTemplate } from './types';

export const CONSTELLATION_TEMPLATES: ConstellationTemplate[] = [
  {
    id: 'ursa-major',
    name: '大熊座',
    nameEn: 'Ursa Major',
    color: '#88ddff',
    accentColor: '#aaffcc',
    bestMonth: '4月',
    latitudeRange: '+90° ~ -30°',
    mythology: '希腊神话中，宙斯将美丽的少女卡利斯托变为大熊，后升上天界成为大熊座，其七颗亮星组成著名的北斗七星。',
    stars: [
      { name: '天枢', nameEn: 'Dubhe', position: [-3.2, 1.8, 0], magnitude: 1.79, distance: 124, spectralType: 'F7V' },
      { name: '天璇', nameEn: 'Merak', position: [-2.2, 1.6, 0], magnitude: 2.37, distance: 79, spectralType: 'A1V' },
      { name: '天玑', nameEn: 'Phecda', position: [-1.0, 0.8, 0], magnitude: 2.44, distance: 84, spectralType: 'A0V' },
      { name: '天权', nameEn: 'Megrez', position: [-0.2, 1.2, 0], magnitude: 3.31, distance: 81, spectralType: 'A3V' },
      { name: '玉衡', nameEn: 'Alioth', position: [0.9, 1.5, 0], magnitude: 1.77, distance: 81, spectralType: 'A0p' },
      { name: '开阳', nameEn: 'Mizar', position: [2.0, 1.3, 0], magnitude: 2.04, distance: 78, spectralType: 'A1V' },
      { name: '摇光', nameEn: 'Alkaid', position: [3.1, 0.6, 0], magnitude: 1.86, distance: 101, spectralType: 'B3V' },
    ],
    connections: [[0, 1], [1, 2], [2, 3], [3, 0], [3, 4], [4, 5], [5, 6]]
  },
  {
    id: 'orion',
    name: '猎户座',
    nameEn: 'Orion',
    color: '#88ccff',
    accentColor: '#ffaa66',
    bestMonth: '1月',
    latitudeRange: '+85° ~ -75°',
    mythology: '希腊神话中的伟大猎人奥利翁，因追求七姐妹被月神阿耳忒弥斯误杀，升上天界成为猎户座，腰间三星为其标志。',
    stars: [
      { name: '参宿四', nameEn: 'Betelgeuse', position: [-2.0, 2.5, 0], magnitude: 0.42, distance: 642, spectralType: 'M2Ia' },
      { name: '参宿五', nameEn: 'Bellatrix', position: [2.0, 2.3, 0], magnitude: 1.64, distance: 250, spectralType: 'B2III' },
      { name: '参宿一', nameEn: 'Alnitak', position: [-1.0, 0.3, 0], magnitude: 1.77, distance: 1260, spectralType: 'O9.5Ib' },
      { name: '参宿二', nameEn: 'Alnilam', position: [0.0, 0.4, 0], magnitude: 1.69, distance: 2000, spectralType: 'B0Ia' },
      { name: '参宿三', nameEn: 'Mintaka', position: [1.0, 0.3, 0], magnitude: 2.23, distance: 1200, spectralType: 'O9.5II' },
      { name: '参宿六', nameEn: 'Saiph', position: [-1.5, -2.0, 0], magnitude: 2.06, distance: 650, spectralType: 'B0.5Ia' },
      { name: '参宿七', nameEn: 'Rigel', position: [1.8, -2.2, 0], magnitude: 0.18, distance: 860, spectralType: 'B8Ia' },
    ],
    connections: [[0, 1], [0, 2], [1, 4], [2, 3], [3, 4], [2, 5], [4, 6], [5, 6]]
  },
  {
    id: 'cassiopeia',
    name: '仙后座',
    nameEn: 'Cassiopeia',
    color: '#cc99ff',
    accentColor: '#ffccff',
    bestMonth: '12月',
    latitudeRange: '+90° ~ -20°',
    mythology: '埃塞俄比亚王后卡西奥佩娅因自恃美貌触怒海神，被钉在天上的椅子上永远旋转，五颗亮星构成W形。',
    stars: [
      { name: '王良四', nameEn: 'Schedar', position: [-2.8, -0.5, 0], magnitude: 2.24, distance: 228, spectralType: 'K0IIIa' },
      { name: '王良一', nameEn: 'Caph', position: [-1.6, 0.8, 0], magnitude: 2.28, distance: 54, spectralType: 'F2III-IV' },
      { name: '策', nameEn: 'Gamma Cas', position: [0.0, 0.0, 0], magnitude: 2.47, distance: 610, spectralType: 'B0.5IVe' },
      { name: '阁道三', nameEn: 'Ruchbah', position: [1.6, 0.9, 0], magnitude: 2.68, distance: 99, spectralType: 'A5V' },
      { name: '阁道二', nameEn: 'Segin', position: [2.8, -0.3, 0], magnitude: 3.37, distance: 440, spectralType: 'B3III' },
    ],
    connections: [[0, 1], [1, 2], [2, 3], [3, 4]]
  },
  {
    id: 'leo',
    name: '狮子座',
    nameEn: 'Leo',
    color: '#ffcc66',
    accentColor: '#ffaa44',
    bestMonth: '4月',
    latitudeRange: '+90° ~ -65°',
    mythology: '代表涅墨亚巨狮，皮坚不可摧，被赫拉克勒斯扼死后升上天界。亮星轩辕十四为其心脏，镰刀形为狮头。',
    stars: [
      { name: '轩辕十四', nameEn: 'Regulus', position: [0.0, -1.5, 0], magnitude: 1.35, distance: 79, spectralType: 'B7V' },
      { name: '轩辕十三', nameEn: 'Eta Leonis', position: [-1.2, 0.0, 0], magnitude: 3.52, distance: 1270, spectralType: 'A0Ib' },
      { name: '轩辕十二', nameEn: 'Algieba', position: [-2.0, 1.2, 0], magnitude: 2.01, distance: 130, spectralType: 'K1IIIb' },
      { name: '轩辕十一', nameEn: 'Adhafera', position: [-2.5, 2.2, 0], magnitude: 3.44, distance: 270, spectralType: 'F0III' },
      { name: '轩辕十', nameEn: 'Ras Elased', position: [-1.8, 3.0, 0], magnitude: 2.98, distance: 250, spectralType: 'B9V' },
      { name: '五帝座一', nameEn: 'Denebola', position: [3.0, 1.0, 0], magnitude: 2.14, distance: 36, spectralType: 'A3V' },
      { name: '太微右垣五', nameEn: 'Zosma', position: [1.8, 2.0, 0], magnitude: 2.56, distance: 58, spectralType: 'A4V' },
    ],
    connections: [[0, 1], [1, 2], [2, 3], [3, 4], [0, 5], [5, 6], [6, 2]]
  },
  {
    id: 'scorpius',
    name: '天蝎座',
    nameEn: 'Scorpius',
    color: '#ff6688',
    accentColor: '#ff8866',
    bestMonth: '7月',
    latitudeRange: '+40° ~ -90°',
    mythology: '毒蝎刺死了猎人奥利翁，两者被放在天空两端永不相见。红色心宿二是蝎的心脏，弯曲线条构成蝎尾。',
    stars: [
      { name: '房宿四', nameEn: 'Pi Sco', position: [-2.5, 1.8, 0], magnitude: 2.89, distance: 590, spectralType: 'B1V' },
      { name: '房宿三', nameEn: 'Delta Sco', position: [-1.8, 1.2, 0], magnitude: 2.29, distance: 400, spectralType: 'B0.3V' },
      { name: '房宿二', nameEn: 'Tau Sco', position: [-1.0, 1.5, 0], magnitude: 2.82, distance: 440, spectralType: 'B0V' },
      { name: '心宿二', nameEn: 'Antares', position: [0.0, 0.0, 0], magnitude: 0.96, distance: 550, spectralType: 'M1.5Iab' },
      { name: '尾宿五', nameEn: 'Theta Sco', position: [1.2, -0.8, 0], magnitude: 1.87, distance: 270, spectralType: 'F1II' },
      { name: '尾宿八', nameEn: 'Shaula', position: [2.2, -1.8, 0], magnitude: 1.62, distance: 700, spectralType: 'B1.5IV' },
      { name: '尾宿九', nameEn: 'Lesath', position: [2.8, -2.5, 0], magnitude: 2.69, distance: 580, spectralType: 'B2IV' },
    ],
    connections: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]
  },
  {
    id: 'cygnus',
    name: '天鹅座',
    nameEn: 'Cygnus',
    color: '#aaddff',
    accentColor: '#88ddff',
    bestMonth: '9月',
    latitudeRange: '+90° ~ -40°',
    mythology: '宙斯化身为天鹅与斯巴达王后勒达幽会，后来升上天界。五颗亮星组成著名的北十字，天津四为其尾。',
    stars: [
      { name: '天津四', nameEn: 'Deneb', position: [0.0, 3.0, 0], magnitude: 1.25, distance: 2600, spectralType: 'A2Ia' },
      { name: '天津九', nameEn: 'Sadr', position: [0.0, 1.0, 0], magnitude: 2.23, distance: 1800, spectralType: 'F8Iab' },
      { name: '辇道增七', nameEn: 'Albireo', position: [0.0, -2.5, 0], magnitude: 3.08, distance: 380, spectralType: 'K2II+B9V' },
      { name: '天津一', nameEn: 'Delta Cyg', position: [-2.0, 0.5, 0], magnitude: 2.87, distance: 165, spectralType: 'B9.5III' },
      { name: '天津二', nameEn: 'Epsilon Cyg', position: [2.0, 0.5, 0], magnitude: 2.48, distance: 72, spectralType: 'K0III' },
    ],
    connections: [[0, 1], [1, 2], [1, 3], [1, 4]]
  },
  {
    id: 'lyra',
    name: '天琴座',
    nameEn: 'Lyra',
    color: '#88ffcc',
    accentColor: '#aaffdd',
    bestMonth: '8月',
    latitudeRange: '+90° ~ -40°',
    mythology: '俄耳甫斯的七弦琴，他用琴声打动冥王救回妻子欧律狄刻，失败后琴被升上天界。织女星是天空第二亮星。',
    stars: [
      { name: '织女一', nameEn: 'Vega', position: [0.0, 2.5, 0], magnitude: 0.03, distance: 25, spectralType: 'A0V' },
      { name: '渐台二', nameEn: 'Sheliak', position: [-1.2, -0.5, 0], magnitude: 3.52, distance: 960, spectralType: 'B7II+B5V' },
      { name: '渐台三', nameEn: 'Sulafat', position: [1.2, -0.5, 0], magnitude: 3.26, distance: 620, spectralType: 'B9III' },
      { name: '渐台一', nameEn: 'Delta Lyrae', position: [0.0, -1.8, 0], magnitude: 4.30, distance: 750, spectralType: 'M4II' },
    ],
    connections: [[0, 1], [0, 2], [1, 3], [2, 3], [0, 3]]
  },
  {
    id: 'andromeda',
    name: '仙女座',
    nameEn: 'Andromeda',
    color: '#ccaaff',
    accentColor: '#ddaaff',
    bestMonth: '11月',
    latitudeRange: '+90° ~ -40°',
    mythology: '埃塞俄比亚公主安德洛墨达被献祭给海怪，被英雄珀耳修斯所救。壁宿二与飞马座相连构成方形。',
    stars: [
      { name: '壁宿二', nameEn: 'Alpheratz', position: [-2.5, 2.0, 0], magnitude: 2.06, distance: 97, spectralType: 'B8IVp' },
      { name: '奎宿九', nameEn: 'Mirach', position: [-1.0, 0.5, 0], magnitude: 2.07, distance: 200, spectralType: 'M0III' },
      { name: '奎宿五', nameEn: 'Almach', position: [0.8, -1.0, 0], magnitude: 2.10, distance: 350, spectralType: 'K3II+B8V' },
      { name: '天大将军一', nameEn: 'Alamch', position: [2.5, -2.5, 0], magnitude: 3.58, distance: 1800, spectralType: 'K4.5II' },
      { name: '奎宿六', nameEn: 'Pi And', position: [1.2, 1.2, 0], magnitude: 4.34, distance: 600, spectralType: 'B5V' },
    ],
    connections: [[0, 1], [1, 2], [2, 3], [1, 4]]
  },
];
