import type { GeometryConfig, Preset } from '@/types';

export const DEFAULT_GEOMETRIES: GeometryConfig[] = [
  {
    id: 'geo-1',
    type: 'icosahedron',
    enabled: true,
    baseSize: 0.8,
    baseColor: '#8B5CF6',
    materialMode: 'solid',
    rotationSpeed: { x: 0.5, y: 0.8, z: 0.3 },
    orbitRadius: 2.5,
    orbitSpeed: 0.3,
    orbitEccentricity: 0.3,
    orbitOffset: 0,
    frequencyBand: 'bass',
    responseSensitivity: 1.0,
    responseSmoothness: 0.5,
    zFloatAmplitude: 1.0,
    scaleMultiplier: 1.5,
    colorShiftIntensity: 0.6,
  },
  {
    id: 'geo-2',
    type: 'torus',
    enabled: true,
    baseSize: 0.6,
    baseColor: '#22D3EE',
    materialMode: 'wireframe',
    rotationSpeed: { x: 0.3, y: 0.6, z: 0.5 },
    orbitRadius: 3.0,
    orbitSpeed: 0.5,
    orbitEccentricity: 0.5,
    orbitOffset: (2 * Math.PI) / 3,
    frequencyBand: 'mid',
    responseSensitivity: 1.2,
    responseSmoothness: 0.4,
    zFloatAmplitude: 1.2,
    scaleMultiplier: 1.8,
    colorShiftIntensity: 0.8,
  },
  {
    id: 'geo-3',
    type: 'octahedron',
    enabled: true,
    baseSize: 0.7,
    baseColor: '#F472B6',
    materialMode: 'solid',
    rotationSpeed: { x: 0.7, y: 0.4, z: 0.6 },
    orbitRadius: 2.8,
    orbitSpeed: 0.4,
    orbitEccentricity: 0.4,
    orbitOffset: (4 * Math.PI) / 3,
    frequencyBand: 'treble',
    responseSensitivity: 1.5,
    responseSmoothness: 0.3,
    zFloatAmplitude: 1.5,
    scaleMultiplier: 2.0,
    colorShiftIntensity: 1.0,
  },
];

export const PRESETS: Record<string, Preset> = {
  gentle: {
    name: '柔和',
    type: 'gentle',
    geometries: [
      {
        responseSensitivity: 0.5,
        rotationSpeed: { x: 0.3, y: 0.5, z: 0.2 },
        scaleMultiplier: 1.2,
        orbitSpeed: 0.2,
        zFloatAmplitude: 0.5,
        colorShiftIntensity: 0.3,
      },
      {
        responseSensitivity: 0.6,
        rotationSpeed: { x: 0.4, y: 0.3, z: 0.4 },
        scaleMultiplier: 1.3,
        orbitSpeed: 0.25,
        zFloatAmplitude: 0.6,
        colorShiftIntensity: 0.4,
      },
      {
        responseSensitivity: 0.4,
        rotationSpeed: { x: 0.2, y: 0.6, z: 0.3 },
        scaleMultiplier: 1.1,
        orbitSpeed: 0.15,
        zFloatAmplitude: 0.4,
        colorShiftIntensity: 0.2,
      },
    ],
  },
  intense: {
    name: '激烈',
    type: 'intense',
    geometries: [
      {
        responseSensitivity: 1.8,
        rotationSpeed: { x: 2.0, y: 2.5, z: 1.5 },
        scaleMultiplier: 2.0,
        orbitSpeed: 0.8,
        zFloatAmplitude: 2.0,
        colorShiftIntensity: 1.0,
      },
      {
        responseSensitivity: 2.0,
        rotationSpeed: { x: 2.5, y: 1.8, z: 2.2 },
        scaleMultiplier: 2.2,
        orbitSpeed: 1.0,
        zFloatAmplitude: 2.5,
        colorShiftIntensity: 1.2,
      },
      {
        responseSensitivity: 1.6,
        rotationSpeed: { x: 1.5, y: 2.8, z: 1.8 },
        scaleMultiplier: 1.9,
        orbitSpeed: 0.9,
        zFloatAmplitude: 2.2,
        colorShiftIntensity: 1.1,
      },
    ],
  },
  random: {
    name: '随机',
    type: 'random',
    geometries: [
      {
        responseSensitivity: Math.random() * 1.5 + 0.5,
        rotationSpeed: {
          x: Math.random() * 2,
          y: Math.random() * 2,
          z: Math.random() * 2,
        },
        scaleMultiplier: Math.random() * 1 + 1.2,
        orbitSpeed: Math.random() * 0.6 + 0.2,
        zFloatAmplitude: Math.random() * 1.5 + 0.5,
        colorShiftIntensity: Math.random() * 0.8 + 0.2,
        orbitEccentricity: Math.random() * 0.9,
      },
      {
        responseSensitivity: Math.random() * 1.5 + 0.5,
        rotationSpeed: {
          x: Math.random() * 2,
          y: Math.random() * 2,
          z: Math.random() * 2,
        },
        scaleMultiplier: Math.random() * 1 + 1.2,
        orbitSpeed: Math.random() * 0.6 + 0.2,
        zFloatAmplitude: Math.random() * 1.5 + 0.5,
        colorShiftIntensity: Math.random() * 0.8 + 0.2,
        orbitEccentricity: Math.random() * 0.9,
      },
      {
        responseSensitivity: Math.random() * 1.5 + 0.5,
        rotationSpeed: {
          x: Math.random() * 2,
          y: Math.random() * 2,
          z: Math.random() * 2,
        },
        scaleMultiplier: Math.random() * 1 + 1.2,
        orbitSpeed: Math.random() * 0.6 + 0.2,
        zFloatAmplitude: Math.random() * 1.5 + 0.5,
        colorShiftIntensity: Math.random() * 0.8 + 0.2,
        orbitEccentricity: Math.random() * 0.9,
      },
    ],
  },
};

export const AUDIO_CONSTANTS = {
  FFT_SIZE: 256,
  SMOOTHING_TIME_CONSTANT: 0.8,
  MAX_DURATION: 60,
  BASS_RANGE: [20, 250],
  MID_RANGE: [250, 2000],
  TREBLE_RANGE: [2000, 20000],
  BEAT_THRESHOLD: 0.6,
  BEAT_HISTORY_SIZE: 43,
} as const;

export const SCENE_CONSTANTS = {
  CAMERA_DISTANCE: 8,
  CAMERA_FOV: 60,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 1000,
  MIN_POLAR_ANGLE: (15 * Math.PI) / 180,
  MAX_POLAR_ANGLE: (75 * Math.PI) / 180,
  BLOOM_THRESHOLD: 0.2,
  BLOOM_STRENGTH: 1.5,
  BLOOM_RADIUS: 0.5,
  MAX_FACES_PER_GEOMETRY: 5000,
  TARGET_FPS: 60,
  MIN_FPS: 45,
} as const;

export const COLORS = {
  BACKGROUND: '#0A0A1A',
  GRADIENT_START: '#8B5CF6',
  GRADIENT_END: '#22D3EE',
  ACCENT: '#F472B6',
  PANEL_BG: 'rgba(255, 255, 255, 0.1)',
  PANEL_BORDER: 'rgba(255, 255, 255, 0.2)',
  TEXT_PRIMARY: 'rgba(255, 255, 255, 0.9)',
  TEXT_SECONDARY: 'rgba(255, 255, 255, 0.6)',
} as const;

export const ANIMATION_CONSTANTS = {
  PARAMETER_EASE_DURATION: 0.5,
  UI_TRANSITION_DURATION: 0.2,
  MOBILE_DRAWER_DURATION: 0.3,
  MIN_SMOOTHNESS: 0.1,
  MAX_SMOOTHNESS: 2.0,
} as const;
