import { v4 as uuidv4 } from 'uuid';
import type { IBook } from '../types';

// 生成20本模拟图书数据
export const generateMockBooks = (): IBook[] => {
  const books: IBook[] = [
    {
      id: uuidv4(),
      title: '红楼梦',
      author: '曹雪芹',
      price: 68.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vintage%20book%20cover%20chinese%20literature%20novel%20red%20mansion&image_size=square_hd',
      category: 'fiction',
      genre: 'literature',
      description: '中国古典四大名著之首，以贾、史、王、薛四大家族的兴衰为背景，以富贵公子贾宝玉为视角，以贾宝玉与林黛玉、薛宝钗的爱情婚姻悲剧为主线，描绘了一批举止见识高于须眉之上的闺阁佳人的人生百态。',
    },
    {
      id: uuidv4(),
      title: '乡土中国',
      author: '费孝通',
      price: 45.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=minimalist%20book%20cover%20social%20science%20academic%20chinese%20rural&image_size=square_hd',
      category: 'non-fiction',
      genre: 'social',
      description: '费孝通先生的社会学经典著作，从乡村社区、文化传递、家族制度、道德观念、权力结构、社会规范、社会变迁等各方面分析、解剖了中国乡土社会的结构及其本色。',
    },
    {
      id: uuidv4(),
      title: '艺术的故事',
      author: '贡布里希',
      price: 128.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=artistic%20book%20cover%20art%20painting%20colorful%20history&image_size=square_hd',
      category: 'non-fiction',
      genre: 'art',
      description: '概括地叙述了从最早的洞窟绘画到当今的实验艺术的发展历程，以阐明艺术史是"各种传统不断迂回、不断改变的历史"。有关艺术的书籍中最著名、最流行的著作之一。',
    },
    {
      id: uuidv4(),
      title: '人类简史',
      author: '尤瓦尔·赫拉利',
      price: 88.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=illustrated%20book%20cover%20history%20human%20evolution%20sapiens&image_size=square_hd',
      category: 'non-fiction',
      genre: 'history',
      description: '从十万年前有生命迹象开始到21世纪资本、科技交织的人类发展史。作者用独特的视角审视人类历史，探讨我们是如何成为地球的主宰者，以及未来可能走向何方。',
    },
    {
      id: uuidv4(),
      title: '时间简史',
      author: '史蒂芬·霍金',
      price: 58.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cosmic%20book%20cover%20science%20physics%20time%20space%20universe&image_size=square_hd',
      category: 'non-fiction',
      genre: 'science',
      description: '探索时间和空间奥秘的科普经典。霍金教授用通俗易懂的语言，带领读者遨游外层空间奇异领域，对遥远星系、黑洞、夸克、"带味"粒子和"自旋"粒子、反物质、"时间箭头"等进行了深入浅出的介绍。',
    },
    {
      id: uuidv4(),
      title: '活着',
      author: '余华',
      price: 42.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vintage%20book%20cover%20chinese%20contemporary%20literature%20rural%20life&image_size=square_hd',
      category: 'fiction',
      genre: 'literature',
      description: '讲述了农村人福贵悲惨的人生遭遇。余华用冷静的笔触，刻画了福贵一生的坎坷命运，展现了生命的张力与韧性，是一部具有震撼力量的现实主义作品。',
    },
    {
      id: uuidv4(),
      title: '万历十五年',
      author: '黄仁宇',
      price: 55.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=historical%20book%20cover%20ming%20dynasty%20chinese%20history%20classic&image_size=square_hd',
      category: 'non-fiction',
      genre: 'history',
      description: '作者用近乎平淡的笔触分析一个皇朝从兴盛走向衰颓的原因，以大历史观的独特视角，通过对明朝万历年间历史人物和事件的剖析，揭示了中国封建社会晚期的结构性问题。',
    },
    {
      id: uuidv4(),
      title: '西方哲学史',
      author: '罗素',
      price: 98.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=philosophical%20book%20cover%20western%20philosophy%20thinkers%20wisdom&image_size=square_hd',
      category: 'non-fiction',
      genre: 'philosophy',
      description: '罗素的代表作，从古希腊哲学一直写到20世纪初，全面介绍了西方哲学的发展历程。作者以清晰、幽默的文笔，将深奥的哲学思想娓娓道来，是入门西方哲学的经典读物。',
    },
    {
      id: uuidv4(),
      title: '三体',
      author: '刘慈欣',
      price: 93.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=sci%20fi%20book%20cover%20three%20body%20problem%20space%20aliens%20cosmic&image_size=square_hd',
      category: 'fiction',
      genre: 'science',
      description: '中国当代科幻文学的里程碑之作。讲述了地球文明与三体文明的交流、对抗与融合，展现了宏大的宇宙观和深刻的人性思考。"黑暗森林法则"等概念影响深远。',
    },
    {
      id: uuidv4(),
      title: '乌合之众',
      author: '古斯塔夫·勒庞',
      price: 38.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=social%20psychology%20book%20cover%20crowd%20mass%20behavior&image_size=square_hd',
      category: 'non-fiction',
      genre: 'social',
      description: '社会心理学领域的经典著作，作者细致地描述了群体心理的特征，分析了人们在群聚状态下的心理、道德、行为特征，解释了群体为何会呈现出"盲目"、"冲动"、"狂热"等特点。',
    },
    {
      id: uuidv4(),
      title: '百年孤独',
      author: '加西亚·马尔克斯',
      price: 55.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=magical%20realism%20book%20cover%20latin%20american%20literature%20mystical&image_size=square_hd',
      category: 'fiction',
      genre: 'literature',
      description: '魔幻现实主义文学的代表作，描写了布恩迪亚家族七代人的传奇故事，以及加勒比海沿岸小镇马孔多的百年兴衰，反映了拉丁美洲一个世纪以来风云变幻的历史。',
    },
    {
      id: uuidv4(),
      title: '美的历程',
      author: '李泽厚',
      price: 48.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chinese%20aesthetics%20book%20cover%20art%20history%20beauty%20journey&image_size=square_hd',
      category: 'non-fiction',
      genre: 'art',
      description: '中国美学史的经典之作，从远古图腾到明清文艺，系统梳理了中国美学思想的发展脉络。作者以"天人合一"的哲学视角，阐述了中国艺术独特的审美追求和精神内涵。',
    },
    {
      id: uuidv4(),
      title: '枪炮、病菌与钢铁',
      author: '贾雷德·戴蒙德',
      price: 72.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=historical%20book%20cover%20guns%20germs%20steel%20civilization&image_size=square_hd',
      category: 'non-fiction',
      genre: 'history',
      description: '一部开创性的历史著作，作者探讨了为何欧亚大陆文明能够征服其他大陆文明的根本原因，提出了地理环境决定论的观点，挑战了种族主义和文化优越论的传统解释。',
    },
    {
      id: uuidv4(),
      title: '存在与时间',
      author: '马丁·海德格尔',
      price: 68.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=existentialism%20book%20cover%20philosophy%20being%20time%20abstract&image_size=square_hd',
      category: 'non-fiction',
      genre: 'philosophy',
      description: '海德格尔的代表作，20世纪最重要的哲学著作之一。作者通过对"此在"（Dasein）的分析，探讨了存在的意义问题，深刻影响了后世的存在主义、解释学等哲学流派。',
    },
    {
      id: uuidv4(),
      title: '围城',
      author: '钱钟书',
      price: 46.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=vintage%20chinese%20book%20cover%20literary%20satire%20fortress%20besieged&image_size=square_hd',
      category: 'fiction',
      genre: 'literature',
      description: '钱钟书的代表作，以讽刺的笔法描绘了抗战初期知识分子群像。"围城"意象已成为人生困境的经典隐喻，作品语言幽默犀利，充满了对人性的深刻洞察。',
    },
    {
      id: uuidv4(),
      title: '思考，快与慢',
      author: '丹尼尔·卡尼曼',
      price: 69.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=psychology%20book%20cover%20thinking%20fast%20slow%20brain%20cognitive&image_size=square_hd',
      category: 'non-fiction',
      genre: 'social',
      description: '诺贝尔经济学奖得主卡尼曼的代表作，揭示了人类思维的两种模式：快思考与慢思考，以及它们如何影响我们的决策。书中充满了对人类认知偏差的精彩洞见。',
    },
    {
      id: uuidv4(),
      title: '艺术哲学',
      author: '丹纳',
      price: 85.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=art%20philosophy%20book%20cover%20aesthetics%20renaissance%20classic&image_size=square_hd',
      category: 'non-fiction',
      genre: 'art',
      description: '法国文艺理论家丹纳的代表作，作者从种族、环境、时代三个维度出发，分析了艺术作品产生的社会历史条件，提出了"艺术的目的是表现事物的主要特征"的重要观点。',
    },
    {
      id: uuidv4(),
      title: '明朝那些事儿',
      author: '当年明月',
      price: 196.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chinese%20history%20book%20cover%20ming%20dynasty%20humorous%20modern&image_size=square_hd',
      category: 'non-fiction',
      genre: 'history',
      description: '以史料为基础，以年代和具体人物为主线，用小说的笔法对明朝三百年历史进行了全新解读。语言风趣幽默，人物形象立体，让严肃的历史变得生动有趣。',
    },
    {
      id: uuidv4(),
      title: '老子',
      author: '李耳',
      price: 32.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ancient%20chinese%20philosophy%20book%20cover%20tao%20te%20ching%20minimalist&image_size=square_hd',
      category: 'non-fiction',
      genre: 'philosophy',
      description: '又称《道德经》，道家学派的经典著作，仅五千言，却蕴含了深邃的哲学智慧。"道可道，非常道"、"上善若水"、"无为而无不为"等思想对中国文化影响深远。',
    },
    {
      id: uuidv4(),
      title: '平凡的世界',
      author: '路遥',
      price: 128.00,
      cover: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=chinese%20contemporary%20literature%20book%20cover%20rural%20youth%20ordinary%20world&image_size=square_hd',
      category: 'fiction',
      genre: 'literature',
      description: '茅盾文学奖获奖作品，全景式地表现了中国当代城乡社会生活，通过复杂的矛盾纠葛，以孙少安、孙少平兄弟为中心，刻画了当时社会各阶层众多普通人的形象。',
    },
  ];

  return books;
};

// 导出生成的图书数据
export const mockBooks = generateMockBooks();
