import type { CanvasElement } from '@/types';
import { getMaterialById } from '@/data/materialData';

/**
 * 将画布元素序列化为标准 SVG 字符串
 *
 * ==================== 变换序列化说明 ====================
 *
 * SVG 中 transform 的执行顺序是 **从右到左**（即最右先应用），
 * 我们需要：先以(50,50)为原点缩放旋转 → 平移到(x,y)
 * 写法：translate(x,y)  rotate(θ)  scale(s)
 *       └──最左(最后应用)─┘        └最右(最先应用)┘
 * 等价数学变换：T * R * S * v
 *
 * 另外为素材增加 translate(-50, -50)，使素材局部坐标系中心对齐到 (0,0)，
 * 保证缩放和旋转都围绕元素几何中心进行（与 CanvasArea 渲染一致）
 */
export const generateSVGString = (
  elements: CanvasElement[],
  canvasWidth: number = 1200,
  canvasHeight: number = 800
): string => {
  const elementsContent = elements
    .map((el) => {
      const material = getMaterialById(el.materialId);
      if (!material) return '';

      return `  <!-- Element: ${material.name} [${el.id}] -->
  <g id="el-${el.id.replace(/[^a-zA-Z0-9_-]/g, '_')}"
     transform="translate(${el.x.toFixed(2)}, ${el.y.toFixed(2)}) rotate(${el.rotation}) scale(${el.scale.toFixed(3)})">
    <g transform="translate(-50, -50)">
      <path d="${material.svgPath}"
            fill="${el.color}"
            stroke="${el.color}"
            stroke-width="1.5"
            stroke-linejoin="round"
            stroke-linecap="round"
            vector-effect="non-scaling-stroke"/>
    </g>
  </g>`;
    })
    .filter(Boolean)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by Collage Workshop · ${new Date().toISOString()} -->
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 ${canvasWidth} ${canvasHeight}"
     width="${canvasWidth}"
     height="${canvasHeight}"
     preserveAspectRatio="xMidYMid meet">
  <rect id="canvas-background"
        x="0" y="0"
        width="${canvasWidth}" height="${canvasHeight}"
        fill="#ffffff"/>
  <g id="collage-layer" transform="translate(0,0)">
${elementsContent}
  </g>
</svg>`;
};

/**
 * 触发 SVG 下载
 * - 使用 Blob + createObjectURL 创建临时下载链接
 * - 默认文件名：Collage_ISO时间戳.svg
 * - 文件名中的冒号和点替换为横杠，避免 Windows 不兼容
 */
export const downloadSVG = (svgString: string, filename?: string): void => {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const finalFilename = filename || `Collage_${timestamp}.svg`;

  const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = finalFilename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 100);
};

/** 网格吸附：把坐标吸附到最近的 gridSize 整数倍网格点 */
export const snapToGrid = (value: number, gridSize: number = 20): number => {
  return Math.round(value / gridSize) * gridSize;
};

/**
 * 对齐吸附：当与其他元素中心距离在 threshold 像素内时自动吸附对齐
 * - 同时检测：同 x / 同 y / 对齐右侧 / 对齐底部
 * - 返回 snapped=true 时可用于UI显示"已对齐"提示
 */
export const snapToNeighbor = (
  x: number,
  y: number,
  elements: CanvasElement[],
  currentId: string,
  threshold: number = 15
): { x: number; y: number; snapped: boolean } => {
  let snappedX = x;
  let snappedY = y;
  let snapped = false;
  const ELEMENT_SIZE = 100;

  for (const el of elements) {
    if (el.id === currentId) continue;

    // 中心对齐 x
    if (Math.abs(el.x - x) < threshold) {
      snappedX = el.x;
      snapped = true;
    }
    // 中心对齐 y
    if (Math.abs(el.y - y) < threshold) {
      snappedY = el.y;
      snapped = true;
    }
    // 与其他元素右边缘对齐
    if (Math.abs(el.x + ELEMENT_SIZE - x) < threshold) {
      snappedX = el.x + ELEMENT_SIZE;
      snapped = true;
    }
    // 与其他元素下边缘对齐
    if (Math.abs(el.y + ELEMENT_SIZE - y) < threshold) {
      snappedY = el.y + ELEMENT_SIZE;
      snapped = true;
    }
    // 与其他元素左边缘对齐
    if (Math.abs(el.x - ELEMENT_SIZE - x) < threshold) {
      snappedX = el.x - ELEMENT_SIZE;
      snapped = true;
    }
    // 与其他元素上边缘对齐
    if (Math.abs(el.y - ELEMENT_SIZE - y) < threshold) {
      snappedY = el.y - ELEMENT_SIZE;
      snapped = true;
    }
  }

  return { x: snappedX, y: snappedY, snapped };
};

/** 坐标夹紧：把 value 限制在 [min+padding, max-padding] 区间 */
export const clampToBounds = (
  value: number,
  min: number,
  max: number,
  padding: number = 0
): number => {
  return Math.max(min + padding, Math.min(max - padding, value));
};

/** 画布坐标 → 屏幕坐标（应用平移缩放）*/
export const canvasToScreen = (
  canvasX: number,
  canvasY: number,
  offsetX: number,
  offsetY: number,
  zoom: number
): { x: number; y: number } => {
  return {
    x: canvasX * zoom + offsetX,
    y: canvasY * zoom + offsetY,
  };
};

/** 屏幕坐标 → 画布坐标（逆向平移缩放，用于把鼠标点换算为画布逻辑点）*/
export const screenToCanvas = (
  screenX: number,
  screenY: number,
  offsetX: number,
  offsetY: number,
  zoom: number
): { x: number; y: number } => {
  return {
    x: (screenX - offsetX) / zoom,
    y: (screenY - offsetY) / zoom,
  };
};
