export type ElementType = 'fire' | 'water' | 'wind' | 'earth' | 'light' | 'dark' | 'composite';

export type RarityType = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface Card {
  id: string;
  name: string;
  element: ElementType;
  rarity: RarityType;
  attack: number;
  defense: number;
  description: string;
  lore: string;
  formula?: [string, string];
}

export const ALL_CARDS: Card[] = [
  {
    id: 'fire',
    name: '火',
    element: 'fire',
    rarity: 'common',
    attack: 10,
    defense: 5,
    description: '最原始的元素之力，燃烧一切',
    lore: '自太初之始，火焰便在世界中心燃烧，温暖万物，也焚毁万物。',
  },
  {
    id: 'water',
    name: '水',
    element: 'water',
    rarity: 'common',
    attack: 8,
    defense: 8,
    description: '流动的元素，以柔克刚',
    lore: '水是万物的起源，它在山川间流淌，赋予大地生机。',
  },
  {
    id: 'wind',
    name: '风',
    element: 'wind',
    rarity: 'common',
    attack: 12,
    defense: 3,
    description: '自由的元素，无拘无束',
    lore: '风从不为谁停留，它掠过天际，带来远方的消息。',
  },
  {
    id: 'earth',
    name: '土',
    element: 'earth',
    rarity: 'common',
    attack: 5,
    defense: 12,
    description: '坚固的元素，守护大地',
    lore: '大地沉默而坚定，承载着一切生灵的重量。',
  },
  {
    id: 'light',
    name: '光',
    element: 'light',
    rarity: 'common',
    attack: 15,
    defense: 2,
    description: '神圣的元素，驱散黑暗',
    lore: '光明来自星辰，它是希望的化身，永远照耀前方。',
  },
  {
    id: 'dark',
    name: '暗',
    element: 'dark',
    rarity: 'common',
    attack: 14,
    defense: 4,
    description: '神秘的元素，吞噬一切',
    lore: '暗影并非邪恶，它只是光的另一面，在深渊中沉默等待。',
  },
  {
    id: 'embers',
    name: '余烬',
    element: 'fire',
    rarity: 'common',
    attack: 8,
    defense: 6,
    description: '燃烧后的残火，仍有余温',
    lore: '火焰熄灭之后，余烬依然温热，等待再次燃烧的时机。',
  },
  {
    id: 'breeze',
    name: '微风',
    element: 'wind',
    rarity: 'common',
    attack: 10,
    defense: 5,
    description: '轻柔的风，拂过面颊',
    lore: '清晨的微风带来花香，也带来新一天的希望。',
  },
  {
    id: 'pebble',
    name: '砾石',
    element: 'earth',
    rarity: 'common',
    attack: 6,
    defense: 14,
    description: '坚硬的小石子，坚不可摧',
    lore: '每一颗砾石都经历了岁月的打磨，虽小却坚韧。',
  },
  {
    id: 'dewdrop',
    name: '露珠',
    element: 'water',
    rarity: 'common',
    attack: 7,
    defense: 9,
    description: '晨露凝结，晶莹剔透',
    lore: '清晨的露珠在叶尖闪烁，折射出七彩的光芒。',
  },
  {
    id: 'steam',
    name: '蒸汽',
    element: 'composite',
    rarity: 'uncommon',
    attack: 15,
    defense: 12,
    formula: ['fire', 'water'],
    description: '水火交融，蒸汽升腾',
    lore: '当烈焰遇上深水，蒸汽弥漫于天地之间，模糊了视野。',
  },
  {
    id: 'mud',
    name: '泥沼',
    element: 'composite',
    rarity: 'uncommon',
    attack: 12,
    defense: 16,
    formula: ['water', 'earth'],
    description: '水土混合，困敌于泥',
    lore: '泥沼吞噬一切莽撞者，唯有耐心者方能穿越。',
  },
  {
    id: 'dust_storm',
    name: '沙尘',
    element: 'composite',
    rarity: 'uncommon',
    attack: 18,
    defense: 10,
    formula: ['wind', 'earth'],
    description: '狂风卷沙，遮天蔽日',
    lore: '沙尘暴来临之时，天地一色，万物皆被覆盖。',
  },
  {
    id: 'smoke',
    name: '烟雾',
    element: 'composite',
    rarity: 'uncommon',
    attack: 16,
    defense: 11,
    formula: ['fire', 'wind'],
    description: '火借风势，烟迷四方',
    lore: '烟雾弥漫，遮蔽视线，使人迷失方向。',
  },
  {
    id: 'obsidian',
    name: '黑曜石',
    element: 'composite',
    rarity: 'uncommon',
    attack: 14,
    defense: 18,
    formula: ['fire', 'earth'],
    description: '熔岩冷却，黑石如镜',
    lore: '火山熔岩遇水急速冷却，形成漆黑如镜的黑曜石。',
  },
  {
    id: 'mist',
    name: '薄雾',
    element: 'composite',
    rarity: 'uncommon',
    attack: 11,
    defense: 15,
    formula: ['water', 'wind'],
    description: '水汽弥漫，朦胧似幻',
    lore: '山间的薄雾如梦似幻，藏着无数仙境的传说。',
  },
  {
    id: 'dusk',
    name: '黄昏',
    element: 'composite',
    rarity: 'uncommon',
    attack: 17,
    defense: 9,
    formula: ['light', 'dark'],
    description: '光暗交替，暮色四合',
    lore: '白昼与黑夜的交界，是最神秘也最美丽的时刻。',
  },
  {
    id: 'morning_glow',
    name: '晨光',
    element: 'composite',
    rarity: 'uncommon',
    attack: 19,
    defense: 8,
    formula: ['light', 'wind'],
    description: '晨风携光，唤醒大地',
    lore: '黎明第一缕光穿过晨风，唤醒沉睡的世界。',
  },
  {
    id: 'shadow_mist',
    name: '暗影迷雾',
    element: 'composite',
    rarity: 'uncommon',
    attack: 16,
    defense: 13,
    formula: ['dark', 'water'],
    description: '暗影化雾，悄然无声',
    lore: '黑暗与水汽交织，化为无声的暗影迷雾。',
  },
  {
    id: 'flamestorm',
    name: '烈焰风暴',
    element: 'composite',
    rarity: 'rare',
    attack: 25,
    defense: 8,
    formula: ['fire', 'wind'],
    description: '火焰借风势，燎原万里',
    lore: '当火遇风，烈焰化为风暴，焚烧沿途一切。',
  },
  {
    id: 'lava',
    name: '熔岩',
    element: 'composite',
    rarity: 'rare',
    attack: 20,
    defense: 18,
    formula: ['fire', 'earth'],
    description: '熔岩奔流，所过皆灰',
    lore: '大地深处的火焰突破地壳，化为赤红的熔岩之河。',
  },
  {
    id: 'storm',
    name: '暴风',
    element: 'composite',
    rarity: 'rare',
    attack: 22,
    defense: 14,
    formula: ['water', 'wind'],
    description: '风雨交加，雷霆万钧',
    lore: '水汽升腾至天穹，化为暴风骤雨，雷鸣电闪。',
  },
  {
    id: 'abyss',
    name: '深渊',
    element: 'composite',
    rarity: 'rare',
    attack: 26,
    defense: 12,
    formula: ['water', 'dark'],
    description: '暗流涌动，深不可测',
    lore: '深渊之下，是光无法触及的永恒寂静。',
  },
  {
    id: 'crystal',
    name: '水晶',
    element: 'composite',
    rarity: 'rare',
    attack: 16,
    defense: 28,
    formula: ['earth', 'light'],
    description: '地之精华，光之凝结',
    lore: '大地中蕴含的光明凝结为水晶，映射出七彩光芒。',
  },
  {
    id: 'necrosis',
    name: '腐朽',
    element: 'composite',
    rarity: 'rare',
    attack: 24,
    defense: 20,
    formula: ['earth', 'dark'],
    description: '大地侵蚀，万物凋零',
    lore: '暗影侵蚀大地，曾经丰饶的土地化为荒芜。',
  },
  {
    id: 'mirror_flame',
    name: '镜焰',
    element: 'composite',
    rarity: 'rare',
    attack: 23,
    defense: 15,
    formula: ['fire', 'light'],
    description: '火焰映光，双倍炽烈',
    lore: '光明映照下的火焰更加炽烈，宛如镜中燃烧。',
  },
  {
    id: 'shadow_fire',
    name: '暗影火',
    element: 'composite',
    rarity: 'rare',
    attack: 27,
    defense: 10,
    formula: ['fire', 'dark'],
    description: '黑暗之火，寒炎刺骨',
    lore: '不散发光明的火焰，带来的不是温暖而是彻骨寒意。',
  },
  {
    id: 'solar_flare',
    name: '日冕',
    element: 'composite',
    rarity: 'epic',
    attack: 35,
    defense: 10,
    formula: ['fire', 'light'],
    description: '烈阳之冠，光芒万丈',
    lore: '太阳最炽烈的爆发，将火焰与光明融为一体。',
  },
  {
    id: 'hellfire',
    name: '炼狱之火',
    element: 'composite',
    rarity: 'epic',
    attack: 32,
    defense: 15,
    formula: ['fire', 'dark'],
    description: '地狱之火，焚尽灵魂',
    lore: '黑暗中燃起的并非凡火，它焚烧的不是肉体，而是灵魂。',
  },
  {
    id: 'holy_water',
    name: '圣水',
    element: 'composite',
    rarity: 'epic',
    attack: 28,
    defense: 22,
    formula: ['water', 'light'],
    description: '圣洁之水，净化邪祟',
    lore: '光明祝福的清泉，洗去一切污秽与诅咒。',
  },
  {
    id: 'aurora',
    name: '极光',
    element: 'composite',
    rarity: 'epic',
    attack: 30,
    defense: 16,
    formula: ['wind', 'light'],
    description: '风中之光，绚丽天幕',
    lore: '高天之上的风与光交织，化为最梦幻的天幕。',
  },
  {
    id: 'void',
    name: '虚空',
    element: 'composite',
    rarity: 'epic',
    attack: 34,
    defense: 8,
    formula: ['wind', 'dark'],
    description: '虚无之风，万物归零',
    lore: '当风归于黑暗，连空间本身也被撕裂为虚无。',
  },
  {
    id: 'petrified_forest',
    name: '石化森林',
    element: 'composite',
    rarity: 'epic',
    attack: 18,
    defense: 35,
    formula: ['earth', 'wind'],
    description: '风化石林，千古屹立',
    lore: '千万年的风沙雕琢，将森林化为永恒的石像。',
  },
  {
    id: 'deep_sea',
    name: '深海',
    element: 'composite',
    rarity: 'epic',
    attack: 26,
    defense: 24,
    formula: ['water', 'earth'],
    description: '幽深海底，压力万钧',
    lore: '深海是地球上最后的秘境，那里藏着无数未知的生命。',
  },
  {
    id: 'chaos',
    name: '混沌',
    element: 'composite',
    rarity: 'legendary',
    attack: 45,
    defense: 25,
    formula: ['light', 'dark'],
    description: '光暗交织，混沌初开',
    lore: '当光明与黑暗彻底交融，混沌便诞生了。混沌是万物的起源，也是万物的归宿。',
  },
  {
    id: 'eclipse',
    name: '日蚀',
    element: 'composite',
    rarity: 'legendary',
    attack: 50,
    defense: 30,
    formula: ['light', 'dark'],
    description: '光暗交蚀，天地变色',
    lore: '光明与黑暗的终极交汇，在这一刻，太阳被吞噬，世界陷入永恒的一瞬。',
  },
  {
    id: 'star_forge',
    name: '星铸',
    element: 'composite',
    rarity: 'legendary',
    attack: 42,
    defense: 38,
    formula: ['fire', 'earth'],
    description: '星辰熔炉，锻造万物',
    lore: '在恒星的核心，烈火与重压锻造出宇宙中最坚硬的物质。',
  },
  {
    id: 'world_tree',
    name: '世界树',
    element: 'composite',
    rarity: 'legendary',
    attack: 30,
    defense: 50,
    formula: ['water', 'earth'],
    description: '生命之树，连接天地',
    lore: '世界树扎根于大地深处，树冠直插云霄，是连接天地的神圣存在。',
  },
  {
    id: 'phoenix',
    name: '凤凰',
    element: 'composite',
    rarity: 'legendary',
    attack: 48,
    defense: 28,
    formula: ['fire', 'wind'],
    description: '浴火重生，不死神鸟',
    lore: '凤凰生于火焰，每次死亡都会在烈焰中重生，象征着永恒的轮回。',
  },
  {
    id: 'leviathan',
    name: '利维坦',
    element: 'composite',
    rarity: 'legendary',
    attack: 40,
    defense: 42,
    formula: ['water', 'dark'],
    description: '深海巨兽，诸水之王',
    lore: '利维坦是深海的统治者，它的身躯庞大到可以环绕大陆一周。',
  },
];

export function generateInitialCardList(): Card[] {
  return JSON.parse(JSON.stringify(ALL_CARDS));
}

export function getCardById(id: string): Card | undefined {
  return ALL_CARDS.find((card) => card.id === id);
}

export const ELEMENT_COLORS: Record<string, string> = {
  fire: '#ff4d2e',
  water: '#2e9bff',
  wind: '#7ee8fa',
  earth: '#c8a24e',
  light: '#ffe066',
  dark: '#8b5cf6',
};

export const RARITY_COLORS: Record<string, string> = {
  common: '#9ca3af',
  uncommon: '#22c55e',
  rare: '#3b82f6',
  epic: '#a855f7',
  legendary: '#f59e0b',
};
