import type { Vertex, PolygonStyles } from './types';

export function exportSVG(
  vertices: Vertex[],
  styles: PolygonStyles,
  width: number,
  height: number
): string {
  const parts: string[] = [];

  parts.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  parts.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`);
  parts.push(`  <!-- Generated by Polygon Editor -->`);
  parts.push(``);

  if (vertices.length >= 3) {
    const points = vertices
      .filter(v => !v.isDeleting)
      .map(v => `${v.x.toFixed(2)},${v.y.toFixed(2)}`)
      .join(' ');

    parts.push(`  <!-- Polygon Shape -->`);
    parts.push(`  <polygon`);
    parts.push(`    points="${points}"`);
    parts.push(`    fill="${styles.fillColor}"`);
    parts.push(`    stroke="${styles.strokeColor}"`);
    parts.push(`    stroke-width="${styles.strokeWidth}"`);
    parts.push(`  />`);
    parts.push(``);
  }

  parts.push(`  <!-- Vertices -->`);
  vertices
    .filter(v => !v.isDeleting)
    .forEach((v, i) => {
      parts.push(`  <circle`);
      parts.push(`    id="vertex-${i}"`);
      parts.push(`    cx="${v.x.toFixed(2)}"`);
      parts.push(`    cy="${v.y.toFixed(2)}"`);
      parts.push(`    r="${styles.vertexRadius}"`);
      parts.push(`    fill="${v.color}"`);
      parts.push(`    stroke="${v.strokeColor}"`);
      parts.push(`    stroke-width="${styles.vertexStrokeWidth}"`);
      parts.push(`  />`);
    });

  parts.push(``);
  parts.push(`</svg>`);

  return parts.join('\n');
}
