import { toSvg, toPng, toBlob } from 'html-to-image';
import { saveAs } from 'file-saver';
import jsPDF from 'jspdf';
import type { ReportContent } from './types';

export async function exportSVG(canvasEl: HTMLElement): Promise<void> {
  if (!canvasEl) return;
  const timestamp = Date.now();
  try {
    const dataUrl = await toSvg(canvasEl, {
      backgroundColor: '#F0F2F5',
      pixelRatio: 2,
    });
    const byteString = atob(dataUrl.split(',')[1]);
    const mimeString = dataUrl.split(',')[0].split(':')[1].split(';')[0];
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {
      ia[i] = byteString.charCodeAt(i);
    }
    const blob = new Blob([ab], { type: mimeString });
    saveAs(blob, `sitebubble-${timestamp}.svg`);
  } catch (err) {
    console.error('导出SVG失败:', err);
  }
}

function renderReportToCanvas(
  content: ReportContent,
  width: number,
  height: number
): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d')!;
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, width, height);

  const padding = 20;
  const sectionGap = 28;
  let y = padding;

  const drawSection = (title: string, text: string, startY: number): number => {
    ctx.fillStyle = '#1A365D';
    ctx.font = 'bold 16px "PingFang SC", "Microsoft YaHei", sans-serif';
    ctx.fillText(title, padding, startY);
    startY += 24;

    ctx.fillStyle = '#374151';
    ctx.font = '13px "PingFang SC", "Microsoft YaHei", sans-serif';
    const maxWidth = width - padding * 2;
    const lineHeight = 20;
    const chars = text.split('');
    let line = '';
    for (let i = 0; i < chars.length; i++) {
      const test = line + chars[i];
      if (ctx.measureText(test).width > maxWidth && line.length > 0) {
        ctx.fillText(line, padding, startY);
        line = chars[i];
        startY += lineHeight;
      } else {
        line = test;
      }
    }
    if (line) {
      ctx.fillText(line, padding, startY);
      startY += lineHeight;
    }
    return startY + sectionGap - lineHeight;
  };

  y = drawSection('一、功能分区（Zoning）', content.zoning, y);
  y = drawSection('二、动线分析（Circulation）', content.circulation, y);
  drawSection('三、生态评估（Ecology）', content.ecology, y);

  ctx.strokeStyle = '#1A365D';
  ctx.lineWidth = 2;
  ctx.strokeRect(1, 1, width - 2, height - 2);

  return canvas;
}

export async function exportPDF(
  canvasEl: HTMLElement,
  reportContent: ReportContent
): Promise<void> {
  if (!canvasEl) return;
  const timestamp = Date.now();

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageW = 297;
  const pageH = 210;
  const margin = 10;
  const leftW = pageW * 0.6 - margin;
  const rightW = pageW * 0.4 - margin * 1.5;
  const contentH = pageH - margin * 2;

  try {
    doc.setFont('helvetica');
    doc.setFontSize(10);
    doc.setTextColor(26, 54, 93);
    doc.text('Site Bubble Diagram Report', margin, 7);
    doc.text(new Date().toLocaleString('zh-CN'), pageW - margin, 7, { align: 'right' });

    doc.setDrawColor(218, 221, 225);
    doc.setLineWidth(0.3);
    doc.line(margin, 10, pageW - margin, 10);

    const canvasDataUrl = await toPng(canvasEl, {
      backgroundColor: '#F0F2F5',
      pixelRatio: 2,
    });
    doc.addImage(
      canvasDataUrl,
      'PNG',
      margin,
      margin + 6,
      leftW,
      contentH - 6,
      undefined,
      'FAST'
    );

    const reportCanvasWidth = 800;
    const reportCanvasHeight = Math.round(
      (reportCanvasWidth * (contentH - 6)) / rightW
    );
    const reportCanvas = renderReportToCanvas(
      reportContent,
      reportCanvasWidth,
      reportCanvasHeight
    );
    const reportDataUrl = reportCanvas.toDataURL('image/png');
    doc.addImage(
      reportDataUrl,
      'PNG',
      pageW * 0.6 + margin / 2,
      margin + 6,
      rightW,
      contentH - 6,
      undefined,
      'FAST'
    );

    doc.setLineWidth(0.5);
    doc.setDrawColor(26, 54, 93);
    doc.rect(margin, margin + 6, leftW, contentH - 6);
    doc.rect(pageW * 0.6 + margin / 2, margin + 6, rightW, contentH - 6);

    doc.setFontSize(8);
    doc.setTextColor(108, 117, 125);
    doc.text(
      `Generated by SiteBubble Designer | Page 1 of 1`,
      pageW / 2,
      pageH - 4,
      { align: 'center' }
    );

    const pdfBlob = doc.output('blob');
    saveAs(pdfBlob, `sitebubble-report-${timestamp}.pdf`);
  } catch (err) {
    console.error('导出PDF失败:', err);
  }
}
