import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import axios from 'axios';

export type PlantStatus = 'seedling' | 'growing' | 'flowering' | 'fruiting' | 'withered';
export type TaskType = 'sowing' | 'watering' | 'fertilizing' | 'pruning' | 'repotting';

export interface Plant {
  id: string;
  name: string;
  variety: string;
  plantDate: string;
  expectedBloomDate?: string;
  expectedHarvestDate?: string;
  status: PlantStatus;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  plantId?: string;
  type: TaskType;
  date: string;
  completed: boolean;
  completedAt?: string;
  postponedCount: number;
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface Photo {
  id: string;
  plantId: string;
  url: string;
  note?: string;
  createdAt: string;
}

interface PlantStore {
  plants: Plant[];
  tasks: Task[];
  photos: Record<string, Photo[]>;
  loading: boolean;

  fetchPlants: () => Promise<void>;
  addPlant: (data: Partial<Plant>) => Promise<Plant | null>;
  updatePlant: (id: string, data: Partial<Plant>) => Promise<Plant | null>;
  deletePlant: (id: string) => Promise<void>;

  fetchTasks: () => Promise<void>;
  addTask: (data: Partial<Task>) => Promise<Task | null>;
  updateTask: (id: string, data: Partial<Task>) => Promise<Task | null>;
  deleteTask: (id: string) => Promise<void>;
  completeTask: (id: string) => Promise<void>;
  postponeTask: (id: string) => Promise<void>;

  fetchPhotos: (plantId: string) => Promise<void>;
  addPhoto: (plantId: string, file: File, note?: string) => Promise<Photo | null>;
  deletePhoto: (id: string) => Promise<void>;
}

export const usePlantStore = create<PlantStore>()(
  persist(
    (set, get) => ({
      plants: [],
      tasks: [],
      photos: {},
      loading: false,

      fetchPlants: async () => {
        try {
          const res = await axios.get('/api/plants');
          set({ plants: res.data });
        } catch (e) {
          console.error('Failed to fetch plants', e);
        }
      },

      addPlant: async (data) => {
        try {
          const res = await axios.post('/api/plants', data);
          set({ plants: [res.data, ...get().plants] });
          return res.data;
        } catch (e) {
          console.error('Failed to add plant', e);
          return null;
        }
      },

      updatePlant: async (id, data) => {
        try {
          const res = await axios.put(`/api/plants/${id}`, data);
          set({ plants: get().plants.map(p => (p.id === id ? res.data : p)) });
          return res.data;
        } catch (e) {
          console.error('Failed to update plant', e);
          return null;
        }
      },

      deletePlant: async (id) => {
        try {
          await axios.delete(`/api/plants/${id}`);
          set({ plants: get().plants.filter(p => p.id !== id) });
        } catch (e) {
          console.error('Failed to delete plant', e);
        }
      },

      fetchTasks: async () => {
        try {
          const res = await axios.get('/api/tasks');
          set({ tasks: res.data });
        } catch (e) {
          console.error('Failed to fetch tasks', e);
        }
      },

      addTask: async (data) => {
        try {
          const res = await axios.post('/api/tasks', data);
          set({ tasks: [...get().tasks, res.data].sort((a, b) => a.date.localeCompare(b.date)) });
          return res.data;
        } catch (e) {
          console.error('Failed to add task', e);
          return null;
        }
      },

      updateTask: async (id, data) => {
        try {
          const res = await axios.put(`/api/tasks/${id}`, data);
          set({ tasks: get().tasks.map(t => (t.id === id ? res.data : t)) });
          return res.data;
        } catch (e) {
          console.error('Failed to update task', e);
          return null;
        }
      },

      deleteTask: async (id) => {
        try {
          await axios.delete(`/api/tasks/${id}`);
          set({ tasks: get().tasks.filter(t => t.id !== id) });
        } catch (e) {
          console.error('Failed to delete task', e);
        }
      },

      completeTask: async (id) => {
        try {
          const res = await axios.post(`/api/tasks/${id}/complete`);
          set({ tasks: get().tasks.map(t => (t.id === id ? res.data : t)) });
        } catch (e) {
          console.error('Failed to complete task', e);
        }
      },

      postponeTask: async (id) => {
        try {
          const res = await axios.post(`/api/tasks/${id}/postpone`);
          set({ tasks: get().tasks.map(t => (t.id === id ? res.data : t)) });
        } catch (e) {
          console.error('Failed to postpone task', e);
        }
      },

      fetchPhotos: async (plantId) => {
        try {
          const res = await axios.get(`/api/plants/${plantId}/photos`);
          set({ photos: { ...get().photos, [plantId]: res.data } });
        } catch (e) {
          console.error('Failed to fetch photos', e);
        }
      },

      addPhoto: async (plantId, file, note) => {
        try {
          const formData = new FormData();
          formData.append('photo', file);
          if (note) formData.append('note', note);
          const res = await axios.post(`/api/plants/${plantId}/photos`, formData, {
            headers: { 'Content-Type': 'multipart/form-data' },
          });
          const current = get().photos[plantId] || [];
          set({ photos: { ...get().photos, [plantId]: [res.data, ...current] } });
          return res.data;
        } catch (e) {
          console.error('Failed to upload photo', e);
          return null;
        }
      },

      deletePhoto: async (id) => {
        try {
          await axios.delete(`/api/photos/${id}`);
          const photos = { ...get().photos };
          Object.keys(photos).forEach(plantId => {
            photos[plantId] = photos[plantId].filter(p => p.id !== id);
          });
          set({ photos });
        } catch (e) {
          console.error('Failed to delete photo', e);
        }
      },
    }),
    {
      name: 'garden-store',
      partialize: state => ({ plants: state.plants, tasks: state.tasks, photos: state.photos }),
    }
  )
);

export const statusColors: Record<PlantStatus, string> = {
  seedling: '#A8E6CF',
  growing: '#FFB347',
  flowering: '#FF6B6B',
  fruiting: '#78C2AD',
  withered: '#8B4513',
};

export const statusLabels: Record<PlantStatus, string> = {
  seedling: '幼苗',
  growing: '生长',
  flowering: '开花',
  fruiting: '结果',
  withered: '枯萎',
};

export const taskColors: Record<TaskType, string> = {
  sowing: '#FFD93D',
  watering: '#6C5CE7',
  fertilizing: '#3BCEAC',
  pruning: '#FF6B6B',
  repotting: '#A29BFE',
};

export const taskLabels: Record<TaskType, string> = {
  sowing: '播种',
  watering: '浇水',
  fertilizing: '施肥',
  pruning: '修剪',
  repotting: '换盆',
};
