import type { Template, ThemePalette } from './types';
import { v4 as uuidv4 } from 'uuid';

export const DEFAULT_THEMES: ThemePalette[] = [
  {
    id: 'theme-business',
    name: '商务蓝',
    colors: ['#2b5797', '#00a1d6', '#6c63ff', '#f50057', '#ffb300'],
  },
  {
    id: 'theme-nature',
    name: '自然绿',
    colors: ['#4caf50', '#8bc34a', '#cddc39', '#ffeb3b', '#ff9800'],
  },
  {
    id: 'theme-warm',
    name: '暖色调',
    colors: ['#e91e63', '#ff5722', '#ff9800', '#ffc107', '#795548'],
  },
  {
    id: 'theme-cool',
    name: '冷色调',
    colors: ['#00bcd4', '#03a9f4', '#2196f3', '#3f51b5', '#673ab7'],
  },
  {
    id: 'theme-dark',
    name: '深色系',
    colors: ['#212121', '#424242', '#616161', '#757575', '#9e9e9e'],
  },
];

function newId(): string {
  return uuidv4();
}

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'template-two-column',
    name: '双栏对比',
    category: '对比图',
    thumbnail: '',
    isTwoColumn: true,
    columnGap: 40,
    components: [
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 80,
        width: 500,
        height: 60,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        columnRole: undefined,
        style: {
          fontSize: 32,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '产品特性对比',
          textAlign: 'center',
        },
      },
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 180,
        width: 500,
        height: 490,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        columnRole: 'left',
        style: {
          fillColor: '#e8f0fe',
          fillColorIndex: 1,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 2,
          fontSize: 16,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '方案 A\n\n• 特性 1\n• 特性 2\n• 特性 3\n• 特性 4\n• 特性 5\n\n优势：成本低\n劣势：功能有限',
          textAlign: 'left',
        },
      },
      {
        id: newId(),
        type: 'text',
        x: 620,
        y: 180,
        width: 500,
        height: 490,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        columnRole: 'right',
        style: {
          fillColor: '#fff3e0',
          fillColorIndex: 4,
          strokeColor: '#ff9800',
          strokeColorIndex: 4,
          strokeWidth: 2,
          fontSize: 16,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '方案 B\n\n• 特性 1\n• 特性 2\n• 特性 3\n• 特性 4\n• 特性 5\n• 特性 6\n• 特性 7\n\n优势：功能全面\n劣势：成本较高',
          textAlign: 'left',
        },
      },
    ],
  },
  {
    id: 'template-timeline',
    name: '水平时间线',
    category: '时间线',
    thumbnail: '',
    components: [
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 60,
        width: 1040,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 28,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '发展历程时间线',
          textAlign: 'center',
        },
      },
      {
        id: newId(),
        type: 'shape',
        x: 100,
        y: 350,
        width: 1000,
        height: 4,
        rotation: 0,
        opacity: 1,
        borderRadius: 2,
        style: {
          fillColor: '#2b5797',
          fillColorIndex: 0,
        },
        data: { shapeType: 'rectangle' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 180,
        y: 335,
        width: 34,
        height: 34,
        rotation: 0,
        opacity: 1,
        borderRadius: 17,
        style: {
          fillColor: '#f50057',
          fillColorIndex: 3,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 120,
        y: 260,
        width: 160,
        height: 60,
        rotation: 0,
        opacity: 1,
        borderRadius: 4,
        style: {
          fontSize: 14,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '2020\n项目启动', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 450,
        y: 335,
        width: 34,
        height: 34,
        rotation: 0,
        opacity: 1,
        borderRadius: 17,
        style: {
          fillColor: '#00a1d6',
          fillColorIndex: 1,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 390,
        y: 260,
        width: 160,
        height: 60,
        rotation: 0,
        opacity: 1,
        borderRadius: 4,
        style: {
          fontSize: 14,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '2021\n产品发布', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 720,
        y: 335,
        width: 34,
        height: 34,
        rotation: 0,
        opacity: 1,
        borderRadius: 17,
        style: {
          fillColor: '#6c63ff',
          fillColorIndex: 2,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 660,
        y: 260,
        width: 160,
        height: 60,
        rotation: 0,
        opacity: 1,
        borderRadius: 4,
        style: {
          fontSize: 14,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '2022\n用户突破100万', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 990,
        y: 335,
        width: 34,
        height: 34,
        rotation: 0,
        opacity: 1,
        borderRadius: 17,
        style: {
          fillColor: '#ffb300',
          fillColorIndex: 4,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 930,
        y: 260,
        width: 160,
        height: 60,
        rotation: 0,
        opacity: 1,
        borderRadius: 4,
        style: {
          fontSize: 14,
          textColor: '#212121',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '2023\n国际化拓展', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-flow',
    name: '垂直流程图',
    category: '流程图',
    thumbnail: '',
    components: [
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 40,
        width: 1040,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 28,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '工作流程图',
          textAlign: 'center',
        },
      },
      {
        id: newId(),
        type: 'text',
        x: 450,
        y: 110,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        style: {
          fillColor: '#2b5797',
          fillColorIndex: 0,
          fontSize: 18,
          fontWeight: 'bold',
          textColor: '#ffffff',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '第一步：需求分析', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 590,
        y: 190,
        width: 20,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fillColor: '#616161',
          fillColorIndex: 0,
        },
        data: { shapeType: 'rectangle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 450,
        y: 230,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        style: {
          fillColor: '#00a1d6',
          fillColorIndex: 1,
          fontSize: 18,
          fontWeight: 'bold',
          textColor: '#ffffff',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '第二步：方案设计', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 590,
        y: 310,
        width: 20,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fillColor: '#616161',
          fillColorIndex: 0,
        },
        data: { shapeType: 'rectangle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 450,
        y: 350,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        style: {
          fillColor: '#6c63ff',
          fillColorIndex: 2,
          fontSize: 18,
          fontWeight: 'bold',
          textColor: '#ffffff',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '第三步：开发实现', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 590,
        y: 430,
        width: 20,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fillColor: '#616161',
          fillColorIndex: 0,
        },
        data: { shapeType: 'rectangle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 450,
        y: 470,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        style: {
          fillColor: '#f50057',
          fillColorIndex: 3,
          fontSize: 18,
          fontWeight: 'bold',
          textColor: '#ffffff',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '第四步：测试上线', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 590,
        y: 550,
        width: 20,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fillColor: '#616161',
          fillColorIndex: 0,
        },
        data: { shapeType: 'rectangle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 450,
        y: 590,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        borderRadius: 8,
        style: {
          fillColor: '#ffb300',
          fillColorIndex: 4,
          fontSize: 18,
          fontWeight: 'bold',
          textColor: '#ffffff',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '第五步：运营维护', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-cards',
    name: '数据卡片',
    category: '数据卡片',
    thumbnail: '',
    components: [
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 50,
        width: 1040,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 28,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '核心业务数据',
          textAlign: 'center',
        },
      },
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 150,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#e8f0fe',
          fillColorIndex: 0,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '总用户数\n\n125,800\n\n月增长 +12.5%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 370,
        y: 150,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#e0f7fa',
          fillColorIndex: 1,
          strokeColor: '#00a1d6',
          strokeColorIndex: 1,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#00a1d6',
          textColorIndex: 1,
          fontFamily: 'system-ui',
        },
        data: { content: '日活跃用户\n\n28,500\n\n日增长 +8.3%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 660,
        y: 150,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#ede7f6',
          fillColorIndex: 2,
          strokeColor: '#6c63ff',
          strokeColorIndex: 2,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#6c63ff',
          textColorIndex: 2,
          fontFamily: 'system-ui',
        },
        data: { content: '转化率\n\n3.24%\n\n环比 +0.5%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 950,
        y: 150,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#fce4ec',
          fillColorIndex: 3,
          strokeColor: '#f50057',
          strokeColorIndex: 3,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#f50057',
          textColorIndex: 3,
          fontFamily: 'system-ui',
        },
        data: { content: '营业收入\n\n¥ 2.58M\n\n同比 +23.8%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 420,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#fff8e1',
          fillColorIndex: 4,
          strokeColor: '#ffb300',
          strokeColorIndex: 4,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#ffb300',
          textColorIndex: 4,
          fontFamily: 'system-ui',
        },
        data: { content: '订单数量\n\n8,420\n\n月增长 +15.2%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 370,
        y: 420,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#e8f5e9',
          fillColorIndex: 1,
          strokeColor: '#4caf50',
          strokeColorIndex: 0,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#4caf50',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '客户满意度\n\n96.5%\n\n提升 +2.1%', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 660,
        y: 420,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#fce4ec',
          fillColorIndex: 3,
          strokeColor: '#e91e63',
          strokeColorIndex: 3,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#e91e63',
          textColorIndex: 3,
          fontFamily: 'system-ui',
        },
        data: { content: '复购率\n\n68.2%\n\n稳定增长', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 950,
        y: 420,
        width: 250,
        height: 220,
        rotation: 0,
        opacity: 1,
        borderRadius: 12,
        style: {
          fillColor: '#e3f2fd',
          fillColorIndex: 0,
          strokeColor: '#2196f3',
          strokeColorIndex: 0,
          strokeWidth: 1,
          fontSize: 16,
          textColor: '#2196f3',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '市场份额\n\n24.8%\n\n行业第二', textAlign: 'center' },
      },
    ],
  },
  {
    id: 'template-person',
    name: '人物介绍',
    category: '人物介绍',
    thumbnail: '',
    components: [
      {
        id: newId(),
        type: 'text',
        x: 80,
        y: 50,
        width: 1040,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 28,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: {
          content: '核心团队成员',
          textAlign: 'center',
        },
      },
      {
        id: newId(),
        type: 'shape',
        x: 150,
        y: 140,
        width: 180,
        height: 180,
        rotation: 0,
        opacity: 1,
        borderRadius: 90,
        style: {
          fillColor: '#e8f0fe',
          fillColorIndex: 0,
          strokeColor: '#2b5797',
          strokeColorIndex: 0,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 100,
        y: 340,
        width: 280,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 22,
          fontWeight: 'bold',
          textColor: '#2b5797',
          textColorIndex: 0,
          fontFamily: 'system-ui',
        },
        data: { content: '张 明', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 100,
        y: 390,
        width: 280,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 16,
          textColor: '#616161',
          textColorIndex: 2,
          fontFamily: 'system-ui',
        },
        data: { content: '创始人 & CEO', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 100,
        y: 430,
        width: 280,
        height: 120,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 14,
          textColor: '#424242',
          textColorIndex: 1,
          fontFamily: 'system-ui',
        },
        data: { content: '10年互联网经验\n前腾讯高级产品经理\n连续创业者', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 510,
        y: 140,
        width: 180,
        height: 180,
        rotation: 0,
        opacity: 1,
        borderRadius: 90,
        style: {
          fillColor: '#e0f7fa',
          fillColorIndex: 1,
          strokeColor: '#00a1d6',
          strokeColorIndex: 1,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 460,
        y: 340,
        width: 280,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 22,
          fontWeight: 'bold',
          textColor: '#00a1d6',
          textColorIndex: 1,
          fontFamily: 'system-ui',
        },
        data: { content: '李 华', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 460,
        y: 390,
        width: 280,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 16,
          textColor: '#616161',
          textColorIndex: 2,
          fontFamily: 'system-ui',
        },
        data: { content: '技术总监', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 460,
        y: 430,
        width: 280,
        height: 120,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 14,
          textColor: '#424242',
          textColorIndex: 1,
          fontFamily: 'system-ui',
        },
        data: { content: '全栈技术专家\n前阿里技术专家\n开源项目贡献者', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'shape',
        x: 870,
        y: 140,
        width: 180,
        height: 180,
        rotation: 0,
        opacity: 1,
        borderRadius: 90,
        style: {
          fillColor: '#ede7f6',
          fillColorIndex: 2,
          strokeColor: '#6c63ff',
          strokeColorIndex: 2,
          strokeWidth: 3,
        },
        data: { shapeType: 'circle' },
      },
      {
        id: newId(),
        type: 'text',
        x: 820,
        y: 340,
        width: 280,
        height: 50,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 22,
          fontWeight: 'bold',
          textColor: '#6c63ff',
          textColorIndex: 2,
          fontFamily: 'system-ui',
        },
        data: { content: '王 芳', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 820,
        y: 390,
        width: 280,
        height: 30,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 16,
          textColor: '#616161',
          textColorIndex: 2,
          fontFamily: 'system-ui',
        },
        data: { content: '设计总监', textAlign: 'center' },
      },
      {
        id: newId(),
        type: 'text',
        x: 820,
        y: 430,
        width: 280,
        height: 120,
        rotation: 0,
        opacity: 1,
        borderRadius: 0,
        style: {
          fontSize: 14,
          textColor: '#424242',
          textColorIndex: 1,
          fontFamily: 'system-ui',
        },
        data: { content: '资深UI/UX设计师\n曾获多项设计大奖\n用户体验布道者', textAlign: 'center' },
      },
    ],
  },
];
